"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body
from sqlalchemy.orm import Session
from db.database import get_db
from utils.dependencies import require_admin
from typing import Any

from controllers.treasury.payout_approval_controller import approve_batch, approve_payout, dispatch_batch, reject_batch, reject_payout

router = APIRouter(prefix="/api/v1/admin")

@router.post("/payouts/{payout_id}/approve", status_code=201, tags=['treasury-payouts'])
def approve_payout_route(
    payout_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    payload: Any = Body(...)
) -> dict[str, Any]:
    return approve_payout(payout_id=payout_id, current_user=current_user, db=db, payload=payload)

@router.post("/payouts/{payout_id}/reject", status_code=201, tags=['treasury-payouts'])
def reject_payout_route(
    payout_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    payload: Any = Body(...)
) -> dict[str, Any]:
    return reject_payout(payout_id=payout_id, current_user=current_user, db=db, payload=payload)

@router.post("/batches/{batch_id}/approve", status_code=201, tags=['treasury-payouts'])
def approve_batch_route(
    batch_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    payload: Any = Body(...)
) -> dict[str, Any]:
    return approve_batch(batch_id=batch_id, current_user=current_user, db=db, payload=payload)

@router.post("/batches/{batch_id}/reject", status_code=201, tags=['treasury-payouts'])
def reject_batch_route(
    batch_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    payload: Any = Body(...)
) -> dict[str, Any]:
    return reject_batch(batch_id=batch_id, current_user=current_user, db=db, payload=payload)

@router.post("/batches/{batch_id}/dispatch", status_code=201, tags=['treasury-payouts'])
def dispatch_batch_route(
    batch_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    payload: Any = Body(...)
) -> dict[str, Any]:
    return dispatch_batch(batch_id=batch_id, current_user=current_user, db=db, payload=payload)
