"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body
from sqlalchemy.orm import Session
from db.database import get_db
from utils.dependencies import require_admin

from controllers.admin.orders_controller import bulk_delete_orders_route, refund_order_route, update_order_tracking_route

router = APIRouter(prefix="/api/v1/admin")

@router.post("/orders/{country_code}/{order_id}/refund", status_code=201, tags=['admin-orders'])
def refund_order_route_route(
    country_code: str,
    order_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return refund_order_route(country_code=country_code, order_id=order_id, current_user=current_user, db=db)

@router.put("/orders/{country_code}/{order_id}/tracking", status_code=200, tags=['admin-orders'])
def update_order_tracking_route_route(
    country_code: str,
    order_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    tracking_number: str = Body('')
):
    return update_order_tracking_route(country_code=country_code, order_id=order_id, current_user=current_user, db=db, tracking_number=tracking_number)

@router.post("/orders/{country_code}/bulk/delete", status_code=201, tags=['admin-orders'])
def bulk_delete_orders_route_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    ids: list[int] = Body(None)
):
    return bulk_delete_orders_route(country_code=country_code, current_user=current_user, db=db, ids=ids)
