"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body, Query
from sqlalchemy.orm import Session
from db.database import get_db
from utils.dependencies import require_admin
from typing import Optional

from controllers.admin.bank_accounts_controller import delete_bank_account_route, list_pending_bank_accounts_route, verify_bank_account_route

router = APIRouter(prefix="/api/v1/admin")

@router.get("/bank-accounts/{country_code}/pending", status_code=200, tags=['admin-bank-accounts'])
def list_pending_bank_accounts_route_route(
    country_code: str,
    kind: str = Query('supplier'),
    page: int = Query(1),
    page_size: int = Query(50),
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return list_pending_bank_accounts_route(country_code=country_code, kind=kind, page=page, page_size=page_size, current_user=current_user, db=db)

@router.post("/bank-accounts/{country_code}/{kind}/{account_id}/verify", status_code=201, tags=['admin-bank-accounts'])
def verify_bank_account_route_route(
    country_code: str,
    kind: str,
    account_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    action: str = Body('approve'),
    note: Optional[str] = Body(None)
):
    return verify_bank_account_route(country_code=country_code, kind=kind, account_id=account_id, current_user=current_user, db=db, action=action, note=note)

@router.delete("/bank-accounts/{country_code}/{kind}/{account_id}", status_code=200, tags=['admin-bank-accounts'])
def delete_bank_account_route_route(
    country_code: str,
    kind: str,
    account_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return delete_bank_account_route(country_code=country_code, kind=kind, account_id=account_id, current_user=current_user, db=db)
