"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body, Query
from sqlalchemy.orm import Session
from db.database import get_db
from utils.dependencies import require_admin
from typing import Optional

from controllers.admin.payouts_controller import list_pending_payouts_route, verify_payout_route

router = APIRouter(prefix="/api/v1/admin")

@router.get("/payouts/{country_code}/pending", status_code=200, tags=['admin-payouts'])
def list_pending_payouts_route_route(
    country_code: str,
    page: int = Query(1),
    page_size: int = Query(50),
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return list_pending_payouts_route(country_code=country_code, page=page, page_size=page_size, current_user=current_user, db=db)

@router.post("/payouts/{country_code}/{payout_id}/verify", status_code=201, tags=['admin-payouts'])
def verify_payout_route_route(
    country_code: str,
    payout_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    status: str = Body('completed'),
    reference: Optional[str] = Body(None),
    notes: Optional[str] = Body(None)
):
    return verify_payout_route(country_code=country_code, payout_id=payout_id, current_user=current_user, db=db, status=status, reference=reference, notes=notes)
