"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body, Query
from sqlalchemy.orm import Session
from db.database import get_db
from utils.dependencies import get_current_user
from typing import Optional

from controllers.geography.country_versioning_controller import VersionDraftBody, approve_config_version, approve_config_version_public, create_config_version, create_config_version_public, get_config_version, get_config_version_public, list_config_versions, list_config_versions_public, publish_config_version, publish_config_version_public, rollback_config_version, rollback_config_version_public

router = APIRouter(prefix="/api/v1")

@router.get("/admin/config-versions/{country_code}", status_code=200, tags=['country-versioning'])
def list_config_versions_route(
    country_code: str,
    config_type: Optional[str] = Query(None),
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> list:
    return list_config_versions(country_code=country_code, config_type=config_type, current_user=current_user, db=db)

@router.get("/config-versions/{country_code}", status_code=200, tags=['country-versioning'])
def list_config_versions_public_route(
    country_code: str,
    config_type: Optional[str] = Query(None),
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> list:
    return list_config_versions_public(country_code=country_code, config_type=config_type, current_user=current_user, db=db)

@router.get("/admin/config-versions/{country_code}/{version_id}", status_code=200, tags=['country-versioning'])
def get_config_version_route(
    country_code: str,
    version_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> dict:
    return get_config_version(country_code=country_code, version_id=version_id, current_user=current_user, db=db)

@router.get("/config-versions/{country_code}/{version_id}", status_code=200, tags=['country-versioning'])
def get_config_version_public_route(
    country_code: str,
    version_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> dict:
    return get_config_version_public(country_code=country_code, version_id=version_id, current_user=current_user, db=db)

@router.post("/admin/config-versions/{country_code}", status_code=201, tags=['country-versioning'])
def create_config_version_route(
    country_code: str,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    body: VersionDraftBody = Body(...)
) -> dict:
    return create_config_version(country_code=country_code, current_user=current_user, db=db, body=body)

@router.post("/config-versions/{country_code}", status_code=201, tags=['country-versioning'])
def create_config_version_public_route(
    country_code: str,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    body: VersionDraftBody = Body(...)
) -> dict:
    return create_config_version_public(country_code=country_code, current_user=current_user, db=db, body=body)

@router.post("/admin/config-versions/{country_code}/{version_id}/approve", status_code=201, tags=['country-versioning'])
def approve_config_version_route(
    country_code: str,
    version_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> dict:
    return approve_config_version(country_code=country_code, version_id=version_id, current_user=current_user, db=db)

@router.post("/config-versions/{country_code}/{version_id}/approve", status_code=201, tags=['country-versioning'])
def approve_config_version_public_route(
    country_code: str,
    version_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> dict:
    return approve_config_version_public(country_code=country_code, version_id=version_id, current_user=current_user, db=db)

@router.post("/admin/config-versions/{country_code}/{version_id}/publish", status_code=201, tags=['country-versioning'])
def publish_config_version_route(
    country_code: str,
    version_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> dict:
    return publish_config_version(country_code=country_code, version_id=version_id, current_user=current_user, db=db)

@router.post("/config-versions/{country_code}/{version_id}/publish", status_code=201, tags=['country-versioning'])
def publish_config_version_public_route(
    country_code: str,
    version_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> dict:
    return publish_config_version_public(country_code=country_code, version_id=version_id, current_user=current_user, db=db)

@router.post("/admin/config-versions/{country_code}/{version_id}/rollback", status_code=201, tags=['country-versioning'])
def rollback_config_version_route(
    country_code: str,
    version_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> dict:
    return rollback_config_version(country_code=country_code, version_id=version_id, current_user=current_user, db=db)

@router.post("/config-versions/{country_code}/{version_id}/rollback", status_code=201, tags=['country-versioning'])
def rollback_config_version_public_route(
    country_code: str,
    version_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> dict:
    return rollback_config_version_public(country_code=country_code, version_id=version_id, current_user=current_user, db=db)
