"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body, Query
from sqlalchemy.orm import Session
from db.database import get_db
from utils.dependencies import require_admin
from typing import Optional

from controllers.admin.suppliers_controller import bulk_manage_suppliers_route, bulk_verify_suppliers_route, list_pending_suppliers, list_suppliers, reject_supplier_route, supplier_comparison, verify_supplier_route

router = APIRouter(prefix="/api/v1/admin")

@router.get("/suppliers/{country_code}", status_code=200, tags=['admin-suppliers'])
def list_suppliers_route(
    country_code: str,
    search: Optional[str] = Query(None),
    page: int = Query(1),
    page_size: int = Query(50),
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return list_suppliers(country_code=country_code, search=search, page=page, page_size=page_size, current_user=current_user, db=db)

@router.get("/suppliers/{country_code}/pending", status_code=200, tags=['admin-suppliers'])
def list_pending_suppliers_route(
    country_code: str,
    page: int = Query(1),
    page_size: int = Query(50),
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return list_pending_suppliers(country_code=country_code, page=page, page_size=page_size, current_user=current_user, db=db)

@router.post("/suppliers/{country_code}/{supplier_id}/verify", status_code=201, tags=['admin-suppliers'])
def verify_supplier_route_route(
    country_code: str,
    supplier_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    note: Optional[str] = Body(None)
):
    return verify_supplier_route(country_code=country_code, supplier_id=supplier_id, current_user=current_user, db=db, note=note)

@router.post("/suppliers/{country_code}/{supplier_id}/reject", status_code=201, tags=['admin-suppliers'])
def reject_supplier_route_route(
    country_code: str,
    supplier_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    note: Optional[str] = Body(None)
):
    return reject_supplier_route(country_code=country_code, supplier_id=supplier_id, current_user=current_user, db=db, note=note)

@router.post("/suppliers/{country_code}/bulk/verify", status_code=201, tags=['admin-suppliers'])
def bulk_verify_suppliers_route_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    ids: list[int] = Body(None),
    action: str = Body('approve'),
    note: Optional[str] = Body(None)
):
    return bulk_verify_suppliers_route(country_code=country_code, current_user=current_user, db=db, ids=ids, action=action, note=note)

@router.post("/suppliers/{country_code}/bulk/manage", status_code=201, tags=['admin-suppliers'])
def bulk_manage_suppliers_route_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    ids: list[int] = Body(None),
    action: str = Body('approve'),
    note: Optional[str] = Body(None),
    badge_level: Optional[str] = Body(None)
):
    return bulk_manage_suppliers_route(country_code=country_code, current_user=current_user, db=db, ids=ids, action=action, note=note, badge_level=badge_level)

@router.get("/suppliers/{country_code}/comparison", status_code=200, tags=['admin-suppliers'])
def supplier_comparison_route(
    country_code: str,
    page: int = Query(1),
    page_size: int = Query(50),
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return supplier_comparison(country_code=country_code, page=page, page_size=page_size, current_user=current_user, db=db)
