"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body
from sqlalchemy.orm import Session
from db.database import get_db
from utils.dependencies import require_admin
from typing import Any, Optional

from controllers.core.ai_upload_controller import UploadFile, cancel_job, create_job, process_job, publish_job

router = APIRouter(prefix="/api/v1")

@router.post("/ai/uploads/jobs", status_code=201, tags=['ai'])
def create_job_route(
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    images: list[UploadFile] = Body(..., embed=True),
    country_code: str = Body(..., embed=True),
    model_used: Optional[str] = Body(..., embed=True),
    prompt_hash: Optional[str] = Body(..., embed=True)
) -> dict[str, Any]:
    return create_job(current_user=current_user, db=db, images=images, country_code=country_code, model_used=model_used, prompt_hash=prompt_hash)

@router.post("/ai/uploads/jobs/{job_id}/publish", status_code=201, tags=['ai'])
def publish_job_route(
    job_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    overrides: Optional[dict] = Body(...)
) -> dict[str, Any]:
    return publish_job(job_id=job_id, current_user=current_user, db=db, overrides=overrides)

@router.post("/ai/uploads/jobs/{job_id}/cancel", status_code=201, tags=['ai'])
def cancel_job_route(
    job_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
) -> dict[str, Any]:
    return cancel_job(job_id=job_id, current_user=current_user, db=db)

@router.post("/ai/uploads/jobs/{job_id}/process", status_code=201, tags=['ai'])
def process_job_route(
    job_id: int
) -> None:
    return process_job(job_id=job_id)
