from __future__ import annotations
from uuid import uuid4
from sqlalchemy import func, UUID
from sqlalchemy import Column, Integer, String, DateTime, Boolean, Text, Numeric, ForeignKey, UniqueConstraint, Index, JSON, text
from sqlalchemy.orm import relationship
from . import Base
from utils.datetime_utils import utcnow as utcnow
from ..mixins import TenantMixin
from db.mixins import VersionMixin
__all__ = ['FlashSale', 'FlashSaleItem', 'EmailCampaign', 'EmailTemplate', 'NewsletterSubscriber', 'EmailCampaignLog', 'CampaignRecipient', 'EmailDeliveryEvent', 'EmailSuppression', 'EmailRuntimeConfig', 'PointsTransaction', 'UserPoints']

class FlashSale(Base, TenantMixin):
    __tablename__ = 'flash_sales'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (
        Index('ix_flash_sales_product_ids_gin', 'product_ids', postgresql_using='gin'),
        Index('ix_flash_sales_country_created', 'country_code', 'created_at'),
        {'schema': 'commerce'},
    )
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    starts_at = Column(DateTime, nullable=False)
    ends_at = Column(DateTime, nullable=False)
    discount_pct = Column(Numeric(5, 2), default=0)
    deleted_at = Column(DateTime, nullable=True)
    deleted_by_id = Column(Integer, nullable=True)
    product_ids = Column(JSON, nullable=True)
    country_code = Column(String(3), nullable=True)
    country = relationship('CountryConfig', foreign_keys='FlashSale.country_code', primaryjoin='foreign(FlashSale.country_code) == CountryConfig.code')
    items = relationship('FlashSaleItem', back_populates='flash_sale', cascade='all, delete-orphan')

class FlashSaleItem(Base, TenantMixin):
    __tablename__ = 'flash_sale_items'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (
        Index('ix_flash_sale_items_country_created', 'country_code', 'created_at'),
        {'schema': 'commerce'},
    )
    id = Column(Integer, primary_key=True, index=True)
    flash_sale_id = Column(Integer, ForeignKey('commerce.flash_sales.id', ondelete='RESTRICT'), nullable=False, index=True)
    product_id = Column(Integer, ForeignKey('commerce.products.id', ondelete='RESTRICT'), nullable=False, index=True)
    original_price = Column(Numeric(10, 2), nullable=False)
    discounted_price = Column(Numeric(10, 2), nullable=False)
    country_code = Column(String(3), nullable=True)
    quantity_limit = Column(Integer, nullable=True)
    flash_sale = relationship('FlashSale', back_populates='items')
    product = relationship('Product')
    country = relationship('CountryConfig', foreign_keys='FlashSaleItem.country_code', primaryjoin='foreign(FlashSaleItem.country_code) == CountryConfig.code')

class EmailCampaign(Base, TenantMixin):
    __tablename__ = 'email_campaigns'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_email_campaigns_country_created', 'country_code', 'created_at'), {'schema': 'communication'})
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    subject = Column(String, nullable=False)
    status = Column(String, default='draft')
    send_at = Column(DateTime, nullable=True)
    created_by = Column(Integer, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)
    from_name = Column(String(200), nullable=True)
    target_audience = Column(Text, nullable=True)
    scheduled_at = Column(DateTime, nullable=True)
    sent_at = Column(DateTime, nullable=True)
    sent_count = Column(Integer, default=0)
    open_count = Column(Integer, default=0)
    click_count = Column(Integer, default=0)
    recipients = relationship('CampaignRecipient', back_populates='campaign', cascade='all, delete-orphan')

class EmailTemplate(Base):
    __tablename__ = 'email_templates'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'communication'},)
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(200), unique=True, index=True, nullable=False)
    subject = Column(String(500), nullable=False)
    content = Column(Text, nullable=True)
    template_type = Column(String(50), default='marketing')
    is_active = Column(Boolean, default=True)
    created_by = Column(Integer, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)

class NewsletterSubscriber(Base):
    __tablename__ = 'newsletter_subscribers'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'communication'},)
    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    created_at = Column(DateTime, default=utcnow)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)

class EmailCampaignLog(Base):
    __tablename__ = 'email_campaign_logs'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'communication'},)
    id = Column(Integer, primary_key=True, index=True)
    campaign_id = Column(Integer, ForeignKey('communication.email_campaigns.id', ondelete='RESTRICT'), nullable=False, index=True)
    recipient_email = Column(String, nullable=False)
    status = Column(String, default='sent')
    sent_at = Column(DateTime, default=utcnow)
    delivered_at = Column(DateTime, nullable=True)
    opened_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=utcnow)

class CampaignRecipient(Base):
    __tablename__ = 'campaign_recipients'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'communication'},)
    id = Column(Integer, primary_key=True, index=True)
    campaign_id = Column(Integer, ForeignKey('communication.email_campaigns.id', ondelete='RESTRICT'), nullable=False, index=True)
    user_id = Column(Integer, nullable=False)
    email = Column(String, nullable=False)
    status = Column(String, default='pending')
    sent_at = Column(DateTime, nullable=True)
    delivered_at = Column(DateTime, nullable=True)
    opened_at = Column(DateTime, nullable=True)
    clicked_at = Column(DateTime, nullable=True)
    bounced_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    campaign = relationship('EmailCampaign', back_populates='recipients')
    user = relationship('User', primaryjoin='foreign(CampaignRecipient.user_id) == User.id')

class EmailDeliveryEvent(Base):
    __tablename__ = 'email_delivery_events'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_email_delivery_events_details_gin', 'details', postgresql_using='gin'), {'schema': 'communication'})
    id = Column(Integer, primary_key=True, index=True)
    event_type = Column(String, nullable=False)
    recipient_email = Column(String, nullable=False)
    subject = Column(String, nullable=True)
    status = Column(String, default='sent')
    details = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=utcnow)

class EmailSuppression(Base):
    __tablename__ = 'email_suppressions'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'communication'},)
    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, nullable=False, index=True)
    reason = Column(String, nullable=False)
    source = Column(String, nullable=False)
    provider = Column(String, nullable=True)
    status = Column(String, default='active')
    notes = Column(Text, nullable=True)
    suppressed_at = Column(DateTime, nullable=True)
    last_event_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=utcnow)

class EmailRuntimeConfig(Base):
    __tablename__ = 'email_runtime_config'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'configuration'},)
    id = Column(Integer, primary_key=True, index=True)
    provider = Column(String(50), default='environment')
    resend_api_key = Column(String, nullable=True)
    resend_webhook_secret = Column(String, nullable=True)
    smtp_host = Column(String, nullable=True)
    smtp_port = Column(Integer, default=587)
    smtp_username = Column(String, nullable=True)
    smtp_password = Column(String, nullable=True)
    is_smtp_use_tls = Column(Boolean, default=True)
    is_smtp_use_ssl = Column(Boolean, default=False)
    smtp_timeout_seconds = Column(Integer, default=15)
    email_from_default = Column(String, nullable=True)
    email_from_promotional = Column(String, nullable=True)
    email_from_transactional = Column(String, nullable=True)
    email_from_notification = Column(String, nullable=True)
    email_from_alert = Column(String, nullable=True)
    email_from_verification = Column(String, nullable=True)
    email_from_login_verification = Column(String, nullable=True)
    email_from_password_reset = Column(String, nullable=True)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)

class PointsTransaction(Base):
    __tablename__ = 'points_transactions'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'commerce'},)
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey('security.users.id', ondelete='RESTRICT'), nullable=False, index=True)
    points = Column(Numeric(12, 2), nullable=False, default=0)
    balance_after = Column(Numeric(12, 2), nullable=True)
    tx_type = Column(String(30), nullable=False, default='earn')
    reason = Column(String(100), nullable=True)
    reference_id = Column(Integer, nullable=True)
    reference_type = Column(String(50), nullable=True)
    created_at = Column(DateTime, default=utcnow)

class UserPoints(Base):
    __tablename__ = 'user_points'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'commerce'},)
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey('security.users.id', ondelete='RESTRICT'), nullable=False, unique=True, index=True)
    points = Column(Numeric(12, 2), nullable=False, default=0)
    lifetime_points = Column(Numeric(12, 2), nullable=False, default=0)
    tier = Column(String(20), default='bronze')
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)
Index('ix_flash_sales_product_ids', text('(product_ids::jsonb)'), postgresql_using='gin')
Index('ix_email_delivery_events_details', text('(details::jsonb)'), postgresql_using='gin')