/**
 * GENERATED PERMISSIONS REGISTRY
 * ===============================
 * Source of truth: `GET /api/v1/rbac/catalog` (see backend/modules/admin/routers/security.py).
 * This file is auto-generated by `scripts/generate-permissions.mjs` from the
 * live catalog. At runtime, `fetchRbacCatalog()` (in `adminPermissions.ts`)
 * refreshes the in-memory cache; `getAvailablePermissions()` below is the
 * synchronous accessor consumed by permission gating UI.
 *
 * If the build-time catalog is empty (e.g. dev server ran without a backend),
 * the file falls back to the hardcoded `STAFF_PERMISSION_GROUPS` matrix so
 * the UI never crashes. See ARCHITECTURE_DIAGRAM.md §7 for the rationale.
 */

export {
  fetchRbacCatalog,
  getAvailablePermissions,
  getAdminPermissions,
  hasAdminPermission,
  STAFF_PERMISSION_GROUPS,
  ADMIN_PERMISSION_MAP,
  canAccessAdminBannerManagement,
  canAccessAdminEmailManagement,
  canAccessAdminPaymentManagement,
  canAccessAdminReturnsManagement,
  canAccessAdminLogisticsPartnerManagement,
  canAccessAdminInvoiceManagement,
  canManageAdminInvoices,
  canAccessAdminProductVerification,
  canAccessAdminFlashSales,
  type AdminStaffRole,
  type StaffPermissionGroup,
  type RbacCatalogResponse,
} from "./adminPermissions";

/** Build-time cache populated by `npm run openapi:gen` / `scripts/generate-permissions.mjs`.
 *  Shape mirrors the runtime RbacCatalogResponse; populated when present. */
export const BUILD_TIME_PERMISSIONS: ReadonlyArray<string> = [];

/**
 * Runtime-mutable registry of feature atoms fetched from
 * ``GET /api/v1/rbac/catalog``. Updated by ``RbacCatalogBootstrap`` once
 * the admin app mounts. UI gating helpers should consult
 * ``getAvailablePermissions()`` rather than the build-time array so they
 * stay in sync with the backend.
 */
let RUNTIME_PERMISSIONS: ReadonlyArray<string> = [];

/**
 * Replace the runtime-mutable RBAC atom list. Called by
 * ``RbacCatalogBootstrap`` with the body of ``GET /api/v1/rbac/catalog``.
 * Safe to call from any client component.
 */
export function applyRbacCatalogAtoms(atoms: ReadonlyArray<string>): void {
  RUNTIME_PERMISSIONS = [...new Set(atoms)];
}

/**
 * Snapshot accessor for the runtime-mutable RBAC atoms. Returns the
 * build-time list when the runtime list is empty (e.g. backend offline
 * or fetch in flight).
 */
export function getRuntimePermissions(): ReadonlyArray<string> {
  return RUNTIME_PERMISSIONS.length > 0 ? RUNTIME_PERMISSIONS : BUILD_TIME_PERMISSIONS;
}