"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body, Query
from sqlalchemy.orm import Session
from db.database import get_db
from utils.dependencies import require_admin

from controllers.admin.users_admin_controller import CreateStaffAccount, UpdateStaffAccount, bulk_delete_users_route, bulk_toggle_users_active_route, bulk_update_staff_accounts_route, bulk_update_users_role_route, create_staff_account_route, delete_staff_account_route, list_staff, update_staff_account_route, update_user_role_route

router = APIRouter(prefix="/api/v1/admin")

@router.get("/users/{country_code}/staff", status_code=200, tags=['admin-users'])
def list_staff_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return list_staff(country_code=country_code, current_user=current_user, db=db)

@router.put("/users/{country_code}/{user_id}/role", status_code=200, tags=['admin-users'])
def update_user_role_route_route(
    country_code: str,
    user_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    role: str = Body('customer')
):
    return update_user_role_route(country_code=country_code, user_id=user_id, current_user=current_user, db=db, role=role)

@router.post("/users/{country_code}/bulk/toggle-active", status_code=201, tags=['admin-users'])
def bulk_toggle_users_active_route_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    ids: list[int] = Body(None, embed=True),
    is_active: bool = Body(False, embed=True)
):
    return bulk_toggle_users_active_route(country_code=country_code, current_user=current_user, db=db, ids=ids, is_active=is_active)

@router.post("/users/{country_code}/bulk/role", status_code=201, tags=['admin-users'])
def bulk_update_users_role_route_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    ids: list[int] = Body(None, embed=True),
    role: str = Body('customer', embed=True)
):
    return bulk_update_users_role_route(country_code=country_code, current_user=current_user, db=db, ids=ids, role=role)

@router.post("/users/{country_code}/staff", status_code=201, tags=['admin-users'])
def create_staff_account_route_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    payload: CreateStaffAccount = Body(...)
):
    return create_staff_account_route(country_code=country_code, current_user=current_user, db=db, payload=payload)

@router.put("/users/{country_code}/staff/{user_id}", status_code=200, tags=['admin-users'])
def update_staff_account_route_route(
    country_code: str,
    user_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    payload: UpdateStaffAccount = Body(...)
):
    return update_staff_account_route(country_code=country_code, user_id=user_id, current_user=current_user, db=db, payload=payload)

@router.delete("/users/{country_code}/staff/{user_id}", status_code=200, tags=['admin-users'])
def delete_staff_account_route_route(
    country_code: str,
    user_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return delete_staff_account_route(country_code=country_code, user_id=user_id, current_user=current_user, db=db)

@router.post("/users/{country_code}/staff/bulk", status_code=201, tags=['admin-users'])
def bulk_update_staff_accounts_route_route(
    country_code: str,
    ids: list[int] = Query(None),
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    payload: UpdateStaffAccount = Body(None)
):
    return bulk_update_staff_accounts_route(country_code=country_code, ids=ids, current_user=current_user, db=db, payload=payload)

@router.post("/users/{country_code}/bulk/delete", status_code=201, tags=['admin-users'])
def bulk_delete_users_route_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    ids: list[int] = Body(None)
):
    return bulk_delete_users_route(country_code=country_code, current_user=current_user, db=db, ids=ids)
