"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from db.database import get_db
from utils.dependencies import require_admin

from controllers.admin.analytics_controller import analytics_chatbot, analytics_customers, analytics_overview, analytics_timeseries, analytics_top_products, analytics_user_growth

router = APIRouter(prefix="/api/v1/admin")

@router.get("/analytics/{country_code}", status_code=200, tags=['admin-analytics'])
def analytics_overview_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return analytics_overview(country_code=country_code, current_user=current_user, db=db)

@router.get("/analytics/{country_code}/timeseries", status_code=200, tags=['admin-analytics'])
def analytics_timeseries_route(
    country_code: str,
    period: str = Query('30d'),
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return analytics_timeseries(country_code=country_code, period=period, current_user=current_user, db=db)

@router.get("/analytics/{country_code}/customers", status_code=200, tags=['admin-analytics'])
def analytics_customers_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return analytics_customers(country_code=country_code, current_user=current_user, db=db)

@router.get("/analytics/{country_code}/top-products", status_code=200, tags=['admin-analytics'])
def analytics_top_products_route(
    country_code: str,
    limit: int = Query(10),
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return analytics_top_products(country_code=country_code, limit=limit, current_user=current_user, db=db)

@router.get("/analytics/{country_code}/user-growth", status_code=200, tags=['admin-analytics'])
def analytics_user_growth_route(
    country_code: str,
    period: str = Query('30d'),
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return analytics_user_growth(country_code=country_code, period=period, current_user=current_user, db=db)

@router.get("/analytics/{country_code}/chatbot", status_code=200, tags=['admin-analytics'])
def analytics_chatbot_route(
    country_code: str,
    period: str = Query('30d'),
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return analytics_chatbot(country_code=country_code, period=period, current_user=current_user, db=db)
