"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body, Query
from sqlalchemy.orm import Session
from infrastructure.database.database import get_db
from infrastructure.utils.dependencies import require_admin
from typing import Optional

from domains.finance.services.sub_ledger_controller import controller_get_ap_summary
from domains.finance.services.sub_ledger_controller import controller_get_ar_summary
from domains.finance.services.sub_ledger_controller import controller_post_ap_payable
from domains.finance.services.sub_ledger_controller import controller_post_ap_payment
from domains.finance.services.sub_ledger_controller import controller_post_ar_invoice
from domains.finance.services.sub_ledger_controller import controller_post_ar_payment

router = APIRouter(prefix="/api/v1")

@router.get("/admin/ar", status_code=200, tags=['finance'])
def controller_get_ar_summary_route(
    db: Session = Depends(get_db),
    customer_id: Optional[int] = Query(None),
    status: Optional[str] = Query(None),
    country_code: Optional[str] = Query(None),
    limit: int = Query(50)
) -> dict:
    return controller_get_ar_summary(db=db, customer_id=customer_id, status=status, country_code=country_code, limit=limit)

@router.get("/ar", status_code=200, tags=['finance'])
def controller_get_ar_summary_route(
    db: Session = Depends(get_db),
    customer_id: Optional[int] = Query(None),
    status: Optional[str] = Query(None),
    country_code: Optional[str] = Query(None),
    limit: int = Query(50)
) -> dict:
    return controller_get_ar_summary(db=db, customer_id=customer_id, status=status, country_code=country_code, limit=limit)

@router.get("/admin/ap", status_code=200, tags=['finance'])
def controller_get_ap_summary_route(
    db: Session = Depends(get_db),
    supplier_id: Optional[int] = Query(None),
    status: Optional[str] = Query(None),
    country_code: Optional[str] = Query(None),
    limit: int = Query(50)
) -> dict:
    return controller_get_ap_summary(db=db, supplier_id=supplier_id, status=status, country_code=country_code, limit=limit)

@router.get("/ap", status_code=200, tags=['finance'])
def controller_get_ap_summary_route(
    db: Session = Depends(get_db),
    supplier_id: Optional[int] = Query(None),
    status: Optional[str] = Query(None),
    country_code: Optional[str] = Query(None),
    limit: int = Query(50)
) -> dict:
    return controller_get_ap_summary(db=db, supplier_id=supplier_id, status=status, country_code=country_code, limit=limit)

@router.get("/admin/ap-ledger", status_code=200, tags=['finance'])
def controller_get_ap_summary_route(
    db: Session = Depends(get_db),
    supplier_id: Optional[int] = Query(None),
    status: Optional[str] = Query(None),
    country_code: Optional[str] = Query(None),
    limit: int = Query(50)
) -> dict:
    return controller_get_ap_summary(db=db, supplier_id=supplier_id, status=status, country_code=country_code, limit=limit)

@router.get("/ap-ledger", status_code=200, tags=['finance'])
def controller_get_ap_summary_route(
    db: Session = Depends(get_db),
    supplier_id: Optional[int] = Query(None),
    status: Optional[str] = Query(None),
    country_code: Optional[str] = Query(None),
    limit: int = Query(50)
) -> dict:
    return controller_get_ap_summary(db=db, supplier_id=supplier_id, status=status, country_code=country_code, limit=limit)

@router.post("/admin/ar-ledger/invoice", status_code=201, tags=['finance'])
def controller_post_ar_invoice_route(
    db: Session = Depends(get_db),
    current_user: dict = Depends(require_admin),
    customer_id: int = Body(...),
    amount: float = Body(...),
    order_id: Optional[int] = Body(None),
    invoice_id: Optional[int] = Body(None),
    due_date: Optional[str] = Body(None),
    description: Optional[str] = Body(None),
    currency: str = Body('OMR'),
    country_code: Optional[str] = Body(None)
) -> dict:
    return controller_post_ar_invoice(db=db, current_user=current_user, customer_id=customer_id, amount=amount, order_id=order_id, invoice_id=invoice_id, due_date=due_date, description=description, currency=currency, country_code=country_code)

@router.post("/ar-ledger/invoice", status_code=201, tags=['finance'])
def controller_post_ar_invoice_route(
    db: Session = Depends(get_db),
    current_user: dict = Depends(require_admin),
    customer_id: int = Body(...),
    amount: float = Body(...),
    order_id: Optional[int] = Body(None),
    invoice_id: Optional[int] = Body(None),
    due_date: Optional[str] = Body(None),
    description: Optional[str] = Body(None),
    currency: str = Body('OMR'),
    country_code: Optional[str] = Body(None)
) -> dict:
    return controller_post_ar_invoice(db=db, current_user=current_user, customer_id=customer_id, amount=amount, order_id=order_id, invoice_id=invoice_id, due_date=due_date, description=description, currency=currency, country_code=country_code)

@router.post("/admin/ar-ledger/payment", status_code=201, tags=['finance'])
def controller_post_ar_payment_route(
    db: Session = Depends(get_db),
    current_user: dict = Depends(require_admin),
    customer_id: int = Body(...),
    amount: float = Body(...),
    invoice_id: Optional[int] = Body(None),
    order_id: Optional[int] = Body(None),
    description: Optional[str] = Body(None),
    currency: str = Body('OMR'),
    country_code: Optional[str] = Body(None)
) -> dict:
    return controller_post_ar_payment(db=db, current_user=current_user, customer_id=customer_id, amount=amount, invoice_id=invoice_id, order_id=order_id, description=description, currency=currency, country_code=country_code)

@router.post("/ar-ledger/payment", status_code=201, tags=['finance'])
def controller_post_ar_payment_route(
    db: Session = Depends(get_db),
    current_user: dict = Depends(require_admin),
    customer_id: int = Body(...),
    amount: float = Body(...),
    invoice_id: Optional[int] = Body(None),
    order_id: Optional[int] = Body(None),
    description: Optional[str] = Body(None),
    currency: str = Body('OMR'),
    country_code: Optional[str] = Body(None)
) -> dict:
    return controller_post_ar_payment(db=db, current_user=current_user, customer_id=customer_id, amount=amount, invoice_id=invoice_id, order_id=order_id, description=description, currency=currency, country_code=country_code)

@router.post("/admin/ap-ledger/payable", status_code=201, tags=['finance'])
def controller_post_ap_payable_route(
    db: Session = Depends(get_db),
    current_user: dict = Depends(require_admin),
    supplier_id: int = Body(...),
    amount: float = Body(...),
    order_id: Optional[int] = Body(None),
    settlement_id: Optional[int] = Body(None),
    due_date: Optional[str] = Body(None),
    description: Optional[str] = Body(None),
    currency: str = Body('OMR'),
    country_code: Optional[str] = Body(None)
) -> dict:
    return controller_post_ap_payable(db=db, current_user=current_user, supplier_id=supplier_id, amount=amount, order_id=order_id, settlement_id=settlement_id, due_date=due_date, description=description, currency=currency, country_code=country_code)

@router.post("/ap-ledger/payable", status_code=201, tags=['finance'])
def controller_post_ap_payable_route(
    db: Session = Depends(get_db),
    current_user: dict = Depends(require_admin),
    supplier_id: int = Body(...),
    amount: float = Body(...),
    order_id: Optional[int] = Body(None),
    settlement_id: Optional[int] = Body(None),
    due_date: Optional[str] = Body(None),
    description: Optional[str] = Body(None),
    currency: str = Body('OMR'),
    country_code: Optional[str] = Body(None)
) -> dict:
    return controller_post_ap_payable(db=db, current_user=current_user, supplier_id=supplier_id, amount=amount, order_id=order_id, settlement_id=settlement_id, due_date=due_date, description=description, currency=currency, country_code=country_code)

@router.post("/admin/ap-ledger/payment", status_code=201, tags=['finance'])
def controller_post_ap_payment_route(
    db: Session = Depends(get_db),
    current_user: dict = Depends(require_admin),
    supplier_id: int = Body(...),
    amount: float = Body(...),
    settlement_id: Optional[int] = Body(None),
    description: Optional[str] = Body(None),
    currency: str = Body('OMR'),
    country_code: Optional[str] = Body(None)
) -> dict:
    return controller_post_ap_payment(db=db, current_user=current_user, supplier_id=supplier_id, amount=amount, settlement_id=settlement_id, description=description, currency=currency, country_code=country_code)

@router.post("/ap-ledger/payment", status_code=201, tags=['finance'])
def controller_post_ap_payment_route(
    db: Session = Depends(get_db),
    current_user: dict = Depends(require_admin),
    supplier_id: int = Body(...),
    amount: float = Body(...),
    settlement_id: Optional[int] = Body(None),
    description: Optional[str] = Body(None),
    currency: str = Body('OMR'),
    country_code: Optional[str] = Body(None)
) -> dict:
    return controller_post_ap_payment(db=db, current_user=current_user, supplier_id=supplier_id, amount=amount, settlement_id=settlement_id, description=description, currency=currency, country_code=country_code)
