"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body
from sqlalchemy.orm import Session
from infrastructure.database.database import get_db
from infrastructure.utils.dependencies import require_admin

from domains.governance.services.permissions.permissions_controller import permission_catalog, permission_hierarchy, update_role_permissions_route

router = APIRouter(prefix="/api/v1/admin")

@router.get("/permissions/{country_code}/catalog", status_code=200, tags=['admin-permissions'])
def permission_catalog_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return permission_catalog(country_code=country_code, current_user=current_user, db=db)

@router.get("/permissions/{country_code}/hierarchy", status_code=200, tags=['admin-permissions'])
def permission_hierarchy_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return permission_hierarchy(country_code=country_code, current_user=current_user, db=db)

@router.put("/permissions/{country_code}/roles/{role}", status_code=200, tags=['admin-permissions'])
def update_role_permissions_route_route(
    country_code: str,
    role: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    permissions: list[str] = Body(None)
):
    return update_role_permissions_route(country_code=country_code, role=role, current_user=current_user, db=db, permissions=permissions)
