"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body, Query
from sqlalchemy.orm import Session
from infrastructure.database.database import get_db
from infrastructure.utils.dependencies import require_admin
from typing import Optional

from domains.governance.services.comms.tickets_controller import list_tickets_route, reply_ticket, ticket_detail, update_ticket_status_route

router = APIRouter(prefix="/api/v1/admin")

@router.get("/tickets/{country_code}", status_code=200, tags=['admin-tickets'])
def list_tickets_route_route(
    country_code: str,
    status: Optional[str] = Query(None),
    page: int = Query(1),
    page_size: int = Query(50),
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return list_tickets_route(country_code=country_code, status=status, page=page, page_size=page_size, current_user=current_user, db=db)

@router.get("/tickets/{country_code}/{ticket_id}", status_code=200, tags=['admin-tickets'])
def ticket_detail_route(
    country_code: str,
    ticket_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return ticket_detail(country_code=country_code, ticket_id=ticket_id, current_user=current_user, db=db)

@router.post("/tickets/{country_code}/{ticket_id}/reply", status_code=201, tags=['admin-tickets'])
def reply_ticket_route(
    country_code: str,
    ticket_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    message: str = Body('')
):
    return reply_ticket(country_code=country_code, ticket_id=ticket_id, current_user=current_user, db=db, message=message)

@router.put("/tickets/{country_code}/{ticket_id}/status", status_code=200, tags=['admin-tickets'])
def update_ticket_status_route_route(
    country_code: str,
    ticket_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    status: str = Body('open')
):
    return update_ticket_status_route(country_code=country_code, ticket_id=ticket_id, current_user=current_user, db=db, status=status)
