"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body, Query
from sqlalchemy.orm import Session
from infrastructure.database.database import get_db
from infrastructure.utils.dependencies import require_admin
from typing import Optional

from infrastructure.database.schemas import ArchiveRequest
from infrastructure.database.schemas import BulkActionRequest
from domains.catalog.services.categories.admin_categories_service import archive_category
from domains.catalog.services.categories.admin_categories_service import bulk_archive_categories
from domains.catalog.services.categories.admin_categories_service import bulk_restore_categories
from domains.accounts.services.permissions.permission_service import create_category
from domains.accounts.services.permissions.permission_service import delete_category
from domains.accounts.services.permissions.permission_service import list_categories
from domains.catalog.services.categories.admin_categories_service import reorder_categories
from domains.catalog.services.categories.admin_categories_service import restore_category
from domains.accounts.services.permissions.permission_service import update_category

router = APIRouter(prefix="/api/v1/admin")

@router.get("/categories/{country_code}", status_code=200, tags=['admin-categories'])
def list_categories_route(
    country_code: str,
    include_deleted: bool = Query(False),
    page: int = Query(1),
    page_size: int = Query(20),
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return list_categories(country_code=country_code, include_deleted=include_deleted, page=page, page_size=page_size, current_user=current_user, db=db)

@router.post("/categories/{country_code}", status_code=201, tags=['admin-categories'])
def create_category_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    name: Optional[str] = Body(None),
    slug: Optional[str] = Body(None),
    parent_id: Optional[int] = Body(None),
    sort_order: int = Body(0),
    description: Optional[str] = Body(None)
):
    return create_category(country_code=country_code, current_user=current_user, db=db, name=name, slug=slug, parent_id=parent_id, sort_order=sort_order, description=description)

@router.put("/categories/{country_code}/{category_id}", status_code=200, tags=['admin-categories'])
def update_category_route(
    country_code: str,
    category_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    name: Optional[str] = Body(None),
    slug: Optional[str] = Body(None),
    parent_id: Optional[int] = Body(None),
    sort_order: Optional[int] = Body(None),
    description: Optional[str] = Body(None)
):
    return update_category(country_code=country_code, category_id=category_id, current_user=current_user, db=db, name=name, slug=slug, parent_id=parent_id, sort_order=sort_order, description=description)

@router.post("/categories/{country_code}/{category_id}/archive", status_code=201, tags=['admin-categories'])
def archive_category_route(
    country_code: str,
    category_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    payload: ArchiveRequest = Body(...)
):
    return archive_category(country_code=country_code, category_id=category_id, current_user=current_user, db=db, payload=payload)

@router.post("/categories/{country_code}/{category_id}/restore", status_code=201, tags=['admin-categories'])
def restore_category_route(
    country_code: str,
    category_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return restore_category(country_code=country_code, category_id=category_id, current_user=current_user, db=db)

@router.post("/categories/{country_code}/reorder", status_code=201, tags=['admin-categories'])
def reorder_categories_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    order: Optional[dict] = Body(None)
):
    return reorder_categories(country_code=country_code, current_user=current_user, db=db, order=order)

@router.post("/categories/{country_code}/bulk/archive", status_code=201, tags=['admin-categories'])
def bulk_archive_categories_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    payload: BulkActionRequest = Body(...)
):
    return bulk_archive_categories(country_code=country_code, current_user=current_user, db=db, payload=payload)

@router.post("/categories/{country_code}/bulk/restore", status_code=201, tags=['admin-categories'])
def bulk_restore_categories_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    payload: BulkActionRequest = Body(...)
):
    return bulk_restore_categories(country_code=country_code, current_user=current_user, db=db, payload=payload)

@router.delete("/categories/{country_code}/{category_id}", status_code=200, tags=['admin-categories'])
def delete_category_route(
    country_code: str,
    category_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return delete_category(country_code=country_code, category_id=category_id, current_user=current_user, db=db)
