"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body, Query
from sqlalchemy.orm import Session
from infrastructure.database.database import get_db
from infrastructure.utils.dependencies import require_admin
from typing import Optional

from domains.catalog.services.products_controller import approve_product_route
from domains.catalog.services.products_controller import bulk_delete_products_route
from domains.catalog.services.products_controller import list_pending_products
from domains.catalog.services.products_controller import reject_product_route
from domains.catalog.services.products_controller import toggle_product_badge_route
from domains.catalog.services.products_controller import unarchive_product_route

router = APIRouter(prefix="/api/v1/admin")

@router.get("/products/{country_code}/pending", status_code=200, tags=['admin-products'])
def list_pending_products_route(
    country_code: str,
    page: int = Query(1),
    page_size: int = Query(50),
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return list_pending_products(country_code=country_code, page=page, page_size=page_size, current_user=current_user, db=db)

@router.post("/products/{country_code}/{product_id}/approve", status_code=201, tags=['admin-products'])
def approve_product_route_route(
    country_code: str,
    product_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return approve_product_route(country_code=country_code, product_id=product_id, current_user=current_user, db=db)

@router.post("/products/{country_code}/{product_id}/reject", status_code=201, tags=['admin-products'])
def reject_product_route_route(
    country_code: str,
    product_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    note: Optional[str] = Body(None)
):
    return reject_product_route(country_code=country_code, product_id=product_id, current_user=current_user, db=db, note=note)

@router.post("/products/{country_code}/{product_id}/badge", status_code=201, tags=['admin-products'])
def toggle_product_badge_route_route(
    country_code: str,
    product_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    field: str = Body('is_featured', embed=True),
    value: bool = Body(True, embed=True)
):
    return toggle_product_badge_route(country_code=country_code, product_id=product_id, current_user=current_user, db=db, field=field, value=value)

@router.post("/products/{country_code}/bulk/delete", status_code=201, tags=['admin-products'])
def bulk_delete_products_route_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    ids: list[int] = Body(None)
):
    return bulk_delete_products_route(country_code=country_code, current_user=current_user, db=db, ids=ids)

@router.post("/products/{country_code}/{product_id}/unarchive", status_code=201, tags=['admin-products'])
def unarchive_product_route_route(
    country_code: str,
    product_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return unarchive_product_route(country_code=country_code, product_id=product_id, current_user=current_user, db=db)
