"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body, Query
from sqlalchemy.orm import Session
from infrastructure.database.database import get_db
from infrastructure.utils.dependencies import require_admin
from typing import Optional

from domains.orders.services._auto_stubs import create_coupon_route
from domains.orders.services._auto_stubs import delete_coupon_route
from domains.orders.services._auto_stubs import list_coupons_route
from domains.orders.services._auto_stubs import update_coupon_route

router = APIRouter(prefix="/api/v1/admin")

@router.get("/coupons/{country_code}", status_code=200, tags=['admin-coupons'])
def list_coupons_route_route(
    country_code: str,
    search: Optional[str] = Query(None),
    page: int = Query(1),
    page_size: int = Query(50),
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return list_coupons_route(country_code=country_code, search=search, page=page, page_size=page_size, current_user=current_user, db=db)

@router.post("/coupons/{country_code}", status_code=201, tags=['admin-coupons'])
def create_coupon_route_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    code: str = Body('', embed=True),
    title: Optional[str] = Body(None, embed=True),
    description: Optional[str] = Body(None, embed=True),
    discount_type: str = Body('percentage', embed=True),
    discount_value: float = Body(0, embed=True),
    maximum_discount: Optional[float] = Body(None, embed=True),
    minimum_order: float = Body(0, embed=True),
    usage_limit: Optional[int] = Body(None, embed=True),
    per_user_limit: Optional[int] = Body(None, embed=True),
    is_active: bool = Body(True, embed=True),
    starts_at: Optional[str] = Body(None, embed=True),
    expires_at: Optional[str] = Body(None, embed=True)
):
    return create_coupon_route(country_code=country_code, current_user=current_user, db=db, code=code, title=title, description=description, discount_type=discount_type, discount_value=discount_value, maximum_discount=maximum_discount, minimum_order=minimum_order, usage_limit=usage_limit, per_user_limit=per_user_limit, is_active=is_active, starts_at=starts_at, expires_at=expires_at)

@router.put("/coupons/{country_code}/{coupon_id}", status_code=200, tags=['admin-coupons'])
def update_coupon_route_route(
    country_code: str,
    coupon_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    code: Optional[str] = Body(None, embed=True),
    title: Optional[str] = Body(None, embed=True),
    description: Optional[str] = Body(None, embed=True),
    discount_type: Optional[str] = Body(None, embed=True),
    discount_value: Optional[float] = Body(None, embed=True),
    maximum_discount: Optional[float] = Body(None, embed=True),
    minimum_order: Optional[float] = Body(None, embed=True),
    usage_limit: Optional[int] = Body(None, embed=True),
    per_user_limit: Optional[int] = Body(None, embed=True),
    is_active: Optional[bool] = Body(None, embed=True),
    starts_at: Optional[str] = Body(None, embed=True),
    expires_at: Optional[str] = Body(None, embed=True)
):
    return update_coupon_route(country_code=country_code, coupon_id=coupon_id, current_user=current_user, db=db, code=code, title=title, description=description, discount_type=discount_type, discount_value=discount_value, maximum_discount=maximum_discount, minimum_order=minimum_order, usage_limit=usage_limit, per_user_limit=per_user_limit, is_active=is_active, starts_at=starts_at, expires_at=expires_at)

@router.delete("/coupons/{country_code}/{coupon_id}", status_code=200, tags=['admin-coupons'])
def delete_coupon_route_route(
    country_code: str,
    coupon_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return delete_coupon_route(country_code=country_code, coupon_id=coupon_id, current_user=current_user, db=db)
