"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from infrastructure.database.database import get_db
from infrastructure.utils.dependencies import require_admin

from controllers.admin.misc_controller import database_overview

router = APIRouter(prefix="/api/v1/admin")

@router.get("/system/database-overview/{country_code}", status_code=200, tags=['admin-system'])
def database_overview_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return database_overview(country_code=country_code, current_user=current_user, db=db)
