"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from infrastructure.database.database import get_db
from infrastructure.utils.dependencies import require_admin
from typing import Optional

from controllers.admin.audit_controller import audit_actions, audit_log_page

router = APIRouter(prefix="/api/v1/admin")

@router.get("/audit/{country_code}", status_code=200, tags=['admin-audit'])
def audit_log_page_route(
    country_code: str,
    page: int = Query(1),
    page_size: int = Query(50),
    action_filter: Optional[str] = Query(None),
    user_id_filter: Optional[int] = Query(None),
    resource_type_filter: Optional[str] = Query(None),
    status_filter: Optional[str] = Query(None),
    search: Optional[str] = Query(None),
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return audit_log_page(country_code=country_code, page=page, page_size=page_size, action_filter=action_filter, user_id_filter=user_id_filter, resource_type_filter=resource_type_filter, status_filter=status_filter, search=search, current_user=current_user, db=db)

@router.get("/audit/{country_code}/actions", status_code=200, tags=['admin-audit'])
def audit_actions_route(
    country_code: str,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return audit_actions(country_code=country_code, current_user=current_user, db=db)
