"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body, Query
from sqlalchemy.orm import Session
from infrastructure.database.database import get_db
from infrastructure.utils.dependencies import require_admin
from typing import Optional
from datetime import date

from domains.finance.services.accounting_controller import JournalEntryBody
from domains.finance.services.accounting_controller import create_journal_entry
from domains.finance.services.accounting_controller import get_account
from domains.finance.services.accounting_controller import get_account_balance
from domains.finance.services.accounting_controller import get_journal_entry
from domains.finance.services.accounting_controller import get_trial_balance
from domains.finance.services.accounting_controller import list_accounts
from domains.finance.services.accounting_controller import list_journal_entries
from domains.finance.services.accounting_controller import seed_chart_of_accounts

router = APIRouter(prefix="/api/v1/admin")

@router.post("/seed", status_code=201, tags=['accounting'], summary="Seed chart of accounts (idempotent)")
def seed_chart_of_accounts_route(
    db: Session = Depends(get_db),
    audit_user_id: Optional[int] = Query(None),
    audit_username: Optional[str] = Query(None),
    audit_user_role: Optional[str] = Query(None)
) -> dict:
    return seed_chart_of_accounts(db=db, audit_user_id=audit_user_id, audit_username=audit_username, audit_user_role=audit_user_role)

@router.get("/accounts", status_code=200, tags=['accounting'], summary="List all accounts")
def list_accounts_route(
    db: Session = Depends(get_db)
) -> list:
    return list_accounts(db=db)

@router.get("/accounts/{code}", status_code=200, tags=['accounting'], summary="Get account by code")
def get_account_route(
    code: str,
    db: Session = Depends(get_db)
):
    return get_account(db=db, code=code)

@router.post("/journal-entries", status_code=201, tags=['accounting'], summary="Create a journal entry")
def create_journal_entry_route(
    db: Session = Depends(get_db),
    current_user: dict = Depends(require_admin),
    body: JournalEntryBody = Body(...)
) -> dict:
    return create_journal_entry(db=db, current_user=current_user, body=body)

@router.get("/journal-entries/{entry_id}", status_code=200, tags=['accounting'], summary="Get journal entry by ID")
def get_journal_entry_route(
    entry_id: int,
    db: Session = Depends(get_db)
):
    return get_journal_entry(db=db, entry_id=entry_id)

@router.get("/journal-entries", status_code=200, tags=['accounting'], summary="List journal entries")
def list_journal_entries_route(
    db: Session = Depends(get_db),
    reference_type: Optional[str] = Query(None),
    reference_id: Optional[int] = Query(None),
    country_code: Optional[str] = Query(None),
    limit: int = Query(50)
) -> list:
    return list_journal_entries(db=db, reference_type=reference_type, reference_id=reference_id, country_code=country_code, limit=limit)

@router.get("/balances/{account_code}", status_code=200, tags=['accounting'], summary="Get account balance")
def get_account_balance_route(
    account_code: str,
    db: Session = Depends(get_db),
    currency: str = Query('OMR')
) -> dict:
    return get_account_balance(db=db, account_code=account_code, currency=currency)

@router.get("/trial-balance", status_code=200, tags=['accounting'], summary="Get trial balance")
def get_trial_balance_route(
    db: Session = Depends(get_db),
    as_of_date: Optional[date] = Query(None),
    currency: str = Query('OMR'),
    country_code: Optional[str] = Query(None)
) -> list:
    return get_trial_balance(db=db, as_of_date=as_of_date, currency=currency, country_code=country_code)
