"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body
from sqlalchemy.orm import Session
from infrastructure.database.database import get_db

from domains.hr.services.hr_controller import check_coi_conflict
from domains.hr.services.hr_controller import create_coi_report
from domains.hr.services.hr_controller import create_disciplinary_case
from domains.hr.services.hr_controller import create_offboarding_case
from domains.hr.services.hr_controller import get_disciplinary_cases
from domains.hr.services.hr_controller import get_employee_graph
from domains.hr.services.hr_controller import get_offboarding_cases
from domains.hr.services.hr_controller import register_address
from domains.hr.services.hr_controller import register_dependent
from domains.hr.services.hr_controller import validate_gcc_compliance

router = APIRouter(prefix="/api/v1")

@router.post("/hr/{employee_id}/addresses", status_code=201, tags=['hr'])
def register_address_route(
    employee_id: int,
    db: Session = Depends(get_db),
    address_data: dict = Body(...)
) -> dict:
    return register_address(employee_id=employee_id, db=db, address_data=address_data)

@router.post("/hr/{employee_id}/dependents", status_code=201, tags=['hr'])
def register_dependent_route(
    employee_id: int,
    db: Session = Depends(get_db),
    dependent_data: dict = Body(...)
) -> dict:
    return register_dependent(employee_id=employee_id, db=db, dependent_data=dependent_data)

@router.get("/hr/{employee_id}/coi-check", status_code=200, tags=['hr'])
def check_coi_conflict_route(
    employee_id: int,
    db: Session = Depends(get_db)
) -> list[dict]:
    return check_coi_conflict(employee_id=employee_id, db=db)

@router.post("/hr/{employee_id}/coi-report", status_code=201, tags=['hr'])
def create_coi_report_route(
    employee_id: int,
    db: Session = Depends(get_db),
    report_data: dict = Body(...)
) -> dict:
    return create_coi_report(employee_id=employee_id, db=db, report_data=report_data)

@router.get("/hr/{employee_id}/compliance", status_code=200, tags=['hr'])
def validate_gcc_compliance_route(
    employee_id: int,
    db: Session = Depends(get_db)
) -> dict:
    return validate_gcc_compliance(employee_id=employee_id, db=db)

@router.get("/hr/{employee_id}/graph", status_code=200, tags=['hr'])
def get_employee_graph_route(
    employee_id: int,
    db: Session = Depends(get_db)
) -> dict:
    return get_employee_graph(employee_id=employee_id, db=db)

@router.get("/hr/disciplinary", status_code=200, tags=['hr'])
def get_disciplinary_cases_route(
    db: Session = Depends(get_db)
) -> list[dict]:
    return get_disciplinary_cases(db=db)

@router.post("/hr/{employee_id}/disciplinary", status_code=201, tags=['hr'])
def create_disciplinary_case_route(
    employee_id: int,
    db: Session = Depends(get_db),
    case_data: dict = Body(...)
) -> dict:
    return create_disciplinary_case(employee_id=employee_id, db=db, case_data=case_data)

@router.get("/hr/offboarding", status_code=200, tags=['hr'])
def get_offboarding_cases_route(
    db: Session = Depends(get_db)
) -> list[dict]:
    return get_offboarding_cases(db=db)

@router.post("/hr/{employee_id}/offboarding", status_code=201, tags=['hr'])
def create_offboarding_case_route(
    employee_id: int,
    db: Session = Depends(get_db),
    case_data: dict = Body(...)
) -> dict:
    return create_offboarding_case(employee_id=employee_id, db=db, case_data=case_data)
