"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from infrastructure.database.database import get_db
from infrastructure.utils.dependencies import get_current_user
from typing import List, Optional

from domains.orders.services.wishlist_controller import WishlistItemOut
from domains.orders.services.wishlist_controller import add_to_wishlist
from domains.orders.services.wishlist_controller import clear_user_wishlist
from domains.orders.services.wishlist_controller import get_wishlist
from domains.orders.services.wishlist_controller import remove_from_wishlist

router = APIRouter(prefix="/api/v1")

@router.get("", response_model=List[WishlistItemOut], status_code=200, tags=['wishlist'])
def get_wishlist_route(
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    limit: int = Query(200),
    cursor: Optional[int] = Query(None)
) -> List[WishlistItemOut]:
    return get_wishlist(current_user=current_user, db=db, limit=limit, cursor=cursor)

@router.post("/{product_id}", response_model=WishlistItemOut, status_code=201, tags=['wishlist'])
def add_to_wishlist_route(
    product_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    return add_to_wishlist(product_id=product_id, current_user=current_user, db=db)

@router.delete("/{product_id}", response_model=dict, status_code=200, tags=['wishlist'])
def remove_from_wishlist_route(
    product_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> dict:
    return remove_from_wishlist(product_id=product_id, current_user=current_user, db=db)

@router.delete("", response_model=dict, status_code=200, tags=['wishlist'])
def clear_user_wishlist_route(
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> dict:
    return clear_user_wishlist(current_user=current_user, db=db)
