"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from infrastructure.database.database import get_db

from controllers.core.export_controller import export_pay_equity

router = APIRouter(prefix="/api/v1")

@router.get("/export/pay-equity", status_code=200)
def export_pay_equity_route(
    db: Session = Depends(get_db)
):
    return export_pay_equity(db=db)
