"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body
from sqlalchemy.orm import Session
from infrastructure.database.database import get_db
from infrastructure.utils.dependencies import require_admin
from typing import Any

from domains.hr.services.hierarchy.hierarchy_service import assign_matrix
from domains.hr.services.hierarchy.hierarchy_service import create_org_unit
from domains.hr.services.hierarchy.hierarchy_service import reassign_employee_manager
from domains.hr.services.hierarchy.hierarchy_service import rebuild_org_unit_paths
from domains.hr.services.hierarchy.hierarchy_service import refresh_authority_levels
from domains.hr.services.hierarchy.hierarchy_service import remove_matrix
from domains.hr.services.hierarchy.hierarchy_service import update_org_unit

router = APIRouter(prefix="/api/v1")

@router.post("/hierarchy/org-units", status_code=201, tags=['hierarchy'], summary="Create an org unit")
def create_org_unit_route(
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    payload: Any = Body(...)
) -> dict:
    return create_org_unit(current_user=current_user, db=db, payload=payload)

@router.put("/hierarchy/org-units/{unit_id}", status_code=200, tags=['hierarchy'], summary="Update an org unit")
def update_org_unit_route(
    unit_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    payload: Any = Body(...)
) -> dict:
    return update_org_unit(unit_id=unit_id, current_user=current_user, db=db, payload=payload)

@router.post("/hierarchy/org-units/rebuild-paths", status_code=201, tags=['hierarchy'], summary="Rebuild org unit materialized paths")
def rebuild_org_unit_paths_route(
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
) -> dict:
    return rebuild_org_unit_paths(current_user=current_user, db=db)

@router.post("/hierarchy/employees/reassign-manager", status_code=201, tags=['hierarchy'], summary="Reassign an employee's manager")
def reassign_employee_manager_route(
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    payload: Any = Body(...)
) -> dict:
    return reassign_employee_manager(current_user=current_user, db=db, payload=payload)

@router.post("/hierarchy/authority-levels/refresh", status_code=201, tags=['hierarchy'], summary="Refresh authority levels")
def refresh_authority_levels_route(
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
) -> dict:
    return refresh_authority_levels(current_user=current_user, db=db)

@router.post("/hierarchy/matrix", status_code=201, tags=['hierarchy'], summary="Assign a matrix (dotted-line) relation")
def assign_matrix_route(
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    payload: Any = Body(...)
) -> dict:
    return assign_matrix(current_user=current_user, db=db, payload=payload)

@router.delete("/hierarchy/matrix/{relation_id}", status_code=200, tags=['hierarchy'], summary="Remove a matrix relation")
def remove_matrix_route(
    relation_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
) -> dict:
    return remove_matrix(relation_id=relation_id, current_user=current_user, db=db)
