"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body, Query
from sqlalchemy.orm import Session
from infrastructure.database.database import get_db
from infrastructure.utils.dependencies import get_current_user
from typing import List, Optional

from infrastructure.database.schemas import ReviewCreate
from infrastructure.database.schemas import ReviewOut
from domains.customers.services.reviews_service import create_review
from domains.orders.services.orders_package_service import delete_review
from domains.customers.services.reviews_service import get_product_reviews
from domains.orders.services._auto_stubs import get_review
from domains.catalog.ports import list_reviews
from domains.customers.services.reviews_service import update_review

router = APIRouter(prefix="/api/v1")

@router.get("/reviews/products/{product_id}", response_model=List[ReviewOut], status_code=200, tags=['reviews'])
def get_product_reviews_route(
    product_id: int,
    db: Session = Depends(get_db),
    limit: int = Query(50),
    cursor: Optional[int] = Query(None)
) -> List[dict]:
    return get_product_reviews(product_id=product_id, db=db, limit=limit, cursor=cursor)

@router.get("/reviews", response_model=List[ReviewOut], status_code=200, tags=['reviews'])
def list_reviews_route(
    db: Session = Depends(get_db),
    product_id: Optional[int] = Query(None),
    limit: int = Query(50),
    cursor: Optional[int] = Query(None)
) -> List[dict]:
    return list_reviews(db=db, product_id=product_id, limit=limit, cursor=cursor)

@router.get("/reviews/{review_id}", response_model=ReviewOut, status_code=200, tags=['reviews'])
def get_review_route(
    review_id: int,
    db: Session = Depends(get_db)
) -> dict:
    return get_review(review_id=review_id, db=db)

@router.post("/reviews/products/{product_id}", response_model=ReviewOut, status_code=201, tags=['reviews'])
def create_review_route(
    product_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    review: ReviewCreate = Body(...)
) -> dict:
    return create_review(product_id=product_id, current_user=current_user, db=db, review=review)

@router.put("/reviews/{review_id}", response_model=ReviewOut, status_code=200, tags=['reviews'])
def update_review_route(
    review_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    review: ReviewCreate = Body(...)
) -> dict:
    return update_review(review_id=review_id, current_user=current_user, db=db, review=review)

@router.delete("/reviews/{review_id}", response_model=ReviewOut, status_code=200, tags=['reviews'])
def delete_review_route(
    review_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> dict:
    return delete_review(review_id=review_id, current_user=current_user, db=db)
