"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from infrastructure.database.database import get_db
from typing import Any, Dict

from domains.orders.services.referrals_controller import get_referral_code
from domains.orders.services.referrals_controller import get_referral_config

router = APIRouter(prefix="/api/v1")

@router.get("/referrals/config", status_code=200, tags=['referrals'], summary="Get the active referral-program configuration")
def get_referral_config_route(
    db: Session = Depends(get_db)
) -> Dict[str, Any]:
    return get_referral_config(db=db)

@router.get("/referrals/code", status_code=200, tags=['referrals'], summary="Get or create the referral code for a user")
def get_referral_code_route(
    user_id: int = Query(None),
    db: Session = Depends(get_db)
) -> Dict[str, Any]:
    return get_referral_code(user_id=user_id, db=db)
