"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body, Query
from sqlalchemy.orm import Session
from db.database import get_db
from utils.dependencies import require_admin
from typing import Any

from controllers.governance.command_center_controller import alerts_route, command_center_root_route, comprehensive_dashboard_route, create_news_route, dashboard_route, dashboard_stats_route, delete_news_route, fraud_alerts_route, headlines_route, heartbeat_route, news_route, realtime_metrics_route, resolve_alert_route, system_metrics_route, treasury_metrics_route

router = APIRouter(prefix="/api/v1/admin")

@router.get("/command-center/heartbeat", status_code=200, tags=['command-center'])
def heartbeat_route_route(
    db: Session = Depends(get_db)
):
    return heartbeat_route(db=db)

@router.get("/command-center/system-metrics", status_code=200, tags=['command-center'])
def system_metrics_route_route(
    db: Session = Depends(get_db)
):
    return system_metrics_route(db=db)

@router.get("/command-center/treasury-metrics", status_code=200, tags=['command-center'])
def treasury_metrics_route_route(
    db: Session = Depends(get_db)
):
    return treasury_metrics_route(db=db)

@router.get("/command-center/dashboard", status_code=200, tags=['command-center'])
def dashboard_route_route(
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return dashboard_route(current_user=current_user, db=db)

@router.get("/command-center/fraud-alerts", status_code=200, tags=['command-center'])
def fraud_alerts_route_route(
    limit: int = Query(50),
    db: Session = Depends(get_db)
):
    return fraud_alerts_route(limit=limit, db=db)

@router.get("/command-center/news", status_code=200, tags=['command-center'])
def news_route_route(
    limit: int = Query(20),
    category: str = Query(None),
    db: Session = Depends(get_db)
):
    return news_route(limit=limit, category=category, db=db)

@router.get("/command-center/headlines", status_code=200, tags=['command-center'])
def headlines_route_route(
    limit: int = Query(20),
    category: str = Query(None),
    db: Session = Depends(get_db)
):
    return headlines_route(limit=limit, category=category, db=db)

@router.post("/command-center/news", status_code=201, tags=['command-center'])
def create_news_route_route(
    db: Session = Depends(get_db),
    payload: dict = Body(None)
):
    return create_news_route(db=db, payload=payload)

@router.delete("/command-center/news/{news_id}", status_code=200, tags=['command-center'])
def delete_news_route_route(
    news_id: int,
    db: Session = Depends(get_db)
):
    return delete_news_route(news_id=news_id, db=db)

@router.get("/command-center/alerts", status_code=200, tags=['command-center'])
def alerts_route_route(
    severity: str = Query(None),
    db: Session = Depends(get_db)
):
    return alerts_route(severity=severity, db=db)

@router.post("/command-center/alerts/{alert_id}/resolve", status_code=200, tags=['command-center'])
def resolve_alert_route_route(
    alert_id: int,
    db: Session = Depends(get_db)
):
    return resolve_alert_route(alert_id=alert_id, db=db)

@router.get("/command-center/dashboard-stats", status_code=200, tags=['command-center'])
def dashboard_stats_route_route(
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
):
    return dashboard_stats_route(current_user=current_user, db=db)

@router.get("/command-center/realtime-metrics", status_code=200, tags=['command-center'])
def realtime_metrics_route_route(
    db: Session = Depends(get_db)
):
    return realtime_metrics_route(db=db)

@router.get("/command-center/comprehensive-dashboard", status_code=200, tags=['command-center'])
def comprehensive_dashboard_route_route(
    current_user: dict = Depends(require_admin),
    country_code: str = Query(None),
    db: Session = Depends(get_db)
):
    return comprehensive_dashboard_route(current_user=current_user, country_code=country_code, db=db)

@router.get("/command-center/", status_code=200, tags=['command-center'])
def command_center_root_route_route(
    db: Session = Depends(get_db)
):
    return command_center_root_route(db=db)
