"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body
from sqlalchemy.orm import Session
from db.database import get_db
from utils.dependencies import require_admin
from typing import Any, Optional

from controllers.treasury.cash_management_write_controller import auto_reconcile_transactions, create_bank_transaction, dispatch_transfer_batch, flag_transaction, import_bank_transactions, queue_dispatch_transfer_batch, reconcile_transaction, record_badge_billing_payment, record_cod_remittance, record_vat_remittance, reject_cod_remittance_receipt, resolve_transaction_exception, trigger_logistics_payouts, trigger_supplier_payouts, upsert_bank_settings, verify_cod_remittance_receipt

router = APIRouter(prefix="/api/v1/admin")

@router.post("/treasury/badge-billing/{billing_id}/payments", status_code=201, tags=['treasury'])
def record_badge_billing_payment_route(
    billing_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    payment_method: str = Body(...),
    transaction_ref: Optional[str] = Body(None),
    notes: Optional[str] = Body(None)
) -> Any:
    return record_badge_billing_payment(billing_id=billing_id, current_user=current_user, db=db, payment_method=payment_method, transaction_ref=transaction_ref, notes=notes)

@router.put("/treasury/bank-settings", status_code=200, tags=['treasury'])
def upsert_bank_settings_route(
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    data: dict = Body(...)
) -> dict[str, Any]:
    return upsert_bank_settings(current_user=current_user, db=db, data=data)

@router.post("/treasury/vat-remittances", status_code=201, tags=['treasury'])
def record_vat_remittance_route(
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    data: dict = Body(...)
) -> Any:
    return record_vat_remittance(current_user=current_user, db=db, data=data)

@router.post("/treasury/bank-transactions", status_code=201, tags=['treasury'])
def create_bank_transaction_route(
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    data: dict = Body(...)
) -> Any:
    return create_bank_transaction(current_user=current_user, db=db, data=data)

@router.post("/treasury/bank-transactions/import", status_code=201, tags=['treasury'])
def import_bank_transactions_route(
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    items: list[dict] = Body(...),
    auto_reconcile: bool = Body(auto_reconcile: bool)
) -> dict:
    return import_bank_transactions(current_user=current_user, db=db, items=items, auto_reconcile=auto_reconcile)

@router.post("/treasury/bank-transactions/{txn_id}/reconcile", status_code=201, tags=['treasury'])
def reconcile_transaction_route(
    txn_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db)
) -> Any:
    return reconcile_transaction(txn_id=txn_id, current_user=current_user, db=db)

@router.post("/treasury/bank-transactions/{txn_id}/flag", status_code=201, tags=['treasury'])
def flag_transaction_route(
    txn_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    reason: str = Body(...)
) -> Any:
    return flag_transaction(txn_id=txn_id, current_user=current_user, db=db, reason=reason)

@router.post("/treasury/bank-transactions/{txn_id}/resolve", status_code=201, tags=['treasury'])
def resolve_transaction_exception_route(
    txn_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    data: dict = Body(...)
) -> Any:
    return resolve_transaction_exception(txn_id=txn_id, current_user=current_user, db=db, data=data)

@router.post("/treasury/bank-transactions/auto-reconcile", status_code=201, tags=['treasury'])
def auto_reconcile_transactions_route(
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    limit: int = Body(limit: int),
    source: Optional[str] = Body(source: Optional[str]),
    category: Optional[str] = Body(category: Optional[str])
) -> dict:
    return auto_reconcile_transactions(current_user=current_user, db=db, limit=limit, source=source, category=category)

@router.post("/treasury/payouts/supplier", status_code=201, tags=['treasury'])
def trigger_supplier_payouts_route(
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    settlement_ids: Optional[list[int]] = Body(None)
) -> list[dict]:
    return trigger_supplier_payouts(current_user=current_user, db=db, settlement_ids=settlement_ids)

@router.post("/treasury/payouts/logistics", status_code=201, tags=['treasury'])
def trigger_logistics_payouts_route(
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    settlement_ids: Optional[list[int]] = Body(None)
) -> list[dict]:
    return trigger_logistics_payouts(current_user=current_user, db=db, settlement_ids=settlement_ids)

@router.post("/treasury/transfers/dispatch", status_code=201, tags=['treasury'])
def dispatch_transfer_batch_route(
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    kind: str = Body(...),
    provider: Optional[str] = Body(provider: Optional[str]),
    dry_run: bool = Body(dry_run: bool)
) -> dict[str, Any]:
    return dispatch_transfer_batch(current_user=current_user, db=db, kind=kind, provider=provider, dry_run=dry_run)

@router.post("/treasury/transfers/dispatch/queue", status_code=201, tags=['treasury'])
def queue_dispatch_transfer_batch_route(
    current_user: dict = Depends(require_admin),
    kind: str = Body(...),
    provider: Optional[str] = Body(provider: Optional[str]),
    dry_run: bool = Body(dry_run: bool)
) -> dict[str, Any]:
    return queue_dispatch_transfer_batch(current_user=current_user, kind=kind, provider=provider, dry_run=dry_run)

@router.post("/treasury/cod/{settlement_id}/remittance", status_code=201, tags=['treasury'])
def record_cod_remittance_route(
    settlement_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    amount: float = Body(...)
) -> Any:
    return record_cod_remittance(settlement_id=settlement_id, current_user=current_user, db=db, amount=amount)

@router.post("/treasury/cod/receipts/{receipt_id}/verify", status_code=201, tags=['treasury'])
def verify_cod_remittance_receipt_route(
    receipt_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    note: Optional[str] = Body(None)
) -> dict[str, Any]:
    return verify_cod_remittance_receipt(receipt_id=receipt_id, current_user=current_user, db=db, note=note)

@router.post("/treasury/cod/receipts/{receipt_id}/reject", status_code=201, tags=['treasury'])
def reject_cod_remittance_receipt_route(
    receipt_id: int,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    note: str = Body(...)
) -> dict[str, Any]:
    return reject_cod_remittance_receipt(receipt_id=receipt_id, current_user=current_user, db=db, note=note)
