"""Generate data dictionary from SQLAlchemy models.

This script introspects the SQLAlchemy Base.metadata and generates
a markdown data dictionary documenting all tables, columns, and relationships.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from sqlalchemy import inspect

from models import Base


def generate_data_dictionary():
    """Generate a markdown data dictionary from the SQLAlchemy models."""
    inspector = inspect(Base.metadata)
    
    lines = [
        "# ZOZI Platform — GENERATED DATA DICTIONARY",
        "",
        "This document is auto-generated from `backend/scripts/generate_data_dictionary.py`.",
        "Do not edit manually — regenerate after any schema change.",
        "",
        "---",
        "",
        "## Table Index (by Schema)",
        "",
    ]
    
    tables_by_schema = {}
    for table in Base.metadata.sorted_tables:
        schema = table.schema or "public"
        if schema not in tables_by_schema:
            tables_by_schema[schema] = []
        tables_by_schema[schema].append(table)
    
    for schema, tables in sorted(tables_by_schema.items()):
        lines.append(f"### {schema}")
        lines.append("")
        for table in tables:
            lines.append(f"- `{table.name}` ({len(table.columns)} columns)")
        lines.append("")
    
    lines.extend([
        "---",
        "",
        "## Detailed Table Definitions",
        "",
    ])
    
    for table in Base.metadata.sorted_tables:
        schema = table.schema or "public"
        lines.append(f"### {schema}.{table.name}")
        lines.append("")
        lines.append("| Column | Type | Nullable | Primary Key | Foreign Key |")
        lines.append("|--------|------|----------|-------------|-------------|")
        
        for column in table.columns:
            fk = ""
            if column.foreign_keys:
                fk_parts = []
                for fk in column.foreign_keys:
                    ref = fk.column
                    fk_parts.append(f"{ref.table.name}.{ref.name}")
                fk = ", ".join(fk_parts)
            
            lines.append(f"| `{column.name}` | {column.type} | {column.nullable} | {column.primary_key} | {fk} |")
        
        lines.append("")
        
        if table.foreign_keys:
            lines.append("**Relationships:**")
            for fk in table.foreign_keys:
                lines.append(f"- `{column.name}` → `{fk.column.table.name}.{fk.column.name}`")
            lines.append("")
    
    lines.extend([
        "---",
        "",
        "*Generated by `backend/scripts/generate_data_dictionary.py`*",
    ])
    
    output = "\n".join(lines)
    
    output_path = Path(__file__).parent.parent / "GENERATED_DATA_DICTIONARY.md"
    output_path.write_text(output)
    print(f"Generated data dictionary: {output_path}")


if __name__ == "__main__":
    generate_data_dictionary()