"""Generate the bounded-context schema migration from ORM metadata.

This script reads all ORM models, extracts their table names and schema assignments,
and generates a migration file with the exact mapping. This guarantees the migration
matches the code exactly.
"""
import os
import sys

os.environ.setdefault("SECRET_KEY", "test-key-for-phase-2")
os.environ.setdefault("FIELD_ENCRYPTION_KEY", "test-enc-key-32characters-long")

sys.path.insert(0, ".")

from db.base import Base
from collections import defaultdict

# Build the mapping from ORM models
table_schema_pairs = []
for k, v in sorted(Base.metadata.tables.items()):
    if v.schema:
        table_name = k.split('.')[-1]
        schema_name = v.schema
        table_schema_pairs.append((table_name, schema_name))

# Also collect all unique schemas
all_schemas = sorted(set(v.schema for v in Base.metadata.tables.values() if v.schema))

# Generate the migration file
header = '''"""bounded_context_schema_migration - REGENERATED from ORM metadata

Revision ID: 20260730_0005
Revises: 20260730_0004
Create Date: 2026-07-30

This migration moves all tables from the public schema into their
correct bounded-context schemas. The mapping is generated directly from
the ORM model __table_args__={"schema": "<context>"} declarations to
guarantee the migration matches the code exactly.

Generated by scripts/generate_schema_migration.py
"""
from typing import Sequence, Union

from alembic import op


revision: str = "20260730_0005"
down_revision: Union[str, None] = "20260730_0004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ALL_SCHEMAS = [
'''

mid = '\n]\n\nTABLE_SCHEMA_MAP = [\n'
for table_name, schema_name in table_schema_pairs:
    mid += f'    ("{table_name}", "{schema_name}"),\n'
mid += ']\n\n\n'

upgrade_down = '''def upgrade() -> None:
    conn = op.get_bind()
    if conn.dialect.name == "sqlite":
        return

    for schema_name in ALL_SCHEMAS:
        op.execute('CREATE SCHEMA IF NOT EXISTS "%s"' % schema_name)

    for table_name, schema_name in TABLE_SCHEMA_MAP:
        op.execute(
            'ALTER TABLE IF EXISTS public."%s" SET SCHEMA "%s"'
            % (table_name, schema_name)
        )

    op.execute(
        'SET search_path TO '
        '"core", "commerce", "finance", "country", "configuration", '
        '"customer", "analytics", "audit", "communication", "hr", '
        '"logistics", "media", "security", "supplier", "trading", '
        '"treasury", "ai", "public"'
    )


def downgrade() -> None:
    conn = op.get_bind()
    if conn.dialect.name == "sqlite":
        return

    for table_name, schema_name in TABLE_SCHEMA_MAP:
        op.execute(
            'ALTER TABLE IF EXISTS "%s"."%s" SET SCHEMA public'
            % (schema_name, table_name)
        )

    for schema_name in ALL_SCHEMAS:
        op.execute('DROP SCHEMA IF EXISTS "%s" CASCADE' % schema_name)
'''

# Build schemas list
schemas_list = ""
for s in all_schemas:
    schemas_list += f'    "{s}",\n'

content = header + schemas_list + mid + upgrade_down

# Write the migration file
migration_path = os.path.join("alembic", "versions", "2026_07_30_0005-20260730_0005_bounded_context_schema_migration.py")
with open(migration_path, "w") as f:
    f.write(content)

print(f"Generated migration with {len(table_schema_pairs)} table-to-schema mappings")
print(f"Schemas: {all_schemas}")
print(f"Written to: {migration_path}")
