"""Single SQL-seed loader for ZOZI (dev/legacy offline utility).

Loads seed rows from the **canonical Python module**
``infrastructure/database/seed/_seed_constants.py`` and writes them via raw
SQL to a local SQLite database. The same Python constants are mirrored to
the ``seed_data/*_full.json`` files (regenerated by
``scripts/regen_seed_json.py``) so any downstream tool that still reads the
JSON keeps working. New code should use the canonical Python module.

The **production** seed path is ``infrastructure.database.seed._common.seed_data()``
which inserts directly into the Neon PostgreSQL tables via SQLAlchemy ORM.
This script is a dev-only offline tool and is deprecated for production use.

Usage:
    cd backend
    python -m scripts.seed_loader --country ALL      # seed every country
    python -m scripts.seed_loader --country AE       # seed only AE rows
    python -m scripts.seed_loader --country SA       # seed only SA rows
    python -m scripts.seed_loader --country ALL --reset  # truncate first

Country scope aligns with Law 5 (country is the orthogonal scope axis).
Money values remain strings in the seed constants so they round-trip as
Decimal per Law 19.
"""
from __future__ import annotations

import argparse
import os
import sqlite3
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable

BACKEND_ROOT = Path(__file__).resolve().parent.parent
# Legacy JSON directory (kept for backward-compat with any tools that still
# read the JSON files; the JSON is regenerated from the Python constants
# module whenever the constants change).
SEED_DIR = BACKEND_ROOT / "infrastructure" / "database" / "seed_data"
# ADR-019: SQLite dev DB lives under backend/var/ (not backend/) so it never
# collides with the application package layout or ships in container images.
DB_PATH = BACKEND_ROOT / "var" / "zozi.db"
DB_PATH.parent.mkdir(parents=True, exist_ok=True)

ALLOWED_COUNTRIES = {"AE", "SA"}

# Mapping from JSON file name to the Python constants module attribute.
# New seed data should be added to ``_seed_constants.py``; this map points
# legacy JSON lookups to the same data.
_JSON_TO_CONSTANT = {
    "suppliers_full.json": "SUPPLIERS",
    "customers_full.json": "CUSTOMERS",
    "products_full.json": "PRODUCTS",
    "logistics_partners_full.json": "LOGISTICS_PARTNERS",
    "banners_full.json": "BANNERS",
    "flash_discounts_full.json": "FLASH_DISCOUNTS",
    "employees_full.json": "EMPLOYEES",
    "country_staff_assignments_full.json": "COUNTRY_STAFF_ASSIGNMENTS",
    "banks_full.json": "BANKS",
    "cities_full.json": "CITIES",
    "commissions_full.json": "COMMISSIONS",
    "payment_gateways_full.json": "PAYMENT_GATEWAYS",
    "tax_rules_full.json": "TAX_RULES",
    "categories_full.json": "CATEGORIES",
}


def _utcnow() -> str:
    return datetime.utcnow().isoformat()


def _load_json(name: str) -> dict[str, Any]:
    """Load seed data from the canonical Python constants module.

    The legacy ``seed_data/<name>`` JSON files are mirrored from the same
    constants; if the constants module is unavailable we fall back to JSON
    for offline dev tools.
    """
    constant_name = _JSON_TO_CONSTANT.get(name)
    if constant_name:
        try:
            from infrastructure.database.seed import _seed_constants
            value = getattr(_seed_constants, constant_name, None)
            if value is not None:
                return value
        except ImportError:
            pass
    # Backward-compat fallback: read from the legacy JSON file.
    import json
    path = SEED_DIR / name
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def _filter_by_country(rows: Iterable[dict[str, Any]], country: str) -> list[dict[str, Any]]:
    if country == "ALL":
        return list(rows)
    if country not in ALLOWED_COUNTRIES:
        raise ValueError(f"Unknown country {country!r}. Use one of {ALLOWED_COUNTRIES} or ALL.")
    return [r for r in rows if r.get("country_code") == country]


def _exec_many(cur: sqlite3.Cursor, sql: str, rows: list[tuple]) -> int:
    """Insert rows one at a time, skipping FK violations.

    Some pre-existing rows in the demo DB have stale supplier FKs (the original
    audit's data-integrity issue, not ours). INSERT OR IGNORE keeps the
    loader non-destructive: if the row already exists or the FK is bad, we
    move on rather than crashing the whole seed run.
    """
    if not rows:
        return 0
    # Convert to INSERT OR IGNORE
    ignored = sql.replace("INSERT OR REPLACE", "INSERT OR IGNORE", 1)
    n = 0
    for row in rows:
        try:
            cur.execute(ignored, row)
            n += 1
        except sqlite3.IntegrityError:
            # Skip row that fails FK check; pre-existing data
            continue
    return n


def seed_suppliers(cur: sqlite3.Cursor, country: str) -> int:
    data = _load_json("suppliers_full.json").get("suppliers", [])
    rows = _filter_by_country(data, country)
    now = _utcnow()
    out: list[tuple] = []
    for s in rows:
        out.append((
            s["uuid"],
            1,                                  # version
            0,                                  # is_deleted
            None,                               # deleted_at
            None,                               # deleted_by
            None,                               # created_by
            None,                               # updated_by
            s["id"],
            s["user_id"],
            s["business_name"],
            s["country_code"],
            s.get("address"),
            s.get("website"),
            s.get("bio"),
            s.get("business_type"),
            None,                               # verified_documents
            1 if s.get("is_verified") else 0,
            s.get("verification_status", "pending"),
            s.get("credibility_score", 0.0),
            now, now,
        ))
    sql = (
        "INSERT OR REPLACE INTO supplier_profiles "
        "(uuid, version, is_deleted, deleted_at, deleted_by, created_by, updated_by, "
        " id, user_id, business_name, country_code, address, website, bio, business_type, "
        " verified_documents, is_verified, verification_status, credibility_score, "
        " created_at, updated_at) VALUES "
        "(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
    )
    return _exec_many(cur, sql, out)


def seed_customers(cur: sqlite3.Cursor, country: str) -> int:
    data = _load_json("customers_full.json").get("customers", [])
    rows = _filter_by_country(data, country)
    now = _utcnow()
    out: list[tuple] = []
    for c in rows:
        out.append((
            f"c{c['country_code'].lower()}{c['id']:013d}"[:32],  # uuid (CHAR(32))
            1,                                  # version
            0,                                  # is_deleted
            None,                               # deleted_at
            None,                               # deleted_by_id
            None,                               # created_by_id
            None,                               # updated_by
            c["id"],
            c["name"],
            c.get("tax_id"),
            c.get("contact_email"),
            c.get("currency", "AED" if c["country_code"] == "AE" else "SAR"),
            c.get("payment_terms_days", 30),
            c.get("credit_limit", "0.00"),
            c["country_code"],
            1 if c.get("is_active", True) else 0,
            now, now,
        ))
    sql = (
        "INSERT OR REPLACE INTO customers "
        "(uuid, version, is_deleted, deleted_at, deleted_by_id, created_by_id, updated_by, "
        " id, name, tax_id, contact_email, currency, payment_terms_days, credit_limit, "
        " country_code, is_active, created_at, updated_at) VALUES "
        "(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
    )
    return _exec_many(cur, sql, out)


def seed_logistics_partners(cur: sqlite3.Cursor, country: str) -> int:
    data = _load_json("logistics_partners_full.json").get("logistics_partners", [])
    rows = _filter_by_country(data, country)
    now = _utcnow()
    out: list[tuple] = []
    for lp in rows:
        out.append((
            f"lp{lp['country_code'].lower()}{lp['id']:013d}"[:32],  # uuid (CHAR(32))
            1,                                  # version
            now,                                # updated_at
            0,                                  # is_deleted
            None,                               # deleted_at
            None,                               # deleted_by
            None,                               # created_by
            None,                               # updated_by
            lp["id"],
            lp["user_id"],
            lp["name"],
            lp["code"],
            lp.get("contact_name"),
            lp.get("contact_email"),
            lp.get("contact_phone"),
            lp.get("website"),
            lp.get("coverage_regions"),
            lp.get("service_types"),
            lp.get("status_code", "active"),
            lp.get("verification_status", "pending"),
            None,                               # verification_note
            None,                               # verified_by
            None,                               # verified_at
            lp["country_code"],
            now,
            lp.get("business_type"),
            lp.get("region"),
            lp.get("city"),
            lp.get("address"),
            lp.get("postal_code"),
            lp.get("tax_id"),
            lp.get("bio"),
            None,                               # about_us
            None,                               # logo_url
            None,                               # banner_url
            None,                               # latitude
            None,                               # longitude
            None,                               # social_links
            None,                               # notes
            1 if lp.get("is_terms_accepted") else 0,
            lp.get("terms_version"),
            None,                               # terms_accepted_at
        ))
    sql = (
        "INSERT OR REPLACE INTO logistics_partners "
        "(uuid, version, updated_at, is_deleted, deleted_at, deleted_by, created_by, updated_by, "
        " id, user_id, name, code, contact_name, contact_email, contact_phone, website, "
        " coverage_regions, service_types, status_code, verification_status, "
        " verification_note, verified_by, verified_at, country_code, created_at, "
        " business_type, region, city, address, postal_code, tax_id, bio, about_us, "
        " logo_url, banner_url, latitude, longitude, social_links, notes, "
        " is_terms_accepted, terms_version, terms_accepted_at) VALUES "
        "(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
    )
    return _exec_many(cur, sql, out)


def seed_products(cur: sqlite3.Cursor, country: str) -> int:
    data = _load_json("products_full.json").get("products", [])
    rows = _filter_by_country(data, country)
    now = _utcnow()
    out: list[tuple] = []
    for p in rows:
        out.append((
            p["id"],
            p["name"],
            p["slug"],
            p.get("description"),
            p.get("short_description"),
            p.get("ai_description"),
            p["sku"],
            p.get("barcode"),
            p["price"],
            p.get("compare_price"),
            p.get("cost_price"),
            p.get("stock", 0),
            p.get("low_stock_threshold", 5),
            p.get("weight"),
            p.get("dimensions"),
            p.get("materials"),
            p.get("image_url"),
            p.get("images"),
            p.get("category"),
            p.get("category_id"),
            p.get("tags"),
            p.get("attributes"),
            p["supplier_id"],
            p["country_code"],
            1 if p.get("is_active", True) else 0,
            1 if p.get("is_featured", False) else 0,
            0,                                  # is_digital
            1 if p.get("is_approved", True) else 0,
            "approved",
            p.get("brand"),
            p.get("color"),
            p.get("sizes"),
            p.get("rating", 0.0),
            p.get("sales_count", 0),
            p.get("meta_title"),
            p.get("meta_description"),
            1 if p.get("is_approved", True) else 0,
            0,                                  # is_deleted
            p.get("discount_starts_at"),
            p.get("discount_ends_at"),
            now, now,
        ))
    sql = (
        "INSERT OR REPLACE INTO products "
        "(id, name, slug, description, short_description, ai_description, sku, barcode, "
        " price, compare_price, cost_price, stock, low_stock_threshold, weight, dimensions, "
        " materials, image_url, images, category, category_id, tags, attributes, "
        " supplier_id, country_code, is_active, is_featured, is_digital, is_verified, "
        " moderation_status, brand, color, sizes, rating, sales_count, "
        " meta_title, meta_description, is_approved, is_deleted, "
        " discount_starts_at, discount_ends_at, created_at, updated_at) VALUES "
        "(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
    )
    return _exec_many(cur, sql, out)


def seed_banners(cur: sqlite3.Cursor, country: str) -> int:
    data = _load_json("banners_full.json").get("banners", [])
    rows = _filter_by_country(data, country)
    now = _utcnow()
    out: list[tuple] = []
    for b in rows:
        out.append((
            b["id"],
            b["title"],
            b.get("subtitle"),
            b.get("image_url"),
            b.get("link"),
            b.get("banner_type", "promotion"),
            1 if b.get("is_active", True) else 0,
            0,                                  # is_deleted
            None,                               # deleted_at
            None,                               # deleted_by_id
            b.get("sort_order", 0),
            b.get("bg_color"),
            b.get("text_color"),
            b.get("subtitle_color"),
            b.get("btn_bg_color"),
            b.get("btn_text_color"),
            b.get("badge_text"),
            b.get("badge_color"),
            b.get("effect"),
            b.get("video_url"),
            b.get("cta_label"),
            b.get("cta_url"),
            b.get("starts_at"),
            b.get("ends_at"),
            None,                               # created_by_id
            b["country_code"],
            now, now,
        ))
    sql = (
        "INSERT OR REPLACE INTO banners "
        "(id, title, subtitle, image_url, link, banner_type, is_active, is_deleted, "
        " deleted_at, deleted_by_id, sort_order, bg_color, text_color, subtitle_color, "
        " btn_bg_color, btn_text_color, badge_text, badge_color, effect, video_url, "
        " cta_label, cta_url, starts_at, ends_at, created_by_id, country_code, "
        " created_at, updated_at) VALUES "
        "(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
    )
    return _exec_many(cur, sql, out)


def seed_flash_discounts(cur: sqlite3.Cursor, country: str) -> int:
    """Seed promotions.flash_sales for demo flash sale campaigns.

    The flash_discounts_full.json file is keyed to the production model
    (FlashSale in domains.promotions.models.promotions). The seeder skips
    silently if the table is missing so the loader remains idempotent.
    """
    cur.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name='flash_sales' AND sql LIKE '%promotions%'"
    )
    if cur.fetchone() is None:
        # Fall back to a non-schema-qualified table (SQLite creates tables
        # without an explicit schema by default).
        cur.execute(
            "SELECT name FROM sqlite_master WHERE type='table' "
            "AND name='flash_sales'"
        )
        if cur.fetchone() is None:
            print("  flash_sales: table missing, skipping")
            return 0
    data = _load_json("flash_discounts_full.json").get("flash_discounts", [])
    rows = _filter_by_country(data, country)
    now = _utcnow()
    out: list[tuple] = []
    for f in rows:
        out.append((
            f["id"],
            f["title"],
            f.get("description"),
            f.get("starts_at"),
            f.get("ends_at"),
            f.get("discount_pct", "0.00"),
            1 if f.get("is_active", True) else 0,
            0,
            None,
            None,
            f["country_code"],
            now, now,
        ))
    sql = (
        "INSERT OR REPLACE INTO flash_sales "
        "(id, title, description, starts_at, ends_at, discount_pct, is_active, "
        " is_deleted, deleted_at, deleted_by_id, country_code, created_at, updated_at) "
        "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)"
    )
    return _exec_many(cur, sql, out)


def seed_country_staff_assignments(cur: sqlite3.Cursor, country: str) -> int:
    """Seed country_staff_assignments for demo admin/supplier/customer.

    Required so that ``auth.country_access_check()`` returns the right
    country for the demo users (Law 5: country is the orthogonal scope
    axis). Without these rows, the empty table causes RLS to grant
    access to every country, defeating country isolation.
    """
    cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='country_staff_assignments'")
    if cur.fetchone() is None:
        print("  country_staff_assignments: table missing, skipping")
        return 0

    data = _load_json("country_staff_assignments_full.json").get("country_staff_assignments", [])
    rows = _filter_by_country(data, country)
    if not rows:
        return 0

    email_to_id: dict[str, int] = {}
    cur.execute("SELECT id, email FROM users")
    for uid, email in cur.fetchall():
        if email:
            email_to_id[email] = uid

    now = _utcnow()
    out: list[tuple] = []
    for a in rows:
        uid = email_to_id.get(a["user_email"])
        if uid is None:
            continue
        out.append((
            a["id"],
            uid,
            a["country_code"],
            a.get("role_in_country", "country_manager"),
            1 if a.get("is_active", True) else 0,
            None,                               # assigned_by
            a.get("notes"),
            1,                                  # version (audit columns)
            now, now,
        ))
    sql = (
        "INSERT OR REPLACE INTO country_staff_assignments "
        "(id, user_id, country_code, role_in_country, is_active, assigned_by, "
        " notes, version, created_at, updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)"
    )
    return _exec_many(cur, sql, out)


def seed_employees(cur: sqlite3.Cursor, country: str) -> int:
    data = _load_json("employees_full.json").get("employees", [])
    rows = _filter_by_country(data, country)
    now = _utcnow()
    out: list[tuple] = []
    for e in rows:
        out.append((
            e["id"],
            e["user_id"],
            e.get("employee_code"),
            e.get("office_id"),
            e.get("department"),
            e.get("position"),
            e.get("employment_type", "full_time"),
            e.get("employment_status", "active"),
            e.get("salary"),
            e.get("currency", "AED" if e["country_code"] == "AE" else "SAR"),
            e["country_code"],
            e.get("hire_date") or "2026-01-01",
            e.get("termination_date"),
            1 if e.get("is_verified") else 0,
            e.get("gender"),
            e.get("years_of_experience"),
            e.get("performance_score"),
            e.get("education_level"),
            e.get("notes"),
            e.get("reporting_manager_id"),
            e.get("hiring_manager_id"),
            e.get("authority_level", 1),
            e.get("org_unit_id"),
            0,                                  # is_deleted
            now, now,
        ))
    sql = (
        "INSERT OR REPLACE INTO employees "
        "(id, user_id, employee_code, office_id, department, position, employment_type, "
        " employment_status, salary, currency, country_code, hire_date, termination_date, "
        " is_verified, gender, years_of_experience, performance_score, education_level, "
        " notes, reporting_manager_id, hiring_manager_id, authority_level, org_unit_id, "
        " is_deleted, created_at, updated_at) VALUES "
        "(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
    )
    return _exec_many(cur, sql, out)


def seed_categories(cur: sqlite3.Cursor, country: str) -> int:
    """Minimal categories seed.

    The ``products_full.json`` references integer ``category_id`` values (1=fashion,
    5=electronics, 8=beauty, 12=grocery) that the ``categories`` table must hold
    for the products FK to succeed.  The detailed taxonomy lives in
    ``categories_full.json``; we only seed the four top-level categories that
    the 2-country demo product set actually points at.
    """
    cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='categories'")
    if cur.fetchone() is None:
        print("  categories: table missing, skipping")
        return 0
    now = _utcnow()
    rows = [
        (1, "Fashion", "fashion", None, 1, 1, "0.0500", now, now, 0, "AE", 1),
        (5, "Electronics", "electronics", None, 1, 1, "0.0300", now, now, 0, "AE", 1),
        (8, "Beauty", "beauty", None, 1, 0, "0.0500", now, now, 0, "AE", 1),
        (12, "Grocery", "grocery", None, 1, 0, "0.0200", now, now, 0, "AE", 1),
    ]
    if country in ("SA", "ALL"):
        sa_rows = [
            (1, "Fashion", "fashion", None, 1, 1, "0.0500", now, now, 0, "SA", 1),
            (5, "Electronics", "electronics", None, 1, 1, "0.0300", now, now, 0, "SA", 1),
            (8, "Beauty", "beauty", None, 1, 0, "0.0500", now, now, 0, "SA", 1),
            (12, "Grocery", "grocery", None, 1, 0, "0.0200", now, now, 0, "SA", 1),
        ]
        if country == "SA":
            rows = [r for r in rows if r[10] == "SA"]
    sql = (
        "INSERT OR REPLACE INTO categories "
        "(id, name, slug, description, parent_id, is_active, commission_rate, "
        " created_at, updated_at, is_deleted, country_code, sort_order) VALUES "
        "(?,?,?,?,?,?,?,?,?,?,?,?)"
    )
    n = 0
    for row in rows:
        try:
            cur.execute(sql, row)
            n += 1
        except sqlite3.IntegrityError as e:
            print(f"  category id={row[0]} {row[1]}: {e}")
    return n


def seed_users(cur: sqlite3.Cursor, country: str) -> int:
    """Seed the demo users (admin, supplier, customer, logistics, employees).

    The country_staff_assignments loader joins by user_email, so without these
    rows the assignments silently produce zero inserts.  Passwords match the
    SEED_*_PASSWORD values documented in ``backend/.env``.
    """
    cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='users'")
    if cur.fetchone() is None:
        print("  users: table missing, skipping")
        return 0
    now = _utcnow()
    # bcrypt hash of 'DevSeed123!' is too heavy to compute inline; use a known
    # pre-computed hash.  The pre-seeded demo users from
    # ``scripts/create_demo_db.py`` use the same value.
    # $2b$12$.... corresponds to bcrypt of 'DevSeed123!' (matches SEED_DEMO_PASSWORD)
    from passlib.hash import bcrypt as _bcrypt
    try:
        pwd_hash = _bcrypt.hash("DevSeed123!")
    except Exception:
        # Fallback: pre-computed hash for 'DevSeed123!' generated with bcrypt.
        # This hash was produced via passlib bcrypt.hashpw('DevSeed123!', bcrypt.gensalt(12)).
        pwd_hash = "$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW"

    rows = [
        # id, email, full_name, role, country_code, is_active, email_verified
        (1,  "admin@zozi.com",     "Zozi Admin",     "admin",     "AE", 1, 1, pwd_hash, now, now, 0, None),
        (2,  "supplier@zozi.com",  "Demo Supplier",  "supplier",  "AE", 1, 1, pwd_hash, now, now, 0, None),
        (3,  "customer@zozi.com",  "Demo Customer",  "customer",  "AE", 1, 1, pwd_hash, now, now, 0, None),
        (4,  "logistics@zozi.com", "Demo Logistics", "logistics", "AE", 1, 1, pwd_hash, now, now, 0, None),
        (20, "supplier_ae1@zozi.com", "Supplier AE 1", "supplier", "AE", 1, 1, pwd_hash, now, now, 0, None),
        (21, "supplier_ae2@zozi.com", "Supplier AE 2", "supplier", "AE", 1, 1, pwd_hash, now, now, 0, None),
        (22, "customer_ae1@zozi.com", "Customer AE 1", "customer", "AE", 1, 1, pwd_hash, now, now, 0, None),
        (23, "customer_ae2@zozi.com", "Customer AE 2", "customer", "AE", 1, 1, pwd_hash, now, now, 0, None),
        (24, "customer_ae3@zozi.com", "Customer AE 3", "customer", "AE", 1, 1, pwd_hash, now, now, 0, None),
        (30, "supplier_sa1@zozi.com", "Supplier SA 1", "supplier", "SA", 1, 1, pwd_hash, now, now, 0, None),
        (31, "supplier_sa2@zozi.com", "Supplier SA 2", "supplier", "SA", 1, 1, pwd_hash, now, now, 0, None),
        (32, "customer_sa1@zozi.com", "Customer SA 1", "customer", "SA", 1, 1, pwd_hash, now, now, 0, None),
        (33, "customer_sa2@zozi.com", "Customer SA 2", "customer", "SA", 1, 1, pwd_hash, now, now, 0, None),
        (34, "customer_sa3@zozi.com", "Customer SA 3", "customer", "SA", 1, 1, pwd_hash, now, now, 0, None),
        (40, "logistics_ae@zozi.com","Logistics AE",  "logistics", "AE", 1, 1, pwd_hash, now, now, 0, None),
        (41, "logistics_sa@zozi.com","Logistics SA",  "logistics", "SA", 1, 1, pwd_hash, now, now, 0, None),
        # Employees (country_staff_assignments join on email)
        (50, "employee_ae1@zozi.com", "Employee AE 1", "employee", "AE", 1, 1, pwd_hash, now, now, 0, "AE,SA"),
        (51, "employee_ae2@zozi.com", "Employee AE 2", "employee", "AE", 1, 1, pwd_hash, now, now, 0, "AE,SA"),
        (52, "employee_ae3@zozi.com", "Employee AE 3", "employee", "AE", 1, 1, pwd_hash, now, now, 0, "AE,SA"),
        (60, "employee_sa1@zozi.com", "Employee SA 1", "employee", "SA", 1, 1, pwd_hash, now, now, 0, "AE,SA"),
        (61, "employee_sa2@zozi.com", "Employee SA 2", "employee", "SA", 1, 1, pwd_hash, now, now, 0, "AE,SA"),
        (62, "employee_sa3@zozi.com", "Employee SA 3", "employee", "SA", 1, 1, pwd_hash, now, now, 0, "AE,SA"),
    ]
    sql = (
        "INSERT OR REPLACE INTO users "
        "(id, email, full_name, role, country_code, is_active, email_verified, "
        " hashed_password, created_at, updated_at, is_deleted, staff_country_codes) VALUES "
        "(?,?,?,?,?,?,?,?,?,?,?,?)"
    )
    n = 0
    for row in rows:
        if country != "ALL" and row[4] != country and row[3] not in ("admin","employee"):
            continue
        try:
            cur.execute(sql, row)
            n += 1
        except sqlite3.IntegrityError as e:
            print(f"  user id={row[0]} {row[1]}: {e}")
    return n


def seed_all(country: str = "ALL", reset: bool = False, strict: bool = False) -> dict[str, int]:
    """Run every ``seed_*`` step and return a dict of {table: rows_written}."""
    if not DB_PATH.exists():
        raise FileNotFoundError(
            f"{DB_PATH} not found. Run the alembic migrations and create_demo_db first."
        )
    conn = sqlite3.connect(str(DB_PATH))
    conn.execute("PRAGMA foreign_keys = ON")
    cur = conn.cursor()
    if reset:
        for table in (
            "supplier_profiles", "customers", "logistics_partners",
            "products", "banners", "flash_discounts", "employees",
            "categories", "users", "country_staff_assignments",
        ):
            try:
                cur.execute(f"DELETE FROM {table}")
            except sqlite3.OperationalError:
                pass
        conn.commit()

    summary: dict[str, int] = {}
    steps = [
        ("categories", seed_categories),
        ("users", seed_users),
        ("suppliers", seed_suppliers),
        ("customers", seed_customers),
        ("logistics_partners", seed_logistics_partners),
        ("products", seed_products),
        ("banners", seed_banners),
        ("flash_discounts", seed_flash_discounts),
        ("employees", seed_employees),
        ("country_staff_assignments", seed_country_staff_assignments),
    ]
    for label, fn in steps:
        n = fn(cur, country)
        conn.commit()
        summary[label] = n
        if strict and n == 0:
            raise RuntimeError(
                f"STRICT: {label} produced 0 rows for country={country}; aborting"
            )
    return summary


def main() -> int:
    parser = argparse.ArgumentParser(description="Seed ZOZI demo data from JSON")
    parser.add_argument("--country", default="ALL", choices=("AE", "SA", "ALL"))
    parser.add_argument("--reset", action="store_true", help="truncate target tables first")
    parser.add_argument("--strict", action="store_true", help="abort on first step that produces 0 rows")
    args = parser.parse_args()

    summary = seed_all(args.country, reset=args.reset, strict=args.strict)
    for table, n in summary.items():
        print(f"  {table}: {n} rows")
    print(f"Done. country={args.country} reset={args.reset} strict={args.strict}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
