"""Canonical HR background-removal provider.

The consolidated implementation lives in :mod:`providers.bg_remover`; this shim
re-exports it so legacy call-site imports (``from providers.hr.bg_remover
import ...``) and the provider audit tests resolve to the real code.
"""
from providers.bg_remover import *  # noqa: F401,F403
from providers.bg_remover import (  # noqa: F401
    AVAILABLE_MODELS,
    VALID_STRATEGIES,
    ProcessingConfig,
    ProcessingStrategy,
    SubjectCategory,
    MemoryManager,
    CleanEdgeRefiner,
    BackgroundRemover,
    SceneAnalyzer,
    HandRemover,
    HoleFiller,
    ThinPartHandler,
    HumanPreserver,
    EdgeRefiner,
    ColorSpaceUtils,
    ImageLoader,
    QualityAnalyzer,
    SubjectDetector,
    ModelSelector,
    MultiModelSegmenter,
    WoodBackgroundRemover,
    ZoziBackgroundRemover,
    AISegmenter,
    EdgeShaver,
    GlobalBackgroundBleeder,
    ArtifactIsolator,
    FloatingArtifactRemover,
    BottomTextEraser,
    Exporter,
    remove_background,
    remove_background_preset,
    remove_background_model,
    remove_background_strategy,
    magic_erase,
    process_product_image,
    generate_angles,
    bytes_to_image,
    _image_to_bytes,
)

__all__ = [
    "AVAILABLE_MODELS",
    "VALID_STRATEGIES",
    "ProcessingConfig",
    "ProcessingStrategy",
    "SubjectCategory",
    "MemoryManager",
    "CleanEdgeRefiner",
    "BackgroundRemover",
    "SceneAnalyzer",
    "HandRemover",
    "HoleFiller",
    "ThinPartHandler",
    "HumanPreserver",
    "EdgeRefiner",
    "ColorSpaceUtils",
    "ImageLoader",
    "QualityAnalyzer",
    "SubjectDetector",
    "ModelSelector",
    "MultiModelSegmenter",
    "WoodBackgroundRemover",
    "ZoziBackgroundRemover",
    "AISegmenter",
    "EdgeShaver",
    "GlobalBackgroundBleeder",
    "ArtifactIsolator",
    "FloatingArtifactRemover",
    "BottomTextEraser",
    "Exporter",
    "remove_background",
    "remove_background_preset",
    "remove_background_model",
    "remove_background_strategy",
    "magic_erase",
    "process_product_image",
    "generate_angles",
    "bytes_to_image",
    "_image_to_bytes",
]
