/**
 * AUTO-GENERATED seed file (will be overwritten by scripts/generate-permissions.mjs).
 * Lists the well-known feature atoms derived from the backend /rbac/catalog.
 * This file is the frontend's import surface for feature gating (Law 167, 197).
 */

export const FEATURE_CATALOG: readonly string[] = Object.freeze([
  "accounts.user.auth",
  "accounts.user.create",
  "accounts.user.read",
  "accounts.user.update",
  "accounts.user.delete",
  "accounts.password.change",
  "accounts.mfa.enable",
  "accounts.mfa.disable",
  "accounts.session.manage",
  "accounts.address.read",
  "accounts.address.create",
  "accounts.address.update",
  "accounts.address.delete",
  "catalog.list",
  "catalog.read",
  "catalog.write",
  "catalog.delete",
  "catalog.search",
  "catalog.approve",
  "catalog.reject",
  "catalog.banners.read",
  "catalog.banners.write",
  "catalog.category.manage",
  "catalog.commission.read",
  "catalog.commission.write",
  "orders.list",
  "orders.read",
  "orders.create",
  "orders.update",
  "orders.cancel",
  "orders.fulfill",
  "orders.export",
  "orders.returns.read",
  "orders.returns.request",
  "orders.returns.manage",
  "finance.ledger.read",
  "finance.ledger.write",
  "finance.commission.read",
  "finance.commission.write",
  "finance.payout.read",
  "finance.payout.write",
  "finance.bank.read",
  "finance.bank.write",
  "finance.treasury.read",
  "finance.reporting.read",
  "customers.profile.read",
  "customers.profile.write",
  "customers.cart.manage",
  "customers.wishlist.manage",
  "customers.reviews.read",
  "customers.reviews.write",
  "customers.address.manage",
  "customers.health.view",
  "suppliers.profile.read",
  "suppliers.profile.write",
  "suppliers.onboarding.read",
  "suppliers.onboarding.write",
  "suppliers.documents.read",
  "suppliers.documents.write",
  "suppliers.health.read",
  "suppliers.invoices.read",
  "suppliers.invoices.write",
  "suppliers.orders.read",
  "suppliers.orders.write",
  "suppliers.returns.read",
  "suppliers.ai_audit.read",
  "suppliers.ai_audit.run",
  "logistics.shipping.tracking",
  "logistics.shipping.manage",
  "logistics.fulfillment.manage",
  "logistics.partners.manage",
  "logistics.sla.manage",
  "logistics.profile.read",
  "logistics.profile.write",
  "promotions.coupons.redeem",
  "promotions.coupons.read",
  "promotions.coupons.write",
  "promotions.promotions.read",
  "promotions.promotions.write",
  "promotions.campaigns.read",
  "promotions.campaigns.send",
  "promotions.flash.read",
  "promotions.flash.write",
  "promotions.banners.read",
  "promotions.banners.write",
  "analytics.read",
  "analytics.dashboard.view",
  "analytics.reports.read",
  "analytics.reports.export",
  "audit.read",
  "audit.logs.read",
  "audit.logs.export",
  "audit.compliance.read",
  "audit.config.manage",
  "audit.anomalies.read",
  "audit.anomalies.manage",
  "audit.command_center.read",
  "audit.command_center.configure",
  "country.configure",
  "country.localization.manage",
  "country.staff.assign",
  "country.tax.manage",
  "country.communications.send",
  "country.rls.manage",
  "country.currency.manage",
  "country.cities.manage",
  "comms.notification.read",
  "comms.notification.send",
  "comms.email.send",
  "comms.email.template.read",
  "comms.email.template.write",
  "comms.email.campaign.read",
  "comms.email.campaign.write",
  "comms.email.suppression.read",
  "comms.email.suppression.write",
  "comms.email.config.read",
  "comms.email.config.write",
  "comms.chat.read",
  "comms.chat.send",
  "comms.ticket.read",
  "comms.ticket.create",
  "comms.proxy.channel.read",
  "comms.proxy.channel.use",
  "comms.proxy.session.read",
  "comms.proxy.message.read",
  "comms.proxy.call.read",
  "comms.proxy.call.place",
  "comms.entity.thread.read",
  "comms.entity.thread.write",
  "hr.employee.read",
  "hr.employee.write",
  "hr.org.read",
  "hr.org.write",
  "hr.office.read",
  "hr.office.write",
  "hr.payroll.read",
  "hr.payroll.write",
  "hr.performance.read",
  "hr.performance.write",
  "hr.role.read",
  "hr.role.write",
  "hr.training.read",
  "hr.training.write",
  "hr.profile.read",
  "hr.profile.write",
  "hr.attendance.read",
  "hr.attendance.write",
  "hr.leave.read",
  "hr.leave.write",
  "hr.schedule.read",
  "hr.schedule.write",
  "hr.tasks.read",
  "hr.tasks.write",
  "hr.documents.read",
  "hr.documents.write",
  "hr.notifications.read",
  "hr.notifications.write",
  "hr.workspace.read",
  "hr.workspace.write",
  "governance.policy.read",
  "governance.policy.write",
  "governance.consent.read",
  "governance.consent.write",
  "governance.compliance.read",
  "governance.access.read",
  "governance.dispute.read",
  "governance.dispute.manage",
  "security.events.read",
  "security.events.manage",
  "security.incidents.read",
  "security.incidents.manage",
  "security.ip_rules.read",
  "security.ip_rules.write",
  "security.fraud.read",
  "security.fraud.manage",
  "media.read",
  "media.write",
]);

export type Feature = (typeof FEATURE_CATALOG)[number];

export const FEATURE_SET: ReadonlySet<Feature> = new Set(FEATURE_CATALOG);

export function isKnownFeature(f: string): f is Feature {
  return FEATURE_SET.has(f as Feature);
}

/** Grouped by namespace for UI tree-building. */
export const FEATURE_GROUPS: Record<string, Feature[]> = {};
for (const f of FEATURE_CATALOG) {
  const ns = f.split(".")[0];
  if (!FEATURE_GROUPS[ns]) FEATURE_GROUPS[ns] = [];
  FEATURE_GROUPS[ns].push(f);
}

let RUNTIME_PERMISSIONS: ReadonlyArray<string> = [];

export function applyRbacCatalogAtoms(atoms: ReadonlyArray<string>): void {
  RUNTIME_PERMISSIONS = [...new Set(atoms)];
}

export function getRuntimePermissions(): ReadonlyArray<string> {
  return RUNTIME_PERMISSIONS.length > 0 ? RUNTIME_PERMISSIONS : FEATURE_CATALOG;
}
