from sqlalchemy import create_engine, text
e = create_engine('postgresql://neondb_owner:npg_pnTuMIq7h9Es@ep-sparkling-dream-za50z6c0-pooler.c-2.eu-west-2.aws.neon.tech/neondb?sslmode=require')
with e.connect() as c:
    r = c.execute(text("SELECT table_name FROM information_schema.tables WHERE table_schema='suppliers'"))
    print('suppliers schema tables:', [row[0] for row in r])
    r = c.execute(text("SELECT table_name FROM information_schema.tables WHERE table_schema='customers'"))
    print('customers schema tables:', [row[0] for row in r])
    r = c.execute(text("SELECT table_name FROM information_schema.tables WHERE table_schema='orders'"))
    print('orders schema tables:', [row[0] for row in r])
    r = c.execute(text("SELECT table_name FROM information_schema.tables WHERE table_schema='country'"))
    print('country schema tables:', [row[0] for row in r])
    r = c.execute(text("SELECT table_name FROM information_schema.tables WHERE table_schema='logistics'"))
    print('logistics schema tables:', [row[0] for row in r])
    r = c.execute(text("SELECT table_name FROM information_schema.tables WHERE table_schema='hr'"))
    print('hr schema tables:', [row[0] for row in r])
