/**
 * Centralized Icon Registry — Web App
 *
 * Import icons from this file instead of directly from "lucide-react".
 * Only the icons actually used in the app are exported here to keep
 * the client bundle small.
 *
 */

export {
  Activity,
  AlertCircle,
  AlertTriangle,
  AlignJustify,
  Archive,
  ArrowDownUp,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpCircle,
  ArrowUpRight,
  ArrowDownRight,
  AtSign,
  Award,
  BadgeCheck,
  BadgePercent,
  Ban,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  Box,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  Check,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardList,
  Clock,
  Clock3,
  Code,
  Compass,
  Copy,
  CreditCard,
  Crown,
  Cpu,
  Database,
  DollarSign,
  Download,
  Gauge,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  FileCheck,
  FileCheck2,
  FileDown,
  FileJson,
  FileSearch,
  FileText,
  FileUp,
  Film,
  Filter,
  Fingerprint,
  Flame,
  Gem,
  Gift,
  GitBranch,
  Globe,
  Globe2,
  Grid2x2,
  GripVertical,
  Hash,
  Headphones,
  Heart,
  History,
  Home,
  Inbox,
  Info,
  Key,
  Keyboard,
  Lamp,
  Layers,
  Layers3,
  LayoutDashboard,
  LayoutGrid,
  Link2,
  ListChecks,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  MapPinOff,
  MapPinned,
  Maximize2,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  MicOff,
  Minus,
  Moon,
  MousePointer,
  Navigation,
  Network,
  Newspaper,
  Package,
  Package2,
  PackageCheck,
  PackageX,
  PenLine,
  Pencil,
  Percent,
  Phone,
  PieChart,
  Play,
  Plus,
  Plug,
  PlugZap,
  Printer,
  QrCode,
  RefreshCw,
  RotateCcw,
  Rows3,
  Save,
  Scale,
  ScanLine,
  ScreenShare,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Share2,
  Shield,
  Sun,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  ShieldX,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Sofa,
  Sparkles,
  Star,
  Store,
  StretchVertical,
  Tag,
  Tags,
  Target,
  ToggleLeft,
  ToggleRight,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  Unlock,
  Upload,
  UploadCloud,
  User,
  UserCheck,
  UserPlus,
  UserX,
  Users,
  Video,
  VideoOff,
  Volume2,
  Wallet,
  Wand2,
  Watch,
  Wifi,
  WifiOff,
  X,
  XCircle,
  Zap,
} from "lucide-react";

/**
 * Brand/social icons were removed from lucide-react core (v1.x).
 * Alias the names the app still imports to the closest available
 * generic icons so the registry stays compatible.
 */
export {
  Camera as Instagram,
  Share2 as Facebook,
  Send as Twitter,
  Link2 as Linkedin,
  Play as Youtube,
} from "lucide-react";

export { Image as ImageIcon } from "lucide-react";
export {
  Coins,
  Receipt,
  Landmark,
  CircleDollarSign,
  Columns,
  Rows,
  FileSpreadsheet,
  PiggyBank,
  ListFilter,
  Workflow,
  CircleCheck,
  CircleCheckBig,
  Split,
  Crop,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  ZoomIn,
  ZoomOut,
  Contrast,
  Move,
  Undo2,
  Droplet,
  Square,
} from "lucide-react";
export type { LucideIcon } from "lucide-react";

