"""controllers.comms.chatbot_controller controller.

Business logic is delegated to services.comms.chatbot_service (routers -> controllers -> services)."""
__all__ = ['_INTENT_PATTERNS', '_NOISE_IN_PRODUCT', '_PRODUCT_REFERENCE_HINT', '_PRODUCT_REQUEST_HINT', '_SEARCH_STOPWORDS', '_SESSION_HISTORY', '_SESSION_MAX_MESSAGES', '_SESSION_TTL', '_STATIC_REPLIES', '_STATIC_REPLIES_AR', '_alternative_results_reply', '_append_to_session', '_build_follow_up_prompts', '_build_relaxed_product_recommendations', '_catalog_guidance_reply', '_category_sales_line', '_classify_intent', '_extract_max_price', '_extract_search_keywords', '_format_price_value', '_get_or_create_session', '_last_product_filters', '_lead_product_line', '_load_browsing_history', '_merge_product_filters', '_price_badge', '_price_proximity_score', '_product_constraints', '_product_results_reply', '_product_subject', '_profile_personalization_hint', '_record_chatbot_event', '_result_guidance_line', '_rounded_budget_prompt', '_safe_json_dumps', '_search_tokens', '_serialize_products', '_should_merge_product_filters', '_should_treat_as_product_search', '_static_reply', '_style_reference_terms', '_style_similarity_score', '_top_counter_values', '_upsell_hint', 'get_shopper_profile', 'handle_message', 'logger', 'record_product_click', 'record_product_view', 'search_products', 'search_products_with_context']

def __getattr__(name):
    _LAZY = {'_INTENT_PATTERNS': 'services.comms.chatbot_service', '_NOISE_IN_PRODUCT': 'services.comms.chatbot_service', '_PRODUCT_REFERENCE_HINT': 'services.comms.chatbot_service', '_PRODUCT_REQUEST_HINT': 'services.comms.chatbot_service', '_SEARCH_STOPWORDS': 'services.comms.chatbot_service', '_SESSION_HISTORY': 'services.comms.chatbot_service', '_SESSION_MAX_MESSAGES': 'services.comms.chatbot_service', '_SESSION_TTL': 'services.comms.chatbot_service', '_STATIC_REPLIES': 'services.comms.chatbot_service', '_STATIC_REPLIES_AR': 'services.comms.chatbot_service', '_alternative_results_reply': 'services.comms.chatbot_service', '_append_to_session': 'services.comms.chatbot_service', '_build_follow_up_prompts': 'services.comms.chatbot_service', '_build_relaxed_product_recommendations': 'services.comms.chatbot_service', '_catalog_guidance_reply': 'services.comms.chatbot_service', '_category_sales_line': 'services.comms.chatbot_service', '_classify_intent': 'services.comms.chatbot_service', '_extract_max_price': 'services.comms.chatbot_service', '_extract_search_keywords': 'services.comms.chatbot_service', '_format_price_value': 'services.comms.chatbot_service', '_get_or_create_session': 'services.comms.chatbot_service', '_last_product_filters': 'services.comms.chatbot_service', '_lead_product_line': 'services.comms.chatbot_service', '_load_browsing_history': 'services.comms.chatbot_service', '_merge_product_filters': 'services.comms.chatbot_service', '_price_badge': 'services.comms.chatbot_service', '_price_proximity_score': 'services.comms.chatbot_service', '_product_constraints': 'services.comms.chatbot_service', '_product_results_reply': 'services.comms.chatbot_service', '_product_subject': 'services.comms.chatbot_service', '_profile_personalization_hint': 'services.comms.chatbot_service', '_record_chatbot_event': 'services.comms.chatbot_service', '_result_guidance_line': 'services.comms.chatbot_service', '_rounded_budget_prompt': 'services.comms.chatbot_service', '_safe_json_dumps': 'services.comms.chatbot_service', '_search_tokens': 'services.comms.chatbot_service', '_serialize_products': 'services.comms.chatbot_service', '_should_merge_product_filters': 'services.comms.chatbot_service', '_should_treat_as_product_search': 'services.comms.chatbot_service', '_static_reply': 'services.comms.chatbot_service', '_style_reference_terms': 'services.comms.chatbot_service', '_style_similarity_score': 'services.comms.chatbot_service', '_top_counter_values': 'services.comms.chatbot_service', '_upsell_hint': 'services.comms.chatbot_service', 'get_shopper_profile': 'services.comms.chatbot_service', 'handle_message': 'services.comms.chatbot_service', 'logger': 'services.comms.chatbot_service', 'record_product_click': 'services.comms.chatbot_service', 'record_product_view': 'services.comms.chatbot_service', 'search_products': 'services.comms.chatbot_service', 'search_products_with_context': 'services.comms.chatbot_service'}
    if name in _LAZY:
        import importlib
        return getattr(importlib.import_module(_LAZY[name]), name)
    raise AttributeError(f'module {__name__!r} has no attribute {name!r}')

# --- auto-wiring re-exports (added by fix_modules) ---
from domains.comms.services.chatbot_service import handle_message, record_product_click
