# backend/scripts/safe_structure_migration.py
"""
safe_structure_migration.py

Safely migrate the ZOZI repository toward the planned target structure.

SAFETY MODEL
------------
1. Default mode is DRY-RUN.
2. No file is moved unless --apply is used.
3. A timestamped backup is created before applying moves.
4. Existing destination files are NOT overwritten by default.
5. Ambiguous code moves are NOT applied automatically unless explicitly approved.
6. The script can analyze and repair the .gitignore problem.
7. The script can force-add important ignored files so git push/pull does not lose them.

USAGE
-----
# 1. Dry run + analyze git + generate suggested domain map
python scripts/safe_structure_migration.py --dry-run --analyze-git --generate-domain-map

# 2. Inspect:
#    migration_reports/plan.md
#    migration_reports/plan.json
#    migration_reports/domain_map.json
#    migration_reports/ignored_important_files.txt
#    migration_reports/gitignore_analysis.md

# 3. Apply safe moves + fix git tracking
python scripts/safe_structure_migration.py \
    --apply \
    --analyze-git \
    --fix-gitignore \
    --overwrite-gitignore \
    --force-add-important \
    --stage-changes

# 4. Apply approved domain moves only after reviewing domain_map.json
python scripts/safe_structure_migration.py \
    --apply \
    --apply-mapping migration_reports/domain_map.json \
    --stage-changes

ROLLBACK
--------
If something goes wrong:

1. Restore from git backup branch created by this script:
   git branch --list "backup/pre-migration-*"

2. Restore from filesystem backup:
   .migration_backups/<timestamp>/

3. If you used --overwrite-gitignore, old .gitignore is saved as:
   .gitignore.bak.<timestamp>
"""

from typing import Optional

import argparse
import datetime
import fnmatch
import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Iterable


# ============================================================================
# CONFIG
# ============================================================================

GENERATED_DIR_NAMES = {
    ".git",
    "node_modules",
    ".venv",
    "venv",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".next",
    ".expo",
    ".turbo",
    "dist",
    "build",
    "coverage",
    "htmlcov",
    "playwright-report",
    "test-results",
    "test-output",
    "web-dist",
    ".migration_backups",
    ".migration_quarantine",
    "migration_reports",
    ".archive",
}

IMPORTANT_SUFFIXES = {
    ".md",
    ".py",
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".cjs",
    ".mjs",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".ini",
    ".sql",
    ".sh",
    ".bat",
    ".ps1",
    ".txt",
    ".css",
    ".html",
}

SECRET_FILE_PATTERNS = [
    re.compile(r"(^|/)\.env$"),
    re.compile(r"(^|/)\.env\..*$"),
    re.compile(r"(^|/)token\.tmp$"),
    re.compile(r"(^|/).*\.(key|pem|p12|pfx|secret)$", re.I),
    re.compile(r"(^|/)id_(rsa|dsa|ecdsa|ed25519)$"),
    re.compile(r"(^|/).*credentials.*\.(json|ya?ml)$", re.I),
    re.compile(r"(^|/)login_rsp\.json$"),
]

SAFE_GITIGNORE = """# ZOZI safe gitignore generated by safe_structure_migration.py
# This ignores generated/runtime artifacts, NOT source code/docs/scripts/tests.

# Python
__pycache__/
*.py[cod]
*.egg-info/
.venv/
venv/
.pytest_cache/
.mypy_cache/
.ruff_cache/
.tox/

# Node / frontend build artifacts
node_modules/
.next/
.expo/
dist/
build/
coverage/
htmlcov/
*.tsbuildinfo
playwright-report/
test-results/
test-output/
web-dist/
.turbo/

# Environment and secrets
.env
.env.*
!.env.example
*.pem
*.key
*.p12
*.pfx
token.tmp

# Local databases
*.db
*.db-shm
*.db-wal
*.sqlite3

# Logs and runtime artifacts
*.log
logs/
backend/log/
backend/var/
frontend/**/var/

# Migration / archive areas
migration_reports/
.migration_backups/
.migration_quarantine/
.archive/

# OS
.DS_Store
Thumbs.db
"""

ALLOWED_ROOT_FILES = {
    ".gitignore",
    ".gitattributes",
    ".editorconfig",
    ".nvmrc",
    ".env.example",
    ".aiignore",
    "README.md",
    "AGENTS.md",
    "CONTRIBUTING.md",
    "CHANGELOG.md",
    "SECURITY.md",
    "LICENSE",
    "LICENSE.md",
    "Makefile",
    "justfile",
    "docker-compose.yml",
    "docker-compose.override.yml",
    "docker-compose.prod.yml",
    "railway.toml",
    "package.json",
    "pnpm-workspace.yaml",
    "vercel.json",
}

ALLOWED_BACKEND_ROOT_FILES = {
    "__init__.py",
    "main.py",
    "lifespan.py",
    "run_server.py",
    "start_server.py",
    "alembic.ini",
    "pyproject.toml",
    "requirements.txt",
    "requirements.lock",
    "Dockerfile",
    "Dockerfile.prod",
    "run_tests.ps1",
    "run_tests.sh",
    "start_backend.ps1",
}

DOMAIN_KEYWORDS = [
    ("treasury", [
        "treasury", "treasurer", "cash_management", "cash_flow", "payout",
        "payment_engine", "payment_orchestrator", "gateway_auto", "gateway_reconciliation",
        "refund_posting", "credit_control",
    ]),
    ("finance", [
        "finance", "financial", "ledger", "sub_ledger", "tax", "invoice",
        "accounting", "commission", "expense", "period_close", "general_ledger",
        "erp_finance", "je_reversal",
    ]),
    ("orders", [
        "order", "checkout", "cart", "fulfillment", "returns", "disputes",
        "wishlist", "reviews",
    ]),
    ("catalog", [
        "product", "category", "categories", "catalog", "search", "filter",
        "variant", "bg_removal", "image_ai", "ocr", "free_image", "media",
        "video", "content",
    ]),
    ("supplier", [
        "supplier",
    ]),
    ("logistics", [
        "logistics", "shipping", "shipment", "tracking", "dispatch",
        "live_tracking", "asset_tracking", "parcel", "delivery",
    ]),
    ("comms", [
        "email", "chat", "notification", "translation", "communication",
        "comm", "entity_chat", "websocket", "video_conferencing",
        "transactional_email", "proxy_communication", "internal_communication",
    ]),
    ("hr", [
        "employee", "hr", "shift", "attendance", "leave", "payroll",
        "performance", "succession", "retention", "offboarding",
        "onboarding_pipeline", "lms", "hse", "dei", "background_check",
        "travel_service", "travel_detector",
    ]),
    ("ai", [
        "ai_", "ai_automation", "ai_copy", "ai_research", "ai_search",
        "ai_variant", "country_ai", "confidence_scoring", "automation_scheduler",
        "command_center_background",
    ]),
    ("fraud", [
        "fraud", "risk", "worm_audit", "ghost_watchdog", "coi", "compliance",
        "audit_service", "audit_trail",
    ]),
    ("auth", [
        "auth", "iam", "rbac", "permission", "effective_permissions",
        "biometric", "triple_auth", "mobile_auth", "qr_service", "kms",
        "encryption",
    ]),
    ("country", [
        "country", "cross_border", "data_residency", "localization",
        "geo_fence", "map_service",
    ]),
    ("core", [
        "user", "users", "config", "constants", "cache", "health", "slug",
        "soft_delete", "pagination", "response", "error", "logging",
        "datetime", "money", "currency", "ip_utils", "versioning", "tracing",
        "realtime", "redis", "metrics", "backup", "db_backup", "migrations",
        "middleware_helpers", "staff_permissions", "category_tree",
        "ghost_record", "entity_messaging", "multi_secret", "secrets_manager",
        "security_audit", "security_metrics", "schema_audit", "api_docs",
        "analytics_service", "ml_worker", "kms_integration", "file_validation",
        "constant_time", "circuit_breaker", "rate_limiter", "websocket_manager",
    ]),
]


# ============================================================================
# DATA MODEL
# ============================================================================

@dataclass
class Action:
    kind: str
    src: str
    dst: str = ""
    reason: str = ""
    tracked: bool = False
    ignored: bool = False
    conflict: bool = False
    replacements: list = field(default_factory=list)
    create_init: bool = False
    reexport_module: str = ""
    status: str = "planned"
    error: str = ""


# ============================================================================
# HELPERS
# ============================================================================

def now_stamp() -> str:
    return datetime.datetime.now().strftime("%Y%m%d_%H%M%S")


def is_subpath(path: Path, base: Path) -> bool:
    try:
        path.relative_to(base)
        return True
    except ValueError:
        return False


def is_secret_file(rel_path: str) -> bool:
    p = rel_path.replace("\\", "/")
    return any(rx.search(p) for rx in SECRET_FILE_PATTERNS)


def classify_domain(stem: str) -> str:
    low = stem.lower()
    for domain, keywords in DOMAIN_KEYWORDS:
        for kw in keywords:
            if kw in low:
                return domain
    return "core"


def router_surface(stem: str) -> str:
    low = stem.lower()
    for surface in ["admin", "supplier", "customer", "public", "webhook"]:
        if low == surface or low.startswith(surface + "_"):
            return surface
    return "common"


def module_from_backend_path(rel_path: str) -> str:
    p = rel_path.replace("\\", "/")
    if not p.startswith("backend/"):
        return ""
    p = p[len("backend/"):]
    if p.endswith(".py"):
        p = p[:-3]
    if p.endswith("/__init__"):
        p = p[:-len("/__init__")]
    return p.replace("/", ".")


# ============================================================================
# MIGRATOR
# ============================================================================

class Migrator:
    def __init__(self, args: argparse.Namespace):
        self.args = args
        self.repo = Path(args.root).resolve()
        self.stamp = now_stamp()
        self.report_dir = self.repo / "migration_reports"
        self.backup_root = self.repo / ".migration_backups" / self.stamp
        self.actions: list[Action] = []
        self.replacements: list[tuple[str, str]] = []
        self.tracked_cache: dict[str, bool] = {}
        self.ignored_cache: dict[str, bool] = {}
        self.git_ok = self._is_git_repo()
        self.notes: list[str] = []

        if not self.repo.is_dir():
            print(f"[FATAL] Repo root not found: {self.repo}", file=sys.stderr)
            sys.exit(2)

        self.report_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # git
    # ------------------------------------------------------------------

    def _is_git_repo(self) -> bool:
        try:
            r = subprocess.run(
                ["git", "rev-parse", "--is-inside-work-tree"],
                cwd=self.repo,
                capture_output=True,
                text=True,
            )
            return r.returncode == 0 and r.stdout.strip() == "true"
        except Exception:
            return False

    def git(self, cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
        full = ["git"] + cmd
        r = subprocess.run(full, cwd=self.repo, capture_output=True, text=True)
        if check and r.returncode != 0:
            raise RuntimeError(f"Git command failed: {' '.join(full)}\n{r.stderr}")
        return r

    def is_tracked(self, rel_path: str) -> bool:
        rel_path = rel_path.replace("\\", "/")
        if rel_path in self.tracked_cache:
            return self.tracked_cache[rel_path]

        if not self.git_ok:
            self.tracked_cache[rel_path] = False
            return False

        r = self.git(["ls-files", "--error-unmatch", "--", rel_path], check=False)
        tracked = r.returncode == 0
        self.tracked_cache[rel_path] = tracked
        return tracked

    def is_ignored(self, rel_path: str) -> bool:
        rel_path = rel_path.replace("\\", "/")
        if rel_path in self.ignored_cache:
            return self.ignored_cache[rel_path]

        if not self.git_ok:
            self.ignored_cache[rel_path] = False
            return False

        r = self.git(["check-ignore", "-q", "--", rel_path], check=False)
        ignored = r.returncode == 0
        self.ignored_cache[rel_path] = ignored
        return ignored

    def git_status_dirty(self) -> bool:
        if not self.git_ok:
            return False
        r = self.git(["status", "--porcelain"], check=False)
        return bool(r.stdout.strip())

    # ------------------------------------------------------------------
    # plan building
    # ------------------------------------------------------------------

    def rel(self, path: Path) -> str:
        try:
            return path.relative_to(self.repo).as_posix()
        except ValueError:
            return str(path)

    def add_move(
        self,
        src_rel: str,
        dst_rel: str,
        reason: str,
        replacements: list | None = None,
        create_init: bool = False,
        reexport_module: str = "",
    ) -> None:
        src = self.repo / src_rel
        if not src.exists():
            return

        dst = self.repo / dst_rel
        conflict = dst.exists()

        action = Action(
            kind="move",
            src=src_rel.replace("\\", "/"),
            dst=dst_rel.replace("\\", "/"),
            reason=reason,
            tracked=self.is_tracked(src_rel),
            ignored=self.is_ignored(src_rel),
            conflict=conflict,
            replacements=replacements or [],
            create_init=create_init,
            reexport_module=reexport_module,
            status="skipped-conflict" if conflict else "planned",
        )
        self.actions.append(action)

        if replacements:
            for old, new in replacements:
                pair = (old, new)
                if pair not in self.replacements:
                    self.replacements.append(pair)

    def add_review(self, src_rel: str, reason: str) -> None:
        src = self.repo / src_rel
        if not src.exists():
            return
        self.actions.append(
            Action(
                kind="review",
                src=src_rel.replace("\\", "/"),
                reason=reason,
                tracked=self.is_tracked(src_rel),
                ignored=self.is_ignored(src_rel),
                status="review",
            )
        )

    def add_mkdir(self, dst_rel: str, reason: str) -> None:
        self.actions.append(
            Action(
                kind="mkdir",
                src="",
                dst=dst_rel.replace("\\", "/"),
                reason=reason,
                status="planned",
            )
        )

    def add_replacement(self, old: str, new: str) -> None:
        pair = (old, new)
        if pair not in self.replacements:
            self.replacements.append(pair)

    def build_plan(self) -> None:
        self.add_target_dirs()
        self.plan_root_files()
        self.plan_documents()
        self.plan_experiments_and_archives()
        self.plan_backend_safe_moves()
        self.plan_frontend_safe_moves()
        self.plan_reviews()

    def add_target_dirs(self) -> None:
        dirs = [
            "documents/scope",
            "documents/archive",
            "scripts/maintenance",
            "scripts/validation",
            "scripts/legacy",
            "scripts/legacy/root",
            "scripts/legacy/runners",
            "scripts/alembic_diagnostics",
            "scripts/legacy_migrations",
            "scripts/runners",
            "experiments",
            "design",
            ".archive",
            ".archive/logs",
            ".archive/zips",
            ".migration_quarantine",
            ".migration_quarantine/root_artifacts",
            "backend/var",
            "backend/var/log",
            "backend/var/artifacts",
            "backend/var/db_artifacts",
            "backend/routers/admin",
            "backend/routers/supplier",
            "backend/routers/customer",
            "backend/routers/public",
            "backend/routers/webhooks",
            "backend/routers/common",
            "backend/controllers/finance",
            "backend/controllers/treasury",
            "backend/controllers/orders",
            "backend/controllers/catalog",
            "backend/controllers/supplier",
            "backend/controllers/logistics",
            "backend/controllers/comms",
            "backend/controllers/hr",
            "backend/controllers/ai",
            "backend/controllers/fraud",
            "backend/controllers/compliance",
            "backend/controllers/core",
            "backend/controllers/country",
            "backend/controllers/media",
            "backend/controllers/auth",
            "backend/controllers/user",
            "backend/services/finance",
            "backend/services/treasury",
            "backend/services/orders",
            "backend/services/catalog",
            "backend/services/supplier",
            "backend/services/logistics",
            "backend/services/comms",
            "backend/services/hr",
            "backend/services/ai",
            "backend/services/fraud",
            "backend/services/compliance",
            "backend/services/core",
            "backend/services/country",
            "backend/services/media",
            "backend/services/auth",
            "backend/services/user",
            "backend/services/search",
            "backend/services/promo",
            "backend/services/ops",
            "backend/models/finance",
            "backend/models/orders",
            "backend/models/catalog",
            "backend/models/supplier",
            "backend/models/logistics",
            "backend/models/comms",
            "backend/models/hr",
            "backend/models/ai",
            "backend/models/fraud",
            "backend/models/compliance",
            "backend/models/core",
            "backend/models/country",
            "backend/models/media",
            "backend/models/auth",
            "backend/models/user",
            "frontend/web_app/scripts/legacy-audit",
            "frontend/web_app/var/artifacts",
            "frontend/mobile_app/var/log",
        ]
        for d in dirs:
            self.add_mkdir(d, "target structure directory")

    def plan_root_files(self) -> None:
        this_script = Path(__file__).resolve()

        # Root markdown / text notes
        for p in sorted(self.repo.glob("*.md")):
            if p.resolve() == this_script:
                continue
            if p.name in ALLOWED_ROOT_FILES:
                continue
            self.add_move(
                self.rel(p),
                f"documents/archive/root-notes/{p.name}",
                "root markdown belongs under documents/archive/root-notes",
            )

        for p in sorted(self.repo.glob("*.txt")):
            if p.resolve() == this_script:
                continue
            self.add_move(
                self.rel(p),
                f"documents/archive/root-notes/{p.name}",
                "root text note belongs under documents/archive/root-notes",
            )

        # Root Python scripts
        for p in sorted(self.repo.glob("*.py")):
            if p.resolve() == this_script:
                continue
            if p.name in ALLOWED_ROOT_FILES:
                continue
            self.add_move(
                self.rel(p),
                f"scripts/legacy/root/{p.name}",
                "root Python script belongs under scripts/legacy/root",
            )

        # Root runners
        for pattern in ("*.bat", "*.ps1", "*.sh"):
            for p in sorted(self.repo.glob(pattern)):
                if p.name in ALLOWED_ROOT_FILES:
                    continue
                self.add_move(
                    self.rel(p),
                    f"scripts/legacy/runners/{p.name}",
                    "root runner script belongs under scripts/legacy/runners",
                )

        # Root logs
        for p in sorted(self.repo.glob("*.log")):
            self.add_move(
                self.rel(p),
                f".archive/logs/{p.name}",
                "root log file should be archived and gitignored",
            )

        # Root zips
        for p in sorted(self.repo.glob("*.zip")):
            self.add_move(
                self.rel(p),
                f".archive/zips/{p.name}",
                "root zip archive should be archived and gitignored",
            )

        # Suspicious root artifacts
        suspicious = [
            "login_form.yml",
            "login_rsp.json",
            "mobile_app.html",
        ]
        for name in suspicious:
            p = self.repo / name
            if p.exists():
                self.add_move(
                    self.rel(p),
                    f".migration_quarantine/root_artifacts/{name}",
                    "suspicious/root artifact quarantined for review",
                )

        # Root directories
        dir_moves = [
            ("image", "design/images", "root image directory belongs under design/images"),
            ("docs", "documents/archive/docs", "root docs/ belongs under documents/archive/docs"),
            ("document", "documents/archive/document", "root document/ belongs under documents/archive/document"),
            ("browser-tests", "frontend/web_app/e2e/imported-browser-tests", "root browser-tests belongs under frontend/web_app/e2e"),
            ("Working_API", "experiments/Working_API", "Working_API belongs under experiments/"),
            ("provider_test", "experiments/provider_test", "provider_test belongs under experiments/"),
            ("_trash", ".archive/_trash", "_trash belongs under .archive/"),
            ("scripts/backend", "experiments/ghost_backend", "ghost backend skeleton belongs under experiments/ghost_backend"),
        ]
        for src, dst, reason in dir_moves:
            if (self.repo / src).exists():
                self.add_move(src, dst, reason)

        for p in sorted(self.repo.glob("backup_*")):
            if p.is_dir():
                self.add_move(
                    self.rel(p),
                    f".archive/{p.name}",
                    "backup directory belongs under .archive/ and should be gitignored",
                )

    def plan_documents(self) -> None:
        docs = self.repo / "documents"
        if not docs.exists():
            return

        allowed = {"scope", "archive", "README.md", "DOCUMENTATION_INDEX.md", "INDEX.md"}
        for p in sorted(docs.iterdir()):
            if p.name in allowed:
                continue
            dst = f"documents/archive/documents-root/{p.name}"
            self.add_move(
                self.rel(p),
                dst,
                "documents/ root must contain only scope/ and archive/",
            )

    def plan_experiments_and_archives(self) -> None:
        # Already handled by plan_root_files directory moves.
        pass

    def plan_backend_safe_moves(self) -> None:
        backend = self.repo / "backend"
        if not backend.exists():
            return

        # Logs
        for p in sorted((backend).glob("*.log")):
            self.add_move(
                self.rel(p),
                f"backend/var/log/{p.name}",
                "backend root log belongs under backend/var/log",
            )

        log_dir = backend / "log"
        if log_dir.exists():
            self.add_move(
                "backend/log",
                "backend/var/log",
                "backend/log belongs under backend/var/log and should be gitignored",
            )

        # DB artifacts
        for pattern in ("*.db", "*.db-shm", "*.db-wal"):
            for p in sorted(backend.glob(pattern)):
                self.add_move(
                    self.rel(p),
                    f"backend/var/db_artifacts/{p.name}",
                    "local database artifact belongs under backend/var/db_artifacts and gitignore",
                )

        # Backend artifacts
        artifact_names = [
            "_import_test_out.txt",
            "alembic_test.json",
            "schema-audit-report.json",
            "schema_mapping.json",
            "backend.log",
            "server_stderr.log",
            "server_stdout.log",
        ]
        for name in artifact_names:
            p = backend / name
            if p.exists():
                self.add_move(
                    f"backend/{name}",
                    f"backend/var/artifacts/{name}",
                    "backend root artifact belongs under backend/var/artifacts",
                )

        # Alembic diagnostics
        diag = [
            "_analyze_graph.py",
            "_diagnose_tree.py",
            "_graph_analysis.py",
        ]
        for name in diag:
            src = backend / "alembic" / name
            if src.exists():
                self.add_move(
                    f"backend/alembic/{name}",
                    f"backend/scripts/alembic_diagnostics/{name.lstrip('_')}",
                    "alembic diagnostics do not belong inside alembic/",
                )

        # Second migrations home
        migrations_dir = backend / "db" / "migrations"
        if migrations_dir.exists():
            self.add_move(
                "backend/db/migrations",
                "backend/scripts/legacy_migrations",
                "second migrations home should be archived; Alembic is the only migrations home",
            )

        # Optional backend code moves
        if self.args.move_backend_code:
            api_file = backend / "api" / "country_communications.py"
            if api_file.exists():
                reps = [
                    ("backend.api.country_communications", "backend.routers.country_communications"),
                    ("api.country_communications", "routers.country_communications"),
                ]
                self.add_move(
                    "backend/api/country_communications.py",
                    "backend/routers/country_communications.py",
                    "API router belongs under backend/routers/",
                    replacements=reps,
                )

            audit = backend / "controllers" / "audit_controller.py"
            if audit.exists():
                reps = [
                    ("backend.controllers.audit_controller", "backend.services.audit.audit_controller"),
                    ("controllers.audit_controller", "services.audit.audit_controller"),
                ]
                self.add_move(
                    "backend/controllers/audit_controller.py",
                    "backend/services/audit/audit_controller.py",
                    "audit_controller contains service logic and belongs under services/audit/",
                    replacements=reps,
                    create_init=True,
                )

    def plan_frontend_safe_moves(self) -> None:
        web = self.repo / "frontend" / "web_app"
        mobile = self.repo / "frontend" / "mobile_app"

        if web.exists():
            patterns = [
                "_audit_*.cjs",
                "verify_*.cjs",
                "inspect-playwright.cjs",
                "_collect_icons.cjs",
                "_gen_lucide.cjs",
            ]
            for pattern in patterns:
                for p in sorted(web.glob(pattern)):
                    self.add_move(
                        self.rel(p),
                        f"frontend/web_app/scripts/legacy-audit/{p.name}",
                        "frontend scratch/audit script belongs under frontend/web_app/scripts/legacy-audit",
                    )

            artifact_patterns = [
                "build_*.log",
                "build_*.txt",
                "*_test*.txt",
                "playwright-results.txt",
                "*.png",
                "tsconfig.tsbuildinfo",
                "-w",
            ]
            for pattern in artifact_patterns:
                for p in sorted(web.glob(pattern)):
                    self.add_move(
                        self.rel(p),
                        f"frontend/web_app/var/artifacts/{p.name}",
                        "frontend root artifact belongs under frontend/web_app/var/artifacts",
                    )

        if mobile.exists():
            for p in sorted(mobile.glob("expo-*.log")):
                self.add_move(
                    self.rel(p),
                    f"frontend/mobile_app/var/log/{p.name}",
                    "mobile expo log belongs under frontend/mobile_app/var/log",
                )

            scripts = mobile / "scripts"
            if scripts.exists():
                for pattern in ("*.log", "*.err"):
                    for p in sorted(scripts.glob(pattern)):
                        self.add_move(
                            self.rel(p),
                            f"frontend/mobile_app/var/log/{p.name}",
                            "mobile script log belongs under frontend/mobile_app/var/log",
                        )

    def plan_reviews(self) -> None:
        backend = self.repo / "backend"
        if backend.exists():
            for p in sorted(backend.glob("*.py")):
                if p.name in ALLOWED_BACKEND_ROOT_FILES:
                    continue
                self.add_review(
                    f"backend/{p.name}",
                    "backend root module must be reviewed before move/delete; imports may break",
                )

        review_dirs = [
            ("backend/location_service", "separate service; decide if it becomes backend/services/location or stays isolated"),
            ("backend/tasks", "merge into backend/jobs/ or backend/services/ after review"),
            ("backend/settings", "move notification_worker into services/ or jobs/ after review"),
            ("backend/tools", "move into scripts/tools/ or keep after review"),
            ("backend/monitoring", "move into infra/monitoring/ after docker-compose reference review"),
            ("monitoring", "move into infra/monitoring/ after docker-compose reference review"),
            ("nginx", "move into infra/nginx/ after docker-compose reference review"),
        ]
        for src, reason in review_dirs:
            if (self.repo / src).exists():
                self.add_review(src, reason)

        # Gitignore broad review
        gi = self.repo / ".gitignore"
        if gi.exists():
            broad = self.detect_broad_gitignore_patterns()
            if broad:
                self.add_review(
                    ".gitignore",
                    "dangerous broad gitignore patterns detected: " + ", ".join(broad),
                )

    # ------------------------------------------------------------------
    # domain map
    # ------------------------------------------------------------------

    def generate_domain_map(self) -> None:
        entries = []
        backend = self.repo / "backend"

        layers = [
            ("services", "domain"),
            ("controllers", "mixed"),
            ("models", "domain"),
            ("routers", "surface"),
        ]

        for layer, mode in layers:
            base = backend / layer
            if not base.exists():
                continue

            for p in sorted(base.glob("*.py")):
                if p.name == "__init__.py":
                    continue

                stem = p.stem
                src_rel = self.rel(p)

                if mode == "surface":
                    sub = router_surface(stem)
                    dst_rel = f"backend/{layer}/{sub}/{p.name}"
                    reason = f"suggested surface grouping: {sub}"
                    reexport = False
                else:
                    domain = classify_domain(stem)
                    dst_rel = f"backend/{layer}/{domain}/{p.name}"
                    reason = f"suggested domain grouping: {domain}"
                    reexport = False

                    if layer == "models" and stem == domain:
                        reexport = True
                        reason += " (re-export __init__ recommended because module name becomes package name)"

                if (self.repo / dst_rel).exists():
                    continue

                entries.append(
                    {
                        "src": src_rel,
                        "dst": dst_rel,
                        "reason": reason,
                        "approved": False,
                        "create_init": True,
                        "reexport_init": reexport,
                    }
                )

        out = self.report_dir / "domain_map.json"
        out.write_text(json.dumps(entries, indent=2), encoding="utf-8")
        self.notes.append(f"Generated domain map: {out}")

    def apply_mapping_file(self, mapping_path: str) -> None:
        path = self.repo / mapping_path
        if not path.exists():
            print(f"[FATAL] Mapping file not found: {path}", file=sys.stderr)
            sys.exit(2)

        data = json.loads(path.read_text(encoding="utf-8"))
        for entry in data:
            if not entry.get("approved"):
                continue

            src = entry["src"]
            dst = entry["dst"]
            reason = entry.get("reason", "approved mapping")
            create_init = bool(entry.get("create_init", False))
            reexport_init = bool(entry.get("reexport_init", False))

            replacements = []
            reexport_module = ""

            if src.endswith(".py") and src.startswith("backend/") and dst.startswith("backend/"):
                old_mod = module_from_backend_path(src)
                new_mod = module_from_backend_path(dst)

                if old_mod and new_mod:
                    # For models where module name becomes package name, prefer re-export instead of rewrite.
                    if not reexport_init:
                        replacements = [
                            ("backend." + old_mod, "backend." + new_mod),
                            (old_mod, new_mod),
                        ]
                    else:
                        reexport_module = old_mod.rsplit(".", 1)[-1]

            self.add_move(
                src,
                dst,
                reason,
                replacements=replacements,
                create_init=create_init,
                reexport_module=reexport_module,
            )

    # ------------------------------------------------------------------
    # gitignore analysis / repair
    # ------------------------------------------------------------------

    def detect_broad_gitignore_patterns(self) -> list[str]:
        gi = self.repo / ".gitignore"
        if not gi.exists():
            return []

        dangerous = []
        broad = {
            "backend", "backend/", "frontend", "frontend/", "documents", "documents/",
            "scripts", "scripts/", "tests", "tests/", "*.py", "*.ts", "*.tsx",
            "*.js", "*.md", "*.txt",
        }

        for line in gi.read_text(encoding="utf-8", errors="replace").splitlines():
            s = line.strip()
            if not s or s.startswith("#"):
                continue
            if s in broad:
                dangerous.append(s)

        return dangerous

    def write_gitignore_template(self, overwrite: bool) -> None:
        gi = self.repo / ".gitignore"

        if overwrite and gi.exists():
            if not self.args.apply:
                self.notes.append("Would overwrite .gitignore with safe template because --overwrite-gitignore was given, but --apply is missing.")
                return

            backup = self.repo / f".gitignore.bak.{self.stamp}"
            shutil.copy2(gi, backup)
            gi.write_text(SAFE_GITIGNORE, encoding="utf-8")
            self.notes.append(f"Overwrote .gitignore with safe template. Old file saved as {self.rel(backup)}")
        else:
            safe = self.repo / ".gitignore.safe"
            safe.write_text(SAFE_GITIGNORE, encoding="utf-8")
            self.notes.append(f"Wrote safe gitignore template to {self.rel(safe)}. Review and replace .gitignore manually or use --overwrite-gitignore --apply.")

    def analyze_git(self) -> None:
        if not self.git_ok:
            self.notes.append("Git repository not detected; skipping git analysis.")
            return

        # Ignored important files
        r = self.git(["ls-files", "--others", "--ignored", "--exclude-standard"], check=False)
        ignored = []
        for line in r.stdout.splitlines():
            p = line.strip()
            if not p:
                continue

            if any(part.lower() in GENERATED_DIR_NAMES for part in Path(p).parts):
                continue

            if is_secret_file(p):
                continue

            if not p.startswith(("documents/", "scripts/", "backend/", "frontend/")):
                continue

            suffix = Path(p).suffix.lower()
            if suffix not in IMPORTANT_SUFFIXES:
                continue

            ignored.append(p)

            if len(ignored) >= 20000:
                break

        out = self.report_dir / "ignored_important_files.txt"
        out.write_text("\n".join(ignored), encoding="utf-8")
        self.notes.append(f"Found {len(ignored)} ignored important files. See {self.rel(out)}")

        # Gitignore analysis
        broad = self.detect_broad_gitignore_patterns()
        md = ["# Gitignore Analysis", ""]
        if broad:
            md.append("## DANGEROUS broad patterns detected")
            md.append("")
            md.append("These patterns can hide source code/docs/scripts from git and cause loss on clone/pull.")
            md.append("")
            for b in broad:
                md.append(f"- `{b}`")
        else:
            md.append("No obviously dangerous broad .gitignore patterns detected.")

        nested = []
        for root, dirs, files in os.walk(self.repo):
            dirs[:] = [d for d in dirs if d.lower() not in GENERATED_DIR_NAMES]
            if ".gitignore" in files:
                rel = self.rel(Path(root) / ".gitignore")
                if rel != ".gitignore":
                    nested.append(rel)

        md.append("")
        md.append("## Nested .gitignore files")
        md.append("")
        if nested:
            for n in nested:
                md.append(f"- `{n}`")
        else:
            md.append("No nested .gitignore files detected.")

        (self.report_dir / "gitignore_analysis.md").write_text("\n".join(md), encoding="utf-8")

    def force_add_important(self, apply: bool) -> None:
        if not self.git_ok:
            self.notes.append("Git repository not detected; cannot force-add important files.")
            return

        files: list[str] = []

        for root, dirs, filenames in os.walk(self.repo):
            root_path = Path(root)
            rel_root = self.rel(root_path)

            dirs[:] = [
                d for d in dirs
                if d.lower() not in GENERATED_DIR_NAMES
                and not d.startswith(".migration_")
                and d != ".archive"
            ]

            for filename in filenames:
                p = root_path / filename
                rel_path = self.rel(p)

                if is_secret_file(rel_path):
                    continue

                suffix = p.suffix.lower()
                if suffix not in IMPORTANT_SUFFIXES:
                    continue

                # Only important top areas
                if not rel_path.startswith(("documents/", "scripts/", "backend/", "frontend/")):
                    continue

                # Do not add runtime artifact dirs
                if "/var/" in rel_path or rel_path.startswith("backend/var/"):
                    continue

                files.append(rel_path)

        out = self.report_dir / "force_add_important.txt"
        out.write_text("\n".join(files), encoding="utf-8")
        self.notes.append(f"Important files candidate count: {len(files)}. See {self.rel(out)}")

        if not apply:
            return

        batch = []
        for f in files:
            batch.append(f)
            if len(batch) >= 100:
                self.git(["add", "-f", "--"] + batch, check=False)
                batch = []

        if batch:
            self.git(["add", "-f", "--"] + batch, check=False)

        self.notes.append("Force-added important ignored files.")

    # ------------------------------------------------------------------
    # backup
    # ------------------------------------------------------------------

    def backup_actions(self) -> None:
        move_actions = [a for a in self.actions if a.kind == "move" and a.status != "skipped-conflict"]
        if not move_actions:
            return

        self.backup_root.mkdir(parents=True, exist_ok=True)

        for a in move_actions:
            src = self.repo / a.src
            dst = self.backup_root / a.src

            if not src.exists():
                continue

            dst.parent.mkdir(parents=True, exist_ok=True)

            if src.is_dir():
                shutil.copytree(
                    src,
                    dst,
                    ignore=shutil.ignore_patterns(
                        "node_modules",
                        ".next",
                        ".expo",
                        "dist",
                        "build",
                        "coverage",
                        "__pycache__",
                        "playwright-report",
                        "test-results",
                        "test-output",
                        "web-dist",
                    ),
                    dirs_exist_ok=True,
                )
            else:
                shutil.copy2(src, dst)

        self.notes.append(f"Backup created at {self.rel(self.backup_root)}")

    # ------------------------------------------------------------------
    # apply moves
    # ------------------------------------------------------------------

    def ensure_init(self, dir_path: Path, reexport_module: str = "") -> None:
        rel_dir = self.rel(dir_path)
        if not rel_dir.startswith("backend/"):
            return

        parts = {x.lower() for x in dir_path.relative_to(self.repo).parts}
        if {"scripts", "tests", "tools", "docs", "monitoring", "var", "static", "log"} & parts:
            return

        init = dir_path / "__init__.py"
        if init.exists():
            return

        if reexport_module:
            init.write_text(
                f"from .{reexport_module} import *  # created by safe_structure_migration.py\n",
                encoding="utf-8",
            )
        else:
            init.write_text("", encoding="utf-8")

    def move_path(self, a: Action) -> None:
        src = self.repo / a.src
        dst = self.repo / a.dst

        if not src.exists():
            a.status = "missing"
            return

        if dst.exists():
            a.status = "skipped-conflict"
            return

        dst.parent.mkdir(parents=True, exist_ok=True)

        try:
            if src.is_file():
                if a.tracked and self.git_ok:
                    self.git(["mv", "--", a.src, a.dst])
                else:
                    shutil.move(src, dst)

                # remove empty source parent
                try:
                    if src.parent.exists() and not any(src.parent.iterdir()):
                        src.parent.rmdir()
                except Exception:
                    pass

                if a.create_init:
                    self.ensure_init(dst.parent, a.reexport_module)

                a.status = "moved"

            elif src.is_dir():
                dst.mkdir(parents=True, exist_ok=True)

                for child in src.rglob("*"):
                    if child.is_file():
                        rel_child = self.rel(child)
                        child_dst = dst / child.relative_to(src)
                        child_dst.parent.mkdir(parents=True, exist_ok=True)

                        if self.is_tracked(rel_child) and self.git_ok:
                            self.git(["mv", "--", rel_child, self.rel(child_dst)])
                        else:
                            shutil.move(child, child_dst)

                shutil.rmtree(src, ignore_errors=True)

                if a.create_init:
                    self.ensure_init(dst, a.reexport_module)

                a.status = "moved"

        except Exception as exc:
            a.status = "error"
            a.error = str(exc)

    def apply_actions(self) -> None:
        # mkdir first
        for a in self.actions:
            if a.kind != "mkdir":
                continue
            dst = self.repo / a.dst
            dst.mkdir(parents=True, exist_ok=True)
            a.status = "created"

        # moves
        for a in self.actions:
            if a.kind != "move":
                continue
            if a.status == "skipped-conflict":
                continue
            self.move_path(a)

    def stage_changes(self) -> None:
        if not self.git_ok:
            return

        staged = []
        for a in self.actions:
            if a.kind == "move" and a.status == "moved" and a.dst:
                staged.append(a.dst)
            if a.kind == "mkdir" and a.status == "created" and a.dst:
                staged.append(a.dst)

        batch = []
        for p in staged:
            batch.append(p)
            if len(batch) >= 100:
                self.git(["add", "--"] + batch, check=False)
                batch = []

        if batch:
            self.git(["add", "--"] + batch, check=False)

        self.notes.append("Staged moved/created paths.")

    # ------------------------------------------------------------------
    # import replacement
    # ------------------------------------------------------------------

    def iter_py_files(self) -> Iterable[Path]:
        for root, dirs, files in os.walk(self.repo):
            root_path = Path(root)

            dirs[:] = [
                d for d in dirs
                if d.lower() not in GENERATED_DIR_NAMES
                and not d.startswith(".migration_")
                and d != "migration_reports"
            ]

            for f in files:
                if f.endswith(".py"):
                    yield root_path / f

    def replace_imports(self, apply: bool) -> None:
        if not self.replacements:
            return

        replacements = sorted(self.replacements, key=lambda x: len(x[0]), reverse=True)
        report = {}

        for py in self.iter_py_files():
            try:
                text = py.read_text(encoding="utf-8", errors="replace")
            except Exception:
                continue

            lines = text.splitlines(keepends=True)
            changed = False

            for i, line in enumerate(lines):
                if "import" not in line:
                    continue

                new_line = line
                for old, new in replacements:
                    pattern = re.compile(r"(?<![\w.])" + re.escape(old) + r"(?![\w.])")
                    if pattern.search(new_line):
                        new_line = pattern.sub(new, new_line)
                        changed = True

                lines[i] = new_line

            if changed:
                report[self.rel(py)] = "would-update" if not apply else "updated"
                if apply:
                    py.write_text("".join(lines), encoding="utf-8")

        out = self.report_dir / "import_rewrites.json"
        out.write_text(json.dumps(report, indent=2), encoding="utf-8")
        self.notes.append(f"Import rewrite report: {self.rel(out)}")

    # ------------------------------------------------------------------
    # reports
    # ------------------------------------------------------------------

    def write_reports(self) -> None:
        plan_json = self.report_dir / "plan.json"
        plan_json.write_text(json.dumps([asdict(a) for a in self.actions], indent=2), encoding="utf-8")

        md = []
        md.append("# Safe Structure Migration Plan")
        md.append("")
        md.append(f"Generated: {datetime.datetime.now().isoformat()}")
        md.append(f"Repo: `{self.repo}`")
        md.append(f"Mode: {'APPLY' if self.args.apply else 'DRY-RUN'}")
        md.append("")
        md.append("## Notes")
        md.append("")
        if self.notes:
            for n in self.notes:
                md.append(f"- {n}")
        else:
            md.append("- none")
        md.append("")

        md.append("## Actions")
        md.append("")
        md.append("| Status | Kind | Source | Destination | Reason | Tracked | Ignored | Conflict | Error |")
        md.append("|---|---|---|---|---|---|---|---|---|")

        for a in self.actions:
            reason = a.reason.replace("|", "/")
            error = a.error.replace("|", "/")
            md.append(
                f"| {a.status} | {a.kind} | `{a.src}` | `{a.dst}` | {reason} | "
                f"{a.tracked} | {a.ignored} | {a.conflict} | {error} |"
            )

        md.append("")
        md.append("## Import replacements")
        md.append("")
        if self.replacements:
            md.append("| Old module | New module |")
            md.append("|---|---|")
            for old, new in sorted(self.replacements):
                md.append(f"| `{old}` | `{new}` |")
        else:
            md.append("No import replacements registered.")

        plan_md = self.report_dir / "plan.md"
        plan_md.write_text("\n".join(md), encoding="utf-8")

    # ------------------------------------------------------------------
    # run
    # ------------------------------------------------------------------

    def preflight(self) -> None:
        if self.args.apply:
            if not self.git_ok and not self.args.no_git:
                print("[FATAL] Git repository not detected. Use --no-git to override (not recommended).", file=sys.stderr)
                sys.exit(2)

            if self.git_ok and self.git_status_dirty() and not self.args.allow_dirty:
                print("[FATAL] Git working tree is dirty. Commit/stash first or use --allow-dirty.", file=sys.stderr)
                sys.exit(2)

            if self.git_ok:
                branch = f"backup/pre-migration-{self.stamp}"
                self.git(["branch", branch], check=False)
                self.notes.append(f"Created backup branch: {branch}")

    def run(self) -> None:
        self.preflight()

        self.build_plan()

        if self.args.generate_domain_map:
            self.generate_domain_map()

        if self.args.apply_mapping:
            self.apply_mapping_file(self.args.apply_mapping)

        if self.args.analyze_git:
            self.analyze_git()

        if self.args.fix_gitignore:
            self.write_gitignore_template(overwrite=False)

        if self.args.overwrite_gitignore:
            self.write_gitignore_template(overwrite=True)

        self.write_reports()

        if self.args.apply:
            if self.args.backup:
                self.backup_actions()

            self.apply_actions()
            self.replace_imports(apply=True)

            if self.args.force_add_important:
                self.force_add_important(apply=True)

            if self.args.stage_changes:
                self.stage_changes()

            self.write_reports()
            print(f"[OK] Migration applied. Reports: {self.report_dir}")
        else:
            self.replace_imports(apply=False)

            if self.args.force_add_important:
                self.force_add_important(apply=False)

            print(f"[DRY-RUN] No files were moved. Reports: {self.report_dir}")


# ============================================================================
# MAIN
# ============================================================================

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Safely migrate ZOZI repository toward the planned target structure."
    )

    parser.add_argument("--root", default=".", help="repository root")
    parser.add_argument("--apply", action="store_true", help="actually apply changes")
    parser.add_argument("--dry-run", action="store_true", help="explicit dry-run (default)")
    parser.add_argument("--analyze-git", action="store_true", help="analyze ignored important files and gitignore")
    parser.add_argument("--fix-gitignore", action="store_true", help="write .gitignore.safe template")
    parser.add_argument("--overwrite-gitignore", action="store_true", help="overwrite .gitignore with safe template when --apply")
    parser.add_argument("--force-add-important", action="store_true", help="force-add important ignored files")
    parser.add_argument("--stage-changes", action="store_true", help="stage moved/created files after apply")
    parser.add_argument("--backup", dest="backup", action="store_true", default=True, help="backup moved files before apply")
    parser.add_argument("--no-backup", dest="backup", action="store_false", help="disable backup")
    parser.add_argument("--move-backend-code", action="store_true", help="enable known backend code moves")
    parser.add_argument("--generate-domain-map", action="store_true", help="generate suggested domain_map.json")
    parser.add_argument("--apply-mapping", default=None, help="apply approved entries from a mapping JSON file")
    parser.add_argument("--allow-dirty", action="store_true", help="allow apply even if git tree is dirty")
    parser.add_argument("--no-git", action="store_true", help="override git requirement")

    args = parser.parse_args()

    # dry-run is default unless --apply
    if not args.apply:
        args.dry_run = True

    m = Migrator(args)
    m.run()
    return 0


if __name__ == "__main__":
    sys.exit(main())