from __future__ import annotations
from uuid import uuid4
from sqlalchemy import func, UUID
from decimal import Decimal
from sqlalchemy import Column, Integer, String, DateTime, Boolean, Text, Numeric, ForeignKey, UniqueConstraint, Index, JSON, text
from sqlalchemy.orm import relationship
from infrastructure.database.types import GUID
from . import Base
from infrastructure.utils.datetime_utils import utcnow as utcnow

# Lazy imports for cross-domain relationships (avoid circular imports)
# All relationships resolved lazily via string reference to avoid circular imports
__all__ = ['CountryConfig', 'CountryCommunication', 'CountryGatewayCredentials', 'ShippingRule']

class CountryConfig(Base):
    __tablename__ = 'country_configs'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_country_configs_country_created', 'country_code', 'created_at'), {'schema': 'country'})
    id = Column(Integer, primary_key=True, index=True)
    basics_id = Column(Integer, ForeignKey('country.country_basics.id', ondelete='RESTRICT'), nullable=True, index=True)
    code = Column(String(2), unique=True, nullable=False, index=True)
    name = Column(String, nullable=False)
    currency = Column(String(3), default='USD')
    currency_symbol = Column(String(10), nullable=True)
    phone_code = Column(String(10), nullable=True)
    language = Column(String(10), default='en')
    timezone = Column(String(60), nullable=True)
    date_format = Column(String(20), default='DD/MM/YYYY')
    status = Column(String(20), default='active')
    is_active = Column(Boolean, default=True)
    is_deleted = Column(Boolean, default=False, nullable=False)
    is_default = Column(Boolean, default=False)
    created_at = Column(DateTime, default=utcnow)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)
    official_name = Column(String(200), nullable=True)
    alpha3 = Column(String(3), nullable=True)
    flag_url = Column(String(500), nullable=True)
    currency_name = Column(String(50), nullable=True)
    exchange_rate_to_usd = Column(Numeric(12, 6), nullable=True)
    capital = Column(String(100), nullable=True)
    region = Column(String(60), nullable=True)
    subregion = Column(String(60), nullable=True)
    population = Column(Integer, nullable=True)
    internet_penetration_pct = Column(Numeric(5, 2), nullable=True)
    gdp_per_capita_usd = Column(Numeric(12, 2), nullable=True)
    urbanization_pct = Column(Numeric(5, 2), nullable=True)
    mobile_subs_per_100 = Column(Numeric(5, 2), nullable=True)
    public_holidays_json = Column(Text, nullable=True)
    macro_indicators_json = Column(Text, nullable=True)
    tax_type = Column(String(20), default='VAT')
    tax_rate = Column(Numeric(5, 4), default=Decimal('0.0000'))
    tax_name = Column(String(50), default='VAT')
    tax_inclusive = Column(Boolean, default=False)
    tax_exempt_categories_json = Column(Text, default='[]')
    tax_reduced_rates_json = Column(Text, default='{}')
    logistics_model = Column(String(30), default='fixed')
    default_vehicle_type = Column(String(30), nullable=True)
    base_rate = Column(Numeric(10, 2), nullable=True)
    per_km_rate = Column(Numeric(10, 2), nullable=True)
    minimum_charge = Column(Numeric(10, 2), nullable=True)
    weight_surcharge_rate = Column(Numeric(5, 4), nullable=True)
    weight_surcharge_threshold_kg = Column(Numeric(10, 2), nullable=True)
    payment_methods_json = Column(Text, default='[]')
    payment_gateways_json = Column(Text, nullable=True)
    logistics_providers_json = Column(Text, nullable=True)
    legal_rules_json = Column(Text, nullable=True)
    product_restrictions_json = Column(Text, default='[]')
    address_format_json = Column(Text, default='{"fields":["street","city","postal_code"],"required":["street","city"]}')
    regions_json = Column(Text, default='[]')
    supplier_requirements_json = Column(Text, nullable=True)
    payout_settings_json = Column(Text, nullable=True)
    commission_tiers_json = Column(Text, nullable=True)
    suggested_gateway_rankings_json = Column(Text, nullable=True)
    suggested_commission_ranges_json = Column(Text, nullable=True)
    consumer_behavior_profile_json = Column(Text, nullable=True)
    economic_tier = Column(String(20), nullable=True)
    fraud_risk_tier = Column(String(10), nullable=True)
    suggested_logistics_model = Column(String(30), nullable=True)
    data_residency_tier = Column(String(20), default='standard')
    data_residency_encrypted = Column(Text, nullable=True)
    confidence_score = Column(Numeric(5, 4), default=Decimal('0.0000'))
    audit_trail_json = Column(Text, nullable=True)
    cod_enabled = Column(Boolean, nullable=True)
    cod_max_amount = Column(Numeric(12, 2), nullable=True)
    cod_verification_required = Column(Boolean, nullable=True)
    cod_remittance_days = Column(Integer, nullable=True)
    settlement_hold_days = Column(Integer, default=3)
    minimum_payout_amount = Column(Numeric(12, 2), nullable=True)
    payout_currency = Column(String(10), nullable=True)
    supplier_kyc_tier = Column(String(20), nullable=True)
    supplier_onboarding_fee = Column(Numeric(12, 2), nullable=True)
    supplier_monthly_fee = Column(Numeric(12, 2), nullable=True)
    supplier_rating_threshold = Column(Numeric(5, 2), nullable=True)
    legal_entity_required = Column(Boolean, default=False)
    consumer_protection_days = Column(Integer, default=14)
    data_privacy_framework = Column(String(20), nullable=True)
    max_package_weight_kg = Column(Numeric(8, 2), nullable=True)
    max_package_dimensions_cm = Column(String(200), nullable=True)
    signature_required_threshold = Column(Numeric(10, 2), nullable=True)
    measurement_system = Column(String(10), default='metric')
    working_days_json = Column(Text, default='[]')
    supported_languages_json = Column(Text, default='[]')
    payout_methods_json = Column(Text, default='[]')
    logistics_zones_json = Column(Text, default='[]')
    country_code = Column(String(2), nullable=True, unique=True, index=True)
    communications = relationship('CountryCommunication', back_populates='country')
    gateway_credentials = relationship('CountryGatewayCredentials', back_populates='country')
    tax_rules = relationship('TaxRule', back_populates='country')
    shipping_rules = relationship('ShippingRule', back_populates='country', primaryjoin='CountryConfig.code == foreign(ShippingRule.country_code)')
    payout_rules = relationship('PayoutRule', back_populates='country', primaryjoin='CountryConfig.code == foreign(PayoutRule.country_code)')
    category_tax_rates = relationship('CountryCategoryTaxRate', back_populates='country', primaryjoin='CountryConfig.code == foreign(CountryCategoryTaxRate.country_code)')
    feature_flags = relationship('CountryFeatureFlag', back_populates='country', primaryjoin='CountryConfig.code == foreign(CountryFeatureFlag.country_code)')
    staff_assignments = relationship('CountryStaffAssignment', back_populates='country', primaryjoin='CountryConfig.code == foreign(CountryStaffAssignment.country_code)')
    config_versions = relationship('CountryConfigVersion', back_populates='country', primaryjoin='CountryConfig.code == foreign(CountryConfigVersion.country_code)')
    commission_rates = relationship('CountryCommissionRate', back_populates='country', primaryjoin='CountryConfig.code == foreign(CountryCommissionRate.country_code)')
    kyc_requirements = relationship('SupplierKYCRequirement', back_populates='country', uselist=False)
    logistics_kyc_requirements = relationship('LogisticsPartnerKYCRequirement', back_populates='country', uselist=False)
    cities = relationship('CountryCity', back_populates='country')
    basics = relationship('CountryBasics', back_populates='country', uselist=False, primaryjoin='CountryConfig.code == foreign(CountryBasics.country_code)')
    economics = relationship('CountryEconomics', back_populates='country', uselist=False)
    legal = relationship('CountryLegal', back_populates='country', uselist=False)
    tax = relationship('CountryTax', back_populates='country', uselist=False)

class CountryCommunication(Base):
    __tablename__ = 'country_communications'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_country_communications_recipient', 'to_user_id', 'status'), Index('ix_country_communications_country_created', 'country_code', 'created_at'), {'schema': 'country'})
    id = Column(Integer, primary_key=True, index=True)
    country_code = Column(String(2), ForeignKey('country.country_configs.code', ondelete='RESTRICT'), nullable=False, index=True)
    from_user_id = Column(Integer, nullable=True)
    to_user_id = Column(Integer, nullable=True)
    subject = Column(String(200), nullable=False)
    body = Column(Text, nullable=False)
    priority = Column(String(20), default='normal')
    category = Column(String(50), nullable=True)
    status = Column(String(20), default='sent')
    related_entity_type = Column(String(50), nullable=True)
    related_entity_id = Column(Integer, nullable=True)
    read_at = Column(DateTime, nullable=True)
    attachments_json = Column(Text, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    country = relationship('CountryConfig', back_populates='communications')
    from_user = relationship('User', primaryjoin='foreign(CountryCommunication.from_user_id) == User.id')
    to_user = relationship('User', primaryjoin='foreign(CountryCommunication.to_user_id) == User.id')

class CountryGatewayCredentials(Base):
    __tablename__ = 'country_gateway_credentials'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_country_gateway_credentials_country_created', 'country_code', 'created_at'), {'schema': 'country'})
    id = Column(Integer, primary_key=True, index=True)
    country_code = Column(String(2), ForeignKey('country.country_configs.code', ondelete='RESTRICT'), nullable=False, index=True)
    gateway_name = Column(String(100), nullable=False)
    environment = Column(String(20), default='test')
    credentials = Column(JSON, nullable=True)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    country = relationship('CountryConfig', back_populates='gateway_credentials')

