from __future__ import annotations
from uuid import uuid4
from sqlalchemy import func, UUID
from sqlalchemy import Column, Integer, String, DateTime, Boolean, Text, ForeignKey, UniqueConstraint, Index, JSON, Numeric, text
from sqlalchemy.orm import relationship
from . import Base
from utils.datetime_utils import utcnow as utcnow
from ..mixins import TenantMixin
from db.mixins import VersionMixin
__all__ = ['Address', 'Cart', 'CartItem', 'AuditLog', 'SupportTicket', 'SupportTicketReply', 'TicketAttachment', 'UserBrowsingHistory', 'CityDistanceMatrix', 'ExecutiveNews', 'UserSession', 'SystemHealthEvent', 'CommandCenterView', 'NewsSource', 'NewsArticle', 'InternalNotice', 'PredictiveSimulation', 'AlertEscalationRule', 'EntityChatThread', 'EntityChatMessage', 'VideoRoom', 'VideoRoomParticipant', 'VideoRoomRecording', 'DirectChatRoom', 'DirectChatMessage', 'GroupChatRoom', 'GroupChatMember', 'GroupChatMessage', 'ShiftHandoverSession', 'ShiftHandoverTask', 'EscalationSLARule', 'EscalationSLALog']

class Address(Base, TenantMixin):
    __tablename__ = 'addresses'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_addresses_country_created', 'country_code', 'created_at'), {'schema': 'customer'})
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey('security.users.id', ondelete='RESTRICT'), nullable=False, index=True)
    label = Column(String, nullable=True)
    full_name = Column(String, nullable=False)
    phone = Column(String, nullable=True)
    address_line1 = Column(String, nullable=False)
    address_line2 = Column(String, nullable=True)
    city = Column(String, nullable=False)
    state = Column(String, nullable=True)
    postal_code = Column(String, nullable=True)
    country = Column(String, default='US')
    is_default = Column(Boolean, default=False)
    user = relationship('User', back_populates='addresses', primaryjoin='foreign(Address.user_id) == User.id')
    created_at = Column(DateTime, default=utcnow)

class Cart(Base, TenantMixin):
    __tablename__ = 'carts'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_carts_country_created', 'country_code', 'created_at'), {'schema': 'commerce'})
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, nullable=False)
    user = relationship('User', back_populates='cart', primaryjoin='foreign(Cart.user_id) == User.id')
    created_at = Column(DateTime, default=utcnow)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)

class CartItem(Base, TenantMixin):
    __tablename__ = 'cart_items'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_cart_items_country_created', 'country_code', 'created_at'), {'schema': 'commerce'})
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, nullable=False)
    product_id = Column(Integer, ForeignKey('commerce.products.id', ondelete='RESTRICT'), nullable=False, index=True)
    quantity = Column(Integer, default=1)
    selected_size = Column(String(50), default='', nullable=False)
    selected_color = Column(String(50), default='', nullable=False)
    variant_id = Column(Integer, nullable=True)
    user = relationship('User', back_populates='cart_items', primaryjoin='foreign(CartItem.user_id) == User.id')
    created_at = Column(DateTime, default=utcnow)
    product = relationship('Product', back_populates='cart_items')

class AuditLog(Base):
    __tablename__ = 'audit_logs'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __partition_by__ = 'range'
    __partition_key__ = 'created_at'
    __table_args__ = (Index('ix_audit_logs_old_value_json_gin', 'old_value_json', postgresql_using='gin'), Index('ix_audit_logs_new_value_json_gin', 'new_value_json', postgresql_using='gin'), Index('ix_audit_logs_details_gin', 'details', postgresql_using='gin'), Index('ix_audit_logs_country_created', 'country_code', 'created_at'), {'schema': 'audit'})
    id = Column(Integer, primary_key=True, index=True)
    log_type = Column(String(50), nullable=True)
    actor = Column(String(255), nullable=True)
    entity = Column(String(255), nullable=True)
    action = Column(String, nullable=False)
    entity_type = Column(String, nullable=False)
    entity_id = Column(Integer, nullable=True)
    user_id = Column(Integer, nullable=True)
    username = Column(String, nullable=True)
    user_role = Column(String, nullable=True)
    country_code = Column(String(3), nullable=True)
    old_value_json = Column(JSON, nullable=True)
    new_value_json = Column(JSON, nullable=True)
    details = Column(JSON, nullable=True)
    ip_address = Column(String, nullable=True)
    created_at = Column(DateTime, default=utcnow)

class SupportTicket(Base, TenantMixin):
    __tablename__ = 'support_tickets'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_support_tickets_country_created', 'country_code', 'created_at'), {'schema': 'communication'})
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, nullable=False)
    subject = Column(String, nullable=False)
    priority = Column(String, default='medium')
    status = Column(String, default='open')
    created_at = Column(DateTime, default=utcnow)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)
    attachments = relationship('TicketAttachment', back_populates='ticket')
    messages = relationship('TicketMessage', back_populates='ticket', cascade='all, delete-orphan')

class SupportTicketReply(Base, TenantMixin):
    __tablename__ = 'support_ticket_replies'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_support_ticket_replies_country_created', 'country_code', 'created_at'), {'schema': 'communication'})
    id = Column(Integer, primary_key=True, index=True)
    ticket_id = Column(Integer, ForeignKey('communication.support_tickets.id', ondelete='RESTRICT'), nullable=False, index=True)
    sender_id = Column(Integer, nullable=False)
    message = Column(Text, nullable=False)
    created_at = Column(DateTime, default=utcnow)
    attachments = relationship('TicketAttachment', back_populates='ticket_reply')

class TicketAttachment(Base, TenantMixin):
    __tablename__ = 'ticket_attachments'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_ticket_attachments_country_created', 'country_code', 'created_at'), {'schema': 'communication'})
    id = Column(Integer, primary_key=True, index=True)
    ticket_reply_id = Column(Integer, ForeignKey('communication.support_ticket_replies.id', ondelete='RESTRICT'), nullable=True, index=True)
    ticket_id = Column(Integer, ForeignKey('communication.support_tickets.id', ondelete='RESTRICT'), nullable=True, index=True)
    file_url = Column(String, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    ticket_reply = relationship('SupportTicketReply', back_populates='attachments')
    ticket = relationship('SupportTicket', back_populates='attachments')

class CityDistanceMatrix(Base):
    __tablename__ = 'city_distance_matrix'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    __table_args__ = ({'schema': 'logistics'},)
    id = Column(Integer, primary_key=True, index=True)
    origin_country_code = Column(String(3), nullable=False)
    origin_city_name = Column(String, nullable=False)
    destination_country_code = Column(String(3), nullable=False)
    destination_city_name = Column(String, nullable=False)
    distance_km = Column(Numeric(10, 2), nullable=True)
    notes = Column(Text, nullable=True)
    created_by = Column(Integer, nullable=True)
    updated_by = Column(Integer, nullable=True)
    created_at = Column(DateTime, default=utcnow)

class ExecutiveNews(Base, TenantMixin):
    __tablename__ = 'executive_news'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_executive_news_country_created', 'country_code', 'created_at'), {'schema': 'analytics'})
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(200), nullable=False)
    summary = Column(Text, nullable=True)
    content = Column(Text, nullable=True)
    url = Column(String(500), nullable=True)
    category = Column(String(50), default='general')
    priority = Column(String(20), default='normal')
    ai_sentiment = Column(String(20), default='neutral')
    published_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=utcnow)

class UserBrowsingHistory(Base):
    __tablename__ = 'user_browsing_history'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'security'},)
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey('security.users.id', ondelete='RESTRICT'), nullable=False, index=True)
    product_id = Column(Integer, nullable=False, index=True)
    viewed_at = Column(DateTime, default=utcnow)

class SystemHealthEvent(Base):
    __tablename__ = 'system_health_events'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    id = Column(Integer, primary_key=True, index=True)
    service = Column(String(100), nullable=True)
    metric_name = Column(String(100), nullable=False)
    metric_value = Column(Numeric(12, 4), nullable=False)
    severity = Column(String(20), default='info')
    message = Column(Text, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    __table_args__ = (Index('ix_health_events_metric_time', 'metric_name', 'created_at'), {'schema': 'customer'})

class UserSession(Base, TenantMixin):
    __tablename__ = 'user_sessions'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_user_sessions_country_created', 'country_code', 'created_at'), {'schema': 'security'})
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey('security.users.id', ondelete='RESTRICT'), nullable=False, index=True)
    session_token = Column(String(255), unique=True, nullable=False, index=True)
    ip_address = Column(String(45), nullable=True)
    user_agent = Column(String(500), nullable=True)
    created_at = Column(DateTime, default=utcnow)

class CommandCenterView(Base):
    __tablename__ = 'command_center_views'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_command_center_views_config_gin', 'config', postgresql_using='gin'), {'schema': 'audit'})
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, nullable=False)
    view_name = Column(String(100), nullable=False)
    config = Column(JSON, nullable=True)
    is_default = Column(Boolean, default=False)
    created_at = Column(DateTime, default=utcnow)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)

class NewsSource(Base):
    __tablename__ = 'news_sources'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'communication'},)
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    url = Column(String(500), nullable=False)
    source_type = Column(String(20), default='rss')
    api_key_required = Column(Boolean, default=False)
    category = Column(String(50), default='general')

class NewsArticle(Base, TenantMixin):
    __tablename__ = 'news_articles'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_news_articles_published', 'published_at'), Index('ix_news_articles_ai_tags_gin', 'ai_tags', postgresql_using='gin'), Index('ix_news_articles_country_created', 'country_code', 'created_at'), {'schema': 'customer'})
    id = Column(Integer, primary_key=True, index=True)
    source_id = Column(Integer, nullable=True)
    external_id = Column(String(255), nullable=True)
    content_hash = Column(String(64), nullable=True, index=True)
    title = Column(String(300), nullable=False)
    summary = Column(Text, nullable=True)
    content = Column(Text, nullable=True)
    url = Column(String(500), nullable=True)
    image_url = Column(String(500), nullable=True)
    published_at = Column(DateTime, nullable=True)
    ai_tags = Column(JSON, nullable=True)
    is_published = Column(Boolean, default=True)
    created_at = Column(DateTime, default=utcnow)

class InternalNotice(Base):
    __tablename__ = 'internal_notices'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'communication'},)
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(200), nullable=False)
    content = Column(Text, nullable=False)
    priority = Column(String(20), default='normal')
    valid_to = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=utcnow)

class PredictiveSimulation(Base):
    __tablename__ = 'predictive_simulations'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'ai'},)
    id = Column(Integer, primary_key=True, index=True)
    simulation_type = Column(String(50), nullable=False)
    parameters_json = Column(Text, nullable=False)
    result_json = Column(Text, nullable=False)
    created_at = Column(DateTime, default=utcnow)

class AlertEscalationRule(Base):
    __tablename__ = 'alert_escalation_rules'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'security'},)
    id = Column(Integer, primary_key=True, index=True)
    alert_type = Column(String(50), nullable=False)
    severity = Column(String(20), default='medium')
    threshold_value = Column(Numeric(15, 2), nullable=True)
    current_tier = Column(Integer, default=0)

class EntityChatThread(Base):
    __tablename__ = 'entity_chat_threads'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    id = Column(Integer, primary_key=True, index=True)
    entity_type = Column(String, nullable=False)
    entity_id = Column(Integer, nullable=False)
    title = Column(String(200), nullable=True)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)
    messages = relationship('EntityChatMessage', back_populates='thread', cascade='all, delete-orphan', primaryjoin='EntityChatThread.id == foreign(EntityChatMessage.thread_id)')
    __table_args__ = (Index('idx_entity_thread', 'entity_type', 'entity_id'), {'schema': 'customer'})

class EntityChatMessage(Base):
    __tablename__ = 'entity_chat_messages'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __partition_by__ = 'range'
    __partition_key__ = 'created_at'
    __table_args__ = ({'schema': 'communication'},)
    id = Column(Integer, primary_key=True, index=True)
    thread_id = Column(Integer, nullable=False)
    sender_id = Column(Integer, nullable=False)
    message = Column(Text, nullable=False)
    message_type = Column(String(20), default='text')
    read_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    thread = relationship('EntityChatThread', back_populates='messages', primaryjoin='foreign(EntityChatMessage.thread_id) == EntityChatThread.id')
    sender = relationship('User', primaryjoin='foreign(EntityChatMessage.sender_id) == User.id')

class VideoRoom(Base, TenantMixin):
    __tablename__ = 'video_rooms'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_video_room_status', 'status'), Index('ix_video_room_created', 'created_at'), Index('ix_video_rooms_country_created', 'country_code', 'created_at'), {'schema': 'customer'})
    id = Column(Integer, primary_key=True, index=True)
    room_id = Column(String(64), unique=True, nullable=False, index=True)
    room_uuid = Column(String(32), unique=True, nullable=True)
    name = Column(String(200), nullable=False)
    is_boardroom = Column(Boolean, default=False)
    status = Column(String(20), default='waiting')
    max_participants = Column(Integer, default=100)
    recording_enabled = Column(Boolean, default=False)
    watermark_enabled = Column(Boolean, default=True)
    transcription_enabled = Column(Boolean, default=True)
    started_at = Column(DateTime, nullable=True)
    ended_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    created_by = Column(Integer, nullable=True)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)
    participants = relationship('VideoRoomParticipant', back_populates='room', cascade='all, delete-orphan')
    recordings = relationship('VideoRoomRecording', back_populates='room', cascade='all, delete-orphan', primaryjoin='VideoRoom.id == foreign(VideoRoomRecording.room_id)')
    creator = relationship('User', foreign_keys='VideoRoom.created_by', primaryjoin='foreign(VideoRoom.created_by) == User.id')

class VideoRoomParticipant(Base):
    __tablename__ = 'video_room_participants'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (UniqueConstraint('room_id', 'user_id', name='uq_video_participant'), {'schema': 'customer'})
    id = Column(Integer, primary_key=True, index=True)
    room_id = Column(Integer, ForeignKey('customer.video_rooms.id', ondelete='RESTRICT'), nullable=False, index=True)
    user_id = Column(Integer, nullable=False)
    role = Column(String(20), default='participant')
    joined_at = Column(DateTime, default=utcnow)
    left_at = Column(DateTime, nullable=True)
    room = relationship('VideoRoom', back_populates='participants')
    user = relationship('User', primaryjoin='foreign(VideoRoomParticipant.user_id) == User.id')

class VideoRoomRecording(Base):
    __tablename__ = 'video_room_recordings'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'media'},)
    id = Column(Integer, primary_key=True, index=True)
    room_id = Column(Integer, nullable=False)
    started_by = Column(Integer, nullable=False)
    recording_url = Column(String(500), nullable=True)
    duration_seconds = Column(Integer, default=0)
    status = Column(String(20), default='recording')
    started_at = Column(DateTime, default=utcnow)
    ended_at = Column(DateTime, nullable=True)
    room = relationship('VideoRoom', back_populates='recordings', primaryjoin='foreign(VideoRoomRecording.room_id) == VideoRoom.id')
    starter = relationship('User', primaryjoin='foreign(VideoRoomRecording.started_by) == User.id')

class DirectChatRoom(Base, TenantMixin):
    __tablename__ = 'direct_chat_rooms'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    id = Column(Integer, primary_key=True, index=True)
    chat_id = Column(String(64), unique=True, nullable=False, index=True)
    participant_one = Column(Integer, nullable=False)
    participant_two = Column(Integer, nullable=False)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)
    messages = relationship('DirectChatMessage', back_populates='room', cascade='all, delete-orphan', primaryjoin='DirectChatRoom.id == foreign(DirectChatMessage.room_id)')
    __table_args__ = (UniqueConstraint('participant_one', 'participant_two', name='uq_direct_chat_pair'), {'schema': 'customer'})

class DirectChatMessage(Base):
    __tablename__ = 'direct_chat_messages'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'communication'},)
    id = Column(Integer, primary_key=True, index=True)
    room_id = Column(Integer, nullable=False)
    sender_id = Column(Integer, nullable=False)
    message = Column(Text, nullable=False)
    message_type = Column(String(20), default='text')
    read_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    room = relationship('DirectChatRoom', back_populates='messages', primaryjoin='foreign(DirectChatMessage.room_id) == DirectChatRoom.id')
    sender = relationship('User', primaryjoin='foreign(DirectChatMessage.sender_id) == User.id')

class GroupChatRoom(Base, TenantMixin):
    __tablename__ = 'group_chat_rooms'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_group_chat_rooms_country_created', 'country_code', 'created_at'), {'schema': 'communication'})
    id = Column(Integer, primary_key=True, index=True)
    chat_id = Column(String(64), unique=True, nullable=False, index=True)
    name = Column(String(200), nullable=False)
    created_at = Column(DateTime, default=utcnow)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)
    members = relationship('GroupChatMember', back_populates='room', cascade='all, delete-orphan', primaryjoin='GroupChatRoom.id == foreign(GroupChatMember.room_id)')
    messages = relationship('GroupChatMessage', back_populates='room', cascade='all, delete-orphan')

class GroupChatMember(Base):
    __tablename__ = 'group_chat_members'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (UniqueConstraint('room_id', 'user_id', name='uq_group_member'), {'schema': 'customer'})
    id = Column(Integer, primary_key=True, index=True)
    room_id = Column(Integer, nullable=False)
    user_id = Column(Integer, nullable=False)
    role = Column(String(20), default='member')
    joined_at = Column(DateTime, default=utcnow)
    room = relationship('GroupChatRoom', back_populates='members', primaryjoin='foreign(GroupChatMember.room_id) == GroupChatRoom.id')
    user = relationship('User', primaryjoin='foreign(GroupChatMember.user_id) == User.id')

class GroupChatMessage(Base):
    __tablename__ = 'group_chat_messages'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'communication'},)
    id = Column(Integer, primary_key=True, index=True)
    room_id = Column(Integer, ForeignKey('communication.group_chat_rooms.id', ondelete='RESTRICT'), nullable=False, index=True)
    sender_id = Column(Integer, nullable=False)
    message = Column(Text, nullable=False)
    message_type = Column(String(20), default='text')
    read_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    room = relationship('GroupChatRoom', back_populates='messages')
    sender = relationship('User', primaryjoin='foreign(GroupChatMessage.sender_id) == User.id')

class ShiftHandoverSession(Base, TenantMixin):
    __tablename__ = 'shift_handover_sessions'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_handover_outgoing', 'outgoing_employee_id'), Index('ix_handover_incoming', 'incoming_employee_id'), Index('ix_handover_status', 'status'), Index('ix_shift_handover_sessions_country_created', 'country_code', 'created_at'), {'schema': 'customer'})
    id = Column(Integer, primary_key=True, index=True)
    outgoing_employee_id = Column(Integer, nullable=False)
    incoming_employee_id = Column(Integer, nullable=True)
    shift_date = Column(DateTime, nullable=False)
    notes = Column(Text, nullable=True)
    status = Column(String(20), default='pending')
    acknowledged_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)
    tasks = relationship('ShiftHandoverTask', back_populates='session', cascade='all, delete-orphan', primaryjoin='ShiftHandoverSession.id == foreign(ShiftHandoverTask.session_id)')

class ShiftHandoverTask(Base):
    __tablename__ = 'shift_handover_tasks'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'hr'},)
    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, nullable=False)
    description = Column(Text, nullable=False)
    priority = Column(String(20), default='normal')
    status = Column(String(20), default='open')
    assigned_to = Column(Integer, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    session = relationship('ShiftHandoverSession', back_populates='tasks', primaryjoin='foreign(ShiftHandoverTask.session_id) == ShiftHandoverSession.id')

class EscalationSLARule(Base, TenantMixin):
    __tablename__ = 'escalation_sla_rules'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'communication'},)
    id = Column(Integer, primary_key=True, index=True)
    escalate_after_minutes = Column(Integer, nullable=False)
    escalate_to_role = Column(String(40), nullable=False)
    notify_via = Column(String(100), default='email,sms')

class EscalationSLALog(Base):
    __tablename__ = 'escalation_sla_logs'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_escalation_message', 'message_id'), Index('ix_escalation_status', 'status'), {'schema': 'customer'})
    id = Column(Integer, primary_key=True, index=True)
    message_id = Column(Integer, nullable=False)
    message_type = Column(String(30), nullable=False)
    original_recipient_id = Column(Integer, nullable=True)
    escalated_to_user_id = Column(Integer, nullable=True)
    escalated_to_role = Column(String(40), nullable=True)
    priority = Column(String(20), nullable=False)
    elapsed_minutes = Column(Integer, default=0)
    status = Column(String(20), default='pending')
    escalated_at = Column(DateTime, nullable=True)
    acknowledged_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=utcnow)
Index('ix_audit_logs_old_value_json', text('(old_value_json::jsonb)'), postgresql_using='gin')
Index('ix_audit_logs_new_value_json', text('(new_value_json::jsonb)'), postgresql_using='gin')
Index('ix_audit_logs_details', text('(details::jsonb)'), postgresql_using='gin')
Index('ix_command_center_views_config', text('(config::jsonb)'), postgresql_using='gin')
Index('ix_news_articles_ai_tags', text('(ai_tags::jsonb)'), postgresql_using='gin')