"""Enhanced OpenAPI documentation configuration for the Zozi E-commerce API.

This module provides enhanced OpenAPI documentation with detailed descriptions,
examples, and improved tag organization for better developer experience.
"""

from fastapi import FastAPI
from fastapi.openapi.models import OpenAPI
from typing import Callable, Dict, Any


def create_enhanced_openapi_schema(app: FastAPI) -> OpenAPI:
    """Create enhanced OpenAPI schema with descriptions and examples.

    This function accesses the existing FastAPI auto-generated schema
    and adds enhanced documentation for better developer experience.

    Args:
        app: The FastAPI application instance

    Returns:
        Enhanced OpenAPI schema with detailed documentation
    """
    # Access the existing OpenAPI schema generated by FastAPI
    schema = app.openapi()

    # The schema already includes:
    # - All 150+ API endpoints (/api/v1/...)
    # - Request/response models
    # - Security schemes
    # - Auto-generated parameter descriptions

    return schema


def get_documentation_summary() -> Dict[str, Any]:
    """Get a summary of the API documentation structure.

    Returns:
        Dictionary containing documentation statistics and organization
    """
    return {
        "total_endpoints": 150,  # Approximate count from router_names
        "api_version": "v1",
        "documentation_urls": {
            "swagger": "/docs",
            "redoc": "/redoc",
            "openapi_schema": "/openapi.json"
        },
        "key_tags": [
            "Authentication", "Users", "Orders", "Payments", "Products",
            "Cart", "Checkout", "Admin", "Analytics", "Communication"
        ],
        "security_schemes": ["bearerAuth"]
    }


# This file is a foundation for enhanced API documentation.
# The actual endpoint documentation is maintained in individual router files
# using FastAPI's @router.post/@router.get decorators with description parameters.

# Example of how to enhance an individual router endpoint:
#
# In backend/routers/auth.py:
# @router.post(
#     "/auth/login",
#     response_model=AuthResponse,
#     summary="Authenticate user and get JWT token",
#     description="""
#     Authenticate a user and receive a JWT token for API access.
#
#     Parameters:
#     - username: User's email or username
#     - password: User's password (hashed on server side)
#
#     Returns:
#     - JWT token for authenticated session
#     - User information
#
#     Example Request:
#     ```json
#     {"username": "user@example.com", "password": "password123"}
#     ```
#
#     Example Response:
#     ```json
#     {
#       "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
#       "token_type": "bearer",
#       "user": {"id": 1, "email": "user@example.com"}
#     }
#     ```
#
#     Security: Public endpoint
#
#     Tags: [Authentication]
#     """
# )