"""Kernel-level constants — named values replacing magic numbers (Law 66)."""

# String length constants
MAX_STRING_255 = 255
MAX_STRING_128 = 128
MAX_STRING_100 = 100
MAX_STRING_50 = 50
COUNTRY_CODE_LEN = 2
UUID_LEN = 36

# Pagination
DEFAULT_PAGE_SIZE = 100
MAX_PAGE_SIZE = 1000

# Retention (days)
DEFAULT_AUDIT_LOGS_RETENTION_DAYS = 2555  # 7 years
DEFAULT_SHIPMENT_EVENTS_RETENTION_DAYS = 180
DEFAULT_CAMPAIGN_RECIPIENTS_RETENTION_DAYS = 180
DEFAULT_CHATBOT_QUERY_EVENTS_RETENTION_DAYS = 180

# WORM
WORM_HASH_LENGTH = 128
AUDIT_CHAIN_KEY_MIN_BYTES = 32