# AUTO-GENERATED controller delegator (routers -> controllers -> services).
"""services.geography.country_audit_admin_service re-exports for HTTP routers."""
from domains.country.services.country_audit_admin_service import add_city as svc_add_city
from domains.country.services.country_audit_admin_service import assign_staff as svc_assign_staff
from domains.country.services.country_audit_admin_service import delete_city as svc_delete_city
from domains.country.services.country_audit_admin_service import list_cities as svc_list_cities
from domains.country.services.country_audit_admin_service import list_communications as svc_list_communications
from domains.country.services.country_audit_admin_service import list_staff as svc_list_staff
from domains.country.services.country_audit_admin_service import list_tax_rates as svc_list_tax_rates
from domains.country.services.country_audit_admin_service import mark_communication_read as svc_mark_communication_read
from domains.country.services.country_audit_admin_service import remove_staff as svc_remove_staff
from domains.country.services.country_audit_admin_service import send_country_communication as svc_send_country_communication
from domains.country.services.country_audit_admin_service import set_tax_rate as svc_set_tax_rate
from domains.country.services.country_audit_admin_service import update_city as svc_update_city

from domains.country.services.country_admin_write_service import list_tax_rates
from domains.country.services.country_admin_write_service import set_tax_rate
from domains.country.services.country_audit_admin_service import list_communications
from domains.country.services.country_admin_write_service import assign_staff
from domains.country.services.country_admin_write_service import list_staff
from domains.country.services.country_admin_write_service import update_city
from domains.country.services.country_admin_write_service import mark_communication_read
from domains.country.services.country_admin_write_service import remove_staff
from domains.country.services.country_admin_write_service import list_cities
from domains.country.services.country_audit_admin_service import add_city
from domains.country.services.country_admin_write_service import delete_city
from domains.country.services.country_audit_admin_service import send_country_communication
