"""controllers.orders.logistics_partner_controller controller.

Business logic is delegated to services.orders.logistics_partner_service (routers -> controllers -> services)."""

from domains.logistics.services.logistics_partner_service import ACTIVE_SHIPMENT_STATUSES
from domains.logistics.services.logistics_partner_service import ALLOWED_LP_DOC_TYPES
from domains.logistics.services.logistics_partner_service import ANALYTICS_LOOKBACK_DAYS
from domains.logistics.services.logistics_partner_service import CURRENT_LOGISTICS_TERMS_VERSION
from domains.logistics.services.logistics_partner_service import PARTNER_HIDDEN_STATUS
from domains.logistics.services.logistics_partner_service import PARTNER_PICKUP_READY_STATUS
from domains.logistics.services.logistics_partner_service import PARTNER_VISIBLE_ASSIGNED_STATUSES
from domains.logistics.services.logistics_partner_service import SLA_ALERT_STATUSES
from domains.logistics.services.logistics_partner_service import _PARTNER_DELETE_BLOCKING_MODELS
from domains.logistics.services.logistics_partner_service import _active_confirmation_map
from domains.logistics.services.logistics_partner_service import _apply_delivery_signature
from domains.logistics.services.logistics_partner_service import _build_live_locations
from domains.logistics.services.logistics_partner_service import _build_partner_delete_blocker
from domains.logistics.services.logistics_partner_service import _build_route_plan
from domains.logistics.services.logistics_partner_service import _calculate_partner_analytics
from domains.logistics.services.logistics_partner_service import _calculate_partner_payout_summary
from domains.logistics.services.logistics_partner_service import _collect_sla_alerts
from domains.logistics.services.logistics_partner_service import _ensure_sla_notifications
from domains.logistics.services.logistics_partner_service import _extract_delivery_signature
from domains.logistics.services.logistics_partner_service import _filter_partner_analytics_period
from domains.logistics.services.logistics_partner_service import _format_compound_location
from domains.logistics.services.logistics_partner_service import _get_partner_for_user
from domains.logistics.services.logistics_partner_service import _haversine_km
from domains.logistics.services.logistics_partner_service import _is_pickup_ready
from domains.logistics.services.logistics_partner_service import _is_shipment_visible_to_partner
from domains.logistics.services.logistics_partner_service import _latest_geo_events_for_shipments
from domains.logistics.services.logistics_partner_service import _next_partner_code
from domains.logistics.services.logistics_partner_service import _notify_partner_transition
from domains.logistics.services.logistics_partner_service import _order_shipment_counts
from domains.logistics.services.logistics_partner_service import _parse_category_pricing_rule_payload
from domains.logistics.services.logistics_partner_service import _parse_optional_service_area_id
from domains.logistics.services.logistics_partner_service import _parse_partner_service_area_payload
from domains.logistics.services.logistics_partner_service import _parse_partner_social_links
from domains.logistics.services.logistics_partner_service import _parse_pricing_profile_payload
from domains.logistics.services.logistics_partner_service import _parse_vehicle_rule_payload
from domains.logistics.services.logistics_partner_service import _partner_api_status
from domains.logistics.services.logistics_partner_service import _partner_dashboard_shipments_query
from domains.logistics.services.logistics_partner_service import _partner_is_active
from domains.logistics.services.logistics_partner_service import _partner_visible_shipments_query
from domains.logistics.services.logistics_partner_service import _pickup_visible_to_partner
from domains.logistics.services.logistics_partner_service import _publish_shipment_update
from domains.logistics.services.logistics_partner_service import _require_admin
from domains.logistics.services.logistics_partner_service import _resolve_partner_user_link
from domains.logistics.services.logistics_partner_service import _sanitize_optional_string
from domains.logistics.services.logistics_partner_service import _scoped_shipments_query
from domains.logistics.services.logistics_partner_service import _serialize_city_distance
from domains.logistics.services.logistics_partner_service import _serialize_lp_doc
from domains.logistics.services.logistics_partner_service import _serialize_partner
from domains.logistics.services.logistics_partner_service import _serialize_partner_analytics_payload
from domains.logistics.services.logistics_partner_service import _serialize_partner_payout
from domains.logistics.services.logistics_partner_service import _shipment_effective_pricing_breakdown
from domains.logistics.services.logistics_partner_service import _shipment_logistics_allocation
from domains.logistics.services.logistics_partner_service import _shipment_partner_revenue
from domains.logistics.services.logistics_partner_service import _shipment_pickup_details
from domains.logistics.services.logistics_partner_service import _status_display
from domains.logistics.services.logistics_partner_service import _utcnow
from domains.logistics.services.logistics_partner_service import _validate_partner_service_area
from domains.logistics.services.logistics_partner_service import accept_partner_terms
from domains.logistics.services.logistics_partner_service import admin_review_lp_document
from domains.logistics.services.logistics_partner_service import bulk_manage_partners
from domains.logistics.services.logistics_partner_service import bulk_update_shipment_status_partner
from domains.logistics.services.logistics_partner_service import create_city_distance
from domains.logistics.services.logistics_partner_service import create_partner
from domains.logistics.services.logistics_partner_service import create_shipment_confirmation_request_partner
from domains.logistics.services.logistics_partner_service import delete_city_distance
from domains.logistics.services.logistics_partner_service import delete_my_partner_category_rule
from domains.logistics.services.logistics_partner_service import delete_my_partner_pricing_profile
from domains.logistics.services.logistics_partner_service import delete_my_partner_service_area
from domains.logistics.services.logistics_partner_service import delete_my_partner_vehicle_rule
from domains.logistics.services.logistics_partner_service import delete_partner
from domains.logistics.services.logistics_partner_service import delete_partner_document
from domains.logistics.services.logistics_partner_service import get_my_partner_profile
from domains.logistics.services.logistics_partner_service import get_partner_analytics
from domains.logistics.services.logistics_partner_service import get_partner_bank_account
from domains.logistics.services.logistics_partner_service import get_partner_dashboard
from domains.logistics.services.logistics_partner_service import get_partner_payouts
from domains.logistics.services.logistics_partner_service import get_partner_pricing_insights
from domains.logistics.services.logistics_partner_service import get_partner_shipments
from domains.logistics.services.logistics_partner_service import get_public_partner
from domains.logistics.services.logistics_partner_service import list_city_distances
from domains.logistics.services.logistics_partner_service import list_my_partner_category_rules
from domains.logistics.services.logistics_partner_service import list_my_partner_pricing_profiles
from domains.logistics.services.logistics_partner_service import list_my_partner_service_areas
from domains.logistics.services.logistics_partner_service import list_my_partner_vehicle_rules
from domains.logistics.services.logistics_partner_service import list_partner_cod_remittance_receipts
from domains.logistics.services.logistics_partner_service import list_partner_documents
from domains.logistics.services.logistics_partner_service import list_partners
from domains.logistics.services.logistics_partner_service import list_pending_partner_payouts
from domains.logistics.services.logistics_partner_service import list_public_partners
from domains.logistics.services.logistics_partner_service import logger
from domains.logistics.services.logistics_partner_service import request_partner_payout
from domains.logistics.services.logistics_partner_service import review_partner_category_rule
from domains.logistics.services.logistics_partner_service import review_partner_pricing_profile
from domains.logistics.services.logistics_partner_service import review_partner_profile
from domains.logistics.services.logistics_partner_service import review_partner_service_area
from domains.logistics.services.logistics_partner_service import review_partner_vehicle_rule
from domains.logistics.services.logistics_partner_service import scan_lookup_shipment_partner
from domains.logistics.services.logistics_partner_service import shipping_quote_for_customer
from domains.logistics.services.logistics_partner_service import submit_partner_profile_for_review
from domains.logistics.services.logistics_partner_service import update_city_distance
from domains.logistics.services.logistics_partner_service import update_my_partner_profile
from domains.logistics.services.logistics_partner_service import update_partner
from domains.logistics.services.logistics_partner_service import update_shipment_status_partner
from domains.logistics.services.logistics_partner_service import upload_partner_cod_remittance_receipt
from domains.logistics.services.logistics_partner_service import upload_partner_document
from domains.logistics.services.logistics_partner_service import upsert_my_partner_category_rule
from domains.logistics.services.logistics_partner_service import upsert_my_partner_pricing_profile
from domains.logistics.services.logistics_partner_service import upsert_my_partner_service_area
from domains.logistics.services.logistics_partner_service import upsert_my_partner_vehicle_rule
from domains.logistics.services.logistics_partner_service import upsert_partner_bank_account
from domains.logistics.services.logistics_partner_service import verify_partner_payout

__all__ = [
    "ACTIVE_SHIPMENT_STATUSES", "ALLOWED_LP_DOC_TYPES", "ANALYTICS_LOOKBACK_DAYS", "CURRENT_LOGISTICS_TERMS_VERSION", "PARTNER_HIDDEN_STATUS", "PARTNER_PICKUP_READY_STATUS",
    "PARTNER_VISIBLE_ASSIGNED_STATUSES", "SLA_ALERT_STATUSES", "_PARTNER_DELETE_BLOCKING_MODELS", "_active_confirmation_map", "_apply_delivery_signature", "_build_live_locations",
    "_build_partner_delete_blocker", "_build_route_plan", "_calculate_partner_analytics", "_calculate_partner_payout_summary", "_collect_sla_alerts", "_ensure_sla_notifications",
    "_extract_delivery_signature", "_filter_partner_analytics_period", "_format_compound_location", "_get_partner_for_user", "_haversine_km", "_is_pickup_ready",
    "_is_shipment_visible_to_partner", "_latest_geo_events_for_shipments", "_next_partner_code", "_notify_partner_transition", "_order_shipment_counts", "_parse_category_pricing_rule_payload",
    "_parse_optional_service_area_id", "_parse_partner_service_area_payload", "_parse_partner_social_links", "_parse_pricing_profile_payload", "_parse_vehicle_rule_payload", "_partner_api_status",
    "_partner_dashboard_shipments_query", "_partner_is_active", "_partner_visible_shipments_query", "_pickup_visible_to_partner", "_publish_shipment_update", "_require_admin",
    "_resolve_partner_user_link", "_sanitize_optional_string", "_scoped_shipments_query", "_serialize_city_distance", "_serialize_lp_doc", "_serialize_partner",
    "_serialize_partner_analytics_payload", "_serialize_partner_payout", "_shipment_effective_pricing_breakdown", "_shipment_logistics_allocation", "_shipment_partner_revenue", "_shipment_pickup_details",
    "_status_display", "_utcnow", "_validate_partner_service_area", "accept_partner_terms", "admin_review_lp_document", "bulk_manage_partners",
    "bulk_update_shipment_status_partner", "create_city_distance", "create_partner", "create_shipment_confirmation_request_partner", "delete_city_distance", "delete_my_partner_category_rule",
    "delete_my_partner_pricing_profile", "delete_my_partner_service_area", "delete_my_partner_vehicle_rule", "delete_partner", "delete_partner_document", "get_my_partner_profile",
    "get_partner_analytics", "get_partner_bank_account", "get_partner_dashboard", "get_partner_payouts", "get_partner_pricing_insights", "get_partner_shipments",
    "get_public_partner", "list_city_distances", "list_my_partner_category_rules", "list_my_partner_pricing_profiles", "list_my_partner_service_areas", "list_my_partner_vehicle_rules",
    "list_partner_cod_remittance_receipts", "list_partner_documents", "list_partners", "list_pending_partner_payouts", "list_public_partners", "logger",
    "request_partner_payout", "review_partner_category_rule", "review_partner_pricing_profile", "review_partner_profile", "review_partner_service_area", "review_partner_vehicle_rule",
    "scan_lookup_shipment_partner", "shipping_quote_for_customer", "submit_partner_profile_for_review", "update_city_distance", "update_my_partner_profile", "update_partner",
    "update_shipment_status_partner", "upload_partner_cod_remittance_receipt", "upload_partner_document", "upsert_my_partner_category_rule", "upsert_my_partner_pricing_profile", "upsert_my_partner_service_area",
    "upsert_my_partner_vehicle_rule", "upsert_partner_bank_account", "verify_partner_payout"
]
