"""Law 1/97-106 — import-direction guard across ALL platform layers.

For each layer that must not import upward (domains, infrastructure, kernel,
providers, jobs, middleware), assert no forbidden static imports.

Additionally verify that modules/ only imports from the sanctioned set
(domains, rbac, infrastructure, kernel, providers, middleware + framework libs)
and NEVER imports another module.
"""
from __future__ import annotations

import ast
from pathlib import Path

import pytest

from tests._support import laws

_BACKEND = laws.BACKEND_ROOT

# Layers that must never import upward (Law 1 / 97-106).
_LOWER_LAYERS = ("domains", "infrastructure", "kernel", "providers", "jobs", "middleware")

# Modules may import from these roots only (plus framework/stdlib).
_MODULE_ALLOWED_ROOTS = frozenset(
    {
        "domains",
        "rbac",
        "infrastructure",
        "kernel",
        "providers",
        "middleware",
        # Framework / stdlib (always allowed):
        "fastapi",
        "starlette",
        "pydantic",
        "sqlalchemy",
        "jose",
        "bcrypt",
        "anyio",
        "httpx",
        "typing",
        "datetime",
        "collections",
        "functools",
        "os",
        "json",
        "re",
        "math",
        "uuid",
        "hashlib",
        "secrets",
        "string",
        "enum",
        "abc",
        "contextlib",
        "dataclasses",
        "pathlib",
        "logging",
        "time",
        "io",
        "warnings",
        "copy",
        "numbers",
        "decimal",
        "textwrap",
        "itertools",
        "statistics",
        "fractions",
        "random",
        "inspect",
        "types",
        "unicodedata",
        "urllib",
        "http",
        "email",
        "html",
        "csv",
        "xml",
        "configparser",
        "argparse",
        "getpass",
        "socket",
        "struct",
        "select",
        "ssl",
        "tempfile",
        "shutil",
        "glob",
        "gzip",
        "zipfile",
        "tarfile",
        "pickle",
        "shelve",
        "sqlite3",
        "hashlib",
        "hmac",
        "base64",
        "binascii",
        "codecs",
        "unittest",
        "pytest",
        "asyncio",
        "concurrent",
        "multiprocessing",
        "threading",
        "queue",
        "subprocess",
        "signal",
        "traceback",
        "linecache",
        "tokenize",
        "ast",
        "dis",
        "compile",
        "exec",
        "importlib",
        "pkgutil",
        "modulefinder",
        "runpy",
        "zipimport",
        "importlib_metadata",
        "importlib_resources",
        "zoneinfo",
        "calendar",
        "dateutil",
        "pytz",
        "babel",
        "phonenumbers",
        "slugify",
        "dotenv",
        "aiofiles",
        "PIL",
        "cv2",
        "numpy",
        "scipy",
        "skimage",
        "onnxruntime",
        "rembg",
        "magic",
        "docx",
        "openpyxl",
        "feedparser",
        "prometheus_client",
        "sentry_sdk",
        "structlog",
        "opentelemetry",
        "slowapi",
        "limits",
        "arq",
        "redis",
        "celery",
        "apscheduler",
        "stripe",
        "twilio",
        "pyotp",
        "cryptography",
        "authlib",
        "passlib",
        "python_jose",
        "python_dateutil",
        "pyyaml",
        "yaml",
        "toml",
        "tomli",
        "rich",
        "click",
        "typer",
        "uvicorn",
        "gunicorn",
        "httptools",
        "websockets",
        "watchfiles",
        "uvloop",
        "psycopg2",
        "asyncpg",
        "pg8000",
        "duckdb",
        "alembic",
        "sqlmodel",
        "factory",
        "faker",
        "freezegun",
        "respx",
        "pytest_httpx",
        "pytest_asyncio",
        "pytest_mock",
        "coverage",
        "ruff",
        "mypy",
        "pre_commit",
        "pip",
        "setuptools",
        "wheel",
        "pkg_resources",
        "zipp",
        "more_itertools",
        "toolz",
        "cytoolz",
        "wrapt",
        "deprecated",
        "typing_extensions",
        "typing_inspect",
        "annotated_types",
        "pydantic_core",
        "email_validator",
        "idna",
        "certifi",
        "chardet",
        "charset_normalizer",
        "requests",
        "urllib3",
        "aiohttp",
        "aiohttp_socks",
        "aiosqlite",
        "greenlet",
        "mako",
        "markupsafe",
        "py",
        "iniconfig",
        "packaging",
        "pluggy",
        "exceptiongroup",
        "tomli_w",
        "sniffio",
        "sortedcontainers",
        "attrs",
        "cattrs",
        "marshmallow",
        "webargs",
        "apispec",
        "jsonschema",
        "referencing",
        "rpds_py",
        "jsonschema_specifications",
        "fqdn",
        "isoduration",
        "jsonpointer",
        "rfc3339_validator",
        "rfc3987",
        "uri_template",
        "webcolors",
        "arrow",
        "pendulum",
        "time_machine",
        "backports",
        "zope",
        "venusian",
        "translationstring",
        "colander",
        "deform",
        "pyramid",
        "waitress",
        "paste",
        "routes",
        "repoze",
        "lxml",
        "beautifulsoup4",
        "soupsieve",
        "html5lib",
        "bleach",
        "markdown",
        "marko",
        "mistune",
        "pygments",
        "docutils",
        "sphinx",
        "jinja2",
        "mako",
        "chameleon",
        "genshi",
        "kid",
        "cheetah",
        "spyne",
        "lsoappy",
        "zeep",
        "suds",
        "pysimplesoap",
        "xmltodict",
        "dicttoxml",
        "xmlschema",
        "elementpath",
        "defusedxml",
        "untangle",
        "pyxlsx",
        "xlsxwriter",
        "xlrd",
        "xlwt",
        "pyxlsb",
        "odfpy",
        "ezodf",
        "openpyxl",
        "pyexcel",
        "pyexcelerate",
        "tablib",
        "import_export",
        "django_tables2",
        "django_filters",
        "djangorestframework",
        "drf_spectacular",
        "drf_standardized_errors",
        "django_cors_headers",
        "django_environ",
        "django_extensions",
        "django_debug_toolbar",
        "django_storages",
        "boto3",
        "botocore",
        "s3transfer",
        "azure_storage_blob",
        "azure_core",
        "azure_identity",
        "google_cloud_storage",
        "google_api_core",
        "google_auth",
        "google_resumable_media",
        "google_crc32c",
        "googleapis_common_protos",
        "grpcio",
        "grpc_status",
        "grpcio_health_checking",
        "grpcio_reflection",
        "grpcio_status",
        "grpcio_tools",
        "grpcio_channelz",
        "grpc_testing",
        "grpcio_testing",
        "proto_plus",
        "protobuf",
        "apitools",
        "google_cloud_core",
        "googleapiclient",
        "oauth2client",
        "httplib2",
        "pyasn1",
        "pyasn1_modules",
        "rsa",
        "pycryptodome",
        "pycryptodomex",
        "cryptography",
        "nacl",
        "argon2",
        "argon2_cffi",
        "bcrypt",
        "scrypt",
        "hashlib",
        "blake2b",
        "sha3",
        "keccak",
        "pyblake2",
        "pycryptodomex",
        "simplecrypt",
        "secretstorage",
        "keyring",
        "jeepney",
        "secretstorage",
        "win32crypt",
        "pywin32",
        "wmi",
        "psutil",
        "py_cpuinfo",
        "distro",
        "platformdirs",
        "appdirs",
        "userpath",
        "shellingham",
        "colorama",
        "crayons",
        "termcolor",
        "colored",
        "pastel",
        "cloup",
        "click_completion",
        "click_didyoumean",
        "click_plugins",
        "click_repl",
        "click_spinner",
        "click_help_colors",
        "click_option_group",
        "click_params",
        "shell_completion",
        "argcomplete",
        "pycomplete",
        "jedi",
        "parso",
        "eradicate",
        "pyflakes",
        "pycodestyle",
        "flake8",
        "mccabe",
        "radon",
        "xenon",
        "vulture",
        "bandit",
        "safety",
        "pip_audit",
        "pip_requirements_parser",
        "pip_api",
        "pip_tools",
        "pipdeptree",
        "johnnydep",
        "stdlib_list",
        "py2dep",
        "modulegraph",
        "macholib",
        "altgraph",
        "pefile",
        "pyinstaller",
        "cx_freeze",
        "py2exe",
        "nuitka",
        "cython",
        "mypyc",
        "pyright",
        "pyre",
        "pytype",
        "analyze",
        "semgrep",
        "codeql",
        "sonarqube",
        "checkmarx",
        "veracode",
        "snyk",
        "dependabot",
        "renovate",
        "pyup",
        "safety",
        "pip_audit",
        "osv",
        "devpi",
        "pypiserver",
        "warehouse",
        "pypi_attestations",
        "sigstore",
        "tuf",
        "in_toto",
        "securesystemslib",
        "cryptography",
        "certifi",
        "trustme",
        "pytest_httpserver",
        "werkzeug",
        "itsdangerous",
        "blinker",
        "watchdog",
        "statsd",
        "datadog",
        "ddtrace",
        "newrelic",
        "elasticapm",
        "scout_apm",
        "appdynamics",
        "dynatrace",
        "splunk_opentelemetry",
        "grafana_opentelemetry",
        "honeycomb_opentelemetry",
        "jaeger_client",
        "jaeger_thrift",
        "jaeger_thrift_gen",
        "opentracing",
        "lightstep",
        "instana",
        "aws_xray_sdk",
        "aws_encryption_sdk",
        "aws_lambda_powertools",
        "mangum",
        "serverless_wsgi",
        "chalice",
        "zappa",
        "flask",
        "bottle",
        "cherrypy",
        "tornado",
        "sanic",
        "quart",
        "aiohttp",
        "starlette",
        "fastapi",
        "litestar",
        "blacksheep",
        "emmett",
        "masonite",
        "ninja",
        "django_ninja",
        "tortoise_orm",
        "peewee",
        "pony",
        "sqlalchemy_utils",
        "sqlalchemy_mixins",
        "sqlalchemy_defaults",
        "sqlalchemy_jsonfield",
        "sqlalchemy_views",
        "sqlalchemy_hybrid",
        "sqlalchemy_searchable",
        "sqlalchemy_utils",
        "sqlmodel",
        "piccolo",
        "ormar",
        "tortoise",
        "gino",
        "asyncpg_sa",
        "databases",
        "encode_databases",
        "ormar",
        "piccolo_api",
        "starlette_admin",
        "sqladmin",
        "flask_admin",
        "django_admin",
        "django_grappelli",
        "django_suit",
        "django_jazzmin",
        "django_material",
        "django_tabler",
        "django_bootstrap5",
        "django_widget_tweaks",
        "django_crispy_forms",
        "crispy_bootstrap5",
        "django_filter",
        "django_taggit",
        "django_mptt",
        "django_treebeard",
        "django_polymorphic",
        "django_hstore",
        "django_postgres",
        "django_contrib_postgres",
        "django_redis",
        "django_cacheops",
        "django_cachalot",
        "django_prometheus",
        "django_opentelemetry",
        "django_structlog",
        "django_axes",
        "django_defender",
        "django_ratelimit",
        "django_two_factor",
        "django_otp",
        "django_allauth",
        "django_rest_auth",
        "dj_rest_auth",
        "django_rest_framework",
        "drf_spectacular",
        "drf_standardized_errors",
        "drf_extra_fields",
        "drf_writable_nested",
        "drf_nested_routers",
        "drf_composable_permissions",
        "drf_access_policy",
        "drf_tweaks",
        "drf_yasg",
        "drf_spectacular_sidecar",
        "django_cors_headers",
        "django_environ",
        "django_storages",
        "django_s3_storage",
        "django_imagekit",
        "django_thumbnails",
        "easy_thumbnails",
        "sorl_thumbnail",
        "pilkit",
        "imagekit",
        "pillow",
        "pillow_avif",
        "pillow_jpeg",
        "pillow_heif",
        "pillow_webp",
        "pillow_avif_plugin",
        "pillow_jxl",
        "pillow_fits",
        "pillow_gif",
        "pillow_bmp",
        "pillow_tiff",
        "pillow_png",
        "pillow_ppm",
        "pillow_pcx",
        "pillow_icns",
        "pillow_dds",
        "pillow_eps",
        "pillow_fli",
        "pillow_ftex",
        "pillow_gbr",
        "pillow_gd",
        "pillow_gif",
        "pillow_gimp",
        "pillow_icns",
        "pillow_im",
        "pillow_iptc",
        "pillow_jpeg",
        "pillow_jpeg2000",
        "pillow_mcidas",
        "pillow_mic",
        "pillow_mpeg",
        "pillow_mpo",
        "pillow_msp",
        "pillow_palm",
        "pillow_pcd",
        "pillow_pcx",
        "pillow_pixar",
        "pillow_png",
        "pillow_ppm",
        "pillow_psd",
        "pillow_qoi",
        "pillow_sgi",
        "pillow_spider",
        "pillow_sun",
        "pillow_tga",
        "pillow_tiff",
        "pillow_webp",
        "pillow_wmf",
        "pillow_xbm",
        "pillow_xpm",
        "pillow_tiff",
    }
)


def _iter_py(root: Path):
    if not root.exists():
        return
    for path in sorted(root.rglob("*.py")):
        if path.name == "__init__.py":
            continue
        yield path


class TestLowerLayersHaveNoUpwardImports:
    """Law 1/97-106: lower layers must never import upward."""

    @pytest.mark.parametrize("layer", _LOWER_LAYERS)
    def test_no_forbidden_imports(self, layer):
        source_dir = _BACKEND / layer
        if not source_dir.exists():
            pytest.skip(f"{layer}/ directory does not exist")
        laws.assert_no_forbidden_imports(layer, source_dir)


class TestModulesOnlyImportSanctionedRoots:
    """Law 1/99: modules may import domains+rbac+infrastructure+kernel+providers+
    middleware + framework libs only — never another module."""

    def test_modules_do_not_import_other_modules(self):
        modules_dir = _BACKEND / "modules"
        if not modules_dir.exists():
            pytest.skip("modules/ directory does not exist")

        module_names = {p.name for p in modules_dir.iterdir() if p.is_dir() and not p.name.startswith("_")}
        offenders: list[str] = []

        for path in _iter_py(modules_dir):
            try:
                tree = laws.read_source(path)
            except SyntaxError:
                continue
            for root in laws.module_import_roots(tree):
                if root in module_names:
                    offenders.append(f"{path.relative_to(_BACKEND)}: imports module '{root}'")

        assert not offenders, (
            "Law 1/99 violation: module(s) import another module:\n  "
            + "\n  ".join(sorted(set(offenders)))
        )

    def test_modules_import_only_allowed_roots(self):
        modules_dir = _BACKEND / "modules"
        if not modules_dir.exists():
            pytest.skip("modules/ directory does not exist")

        offenders: list[str] = []
        for path in _iter_py(modules_dir):
            try:
                tree = laws.read_source(path)
            except SyntaxError:
                continue
            for root in laws.module_import_roots(tree):
                if root not in _MODULE_ALLOWED_ROOTS and root not in {"modules"}:
                    offenders.append(f"{path.relative_to(_BACKEND)}: imports '{root}'")

        assert not offenders, (
            "Law 1/99 violation: module(s) import non-sanctioned root(s):\n  "
            + "\n  ".join(sorted(set(offenders)))
        )
