-- RLS Policies for ZOZI Multi-Country Platform
-- AUTO-GENERATED by utils/rls_interceptor.generate_rls_policy_sql()
-- DO NOT EDIT MANUALLY — regenerate after schema changes
--
-- This file enables Row-Level Security on all country-scoped tables.
-- Each policy ensures data isolation between countries.
-- Run this after applying migrations to enforce RLS.

CREATE OR REPLACE FUNCTION auth.country_access_check(p_country_code TEXT)
RETURNS BOOLEAN AS $$
DECLARE
    v_role TEXT;
BEGIN
    SELECT current_user INTO v_role;

    IF v_role = 'admin' OR v_role = 'postgres' OR v_role = 'service_role' THEN
        RETURN TRUE;
    END IF;

    RETURN EXISTS (
        SELECT 1
        FROM country_staff_assignments csa
        WHERE csa.country_code = p_country_code
          AND csa.is_active = TRUE
          AND csa.user_id = (
              SELECT u.id FROM users u WHERE u.email = current_user LIMIT 1
          )
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE POLICY orders_rls_policy
    ON public.orders
    FOR ALL
    USING (
        public.orders.country_code IS NULL
        OR auth.country_access_check(public.orders.country_code)
    );

CREATE POLICY order_logistics_allocations_rls_policy
    ON public.order_logistics_allocations
    FOR ALL
    USING (
        public.order_logistics_allocations.destination_country IS NULL
        OR auth.country_access_check(public.order_logistics_allocations.destination_country)
    );

CREATE POLICY country_staff_assignments_rls_policy
    ON public.country_staff_assignments
    FOR ALL
    USING (
        public.country_staff_assignments.country_code IS NULL
        OR auth.country_access_check(public.country_staff_assignments.country_code)
    );

CREATE POLICY country_communications_rls_policy
    ON public.country_communications
    FOR ALL
    USING (
        public.country_communications.country_code IS NULL
        OR auth.country_access_check(public.country_communications.country_code)
    );

CREATE POLICY country_gateway_credentials_rls_policy
    ON public.country_gateway_credentials
    FOR ALL
    USING (
        public.country_gateway_credentials.country_code IS NULL
        OR auth.country_access_check(public.country_gateway_credentials.country_code)
    );

CREATE POLICY supplier_country_commissions_rls_policy
    ON public.supplier_country_commissions
    FOR ALL
    USING (
        public.supplier_country_commissions.country_code IS NULL
        OR auth.country_access_check(public.supplier_country_commissions.country_code)
    );

CREATE POLICY country_cities_rls_policy
    ON public.country_cities
    FOR ALL
    USING (
        public.country_cities.country_code IS NULL
        OR auth.country_access_check(public.country_cities.country_code)
    );

CREATE POLICY country_category_tax_rates_rls_policy
    ON public.country_category_tax_rates
    FOR ALL
    USING (
        public.country_category_tax_rates.country_code IS NULL
        OR auth.country_access_check(public.country_category_tax_rates.country_code)
    );

CREATE POLICY country_feature_flags_rls_policy
    ON public.country_feature_flags
    FOR ALL
    USING (
        public.country_feature_flags.country_code IS NULL
        OR auth.country_access_check(public.country_feature_flags.country_code)
    );

CREATE POLICY country_payout_rules_rls_policy
    ON public.country_payout_rules
    FOR ALL
    USING (
        public.country_payout_rules.country_code IS NULL
        OR auth.country_access_check(public.country_payout_rules.country_code)
    );

CREATE POLICY country_config_versions_rls_policy
    ON public.country_config_versions
    FOR ALL
    USING (
        public.country_config_versions.country_code IS NULL
        OR auth.country_access_check(public.country_config_versions.country_code)
    );

CREATE POLICY country_configs_rls_policy
    ON public.country_configs
    FOR ALL
    USING (
        public.country_configs.code IS NULL
        OR auth.country_access_check(public.country_configs.code)
    );

CREATE POLICY country_holiday_calendars_rls_policy
    ON public.country_holiday_calendars
    FOR ALL
    USING (
        public.country_holiday_calendars.country_code IS NULL
        OR auth.country_access_check(public.country_holiday_calendars.country_code)
    );

CREATE POLICY country_localization_rls_policy
    ON public.country_localization
    FOR ALL
    USING (
        public.country_localization.country_code IS NULL
        OR auth.country_access_check(public.country_localization.country_code)
    );

CREATE POLICY country_logistics_zones_rls_policy
    ON public.country_logistics_zones
    FOR ALL
    USING (
        public.country_logistics_zones.country_code IS NULL
        OR auth.country_access_check(public.country_logistics_zones.country_code)
    );

CREATE POLICY country_map_configs_rls_policy
    ON public.country_map_configs
    FOR ALL
    USING (
        public.country_map_configs.country_code IS NULL
        OR auth.country_access_check(public.country_map_configs.country_code)
    );

CREATE POLICY country_payment_aliases_rls_policy
    ON public.country_payment_aliases
    FOR ALL
    USING (
        public.country_payment_aliases.country_code IS NULL
        OR auth.country_access_check(public.country_payment_aliases.country_code)
    );

CREATE POLICY country_legal_contracts_rls_policy
    ON public.country_legal_contracts
    FOR ALL
    USING (
        public.country_legal_contracts.country_code IS NULL
        OR auth.country_access_check(public.country_legal_contracts.country_code)
    );

CREATE POLICY employees_rls_policy
    ON public.employees
    FOR ALL
    USING (
        public.employees.country_code IS NULL
        OR auth.country_access_check(public.employees.country_code)
    );

CREATE POLICY banners_rls_policy
    ON public.banners
    FOR ALL
    USING (
        public.banners.country_code IS NULL
        OR auth.country_access_check(public.banners.country_code)
    );

CREATE POLICY coupons_rls_policy
    ON public.coupons
    FOR ALL
    USING (
        public.coupons.country_code IS NULL
        OR auth.country_access_check(public.coupons.country_code)
    );

CREATE POLICY payments_rls_policy
    ON public.payments
    FOR ALL
    USING (
        public.payments.country_code IS NULL
        OR auth.country_access_check(public.payments.country_code)
    );

CREATE POLICY support_tickets_rls_policy
    ON public.support_tickets
    FOR ALL
    USING (
        public.support_tickets.country_code IS NULL
        OR auth.country_access_check(public.support_tickets.country_code)
    );

CREATE POLICY promotion_engine_configs_rls_policy
    ON public.promotion_engine_configs
    FOR ALL
    USING (
        public.promotion_engine_configs.country_code IS NULL
        OR auth.country_access_check(public.promotion_engine_configs.country_code)
    );

CREATE POLICY return_requests_rls_policy
    ON public.return_requests
    FOR ALL
    USING (
        public.return_requests.country_code IS NULL
        OR auth.country_access_check(public.return_requests.country_code)
    );

CREATE POLICY logistics_partner_profiles_rls_policy
    ON public.logistics_partner_profiles
    FOR ALL
    USING (
        public.logistics_partner_profiles.country_code IS NULL
        OR auth.country_access_check(public.logistics_partner_profiles.country_code)
    );

CREATE POLICY order_items_rls_policy
    ON public.order_items
    FOR ALL
    USING (
        public.order_items.country_code IS NULL
        OR auth.country_access_check(public.order_items.country_code)
    );

CREATE POLICY role_permission_assignments_rls_policy
    ON public.role_permission_assignments
    FOR ALL
    USING (
        public.role_permission_assignments.country_code IS NULL
        OR auth.country_access_check(public.role_permission_assignments.country_code)
    );

CREATE POLICY user_permission_overrides_rls_policy
    ON public.user_permission_overrides
    FOR ALL
    USING (
        public.user_permission_overrides.country_code IS NULL
        OR auth.country_access_check(public.user_permission_overrides.country_code)
    );

CREATE POLICY permission_audit_log_rls_policy
    ON public.permission_audit_log
    FOR ALL
    USING (
        public.permission_audit_log.country_code IS NULL
        OR auth.country_access_check(public.permission_audit_log.country_code)
    );

CREATE POLICY tax_rules_rls_policy
    ON public.tax_rules
    FOR ALL
    USING (
        public.tax_rules.country_code IS NULL
        OR auth.country_access_check(public.tax_rules.country_code)
    );

CREATE POLICY shipping_rules_rls_policy
    ON public.shipping_rules
    FOR ALL
    USING (
        public.shipping_rules.country_code IS NULL
        OR auth.country_access_check(public.shipping_rules.country_code)
    );

CREATE POLICY fraud_rules_rls_policy
    ON public.fraud_rules
    FOR ALL
    USING (
        public.fraud_rules.country_code IS NULL
        OR auth.country_access_check(public.fraud_rules.country_code)
    );

CREATE POLICY commission_agreements_rls_policy
    ON public.commission_agreements
    FOR ALL
    USING (
        public.commission_agreements.country_code IS NULL
        OR auth.country_access_check(public.commission_agreements.country_code)
    );

CREATE POLICY payout_batches_rls_policy
    ON public.payout_batches
    FOR ALL
    USING (
        public.payout_batches.country_code IS NULL
        OR auth.country_access_check(public.payout_batches.country_code)
    );

CREATE POLICY payout_rules_rls_policy
    ON public.payout_rules
    FOR ALL
    USING (
        public.payout_rules.country_code IS NULL
        OR auth.country_access_check(public.payout_rules.country_code)
    );

CREATE POLICY journal_entries_rls_policy
    ON public.journal_entries
    FOR ALL
    USING (
        public.journal_entries.country_code IS NULL
        OR auth.country_access_check(public.journal_entries.country_code)
    );

CREATE POLICY pending_journal_entries_rls_policy
    ON public.pending_journal_entries
    FOR ALL
    USING (
        public.pending_journal_entries.country_code IS NULL
        OR auth.country_access_check(public.pending_journal_entries.country_code)
    );

CREATE POLICY media_assets_rls_policy
    ON public.media_assets
    FOR ALL
    USING (
        public.media_assets.country_code IS NULL
        OR auth.country_access_check(public.media_assets.country_code)
    );

CREATE POLICY escalation_sla_rules_rls_policy
    ON public.escalation_sla_rules
    FOR ALL
    USING (
        public.escalation_sla_rules.country_code IS NULL
        OR auth.country_access_check(public.escalation_sla_rules.country_code)
    );

CREATE POLICY supplier_kyc_requirements_rls_policy
    ON public.supplier_kyc_requirements
    FOR ALL
    USING (
        public.supplier_kyc_requirements.country_code IS NULL
        OR auth.country_access_check(public.supplier_kyc_requirements.country_code)
    );

CREATE POLICY logistics_partner_kyc_requirements_rls_policy
    ON public.logistics_partner_kyc_requirements
    FOR ALL
    USING (
        public.logistics_partner_kyc_requirements.country_code IS NULL
        OR auth.country_access_check(public.logistics_partner_kyc_requirements.country_code)
    );

CREATE POLICY logistics_partner_locations_rls_policy
    ON public.logistics_partner_locations
    FOR ALL
    USING (
        public.logistics_partner_locations.country_code IS NULL
        OR auth.country_access_check(public.logistics_partner_locations.country_code)
    );

CREATE POLICY logistics_partner_service_areas_rls_policy
    ON public.logistics_partner_service_areas
    FOR ALL
    USING (
        public.logistics_partner_service_areas.country_code IS NULL
        OR auth.country_access_check(public.logistics_partner_service_areas.country_code)
    );

CREATE POLICY shop_warehouse_locations_rls_policy
    ON public.shop_warehouse_locations
    FOR ALL
    USING (
        public.shop_warehouse_locations.country_code IS NULL
        OR auth.country_access_check(public.shop_warehouse_locations.country_code)
    );

CREATE POLICY payment_gateway_connections_rls_policy
    ON public.payment_gateway_connections
    FOR ALL
    USING (
        public.payment_gateway_connections.country_code IS NULL
        OR auth.country_access_check(public.payment_gateway_connections.country_code)
    );

CREATE POLICY country_gateway_configs_rls_policy
    ON public.country_gateway_configs
    FOR ALL
    USING (
        public.country_gateway_configs.country_code IS NULL
        OR auth.country_access_check(public.country_gateway_configs.country_code)
    );

CREATE POLICY legal_contract_templates_rls_policy
    ON public.legal_contract_templates
    FOR ALL
    USING (
        public.legal_contract_templates.country_code IS NULL
        OR auth.country_access_check(public.legal_contract_templates.country_code)
    );

CREATE POLICY ip_reputations_rls_policy
    ON public.ip_reputations
    FOR ALL
    USING (
        public.ip_reputations.country_code IS NULL
        OR auth.country_access_check(public.ip_reputations.country_code)
    );

CREATE POLICY parcel_location_trackers_rls_policy
    ON public.parcel_location_trackers
    FOR ALL
    USING (
        public.parcel_location_trackers.country_code IS NULL
        OR auth.country_access_check(public.parcel_location_trackers.country_code)
    );

CREATE POLICY org_units_rls_policy
    ON public.org_units
    FOR ALL
    USING (
        public.org_units.country_code IS NULL
        OR auth.country_access_check(public.org_units.country_code)
    );

CREATE POLICY employee_addresses_rls_policy
    ON public.employee_addresses
    FOR ALL
    USING (
        public.employee_addresses.country_code IS NULL
        OR auth.country_access_check(public.employee_addresses.country_code)
    );

CREATE POLICY messages_rls_policy
    ON public.messages
    FOR ALL
    USING (
        public.messages.country_code IS NULL
        OR auth.country_access_check(public.messages.country_code)
    );

CREATE POLICY internal_channels_rls_policy
    ON public.internal_channels
    FOR ALL
    USING (
        public.internal_channels.country_code IS NULL
        OR auth.country_access_check(public.internal_channels.country_code)
    );

CREATE POLICY video_rooms_rls_policy
    ON public.video_rooms
    FOR ALL
    USING (
        public.video_rooms.country_code IS NULL
        OR auth.country_access_check(public.video_rooms.country_code)
    );

CREATE POLICY shift_handover_logs_rls_policy
    ON public.shift_handover_logs
    FOR ALL
    USING (
        public.shift_handover_logs.country_code IS NULL
        OR auth.country_access_check(public.shift_handover_logs.country_code)
    );

CREATE POLICY shift_handover_sessions_rls_policy
    ON public.shift_handover_sessions
    FOR ALL
    USING (
        public.shift_handover_sessions.country_code IS NULL
        OR auth.country_access_check(public.shift_handover_sessions.country_code)
    );

CREATE POLICY supplier_onboarding_sync_rls_policy
    ON public.supplier_onboarding_sync
    FOR ALL
    USING (
        public.supplier_onboarding_sync.country_code IS NULL
        OR auth.country_access_check(public.supplier_onboarding_sync.country_code)
    );

CREATE POLICY news_articles_rls_policy
    ON public.news_articles
    FOR ALL
    USING (
        public.news_articles.country_code IS NULL
        OR auth.country_access_check(public.news_articles.country_code)
    );

CREATE POLICY offices_rls_policy
    ON public.offices
    FOR ALL
    USING (
        public.offices.country_code IS NULL
        OR auth.country_access_check(public.offices.country_code)
    );

CREATE POLICY supplier_profiles_rls_policy
    ON public.supplier_profiles
    FOR ALL
    USING (
        public.supplier_profiles.country_code IS NULL
        OR auth.country_access_check(public.supplier_profiles.country_code)
    );

CREATE POLICY flash_sales_rls_policy
    ON public.flash_sales
    FOR ALL
    USING (
        public.flash_sales.country_code IS NULL
        OR auth.country_access_check(public.flash_sales.country_code)
    );

CREATE POLICY logistics_partners_rls_policy
    ON public.logistics_partners
    FOR ALL
    USING (
        public.logistics_partners.country_code IS NULL
        OR auth.country_access_check(public.logistics_partners.country_code)
    );

CREATE POLICY payouts_rls_policy
    ON public.payouts
    FOR ALL
    USING (
        public.payouts.country_code IS NULL
        OR auth.country_access_check(public.payouts.country_code)
    );

CREATE POLICY logistics_partner_payouts_rls_policy
    ON public.logistics_partner_payouts
    FOR ALL
    USING (
        public.logistics_partner_payouts.country_code IS NULL
        OR auth.country_access_check(public.logistics_partner_payouts.country_code)
    );

CREATE POLICY email_campaigns_rls_policy
    ON public.email_campaigns
    FOR ALL
    USING (
        public.email_campaigns.country_code IS NULL
        OR auth.country_access_check(public.email_campaigns.country_code)
    );

CREATE POLICY users_rls_policy
    ON public.users
    FOR ALL
    USING (
        public.users.country_code IS NULL
        OR auth.country_access_check(public.users.country_code)
    );

CREATE POLICY addresses_rls_policy
    ON public.addresses
    FOR ALL
    USING (
        public.addresses.country_code IS NULL
        OR auth.country_access_check(public.addresses.country_code)
    );

CREATE POLICY carts_rls_policy
    ON public.carts
    FOR ALL
    USING (
        public.carts.country_code IS NULL
        OR auth.country_access_check(public.carts.country_code)
    );

CREATE POLICY cart_items_rls_policy
    ON public.cart_items
    FOR ALL
    USING (
        public.cart_items.country_code IS NULL
        OR auth.country_access_check(public.cart_items.country_code)
    );

CREATE POLICY wishlists_rls_policy
    ON public.wishlists
    FOR ALL
    USING (
        public.wishlists.country_code IS NULL
        OR auth.country_access_check(public.wishlists.country_code)
    );

CREATE POLICY wishlist_items_rls_policy
    ON public.wishlist_items
    FOR ALL
    USING (
        public.wishlist_items.country_code IS NULL
        OR auth.country_access_check(public.wishlist_items.country_code)
    );

CREATE POLICY reviews_rls_policy
    ON public.reviews
    FOR ALL
    USING (
        public.reviews.country_code IS NULL
        OR auth.country_access_check(public.reviews.country_code)
    );

CREATE POLICY notifications_rls_policy
    ON public.notifications
    FOR ALL
    USING (
        public.notifications.country_code IS NULL
        OR auth.country_access_check(public.notifications.country_code)
    );

CREATE POLICY user_sessions_rls_policy
    ON public.user_sessions
    FOR ALL
    USING (
        public.user_sessions.country_code IS NULL
        OR auth.country_access_check(public.user_sessions.country_code)
    );

CREATE POLICY user_devices_rls_policy
    ON public.user_devices
    FOR ALL
    USING (
        public.user_devices.country_code IS NULL
        OR auth.country_access_check(public.user_devices.country_code)
    );

CREATE POLICY user_login_history_rls_policy
    ON public.user_login_history
    FOR ALL
    USING (
        public.user_login_history.country_code IS NULL
        OR auth.country_access_check(public.user_login_history.country_code)
    );

CREATE POLICY referrals_rls_policy
    ON public.referrals
    FOR ALL
    USING (
        public.referrals.country_code IS NULL
        OR auth.country_access_check(public.referrals.country_code)
    );

CREATE POLICY referral_point_events_rls_policy
    ON public.referral_point_events
    FOR ALL
    USING (
        public.referral_point_events.country_code IS NULL
        OR auth.country_access_check(public.referral_point_events.country_code)
    );

CREATE POLICY ticket_replies_rls_policy
    ON public.ticket_replies
    FOR ALL
    USING (
        public.ticket_replies.country_code IS NULL
        OR auth.country_access_check(public.ticket_replies.country_code)
    );

CREATE POLICY ticket_messages_rls_policy
    ON public.ticket_messages
    FOR ALL
    USING (
        public.ticket_messages.country_code IS NULL
        OR auth.country_access_check(public.ticket_messages.country_code)
    );

CREATE POLICY categories_rls_policy
    ON public.categories
    FOR ALL
    USING (
        public.categories.country_code IS NULL
        OR auth.country_access_check(public.categories.country_code)
    );

CREATE POLICY product_variants_rls_policy
    ON public.product_variants
    FOR ALL
    USING (
        public.product_variants.country_code IS NULL
        OR auth.country_access_check(public.product_variants.country_code)
    );

CREATE POLICY product_filter_options_rls_policy
    ON public.product_filter_options
    FOR ALL
    USING (
        public.product_filter_options.country_code IS NULL
        OR auth.country_access_check(public.product_filter_options.country_code)
    );

CREATE POLICY product_filter_metadata_rls_policy
    ON public.product_filter_metadata
    FOR ALL
    USING (
        public.product_filter_metadata.country_code IS NULL
        OR auth.country_access_check(public.product_filter_metadata.country_code)
    );

CREATE POLICY product_videos_rls_policy
    ON public.product_videos
    FOR ALL
    USING (
        public.product_videos.country_code IS NULL
        OR auth.country_access_check(public.product_videos.country_code)
    );

CREATE POLICY faqs_rls_policy
    ON public.faqs
    FOR ALL
    USING (
        public.faqs.country_code IS NULL
        OR auth.country_access_check(public.faqs.country_code)
    );

CREATE POLICY ai_upload_jobs_rls_policy
    ON public.ai_upload_jobs
    FOR ALL
    USING (
        public.ai_upload_jobs.country_code IS NULL
        OR auth.country_access_check(public.ai_upload_jobs.country_code)
    );

CREATE POLICY ai_staging_products_rls_policy
    ON public.ai_staging_products
    FOR ALL
    USING (
        public.ai_staging_products.country_code IS NULL
        OR auth.country_access_check(public.ai_staging_products.country_code)
    );

CREATE POLICY ai_staging_variants_rls_policy
    ON public.ai_staging_variants
    FOR ALL
    USING (
        public.ai_staging_variants.country_code IS NULL
        OR auth.country_access_check(public.ai_staging_variants.country_code)
    );

CREATE POLICY ai_generation_logs_rls_policy
    ON public.ai_generation_logs
    FOR ALL
    USING (
        public.ai_generation_logs.country_code IS NULL
        OR auth.country_access_check(public.ai_generation_logs.country_code)
    );

CREATE POLICY supplier_bank_accounts_rls_policy
    ON public.supplier_bank_accounts
    FOR ALL
    USING (
        public.supplier_bank_accounts.country_code IS NULL
        OR auth.country_access_check(public.supplier_bank_accounts.country_code)
    );

CREATE POLICY supplier_disputes_rls_policy
    ON public.supplier_disputes
    FOR ALL
    USING (
        public.supplier_disputes.country_code IS NULL
        OR auth.country_access_check(public.supplier_disputes.country_code)
    );

CREATE POLICY supplier_fraud_indicators_rls_policy
    ON public.supplier_fraud_indicators
    FOR ALL
    USING (
        public.supplier_fraud_indicators.country_code IS NULL
        OR auth.country_access_check(public.supplier_fraud_indicators.country_code)
    );

CREATE POLICY supplier_notification_preferences_rls_policy
    ON public.supplier_notification_preferences
    FOR ALL
    USING (
        public.supplier_notification_preferences.country_code IS NULL
        OR auth.country_access_check(public.supplier_notification_preferences.country_code)
    );

CREATE POLICY supplier_settlements_rls_policy
    ON public.supplier_settlements
    FOR ALL
    USING (
        public.supplier_settlements.country_code IS NULL
        OR auth.country_access_check(public.supplier_settlements.country_code)
    );

CREATE POLICY commission_global_configs_rls_policy
    ON public.commission_global_configs
    FOR ALL
    USING (
        public.commission_global_configs.country_code IS NULL
        OR auth.country_access_check(public.commission_global_configs.country_code)
    );

CREATE POLICY commission_badge_tiers_rls_policy
    ON public.commission_badge_tiers
    FOR ALL
    USING (
        public.commission_badge_tiers.country_code IS NULL
        OR auth.country_access_check(public.commission_badge_tiers.country_code)
    );

CREATE POLICY commission_ledger_entries_rls_policy
    ON public.commission_ledger_entries
    FOR ALL
    USING (
        public.commission_ledger_entries.country_code IS NULL
        OR auth.country_access_check(public.commission_ledger_entries.country_code)
    );

CREATE POLICY shipments_rls_policy
    ON public.shipments
    FOR ALL
    USING (
        public.shipments.country_code IS NULL
        OR auth.country_access_check(public.shipments.country_code)
    );

CREATE POLICY shipment_events_rls_policy
    ON public.shipment_events
    FOR ALL
    USING (
        public.shipment_events.country_code IS NULL
        OR auth.country_access_check(public.shipment_events.country_code)
    );

CREATE POLICY shipment_confirmations_rls_policy
    ON public.shipment_confirmations
    FOR ALL
    USING (
        public.shipment_confirmations.country_code IS NULL
        OR auth.country_access_check(public.shipment_confirmations.country_code)
    );

CREATE POLICY shipping_zones_rls_policy
    ON public.shipping_zones
    FOR ALL
    USING (
        public.shipping_zones.country_code IS NULL
        OR auth.country_access_check(public.shipping_zones.country_code)
    );

CREATE POLICY shipping_carriers_rls_policy
    ON public.shipping_carriers
    FOR ALL
    USING (
        public.shipping_carriers.country_code IS NULL
        OR auth.country_access_check(public.shipping_carriers.country_code)
    );

CREATE POLICY logistics_pricing_profiles_rls_policy
    ON public.logistics_pricing_profiles
    FOR ALL
    USING (
        public.logistics_pricing_profiles.country_code IS NULL
        OR auth.country_access_check(public.logistics_pricing_profiles.country_code)
    );

CREATE POLICY logistics_vehicle_rules_rls_policy
    ON public.logistics_vehicle_rules
    FOR ALL
    USING (
        public.logistics_vehicle_rules.country_code IS NULL
        OR auth.country_access_check(public.logistics_vehicle_rules.country_code)
    );

CREATE POLICY logistics_fraud_indicators_rls_policy
    ON public.logistics_fraud_indicators
    FOR ALL
    USING (
        public.logistics_fraud_indicators.country_code IS NULL
        OR auth.country_access_check(public.logistics_fraud_indicators.country_code)
    );

CREATE POLICY logistics_cod_remittance_receipts_rls_policy
    ON public.logistics_cod_remittance_receipts
    FOR ALL
    USING (
        public.logistics_cod_remittance_receipts.country_code IS NULL
        OR auth.country_access_check(public.logistics_cod_remittance_receipts.country_code)
    );

CREATE POLICY logistics_category_pricing_rules_rls_policy
    ON public.logistics_category_pricing_rules
    FOR ALL
    USING (
        public.logistics_category_pricing_rules.country_code IS NULL
        OR auth.country_access_check(public.logistics_category_pricing_rules.country_code)
    );

CREATE POLICY logistics_settlements_rls_policy
    ON public.logistics_settlements
    FOR ALL
    USING (
        public.logistics_settlements.country_code IS NULL
        OR auth.country_access_check(public.logistics_settlements.country_code)
    );

CREATE POLICY logistics_partner_bank_accounts_rls_policy
    ON public.logistics_partner_bank_accounts
    FOR ALL
    USING (
        public.logistics_partner_bank_accounts.country_code IS NULL
        OR auth.country_access_check(public.logistics_partner_bank_accounts.country_code)
    );

CREATE POLICY logistics_partner_documents_rls_policy
    ON public.logistics_partner_documents
    FOR ALL
    USING (
        public.logistics_partner_documents.country_code IS NULL
        OR auth.country_access_check(public.logistics_partner_documents.country_code)
    );

CREATE POLICY employee_roles_rls_policy
    ON public.employee_roles
    FOR ALL
    USING (
        public.employee_roles.country_code IS NULL
        OR auth.country_access_check(public.employee_roles.country_code)
    );

CREATE POLICY employee_attendance_rls_policy
    ON public.employee_attendance
    FOR ALL
    USING (
        public.employee_attendance.country_code IS NULL
        OR auth.country_access_check(public.employee_attendance.country_code)
    );

CREATE POLICY employee_leave_requests_rls_policy
    ON public.employee_leave_requests
    FOR ALL
    USING (
        public.employee_leave_requests.country_code IS NULL
        OR auth.country_access_check(public.employee_leave_requests.country_code)
    );

CREATE POLICY employee_leave_ledgers_rls_policy
    ON public.employee_leave_ledgers
    FOR ALL
    USING (
        public.employee_leave_ledgers.country_code IS NULL
        OR auth.country_access_check(public.employee_leave_ledgers.country_code)
    );

CREATE POLICY employee_assets_rls_policy
    ON public.employee_assets
    FOR ALL
    USING (
        public.employee_assets.country_code IS NULL
        OR auth.country_access_check(public.employee_assets.country_code)
    );

CREATE POLICY employee_biometrics_rls_policy
    ON public.employee_biometrics
    FOR ALL
    USING (
        public.employee_biometrics.country_code IS NULL
        OR auth.country_access_check(public.employee_biometrics.country_code)
    );

CREATE POLICY employee_dependents_rls_policy
    ON public.employee_dependents
    FOR ALL
    USING (
        public.employee_dependents.country_code IS NULL
        OR auth.country_access_check(public.employee_dependents.country_code)
    );

CREATE POLICY employee_certifications_rls_policy
    ON public.employee_certifications
    FOR ALL
    USING (
        public.employee_certifications.country_code IS NULL
        OR auth.country_access_check(public.employee_certifications.country_code)
    );

CREATE POLICY employee_documents_rls_policy
    ON public.employee_documents
    FOR ALL
    USING (
        public.employee_documents.country_code IS NULL
        OR auth.country_access_check(public.employee_documents.country_code)
    );

CREATE POLICY employee_expenses_rls_policy
    ON public.employee_expenses
    FOR ALL
    USING (
        public.employee_expenses.country_code IS NULL
        OR auth.country_access_check(public.employee_expenses.country_code)
    );

CREATE POLICY employee_relations_rls_policy
    ON public.employee_relations
    FOR ALL
    USING (
        public.employee_relations.country_code IS NULL
        OR auth.country_access_check(public.employee_relations.country_code)
    );

CREATE POLICY employee_shift_rosters_rls_policy
    ON public.employee_shift_rosters
    FOR ALL
    USING (
        public.employee_shift_rosters.country_code IS NULL
        OR auth.country_access_check(public.employee_shift_rosters.country_code)
    );

CREATE POLICY employee_travel_requests_rls_policy
    ON public.employee_travel_requests
    FOR ALL
    USING (
        public.employee_travel_requests.country_code IS NULL
        OR auth.country_access_check(public.employee_travel_requests.country_code)
    );

CREATE POLICY employee_work_logs_rls_policy
    ON public.employee_work_logs
    FOR ALL
    USING (
        public.employee_work_logs.country_code IS NULL
        OR auth.country_access_check(public.employee_work_logs.country_code)
    );

CREATE POLICY invoices_rls_policy
    ON public.invoices
    FOR ALL
    USING (
        public.invoices.country_code IS NULL
        OR auth.country_access_check(public.invoices.country_code)
    );

CREATE POLICY invoice_items_rls_policy
    ON public.invoice_items
    FOR ALL
    USING (
        public.invoice_items.country_code IS NULL
        OR auth.country_access_check(public.invoice_items.country_code)
    );

CREATE POLICY fraud_cases_rls_policy
    ON public.fraud_cases
    FOR ALL
    USING (
        public.fraud_cases.country_code IS NULL
        OR auth.country_access_check(public.fraud_cases.country_code)
    );

CREATE POLICY fraud_alerts_rls_policy
    ON public.fraud_alerts
    FOR ALL
    USING (
        public.fraud_alerts.country_code IS NULL
        OR auth.country_access_check(public.fraud_alerts.country_code)
    );

CREATE POLICY fraud_events_rls_policy
    ON public.fraud_events
    FOR ALL
    USING (
        public.fraud_events.country_code IS NULL
        OR auth.country_access_check(public.fraud_events.country_code)
    );

CREATE POLICY fraud_scoring_logs_rls_policy
    ON public.fraud_scoring_logs
    FOR ALL
    USING (
        public.fraud_scoring_logs.country_code IS NULL
        OR auth.country_access_check(public.fraud_scoring_logs.country_code)
    );

CREATE POLICY journal_entry_lines_rls_policy
    ON public.journal_entry_lines
    FOR ALL
    USING (
        public.journal_entry_lines.country_code IS NULL
        OR auth.country_access_check(public.journal_entry_lines.country_code)
    );

CREATE POLICY bank_transactions_rls_policy
    ON public.bank_transactions
    FOR ALL
    USING (
        public.bank_transactions.country_code IS NULL
        OR auth.country_access_check(public.bank_transactions.country_code)
    );

CREATE POLICY cash_accounts_rls_policy
    ON public.cash_accounts
    FOR ALL
    USING (
        public.cash_accounts.country_code IS NULL
        OR auth.country_access_check(public.cash_accounts.country_code)
    );

CREATE POLICY cash_transactions_rls_policy
    ON public.cash_transactions
    FOR ALL
    USING (
        public.cash_transactions.country_code IS NULL
        OR auth.country_access_check(public.cash_transactions.country_code)
    );

CREATE POLICY payout_batch_items_rls_policy
    ON public.payout_batch_items
    FOR ALL
    USING (
        public.payout_batch_items.country_code IS NULL
        OR auth.country_access_check(public.payout_batch_items.country_code)
    );

CREATE POLICY admin_activity_logs_rls_policy
    ON public.admin_activity_logs
    FOR ALL
    USING (
        public.admin_activity_logs.country_code IS NULL
        OR auth.country_access_check(public.admin_activity_logs.country_code)
    );

CREATE POLICY admin_analytics_snapshots_rls_policy
    ON public.admin_analytics_snapshots
    FOR ALL
    USING (
        public.admin_analytics_snapshots.country_code IS NULL
        OR auth.country_access_check(public.admin_analytics_snapshots.country_code)
    );

CREATE POLICY admin_change_audit_logs_rls_policy
    ON public.admin_change_audit_logs
    FOR ALL
    USING (
        public.admin_change_audit_logs.country_code IS NULL
        OR auth.country_access_check(public.admin_change_audit_logs.country_code)
    );

CREATE POLICY fiscal_periods_rls_policy
    ON public.fiscal_periods
    FOR ALL
    USING (
        public.fiscal_periods.country_code IS NULL
        OR auth.country_access_check(public.fiscal_periods.country_code)
    );

CREATE POLICY treasury_accounts_rls_policy
    ON public.treasury_accounts
    FOR ALL
    USING (
        public.treasury_accounts.country_code IS NULL
        OR auth.country_access_check(public.treasury_accounts.country_code)
    );

CREATE POLICY treasury_transactions_rls_policy
    ON public.treasury_transactions
    FOR ALL
    USING (
        public.treasury_transactions.country_code IS NULL
        OR auth.country_access_check(public.treasury_transactions.country_code)
    );

CREATE POLICY cash_flow_forecasts_rls_policy
    ON public.cash_flow_forecasts
    FOR ALL
    USING (
        public.cash_flow_forecasts.country_code IS NULL
        OR auth.country_access_check(public.cash_flow_forecasts.country_code)
    );

CREATE POLICY cash_position_snapshots_rls_policy
    ON public.cash_position_snapshots
    FOR ALL
    USING (
        public.cash_position_snapshots.country_code IS NULL
        OR auth.country_access_check(public.cash_position_snapshots.country_code)
    );

CREATE POLICY gateway_settlement_schedules_rls_policy
    ON public.gateway_settlement_schedules
    FOR ALL
    USING (
        public.gateway_settlement_schedules.country_code IS NULL
        OR auth.country_access_check(public.gateway_settlement_schedules.country_code)
    );

CREATE POLICY ar_ledger_entries_rls_policy
    ON public.ar_ledger_entries
    FOR ALL
    USING (
        public.ar_ledger_entries.country_code IS NULL
        OR auth.country_access_check(public.ar_ledger_entries.country_code)
    );

CREATE POLICY ap_ledger_entries_rls_policy
    ON public.ap_ledger_entries
    FOR ALL
    USING (
        public.ap_ledger_entries.country_code IS NULL
        OR auth.country_access_check(public.ap_ledger_entries.country_code)
    );

CREATE POLICY financial_reports_rls_policy
    ON public.financial_reports
    FOR ALL
    USING (
        public.financial_reports.country_code IS NULL
        OR auth.country_access_check(public.financial_reports.country_code)
    );

CREATE POLICY vat_remittances_rls_policy
    ON public.vat_remittances
    FOR ALL
    USING (
        public.vat_remittances.country_code IS NULL
        OR auth.country_access_check(public.vat_remittances.country_code)
    );

CREATE POLICY refund_ledger_rls_policy
    ON public.refund_ledger
    FOR ALL
    USING (
        public.refund_ledger.country_code IS NULL
        OR auth.country_access_check(public.refund_ledger.country_code)
    );

CREATE POLICY finance_bank_accounts_rls_policy
    ON public.finance_bank_accounts
    FOR ALL
    USING (
        public.finance_bank_accounts.country_code IS NULL
        OR auth.country_access_check(public.finance_bank_accounts.country_code)
    );

CREATE POLICY transaction_ledgers_rls_policy
    ON public.transaction_ledgers
    FOR ALL
    USING (
        public.transaction_ledgers.country_code IS NULL
        OR auth.country_access_check(public.transaction_ledgers.country_code)
    );

CREATE POLICY promotion_ledger_entries_rls_policy
    ON public.promotion_ledger_entries
    FOR ALL
    USING (
        public.promotion_ledger_entries.country_code IS NULL
        OR auth.country_access_check(public.promotion_ledger_entries.country_code)
    );

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Check if RLS is enabled on a table:
-- SELECT relrowsecurity, relforcerowsecurity FROM pg_class WHERE relname = '<table_name>';

-- Check RLS policies on a table:
-- SELECT polname, polrelid::regclass, polqual::text FROM pg_policy;

-- Test country access:
-- SELECT auth.country_access_check('AE');
