"""suppliers domain - service layer package.

Owns all business logic and DB access for the suppliers domain. Module routers
import from here (never query the session directly). Services depend only on
infrastructure, kernel, providers (via services), and their own domain models
(per the dependency laws in ARCHITECTURE_DIAGRAM.md).
"""

from __future__ import annotations

from domains.suppliers.services.supplier_service import (
    accept_supplier_terms,
    admin_set_supplier_badge,
    bulk_inventory_adjust,
    bulk_upload_products,
    compute_credibility_score,
    create_supplier_product,
    delete_supplier_product,
    execute_bulk_operation,
    export_products_csv,
    get_inventory_alerts,
    get_public_supplier_products,
    get_public_supplier_profile,
    get_payout_history,
    get_supplier_analytics,
    get_supplier_analytics_timeseries,
    get_supplier_bank_account,
    get_supplier_inventory,
    get_supplier_label_payload,
    get_supplier_onboarding_status,
    get_supplier_order_detail,
    get_supplier_orders,
    get_supplier_product,
    get_supplier_products,
    get_supplier_profile,
    get_supplier_profile_business,
    get_supplier_regions,
    get_supplier_reports,
    get_supplier_shipments,
    list_public_suppliers,
    process_product_image,
    refresh_supplier_badge,
    request_payout,
    request_verification,
    resolve_public_supplier_slug,
    run_badge_recalculation_cycle,
    screen_supplier,
    update_inventory_levels,
    update_product_stock,
    update_supplier_order_status,
    update_supplier_profile,
    update_supplier_profile_business,
    update_supplier_product,
    update_supplier_regions,
    upload_supplier_parcel_proof,
    upload_supplier_profile_business_media,
    upsert_supplier_bank_account,
)
from domains.suppliers.services.supplier_shared import (
    DEFAULT_MAX_RETURN_WINDOW_DAYS,
    MIN_RETURN_WINDOW_DAYS,
    build_bulk_upload_error,
    build_list_page_payload,
    build_public_supplier_cache_key,
    build_supplier_product_payload,
    build_variant_title,
    coerce_optional_bool,
    deserialize_profile_json,
    generate_variant_product_code,
    get_supplier_max_return_window_days,
    load_shipments_for_orders,
    load_supplier_ai_audit_summary,
    load_users_by_ids,
    map_bulk_upload_error,
    normalize_optional_product_text,
    normalize_product_visibility_regions,
    normalize_product_video_reference,
    normalize_variant_attributes,
    normalize_variant_axes,
    parse_optional_datetime,
    parse_optional_return_window_days,
    parse_product_variants_payload,
    parse_supplier_return_window_days,
    persist_supplier_product,
    product_code_segment,
    queue_supplier_ai_audit,
    replace_product_variants,
    resolve_category_id,
    run_supplier_ai_audit,
    sanitize_profile_json,
    sanitize_profile_string,
    serialize_profile_json,
    serialize_product_variant,
    serialize_product_visibility_regions,
    slugify_supplier_storefront,
)
from domains.suppliers.services.profile.supplier_profile import (
    get_supplier_profile,
    request_verification,
    update_supplier_profile,
)
from domains.suppliers.services.products.supplier_products import (
    create_supplier_product,
    delete_supplier_product,
    get_supplier_product,
    get_supplier_products,
    process_product_image,
    update_supplier_product,
)
from domains.suppliers.services.orders.supplier_orders import (
    get_supplier_label_payload,
    get_supplier_order_detail,
    get_supplier_orders,
    update_supplier_order_status,
    upload_supplier_parcel_proof,
)
from domains.suppliers.services.health.supplier_health import (
    accept_supplier_terms,
    admin_set_supplier_badge,
    bulk_inventory_adjust,
    compute_credibility_score,
    export_products_csv,
    get_inventory_alerts,
    get_payout_history,
    get_public_supplier_products,
    get_public_supplier_profile,
    get_supplier_analytics,
    get_supplier_analytics_timeseries,
    get_supplier_bank_account,
    get_supplier_inventory,
    get_supplier_onboarding_status,
    get_supplier_profile_business,
    get_supplier_regions,
    get_supplier_reports,
    get_supplier_shipments,
    list_public_suppliers,
    refresh_supplier_badge,
    request_payout,
    request_verification,
    resolve_public_supplier_slug,
    run_badge_recalculation_cycle,
    update_inventory_levels,
    update_product_stock,
    update_supplier_profile,
    update_supplier_profile_business,
    update_supplier_regions,
    upload_supplier_profile_business_media,
    upsert_supplier_bank_account,
)
