"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body, Query
from sqlalchemy.orm import Session
from infrastructure.database.database import get_db
from infrastructure.utils.dependencies import get_current_user

from domains.orders.services.orders_controller import OrderCreate
from domains.orders.services.orders_controller import OrderPreviewOut
from domains.orders.services.orders_controller import cancel_order
from domains.orders.services.orders_controller import confirm_order_scan_receipt
from domains.orders.services.orders_controller import create_order
from domains.orders.services.orders_controller import get_order
from domains.orders.services.orders_controller import get_order_invoice
from domains.orders.services.orders_controller import get_order_tracking
from domains.orders.services.orders_controller import get_orders
from domains.orders.services.orders_controller import preview_order
from domains.orders.services.orders_controller import respond_to_shipment_confirmation

router = APIRouter(prefix="/api/v1/customer")

@router.post("/orders", status_code=201, tags=['orders'])
def create_order_route(
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    order: OrderCreate = Body(...)
):
    return create_order(current_user=current_user, db=db, order=order)

@router.post("/orders/preview", response_model=OrderPreviewOut, status_code=201, tags=['orders'])
def preview_order_route(
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    order: OrderCreate = Body(...)
):
    return preview_order(current_user=current_user, db=db, order=order)

@router.get("/orders", status_code=200, tags=['orders'])
def get_orders_route(
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    skip: int = Query(0),
    limit: int = Query(50)
):
    return get_orders(current_user=current_user, db=db, skip=skip, limit=limit)

@router.get("/orders/{order_id}", status_code=200, tags=['orders'])
def get_order_route(
    order_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    return get_order(order_id=order_id, current_user=current_user, db=db)

@router.get("/orders/{order_id}/invoice", status_code=200, tags=['orders'])
def get_order_invoice_route(
    order_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    return get_order_invoice(order_id=order_id, current_user=current_user, db=db)

@router.get("/orders/{order_id}/tracking", status_code=200, tags=['orders'])
def get_order_tracking_route(
    order_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    return get_order_tracking(order_id=order_id, current_user=current_user, db=db)

@router.post("/orders/{order_id}/scan-receipt", status_code=201, tags=['orders'])
def confirm_order_scan_receipt_route(
    order_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    data: dict = Body(...)
):
    return confirm_order_scan_receipt(order_id=order_id, current_user=current_user, db=db, data=data)

@router.post("/orders/{order_id}/cancel", status_code=201, tags=['orders'])
def cancel_order_route(
    order_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    return cancel_order(order_id=order_id, current_user=current_user, db=db)

@router.post("/orders/{order_id}/confirmation-requests/{confirmation_id}/respond", status_code=201, tags=['orders'])
def respond_to_shipment_confirmation_route(
    order_id: int,
    confirmation_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    data: dict = Body(...)
):
    return respond_to_shipment_confirmation(order_id=order_id, confirmation_id=confirmation_id, current_user=current_user, db=db, data=data)
