"""Customer orders router — consolidated from 3 source files."""

from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query, Path, Body, status
from pydantic import BaseModel
from sqlalchemy.orm import Session

from infrastructure.security.dependencies import get_current_user, require_admin
from infrastructure.database.database import get_db
from infrastructure.database.schemas import CartItemCreate, CartSyncRequest, OrderCreate, OrderPreviewOut, ReturnRequestCreate, ReturnRequestOut, ReturnRequestUpdate
from domains.orders.ports import list_return_requests
from domains.orders.services.cart.service import (
    get_cart as svc_get_cart,
    add_to_cart as svc_add_to_cart,
    update_cart_item as svc_update_cart_item,
    remove_cart_item as svc_remove_cart_item,
    clear_cart as svc_clear_cart,
    get_cart_shipping_quote as svc_get_cart_shipping_quote,
    sync_cart as svc_sync_cart,
    CartShippingQuoteRequest,
)
from domains.orders.services.core.order_admin import cancel_order
from domains.orders.services.core.order_admin import confirm_order_scan_receipt
from domains.orders.services.core.order_admin import get_order_tracking
from domains.orders.services.core.order_admin import respond_to_shipment_confirmation
from domains.orders.services.core.order_engine import create_order
from domains.orders.services.core.order_engine import get_order
from domains.orders.services.core.order_engine import get_order_invoice
from domains.orders.services.core.order_engine import get_orders
from domains.orders.services.core.order_engine import preview_order
from domains.orders.services.returns.service import bulk_update_return_requests
from domains.orders.services.returns.service import create_return_request
from domains.orders.services.returns.service import get_return_request
from domains.orders.services.returns.service import update_return_request
from rbac.dependencies import require_feature


router = APIRouter(prefix="/api/v1/customer/orders", tags=["customer", "orders"])


# === From cart.py ===
"""Cart router."""


class CartItemUpdate(BaseModel):
    product_id: int | None = None
    quantity: int


@router.get("")
def get_cart(current_user: dict = Depends(get_current_user), db: Session = Depends(get_db),
    _rf_gate: None = Depends(require_feature("customers.cart.manage"))
):
    result = svc_get_cart(current_user.id, db)
    return {"items": result.items, "subtotal": result.subtotal, "item_count": result.item_count}


@router.post("/items")
def add_to_cart(payload: CartItemCreate, current_user: dict = Depends(get_current_user), db: Session = Depends(get_db),
    _rf_gate: None = Depends(require_feature("customers.cart.manage"))
):
    return svc_add_to_cart(current_user.id, payload, db)


@router.put("/sync")
def sync_cart(
    body: CartSyncRequest,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    _rf_gate: None = Depends(require_feature("customers.cart.manage")),
):
    return svc_sync_cart(current_user.id, body, db)


@router.put("/items/{product_id}")
def update_cart_item(product_id: int, body: CartItemUpdate, current_user: dict = Depends(get_current_user), db: Session = Depends(get_db),
    _rf_gate: None = Depends(require_feature("customers.cart.manage"))
):
    return svc_update_cart_item(
        user_id=current_user.id,
        product_id=product_id,
        quantity=body.quantity,
        selected_size="",
        selected_color="",
        db=db,
    )


@router.delete("/items/{product_id}")
def remove_from_cart(product_id: int, current_user: dict = Depends(get_current_user), db: Session = Depends(get_db),
    _rf_gate: None = Depends(require_feature("customers.cart.manage"))
):
    return svc_remove_cart_item(current_user.id, product_id, db)


@router.delete("")
def clear_cart(current_user: dict = Depends(get_current_user), db: Session = Depends(get_db),
    _rf_gate: None = Depends(require_feature("customers.cart.manage"))
):
    return svc_clear_cart(current_user.id, db)


@router.post("/shipping-quote")
def get_cart_shipping_quote(
    body: CartShippingQuoteRequest,
    db: Session = Depends(get_db),
    _rf_gate: None = Depends(require_feature("logistics.delivery.estimates")),
):
    return svc_get_cart_shipping_quote(body, db)


# === From customer_orders.py ===
"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""


@router.post("/orders", status_code=201, tags=['orders'])
def create_order_route(
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    order: OrderCreate = Body(...),
    _rf_gate: None = Depends(require_feature("orders.create")),
):
    return create_order(current_user=current_user, db=db, order=order)

@router.post("/orders/preview", response_model=OrderPreviewOut, status_code=201, tags=['orders'])
def preview_order_route(
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    order: OrderCreate = Body(...),
    _rf_gate: None = Depends(require_feature("orders.create")),
):
    return preview_order(current_user=current_user, db=db, order=order)

@router.get("/orders", status_code=200, tags=['orders'])
def get_orders_route(
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    skip: int = Query(0),
    limit: int = Query(50),
    _rf_gate: None = Depends(require_feature("orders.list")),
):
    return get_orders(current_user=current_user, db=db, skip=skip, limit=limit)

@router.get("/orders/{order_id}", status_code=200, tags=['orders'])
def get_order_route(
    order_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    _rf_gate: None = Depends(require_feature("orders.read")),
):
    return get_order(order_id=order_id, current_user=current_user, db=db)

@router.get("/orders/{order_id}/invoice", status_code=200, tags=['orders'])
def get_order_invoice_route(
    order_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    _rf_gate: None = Depends(require_feature("orders.read")),
):
    return get_order_invoice(order_id=order_id, current_user=current_user, db=db)

@router.get("/orders/{order_id}/tracking", status_code=200, tags=['orders'])
def get_order_tracking_route(
    order_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    _rf_gate: None = Depends(require_feature("logistics.shipping.tracking")),
):
    return get_order_tracking(order_id=order_id, current_user=current_user, db=db)

@router.post("/orders/{order_id}/scan-receipt", status_code=201, tags=['orders'])
def confirm_order_scan_receipt_route(
    order_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    data: dict = Body(...),
    _rf_gate: None = Depends(require_feature("orders.update")),
):
    return confirm_order_scan_receipt(order_id=order_id, current_user=current_user, db=db, data=data)

@router.post("/orders/{order_id}/cancel", status_code=201, tags=['orders'])
def cancel_order_route(
    order_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    _rf_gate: None = Depends(require_feature("orders.cancel")),
):
    return cancel_order(order_id=order_id, current_user=current_user, db=db)

@router.post("/orders/{order_id}/confirmation-requests/{confirmation_id}/respond", status_code=201, tags=['orders'])
def respond_to_shipment_confirmation_route(
    order_id: int,
    confirmation_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    data: dict = Body(...),
    _rf_gate: None = Depends(require_feature("orders.update")),
):
    return respond_to_shipment_confirmation(order_id=order_id, confirmation_id=confirmation_id, current_user=current_user, db=db, data=data)


# === From returns.py ===
"""Returns router."""


class BulkReturnStatusUpdateBody(BaseModel):
    return_ids: list[int]
    status: str
    resolution_notes: Optional[str] = None
    notes: Optional[str] = None


def _user_context(user) -> dict:
    return {
        "id": getattr(user, "id", None),
        "username": getattr(user, "username", None),
        "role": getattr(user, "role", None),
    }


def _serialize_return(req) -> dict:
    return {
        "id": getattr(req, "id", None),
        "order_id": getattr(req, "order_id", None),
        "order_item_id": getattr(req, "order_item_id", None),
        "customer_id": getattr(req, "user_id", None),
        "intent": getattr(req, "intent", "return"),
        "reason": getattr(req, "reason", None),
        "description": getattr(req, "description", None),
        "images": getattr(req, "images", None),
        "status": getattr(req, "status", None),
        "resolution": getattr(req, "resolution_notes", None),
        "resolution_notes": getattr(req, "resolution_notes", None),
        "refund_amount": getattr(req, "refund_amount", None),
        "items": getattr(req, "items", None),
        "return_window_days": getattr(req, "return_window_days", None),
        "delivered_at": getattr(req, "delivered_at", None),
        "return_deadline": getattr(req, "return_deadline", None),
        "created_at": getattr(req, "created_at", None),
        "updated_at": getattr(req, "updated_at", None),
    }

@router.get("/returns", response_model=list[ReturnRequestOut])
def list_returns(current_user: dict = Depends(get_current_user), db: Session = Depends(get_db),
    _rf_gate: None = Depends(require_feature("orders.returns.read"))
):
    requests = list_return_requests(_user_context(current_user), db)
    return [_serialize_return(req) for req in requests]


@router.post("/returns", response_model=ReturnRequestOut, status_code=201)
def create_return(payload: ReturnRequestCreate, current_user: dict = Depends(get_current_user), db: Session = Depends(get_db),
    _rf_gate: None = Depends(require_feature("customers.returns.request"))
):
    req = create_return_request(_user_context(current_user), payload, db)
    return _serialize_return(req)


@router.get("/{return_id}", response_model=ReturnRequestOut)
def get_return(return_id: int, current_user: dict = Depends(get_current_user), db: Session = Depends(get_db),
    _rf_gate: None = Depends(require_feature("orders.returns.read"))
):
    req = get_return_request(return_id, _user_context(current_user), db)
    return _serialize_return(req)


@router.put("/bulk")
def bulk_update_returns(
    body: BulkReturnStatusUpdateBody,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    _rf_gate: None = Depends(require_feature("orders.returns.manage")),
):
    payload = ReturnRequestUpdate(
        status=body.status,
        notes=body.resolution_notes if body.resolution_notes is not None else body.notes,
    )
    return bulk_update_return_requests(body.return_ids, payload, _user_context(current_user), db)


@router.put("/{return_id}", response_model=ReturnRequestOut)
def update_return(
    return_id: int,
    payload: ReturnRequestUpdate,
    current_user: dict = Depends(require_admin),
    db: Session = Depends(get_db),
    _rf_gate: None = Depends(require_feature("orders.returns.manage")),
):
    req = update_return_request(return_id, payload, _user_context(current_user), db)
    return _serialize_return(req)


@router.put("/{return_id}/status")
def update_return_status(return_id: int, status: str, notes: str = None,     _: dict = Depends(require_admin), db: Session = Depends(get_db),
    _rf_gate: None = Depends(require_feature("orders.returns.manage"))
):
    payload = ReturnRequestUpdate(
        status=status,
        notes=notes,
    )
    req = update_return_request(return_id, payload, _user_context(_), db)
    return {"message": "Updated"}
