"""align every domain table with the mixin-compliance columns

domains/_mixin_compliance.py force-appends five columns (created_at, updated_at,
is_deleted, country_code, version) to EVERY domain table at import time, but the
migration history never created them on most tables. The ORM therefore writes
columns the database does not have. Confirmed failures caused by this drift:

  - audit.audit_logs.version   -> every /api/v1/auth/login returned 500
  - promotions.banners.version -> /api/v1/customer/catalog/banners returned 500
  - catalog search             -> /api/v1/customer/catalog/search returned 500

This adds the missing columns so the ORM and the database agree. All additions
are additive and defaulted, so existing rows are preserved:

  version      integer NOT NULL DEFAULT 1
  created_at   timestamp       DEFAULT now()
  updated_at   timestamp       DEFAULT now()
  is_deleted   boolean  NOT NULL DEFAULT false
  country_code varchar(2)

Generated by diffing live information_schema against the loaded ORM metadata:
171 tables, 210 columns. Tables not yet present in the database are skipped.

Revision ID: 20261004_0013
Revises: 20261003_0012
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "20261004_0013"
down_revision: str | None = "20261003_0012"
branch_labels = None
depends_on = None

# (table, [columns], schema)
_ADDITIONS: list[tuple[str, list, str]] = [    ('addresses', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('cart_items', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('carts', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('email_verification_tokens', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('logistics_partner_bank_accounts', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('mfa_factors', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('ocr_results', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('onboarding_pipelines', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('onboarding_steps', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('otp_codes', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('password_histories', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('password_reset_tokens', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('refresh_token_families', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('revoked_tokens', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('social_identities', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('supplier_bank_accounts', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('user_consents', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('user_devices', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('user_login_histories', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('user_preferences', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('user_sessions', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('users', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'accounts'),
    ('command_center_views', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'audit'),
    ('ai_generation_logs', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'catalog'),
    ('ai_staging_products', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'catalog'),
    ('ai_staging_variants', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'catalog'),
    ('ai_upload_jobs', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'catalog'),
    ('categories', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'catalog'),
    ('product_filter_metadatas', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'catalog'),
    ('product_filter_options', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'catalog'),
    ('product_variants', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'catalog'),
    ('product_videos', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'catalog'),
    ('products', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'catalog'),
    ('reviews', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'catalog'),
    ('video_analytics', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'catalog'),
    ('wishlists', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'catalog'),
    ('direct_chat_messages', [sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('direct_chat_rooms', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('entity_chat_messages', [sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('entity_chat_threads', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('escalation_sla_logs', [sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('escalation_sla_rules', [sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')), sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('group_chat_members', [sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('group_chat_messages', [sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('group_chat_rooms', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('incident_action_items', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('incident_threads', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('incident_war_rooms', [sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('internal_notices', [sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')), sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('meeting_recordings', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('news_articles', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('news_sources', [sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')), sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('support_ticket_replies', [sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')), sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('support_tickets', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('ticket_attachments', [sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')), sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('video_room_participants', [sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('video_room_recordings', [sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('video_rooms', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('war_room_templates', [sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'comms'),
    ('country_map_configs', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'country'),
    ('data_residency_records', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'country'),
    ('logistics_partner_locations', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'country'),
    ('parcel_location_trackers', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'country'),
    ('payment_orchestrator_syncs', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'country'),
    ('shift_handover_logs', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'country'),
    ('shop_warehouse_locations', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'country'),
    ('supplier_onboarding_syncs', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'country'),
    ('referral_point_events', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'customers'),
    ('referrals', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'customers'),
    ('logistics_partner_payouts', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'finance'),
    ('payment_gateway_connections', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'finance'),
    ('payment_reconciliation_runs', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'finance'),
    ('payments', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'finance'),
    ('payouts', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'finance'),
    ('admin_activity_logs', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('admin_analytics_snapshots', [sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('admin_change_audit_logs', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('api_keys', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('badge_billing_records', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('badge_tiers', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('badge_transactions', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('chatbot_query_events', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('commission_badge_tiers', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('commission_global_configs', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('email_provider_configs', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('employee_expenses', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('finance_bank_accounts', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('logistics_cod_remittance_receipts', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('logistics_partner_documents', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('logistics_settlements', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('normalized_webhook_events', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('payment_provider_configs', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('processed_webhook_events', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('product_verifications', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('promotion_order_tiers', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('push_notification_tokens', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('retention_job_runs', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('role_permission_settings', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('shipment_confirmations', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('shipping_carriers', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('shipping_zones', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('supplier_country_commissions', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('system_alerts', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('system_health_events', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('system_settings', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('ticket_replies', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('user_browsing_histories', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'governance'),
    ('alumni_networks', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('coi_reports', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('disciplinary_cases', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('dynamic_qr_sessions', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('employee_activity_logs', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('employee_addresses', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('employee_assets', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('employee_attendances', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('employee_biometrics', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('employee_certifications', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('employee_dependents', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('employee_documents', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('employee_leave_ledgers', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('employee_leave_requests', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('employee_relations', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('employee_risk_scores', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('employee_roles', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('employee_shift_rosters', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('employee_travel_requests', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('employee_work_logs', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('employees', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('geo_fence_logs', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('offboarding_cases', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('offices', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('org_units', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('physical_id_cards', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('shift_handover_sessions', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('shift_handover_tasks', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('training_modules', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'hr'),
    ('city_distance_matrices', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'logistics'),
    ('partner_performance_projections', [sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'logistics'),
    ('shipment_tracking_projections', [sa.Column('country_code', sa.String(2), nullable=True), sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'logistics'),
    ('banners', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'promotions'),
    ('bogo_promotions', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'promotions'),
    ('coupon_usages', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'promotions'),
    ('coupons', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'promotions'),
    ('flash_sales', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'promotions'),
    ('points_transactions', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'promotions'),
    ('promotion_engine_configs', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'promotions'),
    ('promotion_ledger_entries', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'promotions'),
    ('user_points', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'promotions'),
    ('alert_escalation_rules', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('credit_card_bins', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('device_fingerprints', [sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('dlp_violations', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('document_verifications', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('fraud_alerts', [sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('fraud_blacklists', [sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('fraud_case_assignments', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('fraud_cases', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('fraud_events', [sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('fraud_rules', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('fraud_scoring_logs', [sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('fraud_velocity_counters', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('ip_account_linkages', [sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('ip_reputations', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('kyc_verifications', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('logistics_fraud_indicators', [sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('manual_review_queues', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('meeting_action_items', [sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('meeting_transcripts', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('return_abuse_patterns', [sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()), sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'security'),
    ('supplier_disputes', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'suppliers'),
    ('supplier_fraud_indicators', [sa.Column('version', sa.Integer(), nullable=False, server_default='1')], 'suppliers'),
]


def upgrade() -> None:
    for table, cols, schema in _ADDITIONS:
        for col in cols:
            op.add_column(table, col, schema=schema)


def downgrade() -> None:
    for table, cols, schema in reversed(_ADDITIONS):
        for col in reversed(cols):
            op.drop_column(table, col.name, schema=schema)