"""unify country_code width to String(3) (DBA04)

All ``country_code`` columns are normalised to ``String(3)`` to match the
referenced ``country.country_configs.code`` (ISO alpha-3, max 3 chars). This
removes the width drift flagged by DBA04. SQLite ignores VARCHAR length, so the
ORM rebuild already handles it; this migration applies the narrowing on
PostgreSQL only (idempotent: re-ALTERing an already-String(3) column is a no-op).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ccw_unify_20260809'
down_revision: Union[str, None] = '02ebc285f66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (schema, table, existing_nullable) for every country_code column
_TARGETS = (
    (None, 'dynamic_qr_sessions', True),
    (None, 'employee_attendance', True),
    (None, 'employee_shift_rosters', True),
    (None, 'media_upload_sessions', False),
    (None, 'payment_gateway_connections', False),
    (None, 'payout_batches', False),
    (None, 'product_variants', True),
    (None, 'upload_jobs', True),
    ('ai', 'ai_generation_logs', True),
    ('ai', 'ai_staging_products', True),
    ('ai', 'ai_staging_variants', True),
    ('ai', 'ai_upload_jobs', True),
    ('analytics', 'financial_reports', True),
    ('analytics', 'normalized_webhook_events', True),
    ('analytics', 'processed_webhook_events', True),
    ('audit', 'admin_activity_logs', True),
    ('audit', 'admin_analytics_snapshots', True),
    ('audit', 'admin_change_audit_logs', True),
    ('audit', 'audit_logs', True),
    ('audit', 'chatbot_query_events', True),
    ('audit', 'retention_job_runs', True),
    ('commerce', 'badge_billing_records', True),
    ('commerce', 'badge_tiers', True),
    ('commerce', 'badge_transactions', True),
    ('commerce', 'banners', True),
    ('commerce', 'categories', True),
    ('commerce', 'commission_agreements', True),
    ('commerce', 'commission_badge_tiers', True),
    ('commerce', 'commission_category_rates', True),
    ('commerce', 'commission_global_configs', True),
    ('commerce', 'commission_ledger_entries', True),
    ('commerce', 'coupon_usage', True),
    ('commerce', 'coupons', True),
    ('commerce', 'flash_sale_items', True),
    ('commerce', 'flash_sales', True),
    ('commerce', 'order_items', True),
    ('commerce', 'order_logistics_allocations', True),
    ('commerce', 'orders', True),
    ('commerce', 'product_commission_overrides', True),
    ('commerce', 'product_filter_metadata', True),
    ('commerce', 'product_filter_options', True),
    ('commerce', 'product_verifications', True),
    ('commerce', 'products', True),
    ('commerce', 'promotion_engine_configs', True),
    ('commerce', 'promotion_ledger_entries', True),
    ('commerce', 'promotion_order_tiers', True),
    ('commerce', 'return_requests', True),
    ('commerce', 'reviews', True),
    ('communication', 'employee_communication_threads', True),
    ('communication', 'internal_channels', True),
    ('communication', 'push_notification_tokens', True),
    ('communication', 'ticket_replies', True),
    ('configuration', 'country_category_tax_rates', False),
    ('configuration', 'country_commission_rate_history', False),
    ('configuration', 'country_commission_rates', False),
    ('configuration', 'country_communication_threads', False),
    ('configuration', 'country_config_versions', False),
    ('configuration', 'country_feature_flags', False),
    ('configuration', 'country_gateway_configs', False),
    ('configuration', 'country_holiday_calendars', False),
    ('configuration', 'country_legal_contracts', False),
    ('configuration', 'country_localization', False),
    ('configuration', 'country_logistics_zones', False),
    ('configuration', 'country_payment_aliases', False),
    ('configuration', 'country_payout_rules', False),
    ('configuration', 'country_staff_assignments', False),
    ('configuration', 'email_provider_configs', True),
    ('configuration', 'system_alerts', True),
    ('configuration', 'system_settings', True),
    ('country', 'country_cities', False),
    ('country', 'country_communications', False),
    ('country', 'country_configs', True),
    ('country', 'country_economics', False),
    ('country', 'country_gateway_credentials', False),
    ('country', 'country_legal', False),
    ('country', 'country_tax', False),
    ('country', 'logistics_partner_kyc_requirements', False),
    ('country', 'messages', True),
    ('country', 'payout_rule_categories', False),
    ('country', 'payout_rule_products', False),
    ('country', 'supplier_kyc_requirements', False),
    ('country', 'tax_rules', False),
    ('customer', 'referral_point_events', True),
    ('customer', 'referrals', True),
    ('customer', 'wishlist_items', True),
    ('customer', 'wishlists', True),
    ('finance', 'account_balances', True),
    ('finance', 'account_groups', True),
    ('finance', 'accounts', True),
    ('finance', 'accruals', True),
    ('finance', 'ap_bills', True),
    ('finance', 'ap_ledger_entries', True),
    ('finance', 'ar_invoices', True),
    ('finance', 'ar_ledger_entries', True),
    ('finance', 'automation_logs', True),
    ('finance', 'automation_rules', True),
    ('finance', 'bank_accounts', True),
    ('finance', 'bank_mapping_rules', True),
    ('finance', 'bank_reconciliations', True),
    ('finance', 'bank_statement_imports', True),
    ('finance', 'bank_statement_lines', True),
    ('finance', 'bank_transactions', True),
    ('finance', 'budgets', True),
    ('finance', 'cost_centers', True),
    ('finance', 'customers', True),
    ('finance', 'finance_audit_logs', True),
    ('finance', 'finance_automation_logs', True),
    ('finance', 'fiscal_periods', False),
    ('finance', 'fixed_assets', True),
    ('finance', 'invoice_items', True),
    ('finance', 'invoices', True),
    ('finance', 'journal_entries', True),
    ('finance', 'journal_entry_lines', True),
    ('finance', 'payments', True),
    ('finance', 'pending_journal_entries', True),
    ('finance', 'recurring_templates', True),
    ('finance', 'refund_ledger', True),
    ('finance', 'scanned_expenses', True),
    ('finance', 'supplier_settlements', True),
    ('finance', 'transaction_ledgers', True),
    ('finance', 'vat_remittances', True),
    ('finance', 'vendors', True),
    ('hr', 'alumni_network', True),
    ('hr', 'coi_reports', True),
    ('hr', 'country_map_configs', False),
    ('hr', 'data_residency_records', False),
    ('hr', 'disciplinary_cases', True),
    ('hr', 'employee_addresses', False),
    ('hr', 'employee_assets', True),
    ('hr', 'employee_biometrics', True),
    ('hr', 'employee_certifications', True),
    ('hr', 'employee_dependents', True),
    ('hr', 'employee_documents', True),
    ('hr', 'employee_expenses', True),
    ('hr', 'employee_leave_ledgers', True),
    ('hr', 'employee_leave_requests', True),
    ('hr', 'employee_relations', True),
    ('hr', 'employee_risk_scores', True),
    ('hr', 'employee_roles', True),
    ('hr', 'employee_travel_requests', True),
    ('hr', 'employee_work_logs', True),
    ('hr', 'employees', True),
    ('hr', 'geo_fence_logs', True),
    ('hr', 'legal_contract_templates', False),
    ('hr', 'logistics_partner_locations', False),
    ('hr', 'offboarding_cases', True),
    ('hr', 'offices', False),
    ('hr', 'org_units', True),
    ('hr', 'parcel_location_trackers', False),
    ('hr', 'payment_orchestrator_sync', False),
    ('hr', 'payroll_records', True),
    ('hr', 'physical_id_cards', True),
    ('hr', 'shift_handover_logs', False),
    ('hr', 'shop_warehouse_locations', False),
    ('hr', 'supplier_onboarding_sync', False),
    ('logistics', 'logistics_category_pricing_rules', True),
    ('logistics', 'logistics_cod_remittance_receipts', True),
    ('logistics', 'logistics_fraud_indicators', True),
    ('logistics', 'logistics_partner_bank_accounts', True),
    ('logistics', 'logistics_partner_documents', True),
    ('logistics', 'logistics_partner_payouts', True),
    ('logistics', 'logistics_partner_profiles', True),
    ('logistics', 'logistics_partner_service_areas', False),
    ('logistics', 'logistics_partners', True),
    ('logistics', 'logistics_pricing_profiles', True),
    ('logistics', 'logistics_settlements', True),
    ('logistics', 'logistics_vehicle_rules', True),
    ('logistics', 'shipment_confirmations', True),
    ('logistics', 'shipment_events', True),
    ('logistics', 'shipments', True),
    ('logistics', 'shipping_carriers', True),
    ('logistics', 'shipping_rules', False),
    ('logistics', 'shipping_zones', True),
    ('media', 'media_assets', False),
    ('media', 'product_videos', True),
    ('media', 'video_analytics', True),
    ('security', 'api_keys', True),
    ('security', 'email_verification_tokens', True),
    ('security', 'fraud_alerts', True),
    ('security', 'fraud_cases', True),
    ('security', 'fraud_events', True),
    ('security', 'fraud_rules', True),
    ('security', 'fraud_scoring_logs', True),
    ('security', 'ip_reputations', True),
    ('security', 'password_reset_tokens', True),
    ('security', 'permission_audit_log', True),
    ('security', 'permission_categories', False),
    ('security', 'permissions', False),
    ('security', 'revoked_tokens', True),
    ('security', 'role_permission_assignments', True),
    ('security', 'role_permission_settings', True),
    ('security', 'user_devices', True),
    ('security', 'user_login_history', True),
    ('security', 'user_permission_overrides', True),
    ('security', 'users', True),
    ('supplier', 'supplier_badge_billing_history', True),
    ('supplier', 'supplier_badge_catalog', True),
    ('supplier', 'supplier_badges', True),
    ('supplier', 'supplier_bank_accounts', True),
    ('supplier', 'supplier_country_commissions', False),
    ('supplier', 'supplier_disputes', True),
    ('supplier', 'supplier_fraud_indicators', True),
    ('supplier', 'supplier_profiles', True),
    ('treasury', 'cash_accounts', True),
    ('treasury', 'cash_flow_forecasts', True),
    ('treasury', 'cash_position_snapshots', True),
    ('treasury', 'cash_transactions', True),
    ('treasury', 'finance_bank_accounts', True),
    ('treasury', 'gateway_settlement_schedules', True),
    ('treasury', 'payment_provider_configs', True),
    ('treasury', 'payment_reconciliation_runs', True),
    ('treasury', 'payout_batch_items', True),
    ('treasury', 'payout_rules', False),
    ('treasury', 'payouts', True),
    ('treasury', 'treasury_accounts', True),
    ('treasury', 'treasury_transactions', True),
    # TenantMixin-provided country_code columns (mapped_column(String(10)) ->
    # String(3)); the AST generator only captured explicit Column() forms.
    ('analytics', 'executive_news', False),
    ('communication', 'notifications', False),
    ('communication', 'ticket_messages', False),
    ('communication', 'faqs', False),
    ('communication', 'internal_emails', False),
    ('communication', 'masked_messages', False),
    ('communication', 'support_tickets', False),
    ('communication', 'support_ticket_replies', False),
    ('communication', 'ticket_attachments', False),
    ('communication', 'group_chat_rooms', False),
    ('communication', 'escalation_sla_rules', False),
    ('communication', 'email_campaigns', False),
    ('commerce', 'carts', False),
    ('commerce', 'cart_items', False),
    ('customer', 'addresses', False),
    ('customer', 'news_articles', False),
    ('customer', 'video_rooms', False),
    ('customer', 'direct_chat_rooms', False),
    ('customer', 'shift_handover_sessions', False),
    ('security', 'user_sessions', False),
    ('supplier', 'supplier_documents', False),
    ('supplier', 'supplier_notification_preferences', False),
)


def _apply(new_len: int, existing_len: int) -> None:
    if op.get_context().dialect.name != "postgresql":
        return
    for schema, table, nullable in _TARGETS:
        op.alter_column(
            table,
            "country_code",
            type_=sa.String(new_len),
            existing_type=sa.String(existing_len),
            existing_nullable=nullable,
            schema=schema,
        )


def upgrade() -> None:
    _apply(3, 10)


def downgrade() -> None:
    _apply(10, 3)
