"""add_supplier_documents_invoices_product_verifications_logistics_partners

Revision ID: cabbef94c669
Revises: d5477adebb01
Create Date: 2026-03-24 18:16:37.295677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cabbef94c669'
down_revision: Union[str, Sequence[str], None] = 'd5477adebb01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = set(inspector.get_table_names())
    # ### commands auto generated by Alembic - please adjust! ###
    if 'logistics_partners' not in existing:
        op.create_table('logistics_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('coverage_regions', sa.Text(), nullable=True),
    sa.Column('service_types', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('api_key_hash', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('logistics_partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logistics_partners_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_logistics_partners_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_logistics_partners_status'), ['status'], unique=False)

    op.create_table('supplier_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('document_name', sa.String(length=200), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_documents', schema=None) as batch_op:
        batch_op.create_index('ix_supplier_docs_doc_type', ['document_type', 'status'], unique=False)
        batch_op.create_index('ix_supplier_docs_supplier_status', ['supplier_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_documents_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('return_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_requests_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_requests_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_return_requests_user_order_status', ['user_id', 'order_id', 'status'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('invoice_type', sa.String(length=30), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipping_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('picked_at', sa.DateTime(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('total_amount >= 0', name='ck_invoices_total_nonneg'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoices_order_id'), ['order_id'], unique=False)
        batch_op.create_index('ix_invoices_order_supplier', ['order_id', 'supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        batch_op.create_index('ix_invoices_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('product_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verification_type', sa.String(length=50), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('expected_specs', sa.Text(), nullable=True),
    sa.Column('actual_specs', sa.Text(), nullable=True),
    sa.Column('discrepancies', sa.Text(), nullable=True),
    sa.Column('scan_code', sa.String(length=200), nullable=True),
    sa.Column('image_urls', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_verifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_verifications_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_verifications_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_verifications_scan_code'), ['scan_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_verifications_verification_type'), ['verification_type'], unique=False)
        batch_op.create_index('ix_product_verify_order', ['order_id'], unique=False)
        batch_op.create_index('ix_product_verify_product_type', ['product_id', 'verification_type'], unique=False)

    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('quantity > 0', name='ck_invoice_items_qty_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_invoice_items_price_nonneg'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_items_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_items_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.drop_index('ix_banners_banner_type')
        batch_op.drop_index('ix_banners_is_active')
        batch_op.create_index('ix_banners_active_type', ['is_active', 'banner_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_banners_id'), ['id'], unique=False)

    with op.batch_alter_table('campaign_recipients', schema=None) as batch_op:
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tracking_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_campaign_recipients_campaign_id'), ['campaign_id'], unique=False)

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.alter_column('selected_color',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('min_order',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('newsletter_subscribers', schema=None) as batch_op:
        batch_op.drop_index('ix_newsletter_subscribers_email')
        batch_op.create_index(batch_op.f('ix_newsletter_subscribers_email'), ['email'], unique=True)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    order_cols = {c["name"] for c in inspector.get_columns("orders")}
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('subtotal_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('discount_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        if 'vat_amount' in order_cols:
            batch_op.alter_column('vat_amount',
                   existing_type=sa.FLOAT(),
                   type_=sa.Numeric(precision=12, scale=2),
                   existing_nullable=True,
                   existing_server_default=sa.text("'0'"))
        if 'shipping_amount' in order_cols:
            batch_op.alter_column('shipping_amount',
                   existing_type=sa.FLOAT(),
                   type_=sa.Numeric(precision=12, scale=2),
                   existing_nullable=True,
                   existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('compare_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('push_notification_tokens', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('device_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_index('ix_push_tokens_token')
        batch_op.drop_index('ix_push_tokens_user_id')
        batch_op.drop_constraint('uq_push_user_token', type_='unique')
        batch_op.create_index(batch_op.f('ix_push_notification_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_notification_tokens_token'), ['token'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_notification_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_push_tokens_user', ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_push_token_user', ['user_id', 'token'])

    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index('ix_revoked_tokens_expires_at')
        batch_op.drop_index('ix_revoked_tokens_jti')
        batch_op.create_index('ix_revoked_tokens_jti', ['jti'], unique=False)
        batch_op.create_index('ix_revoked_tokens_expires', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_revoked_tokens_id'), ['id'], unique=False)

    with op.batch_alter_table('shipment_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_events_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_events_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_events_status_after'), ['status_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_events_supplier_id'), ['supplier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_events_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_events_status_after'))
        batch_op.drop_index(batch_op.f('ix_shipment_events_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_events_order_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_shipment_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_shipment_events_actor_user_id'))

    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_id'))
        batch_op.drop_index('ix_revoked_tokens_expires')
        batch_op.drop_index('ix_revoked_tokens_jti')
        batch_op.create_index('ix_revoked_tokens_jti', ['jti'], unique=1)
        batch_op.create_index('ix_revoked_tokens_expires_at', ['expires_at'], unique=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('push_notification_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('uq_push_token_user', type_='unique')
        batch_op.drop_index('ix_push_tokens_user')
        batch_op.drop_index(batch_op.f('ix_push_notification_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_push_notification_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_push_notification_tokens_id'))
        batch_op.create_unique_constraint('uq_push_user_token', ['user_id', 'token'])
        batch_op.create_index('ix_push_tokens_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_push_tokens_token', ['token'], unique=False)
        batch_op.alter_column('device_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('compare_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    order_cols = {c["name"] for c in sa.inspect(op.get_bind()).get_columns("orders")}
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        if 'shipping_amount' in order_cols:
            batch_op.alter_column('shipping_amount',
                   existing_type=sa.Numeric(precision=12, scale=2),
                   type_=sa.FLOAT(),
                   existing_nullable=True,
                   existing_server_default=sa.text("'0'"))
        if 'vat_amount' in order_cols:
            batch_op.alter_column('vat_amount',
                   existing_type=sa.Numeric(precision=12, scale=2),
                   type_=sa.FLOAT(),
                   existing_nullable=True,
                   existing_server_default=sa.text("'0'"))
        batch_op.alter_column('discount_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('subtotal_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('newsletter_subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_subscribers_email'))
        batch_op.create_index('ix_newsletter_subscribers_email', ['email'], unique=False)

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('min_order',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('selected_color',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('campaign_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_recipients_campaign_id'))
        batch_op.alter_column('tracking_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    banner_fks = sa.inspect(op.get_bind()).get_foreign_keys('banners')
    banner_created_by_fk_exists = any(
        fk.get('referred_table') == 'users' and fk.get('constrained_columns') == ['created_by']
        for fk in banner_fks
    )
    with op.batch_alter_table('banners', schema=None) as batch_op:
        if not banner_created_by_fk_exists:
            batch_op.create_foreign_key('fk_banners_created_by_users', 'users', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_banners_id'))
        batch_op.drop_index('ix_banners_active_type')
        batch_op.create_index('ix_banners_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_banners_banner_type', ['banner_type'], unique=False)

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_items_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_items_id'))

    op.drop_table('invoice_items')
    with op.batch_alter_table('product_verifications', schema=None) as batch_op:
        batch_op.drop_index('ix_product_verify_product_type')
        batch_op.drop_index('ix_product_verify_order')
        batch_op.drop_index(batch_op.f('ix_product_verifications_verification_type'))
        batch_op.drop_index(batch_op.f('ix_product_verifications_scan_code'))
        batch_op.drop_index(batch_op.f('ix_product_verifications_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_verifications_order_id'))
        batch_op.drop_index(batch_op.f('ix_product_verifications_id'))

    op.drop_table('product_verifications')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_supplier_id'))
        batch_op.drop_index('ix_invoices_status_created')
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_shipment_id'))
        batch_op.drop_index('ix_invoices_order_supplier')
        batch_op.drop_index(batch_op.f('ix_invoices_order_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('return_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_return_requests_user_order_status')
        batch_op.drop_index(batch_op.f('ix_return_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_return_requests_status'))
        batch_op.drop_index(batch_op.f('ix_return_requests_order_id'))
        batch_op.drop_index(batch_op.f('ix_return_requests_id'))

    op.drop_table('return_requests')
    with op.batch_alter_table('supplier_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_documents_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_documents_status'))
        batch_op.drop_index(batch_op.f('ix_supplier_documents_id'))
        batch_op.drop_index('ix_supplier_docs_supplier_status')
        batch_op.drop_index('ix_supplier_docs_doc_type')

    op.drop_table('supplier_documents')
    with op.batch_alter_table('logistics_partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logistics_partners_status'))
        batch_op.drop_index(batch_op.f('ix_logistics_partners_id'))
        batch_op.drop_index(batch_op.f('ix_logistics_partners_code'))

    op.drop_table('logistics_partners')
    # ### end Alembic commands ###

