#!/usr/bin/env python3
"""
Import updater script - updates all import statements after domain reorganization.
"""
import os
import re
from pathlib import Path

# Mapping of old import paths to new import paths
IMPORT_MAPPINGS = {
    # HR domain
    "domains.hr.services.compliance.coi_service": "domains.hr.services.compliance.coi_service",
    "domains.hr.services.coi_engine": "domains.hr.services.compliance.coi_engine",
    "domains.hr.services.dei_auditor": "domains.hr.services.compliance.dei_auditor",
    "domains.hr.services.background_check": "domains.hr.services.compliance.background_check",
    "domains.hr.services.hse_manager": "domains.hr.services.compliance.hse_manager",
    "domains.hr.services.offboarding": "domains.hr.services.compliance.offboarding",
    "domains.hr.services.hierarchy_service": "domains.hr.services.hierarchy.service",
    "domains.hr.services.hierarchy_controller": "domains.hr.services.hierarchy.controller",
    "domains.hr.services.hierarchy_controller__routers": "domains.hr.services.hierarchy.controller__routers",
    "domains.hr.services.hierarchy_hierarchy_service": "domains.hr.services.hierarchy.hierarchy_service",
    "domains.hr.services.org_hierarchy_write_service": "domains.hr.services.hierarchy.write_service",
    "domains.hr.services.employees_service": "domains.hr.services.employee.employees_service",
    "domains.hr.services.employees_controller": "domains.hr.services.employee.controller",
    "domains.hr.services.employees_controller_service": "domains.hr.services.employee.controller_service",
    "domains.hr.services.employees_controller__routers": "domains.hr.services.employee.controller__routers",
    "domains.hr.services.employee_service": "domains.hr.services.employee.service",
    "domains.hr.services.employee_write_service": "domains.hr.services.employee.write_service",
    "domains.hr.services.employee_activity_logger": "domains.hr.services.employee.activity_logger",
    "domains.hr.services.employee_lifecycle_service": "domains.hr.services.employee.lifecycle_service",
    "domains.hr.services.employee_communication_service": "domains.hr.services.communication.service",
    "domains.hr.services.ess_service": "domains.hr.services.ess.ess_service",
    "domains.hr.services.ess_write_service": "domains.hr.services.ess.write_service",
    "domains.hr.services.ghost_watchdog": "domains.hr.services.ghost_watchdog.ghost_watchdog",
    "domains.hr.services.performance_service": "domains.hr.services.performance.service",
    "domains.hr.services.okr_engine": "domains.hr.services.performance.okr_engine",
    "domains.hr.services.okr_controller": "domains.hr.services.performance.okr_controller",
    "domains.hr.services.lms_service": "domains.hr.services.learning.service",
    "domains.hr.services.lms_controller": "domains.hr.services.learning.controller",
    "domains.hr.services.lms_controller__routers": "domains.hr.services.learning.controller__routers",
    "domains.hr.services.lms_write_service": "domains.hr.services.learning.write_service",
    "domains.hr.services.lms_permission_lock": "domains.hr.services.learning.permission_lock",
    "domains.hr.services.learning_write_service": "domains.hr.services.learning.learning_write_service",
    "domains.hr.services.leave_accrual": "domains.hr.services.payroll.leave_accrual",
    "domains.hr.services.payroll_engine": "domains.hr.services.payroll.engine",
    "domains.hr.services.payroll_read_service": "domains.hr.services.payroll.read_service",
    "domains.hr.services.shift_handover": "domains.hr.services.shift.handover",
    "domains.hr.services.shift_roster_service": "domains.hr.services.shift.roster_service",
    "domains.hr.services.shift_scheduling": "domains.hr.services.shift.scheduling",
    "domains.hr.services.succession_service": "domains.hr.services.succession.service",
    "domains.hr.services.succession_controller": "domains.hr.services.succession.controller",
    "domains.hr.services.travel_service": "domains.hr.services.travel.service",
    "domains.hr.services.travel_detector": "domains.hr.services.travel.detector",
    "domains.hr.services.hr_service": "domains.hr.services.core.service",
    "domains.hr.services.hr_controller": "domains.hr.services.core.controller",
    "domains.hr.services.hr_write_service": "domains.hr.services.core.write_service",
    "domains.hr.services.hr_dashboard_service": "domains.hr.services.analytics.dashboard_service",
    "domains.hr.services.risk_service": "domains.hr.services.analytics.risk_service",
    "domains.hr.services.attendance_service": "domains.hr.services.employee.attendance",
    "domains.hr.services.lms": "domains.hr.services.learning.lms",

    # Orders domain
    "domains.promotions.services.coupons.coupons_service": "domains.promotions.services.coupons.coupons_service",
    "domains.orders.services.coupons_read_service": "domains.promotions.services.coupons.coupons_read_service",
    "domains.orders.services.coupons_write_service": "domains.promotions.services.coupons.coupons_write_service",
    "domains.orders.services.commerce_coupons_read_service": "domains.promotions.services.coupons.commerce_coupons_read_service",
    "domains.orders.services.commerce_coupons_write_service": "domains.promotions.services.coupons.commerce_coupons_write_service",
    "domains.orders.services.customer_coupons_create_service": "domains.promotions.services.coupons.customer_coupons_create_service",
    "domains.orders.services.customer_coupons_mgmt_service": "domains.promotions.services.coupons.customer_coupons_mgmt_service",
    "domains.orders.services.coupons_controller": "domains.promotions.services.coupons.coupons_controller",
    "domains.orders.services.coupons_controller__routers": "domains.promotions.services.coupons.coupons_controller__routers",
    "domains.orders.services.promotion_service": "domains.promotions.services.promotion_service",
    "domains.orders.services.promotion_controller": "domains.promotions.services.promotion_controller",
    "domains.orders.services.promotion_controller__routers": "domains.promotions.services.promotion_controller__routers",
    "domains.orders.services.promotion_admin_controller": "domains.promotions.services.promotion_admin_controller",
    "domains.orders.services.promotion_admin_controller__routers": "domains.promotions.services.promotion_admin_controller__routers",
    "domains.orders.services.promotion_admin_write_service": "domains.promotions.services.promotion_admin_write_service",
    "domains.orders.services.promotion_engine_service": "domains.promotions.services.promotion_engine_service",
    "domains.orders.services.promotions_write_service": "domains.promotions.services.promotions_write_service",
    "domains.orders.services.promotion_bogo_service": "domains.promotions.services.bogo.bogo_service",
    "domains.orders.services.promotion_points_service": "domains.promotions.services.coins.promotion_points_service",
    "domains.orders.services.points_service": "domains.promotions.services.coins.points_service",
    "domains.orders.services.flash_sale_service": "domains.catalog.services.pricing.flash_sale_service",
    "domains.orders.services.flash_sale_write_service": "domains.catalog.services.pricing.flash_sale_write_service",
    "domains.orders.services.flash_sale_controller": "domains.catalog.services.pricing.flash_sale_controller",
    "domains.orders.services.flash_sale_controller__routers": "domains.catalog.services.pricing.flash_sale_controller__routers",
    "domains.orders.services.flash_sale_controller_service": "domains.catalog.services.pricing.flash_sale_controller_service",
    "domains.orders.services.bogo_service": "domains.promotions.services.bogo.bogo_service",
    "domains.orders.services.banner_write_service": "domains.promotions.services.banners.banner_write_service",
    "domains.orders.services.search_service": "domains.catalog.services.search.search_service",
    "domains.orders.services.categories_service": "domains.catalog.services.categories.categories_service",
    "domains.orders.services.admin_categories_service": "domains.catalog.services.categories.admin_categories_service",
    "domains.orders.services.logistics_controller": "domains.logistics.services.shipping.logistics_controller",
    "domains.orders.services.logistics_controller__routers": "domains.logistics.services.shipping.logistics_controller__routers",
    "domains.orders.services.logistics_service": "domains.logistics.services.shipping.logistics_service",
    "domains.orders.services.logistics_partner_controller": "domains.logistics.services.partners.logistics_partner_controller",
    "domains.orders.services.logistics_partner_controller__routers": "domains.logistics.services.partners.logistics_partner_controller__routers",
    "domains.orders.services.logistics_partner_service": "domains.logistics.services.partners.logistics_partner_service",
    "domains.orders.services.fulfillment_service": "domains.logistics.services.fulfillment.fulfillment_service",
    "domains.orders.services.supplier_documents_service": "domains.suppliers.services.documents.supplier_documents_service",
    "domains.orders.services.addresses_service": "domains.accounts.services.addresses.addresses_service",
    "domains.orders.services.cart.cart_service": "domains.orders.services.cart.cart_service",
    "domains.orders.services.cart_write_service": "domains.orders.services.cart.cart_write_service",
    "domains.orders.services.cart_controller": "domains.orders.services.cart.cart_controller",
    "domains.orders.services.cart_controller__routers": "domains.orders.services.cart.cart_controller__routers",
    "domains.orders.services.cart_controller_service": "domains.orders.services.cart.cart_controller_service",
    "domains.orders.services.cart_controller_service__orders": "domains.orders.services.cart.cart_controller_service__orders",
    "domains.orders.services.cart.cart_service__orders": "domains.orders.services.cart.cart_service__orders",
    "domains.orders.services.disputes_service": "domains.orders.services.disputes.disputes_service",
    "domains.orders.services.disputes_controller": "domains.orders.services.disputes.disputes_controller",
    "domains.orders.services.disputes_controller__routers": "domains.orders.services.disputes.disputes_controller__routers",
    "domains.orders.services.disputes_write_service": "domains.orders.services.disputes.disputes_write_service",
    "domains.orders.services.returns_service": "domains.orders.services.returns.returns_service",
    "domains.orders.services.returns_controller": "domains.orders.services.returns.returns_controller",
    "domains.orders.services.returns_controller__routers": "domains.orders.services.returns.returns_controller__routers",
    "domains.orders.services.returns_controller_service": "domains.orders.services.returns.returns_controller_service",
    "domains.orders.services.returns_write_service": "domains.orders.services.returns.returns_write_service",
    "domains.orders.services.order_tracking_service": "domains.orders.services.tracking.order_tracking_service",
    "domains.orders.services.orders_order_tracking_service": "domains.orders.services.tracking.orders_order_tracking_service",
    "domains.orders.services.orders_service": "domains.orders.services.order.orders_service",
    "domains.orders.services.orders_controller": "domains.orders.services.order.orders_controller",
    "domains.orders.services.orders_controller__routers": "domains.orders.services.order.orders_controller__routers",
    "domains.orders.services.orders_write_service": "domains.orders.services.order.write_service",
    "domains.orders.services.orders_write_facade": "domains.orders.services.order.write_facade",

    # Catalog domain
    "domains.catalog.services.products_service": "domains.catalog.services.products.products_service",
    "domains.catalog.services.products_controller": "domains.catalog.services.products.products_controller",
    "domains.catalog.services.products_controller__routers": "domains.catalog.services.products.products_controller__routers",
    "domains.catalog.services.products_write_service": "domains.catalog.services.products.products_write_service",
    "domains.catalog.services.product_service": "domains.catalog.services.products.product_service",
    "domains.catalog.services.product_admin_read_service": "domains.catalog.services.products.product_admin_read_service",
    "domains.catalog.services.product_admin_write_service": "domains.catalog.services.products.product_admin_write_service",
    "domains.catalog.services.product_moderation_service": "domains.catalog.services.products.product_moderation_service",
    "domains.catalog.services.product_verification_service": "domains.catalog.services.products.product_verification_service",
    "domains.catalog.services.product_verification_write_service": "domains.catalog.services.products.product_verification_write_service",
    "domains.catalog.services.categories_service": "domains.catalog.services.categories.categories_service",
    "domains.catalog.services.categories_controller": "domains.catalog.services.categories.categories_controller",
    "domains.category.services.category_service": "domains.catalog.services.categories.category_service",
    "domains.catalog.services.category_admin_controller": "domains.catalog.services.categories.category_admin_controller",
    "domains.catalog.services.category_admin_controller__routers": "domains.catalog.services.categories.category_admin_controller__routers",
    "domains.catalog.services.category_admin_read_service": "domains.catalog.services.categories.category_admin_read_service",
    "domains.catalog.services.category_admin_write_service": "domains.catalog.services.categories.category_admin_write_service",
    "domains.catalog.services.search_service": "domains.catalog.services.search.search_service",
    "domains.catalog.services.visual_search_service": "domains.catalog.services.search.visual_search_service",
    "domains.catalog.services.advanced_search_engine": "domains.catalog.services.search.advanced_search_engine",
    "domains.catalog.services.advanced_filter_service": "domains.catalog.services.search.advanced_filter_service",
    "domains.catalog.services.variant_config_service": "domains.catalog.services.variants.variant_config_service",
    "domains.catalog.services.discount_service": "domains.catalog.services.pricing.discount_service",
    "domains.catalog.services.flash_sale_service": "domains.catalog.services.pricing.flash_sale_service",
    "domains.catalog.services.flash_sale_write_service": "domains.catalog.services.pricing.flash_sale_write_service",
    "domains.catalog.services.flash_sale_controller": "domains.catalog.services.pricing.flash_sale_controller",
    "domains.catalog.services.flash_sale_controller__routers": "domains.catalog.services.pricing.flash_sale_controller__routers",
    "domains.catalog.services.flash_sale_controller_service": "domains.catalog.services.pricing.flash_sale_controller_service",

    # Accounts domain
    "domains.accounts.services.addresses.addresses_service": "domains.accounts.services.addresses.addresses_service",
    "domains.accounts.services.commerce_read_service": "domains.accounts.services.addresses.commerce_read_service",
    "domains.accounts.services.commerce_write_service": "domains.accounts.services.addresses.commerce_write_service",
    "domains.accounts.services.customer_router_service": "domains.accounts.services.addresses.customer_router_service",
    "domains.accounts.services.auth_service": "domains.accounts.services.auth.auth_service",
    "domains.accounts.services.otp_service": "domains.accounts.services.auth.otp_service",
    "domains.accounts.services.session_service": "domains.accounts.services.auth.session_service",
    "domains.accounts.services.social_service": "domains.accounts.services.auth.social_service",
    "domains.accounts.services.iam_service": "domains.accounts.services.iam.iam_service",
    "domains.accounts.services.identity_service": "domains.accounts.services.identity.identity_service",
    "domains.accounts.services.identity_admin_service": "domains.accounts.services.identity.identity_admin_service",
    "domains.accounts.services.permissions_service": "domains.accounts.services.permissions.permissions_service",
    "domains.accounts.services.rbac_service": "domains.accounts.services.permissions.rbac_service",
    "domains.accounts.services.users_service": "domains.accounts.services.users.users_service",
    "domains.accounts.services.users_write_service": "domains.accounts.services.users.users_write_service",
    "domains.accounts.services.user_read_service": "domains.accounts.services.users.user_read_service",
    "domains.accounts.services.user_write_ops": "domains.accounts.services.users.user_write_ops",
    "domains.accounts.services.export_service": "domains.accounts.services.export.service",
    "domains.accounts.services.export_controller": "domains.accounts.services.export.controller",
    "domains.accounts.services.employees_service": "domains.hr.services.employees.employees_service",
    "domains.accounts.services.hr_service": "domains.hr.services.core.service",
    "domains.accounts.services.logistics_service": "domains.logistics.services.shipping.logistics_service",
    "domains.accounts.services.logistics_controller": "domains.logistics.services.shipping.logistics_controller",
    "domains.accounts.services.logistics_controller__routers": "domains.logistics.services.shipping.logistics_controller__routers",
    "domains.accounts.services.logistics_partner_service": "domains.logistics.services.partners.logistics_partner_service",
    "domains.accounts.services.shipments_service": "domains.logistics.services.shipping.shipments_service",
    "domains.accounts.services.supplier_documents_service": "domains.suppliers.services.documents.supplier_documents_service",
    "domains.accounts.services.wishlist_service": "domains.customers.services.wishlist.wishlist_service",
    "domains.accounts.services.customer_coupons_create_service": "domains.promotions.services.coupons.customer_coupons_create_service",
    "domains.accounts.services.customer_coupons_mgmt_service": "domains.promotions.services.coupons.customer_coupons_mgmt_service",
    "domains.accounts.services.customer_health_service": "domains.customers.services.health.service",
    "domains.accounts.services.customer_health_list_service": "domains.customers.services.health.list_service",
    "domains.accounts.services.banners_service": "domains.promotions.services.banners.banners_service",
    "domains.accounts.services.categories_service": "domains.catalog.services.categories.categories_service",
    "domains.accounts.services.search_service": "domains.catalog.services.search.search_service",
    "domains.accounts.services.country_dropdown_service": "domains.country.services.geo.country_dropdown_service",
    "domains.accounts.services.country_maps_service": "domains.country.services.geo.country_maps_service",
    "domains.accounts.services.country_payouts_service": "domains.country.services.payouts.country_payouts_service",
    "domains.accounts.services.country_staff_service": "domains.country.services.staff.country_staff_service",
    "domains.accounts.services.translation_service": "domains.country.services.localization.translation_service",
    "domains.accounts.services.translate_controller": "domains.country.services.localization.translate_controller",
    "domains.accounts.services.supplier_finance_service": "domains.finance.services.supplier_finance_service",
    "domains.accounts.services.supplier_payouts_service": "domains.finance.services.payouts.supplier_payouts_service",
    "domains.accounts.services.commission_service": "domains.finance.services.commissions.commission_service",
    "domains.accounts.services.payroll_service": "domains.hr.services.payroll.payroll_service",
    "domains.accounts.services.performance_service": "domains.hr.services.performance.service",
    "domains.accounts.services.hierarchy_service": "domains.hr.services.hierarchy.service",
    "domains.accounts.services.ess_service": "domains.hr.services.ess.ess_service",
    "domains.accounts.services.background_check": "domains.hr.services.compliance.background_check",
    "domains.accounts.services.coi_service": "domains.hr.services.compliance.coi_service",
    "domains.accounts.services.coi_engine": "domains.hr.services.compliance.coi_engine",

    # Governance domain
    "domains.governance.services.orders_service": "domains.governance.services.orders.orders_service",
    "domains.governance.services.flat_orders_service": "domains.governance.services.orders.flat_orders_service",
    "domains.governance.services.products_service": "domains.governance.services.catalog.products_service",
    "domains.governance.services.flat_products_service": "domains.governance.services.catalog.flat_products_service",
    "domains.governance.services.suppliers_service": "domains.governance.services.suppliers.suppliers_service",
    "domains.governance.services.suppliers_controller": "domains.governance.services.suppliers.suppliers_controller",
    "domains.governance.services.country_service": "domains.country.services.country_service",
    "domains.governance.services.country_controller": "domains.country.services.country_controller",
    "domains.governance.services.fraud_service": "domains.governance.services.fraud.service",
    "domains.governance.services.fraud_detection": "domains.governance.services.fraud.detection",
    "domains.governance.services.payouts_service": "domains.governance.services.finance.payouts_service",
    "domains.governance.services.payouts_controller": "domains.governance.services.finance.payouts_controller",
    "domains.governance.services.admin_finance_service": "domains.governance.services.finance.admin_finance_service",

    # Logistics domain
    "domains.logistics.services.logistics_service": "domains.logistics.services.shipping.logistics_service",
    "domains.logistics.services.logistics_controller": "domains.logistics.services.shipping.logistics_controller",
    "domains.logistics.services.logistics_controller__routers": "domains.logistics.services.shipping.logistics_controller__routers",
    "domains.logistics.services.logistics_partner_controller": "domains.logistics.services.partners.logistics_partner_controller",
    "domains.logistics.services.logistics_partner_controller__routers": "domains.logistics.services.partners.logistics_partner_controller__routers",
    "domains.logistics.services.logistics_partner_service": "domains.logistics.services.partners.logistics_partner_service",
    "domains.logistics.services.logistics_partner_pricing": "domains.logistics.services.partners.logistics_partner_pricing",
    "domains.logistics.services.logistics_partner_write_service": "domains.logistics.services.partners.logistics_partner_write_service",
    "domains.logistics.services.logistics_partner_verify_service": "domains.logistics.services.partners.logistics_partner_verify_service",
    "domains.logistics.services.logistics_partner_shipments_service": "domains.logistics.services.partners.logistics_partner_shipments_service",
    "domains.logistics.services.partner_geography_service": "domains.logistics.services.partners.partner_geography_service",
    "domains.logistics.services.fulfillment_service": "domains.logistics.services.fulfillment.fulfillment_service",
    "domains.logistics.services.shipping_tier": "domains.logistics.services.shipments.shipping_tier",
    "domains.logistics.services.logistics_shipping_tier": "domains.logistics.services.shipments.logistics_shipping_tier",
    "domains.logistics.services.shipment_service": "domains.logistics.services.shipments.shipments_service",
    "domains.logistics.services.live_tracking_service": "domains.logistics.services.operations.live_tracking_service",
    "domains.logistics.services.logistics_controller": "domains.logistics.services.operations.logistics_controller",
    "domains.logistics.services.logistics_controller__routers": "domains.logistics.services.operations.logistics_controller__routers",
    "domains.logistics.services.logistics_engine": "domains.logistics.services.operations.logistics_engine",
    "domains.logistics.services.logistics_sla_service": "domains.logistics.services.operations.logistics_sla_service",
    "domains.logistics.services.logistics_write_service": "domains.logistics.services.operations.logistics_write_service",
    "domains.logistics.services.logistics_health_service": "domains.logistics.services.health.logistics_health_service",
    "domains.logistics.services.logistics_health_engine": "domains.logistics.services.health.logistics_health_engine",
    "domains.logistics.services.logistics_health_list_service": "domains.logistics.services.health.logistics_health_list_service",
    "domains.logistics.services.geo_fence_service": "domains.logistics.services.geo.geo_fence_service",
    "domains.logistics.services.geo_resolver": "domains.logistics.services.geo.geo_resolver",
    "domains.logistics.services.geo_service": "domains.logistics.services.geo.geo_service",
    "domains.logistics.services.map_service": "domains.logistics.services.geo.map_service",
    "domains.logistics.services.logistics_locations_service": "domains.logistics.services.geo.logistics_locations_service",
    "domains.logistics.services.logistics_orders_list_service": "domains.orders.services.tracking.logistics_orders_list_service",
    "domains.logistics.services.logistics_orders_v2_service": "domains.orders.services.tracking.logistics_orders_v2_service",
    "domains.logistics.services.country_communication_service": "domains.country.services.comms.country_communication_service",

    # Suppliers domain
    "domains.suppliers.services.supplier_service": "domains.suppliers.services.profile.supplier_service",
    "domains.suppliers.services.supplier_profile_service": "domains.suppliers.services.profile.supplier_profile_service",
    "domains.suppliers.services.supplier_profile_create_service": "domains.suppliers.services.profile.supplier_profile_create_service",
    "domains.suppliers.services.supplier_profile_write_service": "domains.suppliers.services.profile.supplier_profile_write_service",
    "domains.suppliers.services.supplier_products_service": "domains.suppliers.services.products.supplier_products_service",
    "domains.suppliers.services.supplier_products_upload_service": "domains.suppliers.services.products.supplier_products_upload_service",
    "domains.suppliers.services.supplier_documents_service": "domains.suppliers.services.documents.supplier_documents_service",
    "domains.suppliers.services.supplier_document_service": "domains.suppliers.services.documents.supplier_document_service",
    "domains.suppliers.services.supplier_document_controller_service": "domains.suppliers.services.documents.supplier_document_controller_service",
    "domains.suppliers.services.supplier_onboarding_service": "domains.suppliers.services.onboarding.supplier_onboarding_service",
    "domains.suppliers.services.supplier_order_service": "domains.suppliers.services.orders.supplier_order_service",
    "domains.suppliers.services.supplier_orders_service": "domains.suppliers.services.orders.supplier_orders_service",
    "domains.suppliers.services.supplier_orders_verify_service": "domains.suppliers.services.orders.supplier_orders_verify_service",
    "domains.suppliers.services.supplier_health_service": "domains.suppliers.services.health.supplier_health_service",
    "domains.suppliers.services.supplier_health_controller": "domains.suppliers.services.health.supplier_health_controller",
    "domains.suppliers.services.supplier_health_engine": "domains.suppliers.services.health.supplier_health_engine",
    "domains.suppliers.services.supplier_badge_service": "domains.suppliers.services.badges.supplier_badge_service",
    "domains.suppliers.services.supplier_badge_write_service": "domains.suppliers.services.badges.supplier_badge_write_service",
    "domains.suppliers.services.supplier_legal_contract_service": "domains.suppliers.services.contracts.supplier_legal_contract_service",
    "domains.suppliers.services.supplier_finance_service": "domains.suppliers.services.finance.supplier_finance_service",
    "domains.suppliers.services.supplier_payout_service": "domains.suppliers.services.finance.supplier_payout_service",
    "domains.suppliers.services.supplier_payouts_service": "domains.suppliers.services.finance.supplier_payouts_service",
    "domains.suppliers.services.badge_billing_payment": "domains.suppliers.services.badges.badge_billing_payment",
    "domains.suppliers.services.legal_contract_service": "domains.suppliers.services.contracts.legal_contract_service",
    "domains.suppliers.services.onboarding_pipeline": "domains.suppliers.services.onboarding.onboarding_pipeline",
    "domains.suppliers.services.suppliers_service": "domains.suppliers.services.core.suppliers_service",
    "domains.suppliers.services.suppliers_controller": "domains.suppliers.services.core.suppliers_controller",
    "domains.suppliers.services.suppliers_write_service": "domains.suppliers.services.core.suppliers_write_service",

    # Customers domain
    "domains.customers.services.customer_health_service": "domains.customers.services.health.customer_health_service",
    "domains.customers.services.customer_health_list_service": "domains.customers.services.health.customer_health_list_service",
    "domains.customers.services.customer_health_engine": "domains.customers.services.health.customer_health_engine",
    "domains.customers.services.referrals_service": "domains.customers.services.referrals.referrals_service",
    "domains.customers.services.referrals_controller": "domains.customers.services.referrals.referrals_controller",
    "domains.customers.services.referrals_controller__routers": "domains.customers.services.referrals.referrals_controller__routers",
    "domains.customers.services.reviews_service": "domains.customers.services.reviews.reviews_service",
    "domains.customers.services.reviews_controller": "domains.customers.services.reviews.reviews_controller",
    "domains.customers.services.reviews_controller__routers": "domains.customers.services.reviews.reviews_controller__routers",
    "domains.customers.services.wishlist_service": "domains.customers.services.wishlist.wishlist_service",
    "domains.customers.services.wishlist_read_service": "domains.customers.services.wishlist.wishlist_read_service",
    "domains.customers.services.wishlist_write_service": "domains.customers.services.wishlist.wishlist_write_service",
    "domains.customers.services.wishlist_controller": "domains.customers.services.wishlist.wishlist_controller",
    "domains.customers.services.wishlist_controller__routers": "domains.customers.services.wishlist.wishlist_controller__routers",
    "domains.customers.services.cart_service": "domains.orders.services.cart.cart_service",
    "domains.customers.services.cart_write_service": "domains.orders.services.cart.cart_write_service",
    "domains.customers.services.commerce_read_service": "domains.accounts.services.addresses.commerce_read_service",
    "domains.customers.services.commerce_write_service": "domains.accounts.services.addresses.commerce_write_service",
    "domains.customers.services.coupons_service": "domains.promotions.services.coupons.coupons_service",
    "domains.customers.services.coupons_read_service": "domains.promotions.services.coupons.coupons_read_service",
    "domains.customers.services.coupons_write_service": "domains.promotions.services.coupons.coupons_write_service",
    "domains.customers.services.customer_coupons_create_service": "domains.promotions.services.coupons.customer_coupons_create_service",
    "domains.customers.services.customer_coupons_mgmt_service": "domains.promotions.services.coupons.customer_coupons_mgmt_service",
    "domains.customers.services.search_service": "domains.catalog.services.search.search_service",
    "domains.customers.services.user_read_service": "domains.accounts.services.users.user_read_service",
    "domains.customers.services.customer_router_service": "domains.accounts.services.addresses.customer_router_service",

    # Country domain
    "domains.country.services.country_service": "domains.country.services.core.country_service",
    "domains.country.services.country_controller": "domains.country.services.core.country_controller",
    "domains.country.services.country_read_service": "domains.country.services.core.country_read_service",
    "domains.country.services.country_write_service": "domains.country.services.core.country_write_service",
    "domains.country.services.country_admin_service": "domains.country.services.staff.country_admin_service",
    "domains.country.services.country_admin_write_service": "domains.country.services.staff.country_admin_write_service",
    "domains.country.services.country_staff_service": "domains.country.services.staff.country_staff_service",
    "domains.country.services.country_staff_write_service": "domains.country.services.staff.country_staff_write_service",
    "domains.country.services.country_context_service": "domains.country.services.core.country_context_service",
    "domains.country.services.country_config_admin_service": "domains.country.services.core.country_config_admin_service",
    "domains.country.services.country_config_write_service": "domains.country.services.core.country_config_write_service",
    "domains.country.services.countries_service": "domains.country.services.core.countries_service",
    "domains.country.services.country_payouts_service": "domains.country.services.payouts.country_payouts_service",
    "domains.country.services.country_payout_write_service": "domains.country.services.payouts.country_payout_write_service",
    "domains.country.services.country_dropdown_service": "domains.country.services.geo.country_dropdown_service",
    "domains.country.services.country_maps_service": "domains.country.services.geo.country_maps_service",
    "domains.country.services.country_detection": "domains.country.services.geo.country_detection",
    "domains.country.services.localization_service": "domains.country.services.localization.localization_service",
    "domains.country.services.translation_service": "domains.country.services.localization.translation_service",
    "domains.country.services.translate_controller": "domains.country.services.localization.translate_controller",
    "domains.country.services.country_tax_service": "domains.country.services.tax.country_tax_service",
    "domains.country.services.category_tax_profiles": "domains.country.services.tax.category_tax_profiles",
    "domains.country.services.country_restriction_service": "domains.country.services.restriction.country_restriction_service",
    "domains.country.services.country_research": "domains.country.services.research.country_research",
    "domains.country.services.country_auto_populate": "domains.country.services.research.country_auto_populate",
    "domains.country.services.country_auto_populate_write_service": "domains.country.services.research.country_auto_populate_write_service",
    "domains.country.services.country_curated": "domains.country.services.research.country_curated",
    "domains.country.services.country_data_orchestrator": "domains.country.services.research.country_data_orchestrator",
    "domains.country.services.country_heuristic_engine": "domains.country.services.research.country_heuristic_engine",
    "domains.country.services.curated_cities": "domains.country.services.research.curated_cities",
    "domains.country.services.country_ai_research": "domains.country.services.research.country_ai_research",
    "domains.country.services.country_versioning_service": "domains.country.services.versioning.country_versioning_service",
    "domains.country.services.country_versioning_controller": "domains.country.services.versioning.country_versioning_controller",
    "domains.country.services.cross_border_service": "domains.country.services.cross_border.cross_border_service",
    "domains.country.services.cross_border_base": "domains.country.services.cross_border.cross_border_base",
    "domains.country.services.cross_border_detection": "domains.country.services.cross_border.cross_border_detection",
    "domains.country.services.cross_border_tracker": "domains.country.services.cross_border.cross_border_tracker",
    "domains.country.services.country_communication_service": "domains.country.services.comms.country_communication_service",
    "domains.country.services.country_communications_service": "domains.country.services.comms.country_communications_service",
    "domains.country.services.country_communications_read_service": "domains.country.services.comms.country_communications_read_service",
    "domains.country.services.supplier_finance_service": "domains.finance.services.supplier_finance_service",
    "domains.country.services.supplier_payouts_service": "domains.finance.services.payouts.supplier_payouts_service",
    "domains.country.services.admin_cash_service": "domains.governance.services.finance.admin_cash_service",
    "domains.country.services.admin_commission_service": "domains.country.services.admin_commission_service",
    "domains.country.services.admin_commerce_configuration_service": "domains.country.services.admin_commerce_configuration_service",
    "domains.country.services.admin_commerce_geography_service": "domains.country.services.admin_commerce_geography_service",
    "domains.country.services.admin_geography_audit_service": "domains.country.services.admin_geography_audit_service",
    "domains.country.services.admin_geography_configuration_service": "domains.country.services.admin_geography_configuration_service",
    "domains.country.services.admin_logistics_fallback_read_service": "domains.country.services.admin_logistics_fallback_read_service",
    "domains.country.services.country_admin_service": "domains.country.services.country_admin_service",
    "domains.country.services.flat_admin_commerce_configuration_service": "domains.country.services.flat_admin_commerce_configuration_service",
    "domains.country.services.flat_admin_commerce_geography_service": "domains.country.services.flat_admin_commerce_geography_service",
    "domains.country.services.flat_admin_geography_audit_service": "domains.country.services.flat_admin_geography_audit_service",
    "domains.country.services.flat_admin_geography_configuration_service": "domains.country.services.flat_admin_geography_configuration_service",
    "domains.country.services.flat_country_admin_service": "domains.country.services.flat_country_admin_service",
    "domains.country.services.public_commerce_validation_service": "domains.country.services.public_commerce_validation_service",
    "domains.country.services.flat_public_commerce_validation_service": "domains.country.services.flat_public_commerce_validation_service",

    # Finance domain
    "domains.finance.services.finance.py": "domains.finance.services.core.service",
    "domains.finance.services.treasury.py": "domains.finance.services.treasury.core",
    "domains.finance.services.treasury": "domains.finance.services.treasury.core",
    "domains.finance.services.treasury_service": "domains.finance.services.treasury.treasury_service",
    "domains.finance.services.treasury_engine": "domains.finance.services.treasury.treasury_engine",
    "domains.finance.services.treasury_adapter": "domains.finance.services.treasury.treasury_adapter",
    "domains.finance.services.treasury_query_service": "domains.finance.services.treasury.treasury_query_service",
    "domains.finance.services.treasury_router_service": "domains.finance.services.treasury.treasury_router_service",
    "domains.finance.services.cash_management_service": "domains.finance.services.treasury.cash_management_service",
    "domains.finance.services.cash_management_controller": "domains.finance.services.treasury.cash_management_controller",
    "domains.finance.services.cash_management_write_service": "domains.finance.services.treasury.cash_management_write_service",
    "domains.finance.services.cash_flow_forecast_service": "domains.finance.services.treasury.cash_flow_forecast_service",
    "domains.finance.services.payments": "domains.finance.services.payments.payments",
    "domains.finance.services.payments.py": "domains.finance.services.payments.payments",
    "domains.finance.services.payment_engine": "domains.finance.services.payments.payment_engine",
    "domains.finance.services.payment_orchestrator": "domains.finance.services.payments.payment_orchestrator",
    "domains.finance.services.payment_event_handlers": "domains.finance.services.payments.payment_event_handlers",
    "domains.finance.services.gateway_reconciliation_service": "domains.finance.services.payments.gateway_reconciliation_service",
    "domains.finance.services.gateway_auto_enable": "domains.finance.services.payments.gateway_auto_enable",
    "domains.finance.services.payout_engine": "domains.finance.services.payouts.payout_engine",
    "domains.finance.services.payout_batch_service": "domains.finance.services.payouts.payout_batch_service",
    "domains.finance.services.payout_dispatch_service": "domains.finance.services.payouts.payout_dispatch_service",
    "domains.finance.services.payout_read_service": "domains.finance.services.payouts.payout_read_service",
    "domains.finance.services.payout_status_service": "domains.finance.services.payouts.payout_status_service",
    "domains.finance.services.payout_admin_service": "domains.finance.services.payouts.payout_admin_service",
    "domains.finance.services.payout_admin_write_service": "domains.finance.services.payouts.payout_admin_write_service",
    "domains.finance.services.payout_approval_controller": "domains.finance.services.payouts.payout_approval_controller",
    "domains.finance.services.payout_approval_read_service": "domains.finance.services.payouts.payout_approval_read_service",
    "domains.finance.services.payout_approval_service": "domains.finance.services.payouts.payout_approval_service",
    "domains.finance.services.payout_approval_write_service": "domains.finance.services.payouts.payout_approval_write_service",
    "domains.finance.services.commission_service": "domains.finance.services.commissions.commission_service",
    "domains.finance.services.commission_controller": "domains.finance.services.commissions.commission_controller",
    "domains.finance.services.commission_engine": "domains.finance.services.commissions.commission_engine",
    "domains.finance.services.commission_geography_service": "domains.finance.services.commissions.commission_geography_service",
    "domains.finance.services.commission_write_service": "domains.finance.services.commissions.commission_write_service",
    "domains.finance.services.commission_admin_write_service": "domains.finance.services.commissions.commission_admin_write_service",
    "domains.finance.services.general_ledger_service": "domains.finance.services.ledger.general_ledger_service",
    "domains.finance.services.sub_ledger_service": "domains.finance.services.ledger.sub_ledger_service",
    "domains.finance.services.sub_ledger_controller": "domains.finance.services.ledger.sub_ledger_controller",
    "domains.finance.services.accounting_controller": "domains.finance.services.ledger.accounting_controller",
    "domains.finance.services.invoice_service": "domains.finance.services.ledger.invoice_service",
    "domains.finance.services.invoice_controller": "domains.finance.services.ledger.invoice_controller",
    "domains.finance.services.invoice_write_service": "domains.finance.services.ledger.invoice_write_service",
    "domains.finance.services.je_reversal_service": "domains.finance.services.ledger.je_reversal_service",
    "domains.finance.services.period_close_service": "domains.finance.services.ledger.period_close_service",
    "domains.finance.services.tax_service": "domains.finance.services.tax.tax_service",
    "domains.finance.services.vat_rates": "domains.finance.services.tax.vat_rates",
    "domains.finance.services.financial_reporting": "domains.finance.services.reporting.financial_reporting",
    "domains.finance.services.financial_reports_service": "domains.finance.services.reporting.financial_reports_service",
    "domains.finance.services.finance_dashboard_service": "domains.finance.services.reporting.finance_dashboard_service",
    "domains.finance.services.reporting_service": "domains.finance.services.reporting.reporting_service",
    "domains.finance.services.admin_reporting_service": "domains.finance.services.reporting.admin_reporting_service",
    "domains.finance.services.supplier_finance_service": "domains.finance.services.supplier_finance_service",
    "domains.finance.services.supplier_payout_service": "domains.finance.services.payouts.supplier_payout_service",
    "domains.finance.services.supplier_payouts_service": "domains.finance.services.payouts.supplier_payouts_service",
    "domains.finance.services.public_finance_creation_service": "domains.finance.services.creation.public_finance_creation_service",
    "domains.finance.services.flat_public_finance_creation_service": "domains.finance.services.creation.flat_public_finance_creation_service",
    "domains.finance.services.flat_admin_finance_creation_service": "domains.finance.services.creation.flat_admin_finance_creation_service",
    "domains.finance.services.flat_admin_finance_geography_service": "domains.finance.services.creation.flat_admin_finance_geography_service",

    # Security domain
    "domains.security.services.security_dependencies": "domains.security.services.core.dependencies",
    "domains.security.services.iam_service__security": "domains.security.services.iam.service",
    "domains.security.services.security_auth_write_service": "domains.security.services.iam.auth_write_service",
    "domains.security.services.fraud_service": "domains.security.services.fraud.service",
    "domains.security.services.fraud_detection": "domains.security.services.fraud.detection",
    "domains.security.services.fraud_detection_service": "domains.security.services.fraud.detection_service",
    "domains.security.services.fraud_engine": "domains.security.services.fraud.engine",
    "domains.security.services.fraud_admin_service": "domains.security.services.fraud.admin_service",
    "domains.security.services.fraud_admin_controller_service": "domains.security.services.fraud.admin_controller_service",
    "domains.security.services.security_fraud_admin_service": "domains.security.services.fraud.security_admin_service",
    "domains.security.services.flat_fraud_engine": "domains.security.services.fraud.flat_engine",
    "domains.security.services.flat_security_fraud_admin_service": "domains.security.services.fraud.flat_admin_service",
    "domains.security.services.public_security_detection_service": "domains.security.services.threat.detection_service",
    "domains.security.services.public_security_health_service": "domains.security.services.threat.health_service",
    "domains.security.services.public_security_operations_service": "domains.security.services.threat.operations_service",
    "domains.security.services.public_security_registration_service": "domains.security.services.threat.registration_service",
    "domains.security.services.admin_security_detection_service": "domains.security.services.threat.admin_detection_service",
    "domains.security.services.admin_security_health_service": "domains.security.services.threat.admin_health_service",
    "domains.security.services.admin_security_operations_service": "domains.security.services.threat.admin_operations_service",
    "domains.security.services.admin_security_registration_service": "domains.security.services.threat.admin_registration_service",
    "domains.security.services.flat_admin_security_health_service": "domains.security.services.threat.flat_admin_health_service",
    "domains.security.services.flat_admin_security_operations_service": "domains.security.services.threat.flat_admin_operations_service",
    "domains.security.services.flat_admin_security_registration_service": "domains.security.services.threat.flat_admin_registration_service",
    "domains.security.services.behavioral_analytics": "domains.security.services.threat.behavioral_analytics",
    "domains.security.services.confidence_scoring": "domains.security.services.threat.confidence_scoring",
    "domains.security.services.impossible_travel_write_service": "domains.security.services.threat.impossible_travel",
    "domains.security.services.siem_engine": "domains.security.services.threat.siem_engine",
    "domains.security.services.external_contact": "domains.security.services.comms.external_contact",
    "domains.security.services.proxy_communication": "domains.security.services.comms.proxy_communication",
    "domains.security.services.qr_service": "domains.security.services.comms.qr_service",
    "domains.security.services.public_commerce_validation_service": "domains.security.services.validation.commerce",
    "domains.security.services.ess_service": "domains.security.services.ess.service",

    # Analytics domain
    "domains.analytics.services.analytics_service": "domains.analytics.services.core.service",
    "domains.analytics.services.analytics_controller": "domains.analytics.services.core.controller",
    "domains.analytics.services.analytics_fallback_service": "domains.analytics.services.core.fallback_service",
    "domains.analytics.services.analytics_service__analytics": "domains.analytics.services.core.legacy_service",
    "domains.analytics.services.flat_analytics_service": "domains.analytics.services.core.flat_service",
    "domains.analytics.services.flat_analytics_fallback_service": "domains.analytics.services.core.flat_fallback_service",
    "domains.analytics.services.flat_analytics_service__analytics": "domains.analytics.services.core.flat_legacy_service",
    "domains.analytics.services.admin_analytics_service": "domains.analytics.services.admin.service",
    "domains.analytics.services.admin_dashboard_service": "domains.analytics.services.admin.dashboard_service",
    "domains.analytics.services.flat_admin_analytics_service": "domains.analytics.services.admin.flat_service",
    "domains.analytics.services.flat_admin_dashboard_service": "domains.analytics.services.admin.flat_dashboard_service",
    "domains.analytics.services.command_center_service": "domains.analytics.services.command_center.service",
    "domains.analytics.services.command_center_query_service": "domains.analytics.services.command_center.query_service",
    "domains.analytics.services.command_center_background": "domains.analytics.services.command_center.background",

    # Audit domain
    "domains.audit.services.audit_service": "domains.audit.services.core.service",
    "domains.audit.services.audit_query_service": "domains.audit.services.core.query_service",
    "domains.audit.services.audit_trail_service": "domains.audit.services.core.trail_service",
    "domains.audit.services.compliance_engine": "domains.audit.services.compliance.engine",
    "domains.audit.services.ediscovery": "domains.audit.services.compliance.ediscovery",
    "domains.audit.services.retention_service": "domains.audit.services.compliance.retention_service",
    "domains.audit.services.worm_audit": "domains.audit.services.compliance.worm",
    "domains.audit.services.data_residency": "domains.audit.services.data.residency",
    "domains.audit.services.data_residency_service": "domains.audit.services.data.residency_service",
    "domains.audit.services.flat_data_residency_service": "domains.audit.services.data.flat_residency_service",

    # Comms domain
    "domains.comms.services.comms_unified_service": "domains.comms.services.unified.service",
    "domains.comms.services.entity_messaging": "domains.comms.services.messaging.entity",
    "domains.comms.services.internal_channels_service": "domains.comms.services.channel.internal",
    "domains.comms.services.public_comms_status_service": "domains.comms.services.status.public",
    "domains.comms.services.public_comms_unified_service": "domains.comms.services.status.public_unified",
    "domains.comms.services.system_comms_status_service": "domains.comms.services.status.system",
    "domains.comms.services.admin_comms_geography_service": "domains.comms.services.admin.geography",
    "domains.comms.services.admin_comms_unified_service": "domains.comms.services.admin.unified",
    "domains.comms.services.chat_enrichment_service": "domains.comms.services.messaging.chat_enrichment",
    "domains.comms.services.flat_admin_comms_geography_service": "domains.comms.services.admin.flat_geography",
    "domains.comms.services.chat_service": "domains.comms.services.messaging.chat.service",
    "domains.comms.services.chat_read_service": "domains.comms.services.messaging.chat.read_service",
    "domains.comms.services.chat_write_service": "domains.comms.services.messaging.chat.write_service",
    "domains.comms.services.chat_write_controller": "domains.comms.services.messaging.chat.write_controller",
    "domains.comms.services.chatbot_service": "domains.comms.services.autobot.chatbot_service",
    "domains.comms.services.chatbot_controller": "domains.comms.services.autobot.chatbot_controller",
    "domains.comms.services.chatbot_controller__routers": "domains.comms.services.autobot.chatbot_controller__routers",
    "domains.comms.services.email_service": "domains.comms.services.email.service",
    "domains.comms.services.email_gateway": "domains.comms.services.email.email_gateway",
    "domains.comms.services.email_management_service": "domains.comms.services.email.email_management_service",
    "domains.comms.services.email_write_service": "domains.comms.services.email.email_write_service",
    "domains.comms.services.email_event_service": "domains.comms.services.email.email_event_service",
    "domains.comms.services.email_enrichment": "domains.comms.services.email.email_enrichment",
    "domains.comms.services.email_reputation": "domains.comms.services.email.email_reputation",
    "domains.comms.services.transactional_email": "domains.comms.services.email.transactional_email",
    "domains.comms.services.transactional_email_service": "domains.comms.services.email.transactional_email_service",
    "domains.comms.services.tickets_service": "domains.comms.services.tickets.service",
    "domains.comms.services.tickets_write_service": "domains.comms.services.tickets.write_service",
    "domains.comms.services.tickets_controller": "domains.comms.services.tickets.controller",
    "domains.comms.services.notification_service": "domains.comms.services.notification.service",
    "domains.comms.services.push_notifications_service": "domains.comms.services.notification.push_service",
    "domains.comms.services.video_service": "domains.comms.services.video.service",
    "domains.comms.services.video_conferencing": "domains.comms.services.video.conferencing",
    "domains.comms.services.video_room_service": "domains.comms.services.video.room_service",
    "domains.comms.services.video_room_write_service": "domains.comms.services.video.room_write_service",
    "domains.comms.services.whatsapp_service": "domains.comms.services.marketing.whatsapp_service",
    "domains.comms.services.campaign_geography_service": "domains.comms.services.marketing.campaign_geography_service",

    # Promotions domain
    "domains.promotions.services.promotion_service": "domains.promotions.services.core.service",
    "domains.promotions.services.promotion_controller": "domains.promotions.services.core.controller",
    "domains.promotions.services.promotion_controller__routers": "domains.promotions.services.core.controller__routers",
    "domains.promotions.services.promotion_admin_controller": "domains.promotions.services.admin.controller",
    "domains.promotions.services.promotion_admin_controller__routers": "domains.promotions.services.admin.controller__routers",
    "domains.promotions.services.promotion_admin_write_service": "domains.promotions.services.admin.write_service",
    "domains.promotions.services.promotion_engine_service": "domains.promotions.services.core.engine",
    "domains.promotions.services.promotions_write_service": "domains.promotions.services.core.write_service",
    "domains.promotions.services.coupons_service": "domains.promotions.services.coupons.service",
    "domains.promotions.services.coupons_read_service": "domains.promotions.services.coupons.read_service",
    "domains.promotions.services.coupons_write_service": "domains.promotions.services.coupons.write_service",
    "domains.promotions.services.coupons_controller": "domains.promotions.services.coupons.controller",
    "domains.promotions.services.coupons_controller__routers": "domains.promotions.services.coupons.controller__routers",
    "domains.promotions.services.commerce_coupons_read_service": "domains.promotions.services.coupons.commerce_read",
    "domains.promotions.services.commerce_coupons_write_service": "domains.promotions.services.coupons.commerce_write",
    "domains.promotions.services.customer_coupons_create_service": "domains.promotions.services.coupons.customer_create",
    "domains.promotions.services.customer_coupons_mgmt_service": "domains.promotions.services.coupons.customer_mgmt",
    "domains.promotions.services.coupons_legacy_write_service": "domains.promotions.services.coupons.legacy_write",
    "domains.promotions.services.bogo_service": "domains.promotions.services.bogo.service",
    "domains.promotions.services.promotion_bogo_service": "domains.promotions.services.bogo.service",
    "domains.promotions.services.points_service": "domains.promotions.services.coins.points",
    "domains.promotions.services.promotion_points_service": "domains.promotions.services.coins.promotion_points",
    "domains.promotions.services.coin_service": "domains.promotions.services.coins.coin",
    "domains.promotions.services.banner_service": "domains.promotions.services.banners.service",
    "domains.promotions.services.banner_write_service": "domains.promotions.services.banners.write_service",
    "domains.promotions.services.banner_controller": "domains.promotions.services.banners.controller",
    "domains.promotions.services.banner_controller__routers": "domains.promotions.services.banners.controller__routers",
    "domains.promotions.services.banners_service": "domains.promotions.services.banners.banners",
    "domains.promotions.services.admin_promotions_write_service": "domains.promotions.services.admin.promotions_write",
    "domains.promotions.services.admin_promotions_service": "domains.promotions.services.admin.promotions",
    "domains.promotions.services.admin_promotions_routes_service": "domains.promotions.services.admin.promotions_routes",
}


def update_imports_in_file(filepath: str) -> int:
    """Update imports in a single file. Returns number of changes made."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
    except (UnicodeDecodeError, IOError):
        return 0

    original_content = content
    changes = 0

    # Update "from X import Y" statements
    for old_import, new_import in IMPORT_MAPPINGS.items():
        # Match "from old_import import ..."
        pattern = rf'^{re.escape(old_import)}\b'
        if re.search(pattern, content, re.MULTILINE):
            content = re.sub(pattern, new_import, content, flags=re.MULTILINE)
            changes += 1

    # Also handle "import X" statements
    for old_import, new_import in IMPORT_MAPPINGS.items():
        # Convert "from X import Y" to "import X" format
        old_module = old_import.replace("from ", "").replace(" import ", ".")
        new_module = new_import.replace("from ", "").replace(" import ", ".")
        pattern = rf'^{re.escape(old_module)}\b'
        if re.search(pattern, content, re.MULTILINE):
            content = re.sub(pattern, new_module, content, flags=re.MULTILINE)
            changes += 1

    if content != original_content:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

    return changes


def main():
    backend_dir = Path("backend")
    total_changes = 0
    files_changed = 0

    # Find all Python files
    for py_file in backend_dir.rglob("*.py"):
        if "__pycache__" in str(py_file):
            continue
        changes = update_imports_in_file(str(py_file))
        if changes > 0:
            total_changes += changes
            files_changed += 1
            print(f"Updated {changes} imports in {py_file}")

    print(f"\nTotal: {total_changes} imports updated in {files_changed} files")


if __name__ == "__main__":
    main()
