import json
import os

findings = [
    {
        "id": "CONTR-001",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/modules/logistics/routers/logistics.py",
        "line": "21,54",
        "current": "Doc declares singular prefix; every backend router and frontend page uses plural `logistics-partners`",
        "target": "/logistics-partners/* as implemented in backend routers and frontend pages",
        "fix": "Update `ARCHITECTURE_STACK.md` to `/logistics-partners/*` to match implemented contract",
        "effort": "S",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-002",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/domains/",
        "line": "",
        "current": "Architecture claims exactly 15 canonical domains; source tree has 17 domain packages",
        "target": "15 canonical domains as documented in ARCHITECTURE_STACK.md",
        "fix": "Either fold `payments` back into `finance` and remove `media`, or update architecture doc to 17-domain list with migration plans",
        "effort": "M",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-003",
        "dimension": "21_contradictions",
        "phase": "security",
        "status": "NEW",
        "file": "backend/requirements.txt",
        "line": "19",
        "current": "Canonical cache client is Valkey, yet `requirements.txt` still pins the Redis Python package",
        "target": "Only Valkey declared in requirements.txt; Redis absent",
        "fix": "Remove `redis==8.0.1` from `requirements.txt` and ensure only `valkey` is declared",
        "effort": "S",
        "priority": "P0",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-004",
        "dimension": "21_contradictions",
        "phase": "security",
        "status": "NEW",
        "file": "backend/requirements.txt",
        "line": "34",
        "current": "Avoid-list explicitly forbids `requests`, but it remains a pinned dependency",
        "target": "No `requests` package in requirements.txt; httpx used instead",
        "fix": "Remove `requests` from `requirements.txt` and replace any usage with `httpx`",
        "effort": "S",
        "priority": "P0",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-005",
        "dimension": "21_contradictions",
        "phase": "security",
        "status": "NEW",
        "file": "backend/infrastructure/security/rate_limiter.py",
        "line": "20",
        "current": "Tech stack names `fastapi-limiter-valkey` as canonical, but application imports and instantiates `slowapi`",
        "target": "Application uses `fastapi-limiter-valkey` as declared in TECHNOLOGY_STACK.md",
        "fix": "Migrate to `fastapi-limiter-valkey` or update the tech stack to reflect `slowapi`",
        "effort": "M",
        "priority": "P2",
        "confidence": "4",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-006",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "frontend/web_app/package.json",
        "line": "",
        "current": "Approved frontend i18n library is not installed",
        "target": "`next-intl` present in web_app/package.json dependencies",
        "fix": "Add `next-intl` to `web_app/package.json` or remove it from the tech stack",
        "effort": "S",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-007",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "frontend/web_app/package.json",
        "line": "30",
        "current": "One-patch version drift between canonical version and lockfile",
        "target": "Next.js version 16.3.5 in package.json",
        "fix": "Bump `web_app/package.json` to `16.3.5` to match the tech stack",
        "effort": "S",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-008",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "frontend/web_app/package.json",
        "line": "36",
        "current": "Web app pins Zustand to `^5.0.11`, below documented `5.0.14`",
        "target": "Zustand version 5.0.14 in package.json",
        "fix": "Update `web_app/package.json` to `5.0.14`",
        "effort": "S",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-009",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "frontend/web_app/package.json",
        "line": "26",
        "current": "Major version drift: doc requires 13.2.0+, code installs 12.0.0",
        "target": "framer-motion version 13.2.0+ in package.json",
        "fix": "Upgrade `framer-motion` to `13.2.0+` or downgrade the tech stack entry",
        "effort": "S",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-010",
        "dimension": "21_contradictions",
        "phase": "security",
        "status": "NEW",
        "file": "backend/config.py",
        "line": "491-493",
        "current": "OpenTelemetry is listed as optional in tech stack, but production config validator rejects any deployment without it",
        "target": "OpenTelemetry optional in config validator or marked required in tech stack",
        "fix": "Make the OTEL requirement conditional on an explicit feature flag, or reclassify OpenTelemetry as required in the tech stack",
        "effort": "M",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-011",
        "dimension": "21_contradictions",
        "phase": "security",
        "status": "NEW",
        "file": "backend/config.py",
        "line": "552-554",
        "current": "HF_API_TOKEN is documented as optional/fallback-only, but config hard-fails if it is missing",
        "target": "HF_API_TOKEN optional in config validator or HuggingFace marked required in tech stack",
        "fix": "Remove the hard requirement for `HF_API_TOKEN` from `config.py` or mark HuggingFace as a required provider in the tech stack",
        "effort": "M",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-012",
        "dimension": "21_contradictions",
        "phase": "security",
        "status": "NEW",
        "file": "backend/config.py",
        "line": "502-510",
        "current": "Communications providers are treated as mandatory by the config validator despite being listed as standard infrastructure",
        "target": "Twilio/WhatsApp config optional with graceful degradation matching documented provider pattern",
        "fix": "Make Twilio/WhatsApp config optional with graceful degradation, matching the documented provider pattern",
        "effort": "M",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-013",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/domains/accounts/models/onboarding.py",
        "line": "58",
        "current": "Security domain comment says OCRResult lives in `media` schema, but actual model is created in `accounts` schema",
        "target": "OCRResult model created in `media` schema per security domain comment",
        "fix": "Move `OCRResult` to the `media` schema and update the migration",
        "effort": "M",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-014",
        "dimension": "21_contradictions",
        "phase": "security",
        "status": "NEW",
        "file": "backend/infrastructure/redis/client.py",
        "line": "1-3",
        "current": "Tech stack declares Redis obsolete, yet a backward-compatibility Redis shim remains in the codebase",
        "target": "No Redis shim in codebase; all imports migrated to Valkey",
        "fix": "Remove `infrastructure/redis/` after all imports are migrated to Valkey",
        "effort": "S",
        "priority": "P0",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-015",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/modules/admin/routers/analytics.py",
        "line": "48",
        "current": "Some routers include `/api/v1` in their prefix while others omit it, producing two distinct API version surfaces",
        "target": "Consistent router prefix convention across all backend routers",
        "fix": "Standardize all router prefixes to include `/api/v1` or remove it globally",
        "effort": "M",
        "priority": "P0",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-016",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/domains/payments/services/payment_service.py",
        "line": "3",
        "current": "`payments` is listed as a full domain in the architecture, but the code is explicitly a temporary scaffold",
        "target": "Architecture doc accurately reflects payments domain maturity",
        "fix": "Mark `payments` as a scaffold in the architecture doc, or complete the migration into `finance`",
        "effort": "M",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-017",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/domains/media/",
        "line": "",
        "current": "Architecture says media has no dedicated domain, yet a `media/` package exists under `domains/`",
        "target": "Architecture doc and source tree agree on media domain status",
        "fix": "Remove the empty `domains/media/` directory or promote it to a canonical domain in the architecture doc",
        "effort": "M",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-018",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "frontend/web_app/src/app/",
        "line": "",
        "current": "Architecture doc shows a simplified route tree; the actual frontend has many more route groups than documented",
        "target": "Architecture doc lists actual frontend route groups or references a generated route map",
        "fix": "Update the architecture doc to list the actual route groups or reference a generated route map",
        "effort": "S",
        "priority": "P2",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-019",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/requirements.txt",
        "line": "8",
        "current": "Tech stack pins FastAPI to the 0.141 line, but `requirements.txt` resolves to 0.115.2",
        "target": "FastAPI 0.141.x in requirements.txt",
        "fix": "Align `requirements.txt` to `fastapi==0.141.x`",
        "effort": "S",
        "priority": "P0",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-020",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/requirements.txt",
        "line": "15",
        "current": "Tech stack requires Alembic 1.19.1 or later; lockfile resolves to 1.18.5",
        "target": "Alembic 1.19.1+ in requirements.txt",
        "fix": "Bump Alembic to `1.19.1` in `requirements.txt`",
        "effort": "S",
        "priority": "P0",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-021",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/requirements.txt",
        "line": "38",
        "current": "Tech stack requires 2.9.1+, but the lockfile resolves to 2.7.1",
        "target": "pydantic-settings 2.9.1+ in requirements.txt",
        "fix": "Update `pydantic-settings` to `2.9.1+`",
        "effort": "S",
        "priority": "P0",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-022",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/requirements.txt",
        "line": "29",
        "current": "Tech stack requires Celery 5.5 or later; requirements.txt pins 5.4.0",
        "target": "Celery 5.5+ in requirements.txt",
        "fix": "Bump Celery to `5.5+` in `requirements.txt`",
        "effort": "S",
        "priority": "P0",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-023",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/requirements.txt",
        "line": "86",
        "current": "Tech stack requires Stripe SDK 15.5.1; lockfile resolves to 15.3.1",
        "target": "Stripe SDK 15.5.1 in requirements.txt",
        "fix": "Update Stripe SDK to `15.5.1`",
        "effort": "S",
        "priority": "P0",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-024",
        "dimension": "21_contradictions",
        "phase": "security",
        "status": "NEW",
        "file": "backend/requirements.txt",
        "line": "",
        "current": "Tech stack declares `cryptography` as a required dependency for field-level encryption, but it is absent from `requirements.txt`",
        "target": "`cryptography==50.0.1` present in requirements.txt",
        "fix": "Add `cryptography==50.0.1` to `requirements.txt`",
        "effort": "S",
        "priority": "P0",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-025",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/uv.lock",
        "line": "3",
        "current": "Tech stack mandates Python 3.13.x; the lockfile permits any Python >=3.11",
        "target": "uv.lock requires-python =>=3.13,<3.14",
        "fix": "Tighten `uv.lock` to `requires-python =>=3.13,<3.14`",
        "effort": "S",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-026",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/requirements.txt",
        "line": "11",
        "current": "Tech stack explicitly constrains Starlette to a narrow range; `requirements.txt` leaves it unpinned",
        "target": "starlette>=1.6.0,<1.7.0 pinned in requirements.txt",
        "fix": "Pin `starlette>=1.6.0,<1.7.0` in `requirements.txt`",
        "effort": "S",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-027",
        "dimension": "21_contradictions",
        "phase": "security",
        "status": "NEW",
        "file": "frontend/web_app/package.json",
        "line": "27",
        "current": "Backend avoid-list forbids `python-jose` (Python), but the frontend independently uses the browser `jose` library, which is allowed. Architecture doc does not clarify this scope.",
        "target": "TECHNOLOGY_STACK.md clarifies that `jose` avoidance applies only to Python `python-jose` package",
        "fix": "Clarify in `TECHNOLOGY_STACK.md` that the `jose` avoidance applies only to the Python `python-jose` package; the browser `jose` package remains approved",
        "effort": "S",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-028",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/domains/accounts/models/onboarding.py",
        "line": "19-20",
        "current": "The onboarding model claims the canonical User still lives in `governance.users`, but `user.py` already declares `schema=\"accounts\"`",
        "target": "onboarding.py TODO removed; canonical User location clearly documented as `accounts.users`",
        "fix": "Remove the outdated TODO from `onboarding.py` and close the migration tracking ticket",
        "effort": "S",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-029",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/domains/governance/models/admin.py",
        "line": "",
        "current": "Comment says governance user copies should be removed, but the governance models remain actively used and imported",
        "target": "Governance user copies migrated to accounts or stale TODO archived",
        "fix": "Complete the governance→accounts migration or archive the stale TODO",
        "effort": "S",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-030",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "_most_imp_docx/ARCHITECTURE_STACK.md",
        "line": "172,147",
        "current": "Law 18 forbids root-level `utils/`, but the same document explicitly lists `infrastructure/utils/` as the canonical location for \"pure technical helpers\"",
        "target": "Law 18 explicitly permits `infrastructure/utils/` while forbidding root-level `utils/`",
        "fix": "Reword Law 18 to clarify that `infrastructure/utils/` is sanctioned while root-level `utils/` is forbidden",
        "effort": "S",
        "priority": "P2",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-031",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/alembic/versions/2026_07_27_09_08-20260727_0908_add_check_constraints_to_status_enum_columns.py",
        "line": "20,34,44,50,56,62,68,74",
        "current": "Models declare domain schemas (`orders`, `comms`, `customers`, `logistics`), but the migration adds check constraints using `schema=None` (defaults to `public`)",
        "target": "Check constraints added to correct domain schemas, not `public`",
        "fix": "Add the correct `schema=\"<domain>\"` to every `op.batch_alter_table` in this migration",
        "effort": "M",
        "priority": "P0",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-032",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "frontend/web_app/src/app/api/auth/register/route.ts",
        "line": "8",
        "current": "Next.js API proxy routes forward to `/auth/register` and `/auth/me` (no `/api/v1` prefix), but FastAPI registers these endpoints under `/api/v1/auth/register` and `/api/v1/auth/me`",
        "target": "Next.js proxy routes forward to `/api/v1/auth/register` and `/api/v1/auth/me`",
        "fix": "Update the Next.js proxy routes to forward to `/api/v1/auth/register` and `/api/v1/auth/me`, or add an unversioned alias router in FastAPI",
        "effort": "M",
        "priority": "P0",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-033",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/modules/admin/routers/analytics.py",
        "line": "48",
        "current": "Router prefixes are inconsistent: some include `/api/v1` and others omit it, creating two divergent API surfaces under the same app",
        "target": "Consistent router prefix convention across all backend routers",
        "fix": "Standardize all router prefixes to include `/api/v1` or remove it globally",
        "effort": "M",
        "priority": "P0",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-034",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "frontend/mobile_app/app/logistics-partner/login.tsx",
        "line": "48",
        "current": "Mobile partner-facing screens use `/logistics-partner/` (singular) while web admin uses `/logistics-partners/` (plural) for the same resource",
        "target": "Canonical path `/logistics-partners/*` used consistently across mobile and web",
        "fix": "Align all platforms to a single canonical path (`/logistics-partners/*` recommended to match bulk of codebase)",
        "effort": "S",
        "priority": "P1",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-035",
        "dimension": "21_contradictions",
        "phase": "arch",
        "status": "NEW",
        "file": "backend/alembic/versions/2026_07_28_0000_employee_hr_tables.py",
        "line": "20-150",
        "current": "The migration creates 9+ HR-domain tables in the `public` schema (no schema qualifier), but every corresponding ORM model declares `schema=\"hr\"`",
        "target": "HR tables created in `hr` schema matching ORM model declarations",
        "fix": "Either add `schema=\"hr\"` to every `op.create_table` in `2026_07_28_0000_employee_hr_tables.py` and all subsequent HR-table migrations, or remove `schema=\"hr\"` from the ORM models",
        "effort": "M",
        "priority": "P0",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    },
    {
        "id": "CONTR-036",
        "dimension": "21_contradictions",
        "phase": "security",
        "status": "NEW",
        "file": "backend/infrastructure/utils/redis_client.py",
        "line": "1",
        "current": "Tech stack declares Redis obsolete and Valkey canonical, yet production code imports a module named `redis_client` which is a Valkey shim",
        "target": "No `redis_client` module name; imports use `valkey_client` consistently",
        "fix": "Rename `redis_client` to `valkey_client` across all import sites, or add a CI lint rule banning new `redis` imports",
        "effort": "M",
        "priority": "P2",
        "confidence": "5",
        "cluster": "",
        "section": "2 - Contradiction Table (§7.21)"
    }
]

output_path = r'D:\Projects\10- E-COMMERCE WEBSITE\zozi\_audit\compiler\logs\batches\extra_findings_21_contradictions.json'
os.makedirs(os.path.dirname(output_path), exist_ok=True)

with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(findings, f, indent=2, ensure_ascii=False)

print(f'Wrote {len(findings)} findings to {output_path}')
