# AUTO-GENERATED controller delegator (routers -> controllers -> services).
"""services.geography.country_config_admin_service re-exports for HTTP routers."""
from services.geography.country_config_admin_service import add_country_city as svc_add_country_city, archive_country as svc_archive_country, bulk_archive_countries as svc_bulk_archive_countries, bulk_restore_countries as svc_bulk_restore_countries, create_country_commission_rate as svc_create_country_commission_rate, create_feature_flag as svc_create_feature_flag, delete_country_city as svc_delete_country_city, delete_country_commission_rate as svc_delete_country_commission_rate, delete_feature_flag as svc_delete_feature_flag, hard_delete_country as svc_hard_delete_country, list_country_commission_rates as svc_list_country_commission_rates, patch_country_city as svc_patch_country_city, restore_country as svc_restore_country, toggle_country_active as svc_toggle_country_active, update_feature_flag as svc_update_feature_flag

from services.geography.country_config_admin_service import bulk_restore_countries
from services.geography.country_config_admin_service import create_feature_flag
from services.geography.country_config_admin_service import add_country_city
from services.geography.country_config_admin_service import hard_delete_country
from services.geography.country_config_admin_service import toggle_country_active
from services.geography.country_config_admin_service import create_country_commission_rate
from services.geography.country_config_admin_service import restore_country
from services.geography.country_config_admin_service import bulk_archive_countries
from services.geography.country_config_admin_service import delete_feature_flag
from services.geography.country_config_admin_service import list_country_commission_rates
from services.geography.country_config_admin_service import patch_country_city
from services.geography.country_config_admin_service import delete_country_commission_rate
from services.geography.country_config_admin_service import update_feature_flag
from services.geography.country_config_admin_service import delete_country_city
from services.geography.country_config_admin_service import archive_country
