from __future__ import annotations
from uuid import uuid4
from sqlalchemy import func, UUID
from sqlalchemy import Column, Integer, String, DateTime, Boolean, Text, ForeignKey, UniqueConstraint, Index, JSON, CheckConstraint, text
from sqlalchemy.orm import relationship
from infrastructure.database.types import GUID
from . import Base
from domains.country.models.countries import CountryConfig  # noqa: F401
from infrastructure.utils.datetime_utils import utcnow as utcnow
from infrastructure.database.mixins import TenantMixin, VersionMixin
__all__ = ['Notification', 'Announcement', 'FAQ', 'HelpCategory', 'TicketMessage', 'ProxyChannel', 'ProxySession', 'ProxyMessage', 'ProxyCallLog', 'EmployeeCommunicationThread', 'ExternalContactMasking', 'CommunicationAuditTrail', 'InternalChannel', 'InternalChannelMember', 'InternalMessage', 'ChatAttachment', 'InternalEmail', 'EmailFolder', 'MaskedMessage']

class Notification(Base, TenantMixin):
    __tablename__ = 'notifications'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_notifications_user_id', 'user_id'), Index('ix_notifications_is_read', 'is_read'), Index('ix_notifications_user_read', 'user_id', 'is_read'), Index('ix_notifications_variables', 'variables'), Index('ix_notifications_country_created', 'country_code', 'created_at'), {'schema': 'comms'})
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, nullable=False)
    type = Column(String(50), nullable=True)
    title = Column(String(255), nullable=False)
    message = Column(Text, nullable=False)
    channel = Column(String(255), default='in_app')
    priority = Column(String(50), default='medium')
    is_read = Column(Boolean, default=False)
    read_at = Column(DateTime, nullable=True)
    link = Column(String(500), nullable=True)
    template = Column(String(255), nullable=True)
    variables = Column(JSON, nullable=True)
    scheduled_at = Column(DateTime, nullable=True)
    status_code = Column(String(50), default='delivered')
    created_at = Column(DateTime, default=utcnow)

class TicketMessage(Base, TenantMixin):
    __tablename__ = 'ticket_messages'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_ticket_messages_country_created', 'country_code', 'created_at'), {'schema': 'comms'})
    id = Column(Integer, primary_key=True, index=True)
    ticket_id = Column(Integer, ForeignKey('comms.support_tickets.id', ondelete='RESTRICT'), nullable=False, index=True)
    sender_id = Column(Integer, nullable=False)
    message = Column(Text, nullable=False)
    is_admin = Column(Boolean, default=False)
    created_at = Column(DateTime, default=utcnow)
    ticket = relationship('SupportTicket', back_populates='messages')
    sender = relationship('User', primaryjoin='foreign(TicketMessage.sender_id) == User.id')

class Announcement(Base):
    __tablename__ = 'announcements'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'comms'},)
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(255), nullable=False)
    content = Column(Text, nullable=False)
    is_active = Column(Boolean, default=True)
    starts_at = Column(DateTime, nullable=True)
    ends_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)

class FAQ(Base, TenantMixin):
    __tablename__ = 'faqs'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_faqs_country_created', 'country_code', 'created_at'), {'schema': 'comms'})
    id = Column(Integer, primary_key=True, index=True)
    question = Column(Text, nullable=False)
    answer = Column(Text, nullable=False)
    category = Column(String(255), nullable=True)
    created_at = Column(DateTime, default=utcnow)

class HelpCategory(Base):
    __tablename__ = 'help_categories'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'comms'},)
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    created_at = Column(DateTime, default=utcnow)

class ProxyChannel(Base):
    __tablename__ = 'proxy_channels'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    id = Column(Integer, primary_key=True, index=True)
    entity_type = Column(String(50), nullable=False)
    entity_id = Column(Integer, nullable=False)
    proxy_phone = Column(String(50), unique=True, nullable=False, index=True)
    proxy_email = Column(String(255), unique=True, nullable=False, index=True)
    participants = Column(JSON, nullable=True)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)
    __table_args__ = (Index('idx_proxy_entity', 'entity_type', 'entity_id'), Index('ix_proxy_channels_participants', 'participants'), {'schema': 'comms'})
    sessions = relationship('ProxySession', back_populates='channel', cascade='all, delete-orphan')
    call_logs = relationship('ProxyCallLog', back_populates='channel', cascade='all, delete-orphan')

class ProxySession(Base):
    __tablename__ = 'proxy_sessions'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_proxy_sessions_session_metadata', 'session_metadata'), {'schema': 'comms'})
    id = Column(Integer, primary_key=True, index=True)
    channel_id = Column(Integer, ForeignKey('comms.proxy_channels.id', ondelete='RESTRICT'), nullable=False, index=True)
    participant_one_id = Column(Integer, nullable=False)
    participant_two_id = Column(Integer, nullable=False)
    started_at = Column(DateTime, default=utcnow)
    ended_at = Column(DateTime, nullable=True)
    is_encrypted = Column(Boolean, default=True)
    session_metadata = Column(JSON, nullable=True)
    channel = relationship('ProxyChannel', back_populates='sessions')
    participant_one = relationship('User', primaryjoin='foreign(ProxySession.participant_one_id) == User.id')
    participant_two = relationship('User', primaryjoin='foreign(ProxySession.participant_two_id) == User.id')
    messages = relationship('ProxyMessage', back_populates='session', cascade='all, delete-orphan')

class ProxyMessage(Base):
    __tablename__ = 'proxy_messages'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'comms'},)
    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, ForeignKey('comms.proxy_sessions.id', ondelete='RESTRICT'), nullable=False, index=True)
    sender_id = Column(Integer, nullable=False)
    recipient_id = Column(Integer, nullable=False)
    message_type = Column(String(50), default='text')
    content = Column(Text, nullable=False)
    is_masked = Column(Boolean, default=True)
    read_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    session = relationship('ProxySession', back_populates='messages')
    sender = relationship('User', primaryjoin='foreign(ProxyMessage.sender_id) == User.id')
    recipient = relationship('User', primaryjoin='foreign(ProxyMessage.recipient_id) == User.id')

class ProxyCallLog(Base):
    __tablename__ = 'proxy_call_logs'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'comms'},)
    id = Column(Integer, primary_key=True, index=True)
    channel_id = Column(Integer, ForeignKey('comms.proxy_channels.id', ondelete='RESTRICT'), nullable=False, index=True)
    caller_id = Column(Integer, nullable=False)
    callee_id = Column(Integer, nullable=False)
    direction = Column(String(50), nullable=False)
    duration_seconds = Column(Integer, default=0)
    call_recording_url = Column(String(500), nullable=True)
    is_recorded = Column(Boolean, default=False)
    started_at = Column(DateTime, default=utcnow)
    ended_at = Column(DateTime, nullable=True)
    channel = relationship('ProxyChannel', back_populates='call_logs')
    caller = relationship('User', primaryjoin='foreign(ProxyCallLog.caller_id) == User.id')
    callee = relationship('User', primaryjoin='foreign(ProxyCallLog.callee_id) == User.id')

class EmployeeCommunicationThread(Base, TenantMixin):
    __tablename__ = 'employee_communication_threads'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_emp_comm_entity', 'entity_type', 'entity_id'), Index('ix_emp_comm_country_created', 'country_code', 'created_at'), {'schema': 'comms'})
    id = Column(Integer, primary_key=True, index=True)
    entity_id = Column(Integer, nullable=False)
    entity_type = Column(String(50), nullable=False)
    participants = Column(Text, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    country_code = Column(String(2), nullable=True)
    country = relationship('CountryConfig', primaryjoin='foreign(EmployeeCommunicationThread.country_code) == CountryConfig.code')

class ExternalContactMasking(Base):
    __tablename__ = 'external_contact_maskings'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (UniqueConstraint('user_id', 'external_contact_type', 'external_contact_id', name='uq_masking_contact'), Index('ix_masking_user', 'user_id'), {'schema': 'comms'})
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, nullable=False)
    external_contact_type = Column(String(50), nullable=False)
    external_contact_id = Column(Integer, nullable=False)
    masked_phone = Column(String(20), nullable=True)
    masked_email = Column(String(255), nullable=True)
    user = relationship('User', primaryjoin='foreign(ExternalContactMasking.user_id) == User.id')

class CommunicationAuditTrail(Base):
    __tablename__ = 'communication_audit_trails'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_comm_entity', 'entity_type', 'entity_id'), Index('ix_comm_user', 'user_id', 'created_at'), Index('ix_communication_audit_trail_metadata_json', 'metadata_json'), {'schema': 'comms'})
    id = Column(Integer, primary_key=True, index=True)
    entity_type = Column(String(50), nullable=False)
    entity_id = Column(Integer, nullable=False)
    user_id = Column(Integer, nullable=True)
    action = Column(String(50), nullable=False)
    channel = Column(String(50), nullable=False)
    content_preview = Column(Text, nullable=True)
    metadata_json = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    user = relationship('User', primaryjoin='foreign(CommunicationAuditTrail.user_id) == User.id')

class InternalChannel(Base, TenantMixin):
    __tablename__ = 'internal_channels'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (
        Index('ix_internal_channel_entity', 'entity_type', 'entity_id'),
        Index('ix_internal_channels_allowed_roles', 'allowed_roles'),
        Index('ix_internal_channels_country_created', 'country_code', 'created_at'),
        {'schema': 'comms'},
    )
    id = Column(Integer, primary_key=True, index=True)
    entity_type = Column(String(50), nullable=False)
    entity_id = Column(Integer, nullable=False)
    name = Column(String(200), nullable=False)
    channel_id = Column(String(64), unique=True, nullable=True, index=True)
    description = Column(Text, nullable=True)
    is_public = Column(Boolean, default=True)
    created_by = Column(Integer, nullable=True)
    country_code = Column(String(2), nullable=True)
    allowed_roles = Column(JSON, nullable=True)
    country = relationship('CountryConfig', primaryjoin='foreign(InternalChannel.country_code) == CountryConfig.code')
    members = relationship('InternalChannelMember', back_populates='channel', cascade='all, delete-orphan')
    messages = relationship('InternalMessage', back_populates='channel', cascade='all, delete-orphan')

class InternalChannelMember(Base):
    __tablename__ = 'internal_channel_members'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (UniqueConstraint('channel_id', 'user_id', name='uq_channel_member'), {'schema': 'comms'})
    id = Column(Integer, primary_key=True, index=True)
    channel_id = Column(Integer, ForeignKey('comms.internal_channels.id', ondelete='RESTRICT'), nullable=False, index=True)
    user_id = Column(Integer, nullable=False)
    role = Column(String(20), default='member')
    joined_at = Column(DateTime, default=utcnow)
    channel = relationship('InternalChannel', back_populates='members')
    user = relationship('User', primaryjoin='foreign(InternalChannelMember.user_id) == User.id')

class InternalMessage(Base):
    __tablename__ = 'internal_messages'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_internal_msg_channel', 'channel_id'), Index('ix_internal_msg_user', 'user_id'), {'schema': 'comms'})
    id = Column(Integer, primary_key=True, index=True)
    channel_id = Column(Integer, ForeignKey('comms.internal_channels.id', ondelete='RESTRICT'), nullable=False, index=True)
    user_id = Column(Integer, nullable=False)
    message = Column(Text, nullable=False)
    message_type = Column(String(20), default='text')
    is_masked = Column(Boolean, default=True)
    read_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    channel = relationship('InternalChannel', back_populates='messages')
    user = relationship('User', primaryjoin='foreign(InternalMessage.user_id) == User.id')

class ChatReadReceipt(Base):
    __tablename__ = 'chat_read_receipts'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (UniqueConstraint('message_id', 'message_type', 'employee_id', name='uq_chat_read_receipt'), Index('ix_chat_read_receipts_employee', 'employee_id'), {'schema': 'comms'})
    id = Column(Integer, primary_key=True, index=True)
    message_id = Column(Integer, nullable=False, index=True)
    message_type = Column(String(20), nullable=False, default='direct')
    employee_id = Column(Integer, nullable=False)
    read_at = Column(DateTime, default=utcnow)

class ChatAttachment(Base):
    __tablename__ = 'chat_attachments'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'comms'},)
    id = Column(Integer, primary_key=True, index=True)
    message_id = Column(Integer, nullable=False, index=True)
    message_type = Column(String(20), nullable=False, default='direct')
    attachment_type = Column(String(20), nullable=False)
    file_url = Column(String(500), nullable=False)
    file_name = Column(String(200), nullable=False)
    file_size_bytes = Column(Integer, nullable=False)
    mime_type = Column(String(100), nullable=False)
    thumbnail_url = Column(String(500), nullable=True)
    duration_seconds = Column(Integer, nullable=True)
    waveform_json = Column(Text, nullable=True)
    is_processed = Column(Boolean, default=False)

class InternalEmail(Base, TenantMixin):
    __tablename__ = 'internal_emails'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_internal_emails_thread_id', 'thread_id'), Index('ix_internal_emails_sender_id', 'sender_id'), Index('ix_internal_emails_folder_id', 'folder_id'), Index('ix_internal_emails_country_created', 'country_code', 'created_at'), {'schema': 'comms'})
    id = Column(Integer, primary_key=True, index=True)
    sender_id = Column(Integer, nullable=False)
    subject = Column(String(200), nullable=False)
    body_html = Column(Text, nullable=True)
    body_text = Column(Text, nullable=True)
    recipients = Column(Text, nullable=True)
    thread_id = Column(String(64), nullable=True)
    is_external = Column(Boolean, default=False)
    external_message_id = Column(String(200), nullable=True)
    in_reply_to_id = Column(Integer, ForeignKey('comms.internal_emails.id', ondelete='RESTRICT'), nullable=True, index=True)
    folder_id = Column(Integer, ForeignKey('comms.email_folders.id', ondelete='RESTRICT'), nullable=True, index=True)
    created_at = Column(DateTime, default=utcnow)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)
    replies = relationship('InternalEmail', remote_side=[id], backref='parent')
    folder = relationship('EmailFolder', backref='emails')

class EmailFolder(Base):
    __tablename__ = 'email_folders'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = ({'schema': 'comms'},)
    id = Column(Integer, primary_key=True, index=True)
    employee_id = Column(Integer, nullable=False)
    name = Column(String(50), nullable=False)
    folder_type = Column(String(20), default='inbox')
    sort_order = Column(Integer, default=0)
    is_system = Column(Boolean, default=True)
    created_at = Column(DateTime, default=utcnow)

class MaskedMessage(Base, TenantMixin):
    __tablename__ = 'masked_messages'
    uuid = Column(GUID(), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_masked_messages_sender', 'sender_id'), Index('ix_masked_messages_recipient', 'recipient_ref'), Index('ix_masked_messages_hash', 'message_hash'), Index('ix_masked_messages_country_created', 'country_code', 'created_at'), {'schema': 'comms'})
    id = Column(Integer, primary_key=True, index=True)
    sender_id = Column(Integer, nullable=False)
    recipient_ref = Column(String(200), nullable=False)
    message_hash = Column(Integer, nullable=False)
    content = Column(Text, nullable=False)
    created_at = Column(DateTime, default=utcnow)
    sender = relationship('User', primaryjoin='foreign(MaskedMessage.sender_id) == User.id')