"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Body, Request
from sqlalchemy.orm import Session

from controllers.core.translate_controller import TranslateRequest, TranslateResponse, translate_texts

router = APIRouter(prefix="/api/v1")

@router.post("/translate", response_model=TranslateResponse, status_code=201, tags=['translate'])
def translate_texts_route(
    request: Request,
    body: TranslateRequest = Body(...)
) -> TranslateResponse:
    return translate_texts(request=request, body=body)
