# === From supplier_supplier_supplier_health.py ===
from suppliers.router import router  # noqa: F401
"""AUTO-GENERATED — DO NOT EDIT MANUALLY (generated by routers/generated/auto_router.py)"""

from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from infrastructure.database.database import get_db
from infrastructure.utils.dependencies import get_current_user
from typing import Optional

from controllers.supplier.supplier_health_controller import get_supplier_health, list_supplier_health


@router.get("/health/suppliers/{supplier_id}", status_code=200, tags=['supplier-health'])
def get_supplier_health_route(
    supplier_id: int,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    country_code: Optional[str] = Query(None)
) -> dict:
    return get_supplier_health(supplier_id=supplier_id, current_user=current_user, db=db, country_code=country_code)

@router.get("/health/suppliers", status_code=200, tags=['supplier-health'])
def list_supplier_health_route(
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
    country_code: Optional[str] = Query(None)
) -> dict:
    return list_supplier_health(current_user=current_user, db=db, country_code=country_code)

