from __future__ import annotations
from uuid import uuid4
from sqlalchemy import func, UUID
from sqlalchemy import Column, Integer, String, DateTime, Boolean, Text, Numeric, ForeignKey, UniqueConstraint, Index, JSON
from sqlalchemy.orm import relationship
from . import Base
from utils.datetime_utils import utcnow as _utcnow
__all__ = ['LogisticsPartner', 'LogisticsPartnerProfile', 'LogisticsPartnerServiceArea', 'LogisticsPricingProfile', 'LogisticsVehicleRule', 'Shipment', 'ShipmentEvent', 'LogisticsCategoryPricingRule']

class LogisticsPartner(Base):
    __tablename__ = 'logistics_partners'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_logistics_partners_coverage_regions_gin', 'coverage_regions', postgresql_using='gin'), Index('ix_logistics_partners_service_types_gin', 'service_types', postgresql_using='gin'), Index('ix_logistics_partners_social_links_gin', 'social_links', postgresql_using='gin'), Index('ix_logistics_partners_country_created', 'country_code', 'created_at'), {'schema': 'logistics'})
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey('core.users.id', ondelete='RESTRICT'), nullable=True, index=True)
    name = Column(String, nullable=False)
    code = Column(String, unique=True, nullable=False)
    contact_name = Column(String, nullable=True)
    contact_email = Column(String, nullable=True)
    contact_phone = Column(String, nullable=True)
    website = Column(String, nullable=True)
    coverage_regions = Column(JSON, nullable=True)
    service_types = Column(JSON, nullable=True)
    status = Column(String, default='active')
    verification_status = Column(String, default='pending')
    verification_note = Column(String, nullable=True)
    verified_by = Column(Integer, nullable=True)
    verified_at = Column(DateTime, nullable=True)
    country_code = Column(String(3), ForeignKey('country.country_configs.code', ondelete='RESTRICT'), nullable=True, index=True)
    created_at = Column(DateTime, default=_utcnow)
    business_type = Column(String, nullable=True)
    region = Column(String, nullable=True)
    city = Column(String, nullable=True)
    address = Column(Text, nullable=True)
    postal_code = Column(String, nullable=True)
    tax_id = Column(String, nullable=True)
    bio = Column(Text, nullable=True)
    about_us = Column(Text, nullable=True)
    logo_url = Column(String, nullable=True)
    banner_url = Column(String, nullable=True)
    latitude = Column(Numeric(10, 7), nullable=True)
    longitude = Column(Numeric(10, 7), nullable=True)
    social_links = Column(JSON, nullable=True)
    notes = Column(Text, nullable=True)
    is_terms_accepted = Column(Boolean, default=False)
    terms_version = Column(String, nullable=True)
    terms_accepted_at = Column(DateTime, nullable=True)
    profile = relationship('LogisticsPartnerProfile', back_populates='partner', cascade='all, delete-orphan')
    service_areas = relationship('LogisticsPartnerServiceArea', back_populates='partner')
    pricing_profiles = relationship('LogisticsPricingProfile', back_populates='partner')
    vehicle_rules = relationship('LogisticsVehicleRule', back_populates='partner')
    category_pricing_rules = relationship('LogisticsCategoryPricingRule', back_populates='partner')
    payouts = relationship('LogisticsPartnerPayout', back_populates='partner')
    country = relationship('CountryConfig', foreign_keys=[country_code])

class LogisticsPartnerProfile(Base):
    __tablename__ = 'logistics_partner_profiles'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_logistics_partner_profiles_country_created', 'country_code', 'created_at'), {'schema': 'logistics'})
    id = Column(Integer, primary_key=True, index=True)
    partner_id = Column(Integer, ForeignKey('logistics.logistics_partners.id', ondelete='RESTRICT'), nullable=False, unique=True, index=True)
    tax_id = Column(String, nullable=True)
    registration_number = Column(String, nullable=True)
    business_type = Column(String, nullable=True)
    years_in_business = Column(Integer, nullable=True)
    insurance_provider = Column(String, nullable=True)
    insurance_policy_number = Column(String, nullable=True)
    insurance_expiry = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)
    country_code = Column(String(3), ForeignKey('country.country_configs.code', ondelete='RESTRICT'), nullable=True, index=True)
    country = relationship('CountryConfig', foreign_keys=[country_code])
    partner = relationship('LogisticsPartner', back_populates='profile')

class LogisticsPartnerServiceArea(Base):
    __tablename__ = 'logistics_partner_service_areas'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_logistics_partner_service_areas_country_created', 'country_code', 'created_at'), {'schema': 'logistics'})
    id = Column(Integer, primary_key=True, index=True)
    partner_id = Column(Integer, ForeignKey('logistics.logistics_partners.id', ondelete='RESTRICT'), nullable=False, index=True)
    country_code = Column(String(3), nullable=False)
    country_name = Column(String, nullable=False)
    origin_city = Column(String, nullable=False)
    city_name = Column(String, nullable=False)
    zone_label = Column(String, nullable=True)
    charge_amount = Column(Numeric(10, 2), nullable=True)
    minimum_charge = Column(Numeric(10, 2), nullable=True)
    per_kg_rate = Column(Numeric(10, 2), nullable=True)
    pickup_charge = Column(Numeric(10, 2), nullable=True)
    dropoff_charge = Column(Numeric(10, 2), nullable=True)
    per_km_rate = Column(Numeric(10, 2), nullable=True)
    currency = Column(String(3), default='USD')
    delivery_days_min = Column(Integer, nullable=True)
    delivery_days_max = Column(Integer, nullable=True)
    is_active = Column(Boolean, default=True)
    approval_status = Column(String, default='pending')
    review_note = Column(String, nullable=True)
    reviewed_by = Column(Integer, nullable=True)
    reviewed_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)
    partner = relationship('LogisticsPartner', back_populates='service_areas')
    pricing_profiles = relationship('LogisticsPricingProfile', back_populates='service_area', cascade='all, delete-orphan')
    vehicle_rules = relationship('LogisticsVehicleRule', back_populates='service_area', cascade='all, delete-orphan')
    category_pricing_rules = relationship('LogisticsCategoryPricingRule', back_populates='service_area', cascade='all, delete-orphan')

class LogisticsPricingProfile(Base):
    __tablename__ = 'logistics_pricing_profiles'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_logistics_pricing_profiles_country_created', 'country_code', 'created_at'), {'schema': 'logistics'})
    id = Column(Integer, primary_key=True, index=True)
    partner_id = Column(Integer, ForeignKey('logistics.logistics_partners.id', ondelete='RESTRICT'), nullable=False, index=True)
    service_area_id = Column(Integer, ForeignKey('logistics.logistics_partner_service_areas.id', ondelete='RESTRICT'), nullable=False, index=True)
    profile_name = Column(String, nullable=False)
    base_in_city_fee = Column(Numeric(10, 2), nullable=True)
    per_kg_rate = Column(Numeric(10, 2), nullable=True)
    minimum_charge = Column(Numeric(10, 2), nullable=True)
    maximum_charge = Column(Numeric(10, 2), nullable=True)
    fuel_multiplier = Column(Numeric(5, 4), default=1.0)
    base_inter_city_fee = Column(Numeric(10, 2), nullable=True)
    per_km_rate = Column(Numeric(10, 2), nullable=True)
    bulk_discount_threshold_kg = Column(Numeric(10, 2), nullable=True)
    bulk_discount_percent = Column(Numeric(5, 4), nullable=True)
    currency = Column(String(3), default='USD')
    is_active = Column(Boolean, default=True)
    approval_status = Column(String, default='pending')
    review_note = Column(String, nullable=True)
    reviewed_by = Column(Integer, ForeignKey('core.users.id', ondelete='RESTRICT'), nullable=True, index=True)
    reviewed_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)
    country_code = Column(String(3), nullable=True, index=True)
    partner = relationship('LogisticsPartner', back_populates='pricing_profiles')
    service_area = relationship('LogisticsPartnerServiceArea', back_populates='pricing_profiles')

class LogisticsVehicleRule(Base):
    __tablename__ = 'logistics_vehicle_rules'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_logistics_vehicle_rules_country_created', 'country_code', 'created_at'), {'schema': 'logistics'})
    id = Column(Integer, primary_key=True, index=True)
    partner_id = Column(Integer, ForeignKey('logistics.logistics_partners.id', ondelete='RESTRICT'), nullable=False, index=True)
    service_area_id = Column(Integer, ForeignKey('logistics.logistics_partner_service_areas.id', ondelete='RESTRICT'), nullable=False, index=True)
    vehicle_type = Column(String, nullable=False)
    max_weight_kg = Column(Numeric(10, 2), nullable=True)
    cost_multiplier = Column(Numeric(5, 4), nullable=True)
    priority_rank = Column(Integer, default=0)
    route_scope = Column(String, nullable=True)
    max_volume_cm3 = Column(Numeric(12, 2), nullable=True)
    is_active = Column(Boolean, default=True)
    approval_status = Column(String, default='pending')
    review_note = Column(String, nullable=True)
    reviewed_by = Column(Integer, ForeignKey('core.users.id', ondelete='RESTRICT'), nullable=True, index=True)
    reviewed_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)
    country_code = Column(String(3), nullable=True, index=True)
    partner = relationship('LogisticsPartner', back_populates='vehicle_rules')
    service_area = relationship('LogisticsPartnerServiceArea', back_populates='vehicle_rules')

class LogisticsCategoryPricingRule(Base):
    __tablename__ = 'logistics_category_pricing_rules'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_logistics_category_pricing_rules_country_created', 'country_code', 'created_at'), {'schema': 'logistics'})
    id = Column(Integer, primary_key=True, index=True)
    partner_id = Column(Integer, ForeignKey('logistics.logistics_partners.id', ondelete='RESTRICT'), nullable=False, index=True)
    service_area_id = Column(Integer, ForeignKey('logistics.logistics_partner_service_areas.id', ondelete='RESTRICT'), nullable=True, index=True)
    category_name = Column(String, nullable=False)
    flat_fee_override = Column(Numeric(10, 2), nullable=True)
    special_handling_fee = Column(Numeric(10, 2), nullable=True)
    currency = Column(String(3), default='USD')
    is_active = Column(Boolean, default=True)
    approval_status = Column(String, default='pending')
    review_note = Column(String, nullable=True)
    reviewed_by = Column(Integer, ForeignKey('core.users.id', ondelete='RESTRICT'), nullable=True, index=True)
    reviewed_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)
    country_code = Column(String(3), nullable=True, index=True)
    partner = relationship('LogisticsPartner', back_populates='category_pricing_rules')
    service_area = relationship('LogisticsPartnerServiceArea', back_populates='category_pricing_rules')

class Shipment(Base):
    __tablename__ = 'shipments'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_shipments_order_id', 'order_id'), Index('ix_shipments_country_created', 'country_code', 'created_at'), {'schema': 'logistics'})
    id = Column(Integer, primary_key=True, index=True)
    order_id = Column(Integer, ForeignKey('commerce.orders.id', ondelete='RESTRICT'), nullable=False, index=True)
    supplier_id = Column(Integer, ForeignKey('core.users.id', ondelete='RESTRICT'), nullable=False, index=True)
    assigned_partner_id = Column(Integer, ForeignKey('logistics.logistics_partners.id', ondelete='RESTRICT'), nullable=True, index=True)
    carrier_id = Column(Integer, ForeignKey('logistics.shipping_carriers.id', ondelete='RESTRICT'), nullable=True, index=True)
    tracking_number = Column(String, unique=True, nullable=True)
    carrier_name = Column(String, nullable=True)
    status = Column(String, default='processing')
    distribution_channel = Column(String, nullable=True)
    current_hub = Column(String, nullable=True)
    scan_code = Column(String, nullable=True)
    package_count = Column(Integer, default=1)
    package_weight_kg = Column(Numeric(5, 2), nullable=True)
    package_dimensions = Column(String, nullable=True)
    packaged_at = Column(DateTime, nullable=True)
    packaged_by_user_id = Column(Integer, nullable=True)
    packaged_notes = Column(String, nullable=True)
    packaging_notes = Column(String, nullable=True)
    shipped_at = Column(DateTime, nullable=True)
    estimated_delivery = Column(DateTime, nullable=True)
    actual_delivery = Column(DateTime, nullable=True)
    delivery_signature_name = Column(String, nullable=True)
    delivery_signature_data_url = Column(String, nullable=True)
    delivery_signature_captured_at = Column(DateTime, nullable=True)
    notes = Column(Text, nullable=True)
    accepted_vehicle_type = Column(String, nullable=True)
    accepted_vehicle_multiplier = Column(Numeric(5, 4), nullable=True)
    accepted_vehicle_selected_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)
    country_code = Column(String(3), nullable=True, index=True)
    order = relationship('Order', back_populates='shipments')
    supplier = relationship('User', backref='shipments')
    assigned_partner = relationship('LogisticsPartner', backref='shipments')
    carrier = relationship('ShippingCarrier', backref='shipments')

class ShipmentEvent(Base):
    __tablename__ = 'shipment_events'
    uuid = Column(UUID(as_uuid=True), default=uuid4, unique=True, nullable=True)
    version = Column(Integer, nullable=False, default=1)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    is_deleted = Column(Boolean, default=False, server_default='false', nullable=False, index=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    deleted_by = Column(Integer, nullable=True)
    created_by = Column(Integer, nullable=True, index=True)
    updated_by = Column(Integer, nullable=True, index=True)
    __table_args__ = (Index('ix_shipment_events_shipment_id', 'shipment_id'), Index('ix_shipment_events_order_id', 'order_id'), Index('ix_shipment_events_country_created', 'country_code', 'created_at'), {'schema': 'logistics'})
    id = Column(Integer, primary_key=True, index=True)
    shipment_id = Column(Integer, ForeignKey('logistics.shipments.id', ondelete='RESTRICT'), nullable=True, index=True)
    order_id = Column(Integer, ForeignKey('commerce.orders.id', ondelete='RESTRICT'), nullable=True, index=True)
    supplier_id = Column(Integer, ForeignKey('core.users.id', ondelete='RESTRICT'), nullable=False, index=True)
    actor_user_id = Column(Integer, ForeignKey('core.users.id', ondelete='RESTRICT'), nullable=True, index=True)
    actor_role = Column(String, nullable=True)
    event_type = Column(String, nullable=False)
    status_after = Column(String, nullable=True)
    distribution_channel = Column(String, nullable=True)
    location = Column(String, nullable=True)
    latitude = Column(Numeric(10, 8), nullable=True)
    longitude = Column(Numeric(11, 8), nullable=True)
    scan_code = Column(String, nullable=True)
    notes = Column(String, nullable=True)
    created_at = Column(DateTime, default=_utcnow)
    country_code = Column(String(3), nullable=True, index=True)