"""Split the normalised finding set into one bounded work packet per dimension
so a verification sub-agent never has to read the whole corpus.

Writes:
  _audit/compiler/packets/<dimension>.json   one packet per dimension
  _audit/compiler/packets/MANIFEST.md        allocation table for the orchestrator

Read-only with respect to the codebase. Touches nothing under _audit/dimensions.
"""

from __future__ import annotations

import json
import os
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
COMP = os.path.join(ROOT, "_audit", "compiler")
SRC = os.path.join(COMP, "_findings.json")
PKT = os.path.join(COMP, "packets")

SUBSECTIONS = [
    "Architectural", "Technological", "Logical", "Database Wiring", "Table",
    "Frontend Web", "Frontend Mobile", "Test File", "Environmental",
    "Over All", "Feature Relation",
]


def main() -> int:
    data = json.load(open(SRC, encoding="utf-8"))
    rows = data["findings"]

    by_dim = defaultdict(list)
    for r in rows:
        by_dim[r["_dimension"]].append(r)

    os.makedirs(PKT, exist_ok=True)
    for f in os.listdir(PKT):
        if f.endswith(".json"):
            os.remove(os.path.join(PKT, f))

    manifest = [
        "# COMPILER WORK PACKETS — run 8",
        "",
        "Generated by `_audit/compiler/build_packets.py` from "
        "`_audit/compiler/_findings.json`.",
        "One packet per dimension file. A verification sub-agent reads exactly",
        "its own packet plus the benchmark, then writes a verdict file.",
        "",
        "| # | packet | records | with repo path | subsection | agent id |",
        "|---|--------|---------|----------------|------------|----------|",
    ]

    # Largest packets first so the long pole starts earliest.
    ordered = sorted(by_dim.items(), key=lambda kv: (-len(kv[1]), kv[0]))
    for n, (dim, recs) in enumerate(ordered, start=1):
        agent = f"COMP-V{n:02d}-{dim}"
        with_path = sum(1 for r in recs if r["_path"])
        subs = sorted({r["_subsection"] for r in recs}, key=SUBSECTIONS.index)
        packet = {
            "agent_id": agent,
            "dimension": dim,
            "record_count": len(recs),
            "records_with_repo_path": with_path,
            "records_without_repo_path": len(recs) - with_path,
            "subsections": subs,
            "canonical_fields": data["canonical_fields"],
            "np_token": data["np_token"],
            "records": recs,
        }
        with open(os.path.join(PKT, f"{dim}.json"), "w", encoding="utf-8") as fh:
            json.dump(packet, fh, indent=1, ensure_ascii=False)
        manifest.append(
            f"| {n} | {dim} | {len(recs)} | {with_path} | "
            f"{', '.join(subs)} | `{agent}` |"
        )

    with open(os.path.join(PKT, "MANIFEST.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(manifest) + "\n")

    total = len(rows)
    print(f"packets written : {len(ordered)}")
    print(f"records covered : {total}")
    big = [(d, len(r)) for d, r in ordered[:6]]
    print("largest packets : " + ", ".join(f"{d}={c}" for d, c in big))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
