const { chromium } = require("playwright");
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  const errors = [];
  page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
  page.on("pageerror", (e) => errors.push("PAGEERR: " + e.message));
  const BASE = "http://localhost:3111";
  await page.goto(BASE + "/admin/login", { waitUntil: "domcontentloaded" });
  await page.waitForSelector('input[placeholder="Your username"]', { timeout: 20000 });
  await page.fill('input[placeholder="Your username"]', "admin@test.com");
  await page.fill('input[type="password"]', "admin123");
  await page.click('button:has-text("Sign In")');
  await page.waitForTimeout(3500);
  console.log("after login url:", page.url());
  await page.goto(BASE + "/admin/command-center", { waitUntil: "domcontentloaded" });
  await page.waitForTimeout(8000);
  const text = await page.evaluate(() => document.body.innerText.slice(0, 2000));
  await page.screenshot({ path: "C:\\Users\\user\\AppData\\Local\\Temp\\opencode\\cc_shot.png", fullPage: true });
  console.log("=== BODY TEXT (head) ===");
  console.log(text);
  console.log("=== CONSOLE ERRORS ===");
  console.log(errors.slice(0, 25).join("\n"));
  await browser.close();
})();
